OpenBB-finance/OpenBB

- due_diligence/business_insider_api.py
- fundamental_analysis/business_insider_api.py
- requirements.txt
This PR replaces FuzzyWuzzy with RapidFuzz, which is faster and uses a MIT license.
Following https://news.ycombinator.com/item?id=26259362 the current library might cause license issues, while a MIT licensed one definitely does not.
Another advantage is that it comes with wheels, so the user does not need a C/C++ compiler.
> replace fuzzywuzzy with rapidfuzz

- README.md
It seems you can load -t btcusd -s 2017-10-01 so mention crypto in the readme. Also you don't need an alpha vantage key to get the daily OHLC values (for now at least) so also mention that below the key section
> it can load btcusd, add crypto

- .github/workflows/test.yml
Instead of `selecting` a small list of key tests, let's `ignore` only those tests that our codebase currently fails.
Future PRs can clean up failing tests and remove them from the list.  High priority items to remove would be:
```
1     E722 do not use bare 'except'
1     E741 ambiguous variable name 'l'
20    F401 '.discovery' imported but unused
5     F841 local variable 'line' is assigned to but never used
```
> GitHub Actions: Add more flake8 tests

- .github/workflows/test.yml
- gamestonk_terminal/helper_funcs.py
`l` and `1` look too much alike to a casual reader so `l` should not be used as a variable name.
> Do not use the ambiguous variable name 'l'

- .github/workflows/test.yml
- gamestonk_terminal/sentiment/twitter_api.py
- gamestonk_terminal/technical_analysis/overlap.py
- gamestonk_terminal/technical_analysis/volume.py
% `flake8 --select=F841 --statistics`
```
./gamestonk_terminal/technical_analysis/volume.py:132:13: F841 local variable 'axVolume' is assigned to but never used
./gamestonk_terminal/technical_analysis/volume.py:241:13: F841 local variable 'axVolume' is assigned to but never used
./gamestonk_terminal/technical_analysis/overlap.py:251:13: F841 local variable 'axVolume' is assigned to but never used
./gamestonk_terminal/sentiment/twitter_api.py:169:13: F841 local variable 'n_pct' is assigned to but never used
```
We are assigning values to `n_pct` and `axVolume` but we are never using the results.  __Could these lines of code be safely eliminated?__
If there are desirable side effects from calling `axPrice.twinx()` then both flake8 and pylint should be satisfied with
`_ = axPrice.twinx()` …
> Fix local variable is assigned to but never used

- terminal.py
Recreated this on a new branch since there had been so many changes in the meantime. From the original PR:
This pull implements extremely basic export functionality and is intended to contribute toward a resolution of #7.
I'm just exposing the built in pandas IO formats on df_stock, nothing fancy. The only things the user can specify are the file format (I went ahead and implemented the ones I thought would be most desired but it would be easy to expose others) and the destination filename (the export goes to stdout if -f is unspecified). Can throw an exception in case you specify a format (e.g. excel) that doesn't support output to stdout, but don't also specify the filename. Otherwise works well and does what it says on the tin.
> Adds export command to save LOADed data to a variety of formats: the sequel

- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/main_helper.py
- gamestonk_terminal/res_menu.py
- gamestonk_terminal/technical_analysis/overlap.py
- terminal.py
This PR does several things, the main one is replacing the source of the historical prices when loading a stock.
This is because of 2 things:
- Alpha Vantage restrictions are much harsher than Yahoo Finance
- AV: 5 API requests per minute; 500 API requests per day
- Yahoo Finance API requests are limited to 2,000 requests per hour per IP (or up to a total of 48,000 requests a day)
- Yahoo Finance provides stocks on the NSE (India) which has been required by #61
Note: It's still possible to use AV data, but by default YF will be used. The only "issue" with YF is the fact that the data tends to be generally shorter, this shouldn't be a problem anyway because the data provided by YF should be good enough for all functionalities of the terminal.
Note2: If we're playing with intraday data, and …
> Get main data from yahoo finance

- gamestonk_terminal/discovery/disc_menu.py
- gamestonk_terminal/due_diligence/dd_menu.py
- gamestonk_terminal/fundamental_analysis/fa_menu.py
- gamestonk_terminal/prediction_techniques/pred_menu.py
- gamestonk_terminal/sentiment/sen_menu.py
- gamestonk_terminal/technical_analysis/ta_menu.py
- terminal.py
I expanded the history and autocomplete to the other menus.
Also, I added nested dictionaries for word completion. Right now every command is atomic. There's no other suggestions once you type the first word.
**TODO**:
Add autocomplete to the command options, e.g.,: `view [-h] -t S_TICKER [-s S_START_DATE] [-i {1,5,15,30,60}] [--type TYPE]`
I also used VSCODE "organize imports"... Sorry for the mess in the PR.
> Another go with the prompt_toolkit

- gamestonk_terminal/prediction_techniques/fbprophet.py
Using prophet as is is giving a 
"['date'] not in index"
Checking the object, the index is actually Date.
> Fixing prophet run

- gamestonk_terminal/README.md
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/prediction_techniques/README.md
- gamestonk_terminal/prediction_techniques/arima.py
- gamestonk_terminal/prediction_techniques/ets.py
- gamestonk_terminal/prediction_techniques/fbprophet.py
- gamestonk_terminal/prediction_techniques/knn.py
- gamestonk_terminal/prediction_techniques/neural_networks.py
- gamestonk_terminal/prediction_techniques/pred_helper.py
- gamestonk_terminal/prediction_techniques/pred_menu.py
- gamestonk_terminal/prediction_techniques/regression.py
- gamestonk_terminal/prediction_techniques/sma.py
The code is a bit of a mess, but it's working :)
The user enters in "backtesting mode" when it sets the flag "-e" for end_date when in prediction.
The different features are:
- Normal plot shows what is the actual data vs the predicted
- A new plot that shows in better detail actual data vs predicted, and error in percentage
- Prints the actual data vs predicted vs error percentage
- Prints some KPIs, such as RMSE, MAE, MAPE
> Backtesting prediction

- ROADMAP.md
- gamestonk_terminal/discovery/README.md
- gamestonk_terminal/discovery/ark_api.py
- gamestonk_terminal/discovery/disc_menu.py
- gamestonk_terminal/discovery/yahoo_finance_api.py
Top losers: 
@aia ark_order was failing due to no data in https://cathiesark.com/ark-funds-combined/complete-holdings when "combined" filter is selected. Not sure why, since ARKK, ARKW, ARKF, ... are not empty.
> Add losers command on discovery menu

- README.md
- gamestonk_terminal/prediction_techniques/README-gpu-accel.md
- gamestonk_terminal/prediction_techniques/README.md
- gamestonk_terminal/prediction_techniques/fbprophet.py
- gamestonk_terminal/prediction_techniques/neural_networks.py
- terminal.py
- Fix terminal colors not rendering under Windows cmd.exe 
- Fix uncommon issue where 'date' column would be named 'Date', breaking fbprophet predictions. Didn't bother investigating, just lowercased the column names.
- Add documentation for GPU acceleration in TensorFlow for GamestonkTerminal (under pred)
- Refactor out common code from NN definitions (made the file less than half as long)
- Print exception traces for NNs
- Add a few new flags to NN (documented)
- Add some missing loss functions to NNs (there are more, but I chose some common ones)
- Add documentation links to --help menu for NNs within pred
> Add NN options, simplify code, minor fixes

- gamestonk_terminal/comparison_analysis/yahoo_finance_api.py
- gamestonk_terminal/prediction_techniques/arima.py
- gamestonk_terminal/prediction_techniques/ets.py
- gamestonk_terminal/prediction_techniques/fbprophet.py
- gamestonk_terminal/prediction_techniques/knn.py
- gamestonk_terminal/prediction_techniques/neural_networks.py
- gamestonk_terminal/prediction_techniques/regression.py
- gamestonk_terminal/prediction_techniques/sma.py
Added scaling to arima, ets, fbprophet, knn, nn, regression, sma and historical yahoo_finance_api.
Left corr at yahoo-finance_api untouched, as i think corr maps work best as squares.
> Added scaling to arima, ets, fbprophet, knn, nn, regression, sma and historical yahoo_finance_api

- .github/workflows/Mac.yml
- .github/workflows/test.yml
- .github/workflows/windows.yml
- gamestonk_terminal/feature_flags.py
- gamestonk_terminal/menu.py
This patch resolves the issue that was causing interactive plots to hang when prompt_toolkit is used by registering [matplotlib.pyplot.draw()](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.draw.html) as the input hook for the prompt session, which means the graphs will get updated whenever the prompt is blocked waiting for input. It will still be necessary to use the feature flag to disable prompt toolkit for batch scripts (since it expects a tty and doesn't work if stdin is just a file) but for the interactive use case this should enable both prompt_toolkit and plt.ion to coexist peacefully so it can work as the default. I checked with basic (view) plots and it appears to work well.
Potentially unblocks #177.
> Registers pyplot.draw as inputhook for prompt_toolkit

- README.md
- poetry.lock
- pyproject.toml
- terminal.py
see commit messages, 
- lib wrangling
- documentation for common issue workarounds
- support initial commands from stdin
Example command line usage: `python terminal.py "load -t gme"`
Example usage with `launch.json` in vscode (better dev experience)
```json
{
"version": "0.2.0",
"configurations": [
{
"name": "Python: GamestonkTerminal",
"type": "python",
"request": "launch",
"cwd": "${workspaceFolder}",
"program": "${workspaceFolder}/terminal.py",
"args": ["load", "-t", "gme"],
"console": "integratedTerminal",
"env": {
"GTFF_ENABLE_PREDICT": "True", 
"GT_API_KEY_ALPHAVANTAGE": "myfakeapikey",
},
}
]
}
```
For "full" stdin support, would be good to have:
- multiple commands: `python terminal.py "load -t gme && pred && lstm -i 128 --batch_size 128"`
- support for standard operators
```bash …
```
> Fix tf libs issue, add basic support for stdin

- notebooks/templates/econ_data.ipynb
The strength of the US Dollar is another good indicator of the general economy. This PR adds US dollar vs Euro and Yen to the econ data in papermill.
> Add US Dollar strength against the Euro and Yen to the econ data

- ROADMAP.md
- gamestonk_terminal/comparison_analysis/README.md
- gamestonk_terminal/comparison_analysis/ca_controller.py
- gamestonk_terminal/comparison_analysis/finbrain_api.py
- gamestonk_terminal/comparison_analysis/market_watch_api.py
The new commands allow:
Also, fixed a bug that was adding the main ticker to the list of similar companies when selecting one of the financials command.
> Add Sentiment area under Comparison Analysis

- ROADMAP.md
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/prediction_techniques/README.md
- gamestonk_terminal/prediction_techniques/neural_networks.py
- gamestonk_terminal/prediction_techniques/pred_helper.py
This aims to implement #240 .
As default I chose to plot the median prediction values. And filled the area between quantile 10 and 90%
Examples shown below:
> Enable median/quantiles around loop of Neural Networks predictions

- README.md
- gamestonk_terminal/config_terminal.py
- gamestonk_terminal/due_diligence/README.md
- gamestonk_terminal/due_diligence/dd_menu.py
- gamestonk_terminal/due_diligence/news_api.py
This change was required due to #255 because:
1. Finviz only gives news titles + link, not sorted
2. Finviz is limited in the sources by focusing on Yahoo Finance mainly
News API seems to be the right way to go with this
> Change news source from Finviz to News API

- gamestonk_terminal/portfolio/port_controller.py
I don't like Robinhood either, but not everyone who is going to use/see this in the future is going to have the same context. Let's keep the code clean and professional.
> remove "fuck these guys" from Robinhood

- gamestonk_terminal/behavioural_analysis/README.md
- gamestonk_terminal/behavioural_analysis/reddit_view.py
This attempts to solve the issue mentioned in #275 
The commands that used the function `psaw_api.search_submissions` and the parameter `after` are not working as before. Once removing this parameter it works fine. I just commented it out, we can revisit this at a later stage
> Remove after param from psaw, because it's breaking reddit api

- ROADMAP.md
- gamestonk_terminal/discovery/disc_controller.py
- gamestonk_terminal/technical_analysis/README.md
- gamestonk_terminal/technical_analysis/finviz_view.py
- gamestonk_terminal/technical_analysis/ta_controller.py
While looking into finviz API I found this graph interesting, which is the same as `candle` but with some more info around. 
I thought it would be good to also have a view command with the support/resistance trendlines in the technical analysis menu, and thought that we could add this so that we have another source of data, and not the same repeated command.
Let me know if you disagree, regarding:
- Having a view command on technical analysis
- Not using the same source as `candle` with a really similar outcome
> Add view command to technical analysis with trendlines

- ROADMAP.md
- gamestonk_terminal/screener/README.md
- gamestonk_terminal/screener/screener_controller.py
- gamestonk_terminal/screener/yahoo_finance_view.py
Add `historical` command to screener menu, to allow to visualise stocks. Limit to 10, otherwise too noisy.
Had to add a workaround because YahooFinance API rate limit fails to download several stocks.
Looks like this:
> Add view to screener data

- gamestonk_terminal/comparison_analysis/ca_controller.py
This is for the case when more than 10 similar companies
are available. This allows getting better representation compared to
always getting the first 10 similar companies from the list that's
ordered alphabetically
> Randomize similar companies before selecting 10 for analysis

- ROADMAP.md
- gamestonk_terminal/README.md
- gamestonk_terminal/comparison_analysis/README.md
- gamestonk_terminal/comparison_analysis/ca_controller.py
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/portfolio_optimization/README.md
- gamestonk_terminal/portfolio_optimization/optimizer_helper.py
- gamestonk_terminal/portfolio_optimization/optimizer_view.py
- gamestonk_terminal/portfolio_optimization/po_controller.py
- gamestonk_terminal/screener/README.md
- gamestonk_terminal/screener/finviz_view.py
- gamestonk_terminal/screener/screener_controller.py
- gamestonk_terminal/screener/yahoo_finance_view.py
- gamestonk_terminal/technical_analysis/README.md
See https://github.com/DidierRLopes/GamestonkTerminal/tree/picky-po/gamestonk_terminal/portfolio_optimization
Doesn't change the program functionality (apart from the fact that there's a new optimization command + from screener it is possible to jump to PO carrying last screened stocks), it's mostly details in user usage/visualization.
> Big-ish PO refactoring

- ROADMAP.md
- gamestonk_terminal/README.md
- gamestonk_terminal/discovery/README.md
- gamestonk_terminal/discovery/disc_controller.py
- gamestonk_terminal/discovery/seeking_alpha_model.py
- gamestonk_terminal/discovery/seeking_alpha_view.py
Here is my first attempt at contributing to this awesome project!
I find it useful to see the latest _stock_ news. Seeking Alpha page https://seekingalpha.com/market-news was used as a source of articles, which is also quite lively and up to date.
Two commands were introduced to the `disc` menu (maybe there is better place to have this?)
```
market_news    latest news [SeekingAlpha]
news_article   news article [SeekingAlpha]
```
The `market_news` command will fetch the aforementioned web page and take out article titles and present user with the list of titles, URLs and IDs. For example:
```
(✨) (disc)> market_news
3682093 - National Retail Properties declares $0.52 dividend ( https://seekingalpha.com/news/3682093-national-retail-properties-declares-0_52-dividend )
3682101 - Oxford …
```
> add market_news and news_article to disc menu

- gamestonk_terminal/discovery/README.md
- gamestonk_terminal/discovery/seeking_alpha_model.py
- gamestonk_terminal/discovery/seeking_alpha_view.py
User can specify the starting date of the articles to print for `latest` command.
```
(✨) (disc)> latest -h
usage: latest [-i N_ID] [-n N_NUM] [-d N_DATE] [-h]
Latest news articles. [Source: Seeking Alpha]
optional arguments:
-i N_ID, --id N_ID    article ID number
-n N_NUM, --num N_NUM
number of articles being printed
-d N_DATE, --date N_DATE
starting date
-h, --help            show this help message
```
Today/Latest:
```
(✨) (disc)> latest -n 3
2021-04-17 12:53:25 - 3682747 - Goldman, Morgan Stanley signal plans for crypto ‘disruption’: Alpha Tactics
https://seekingalpha.com/news/3682747-goldman-morgan-stanley-signal-plans-for-crypto-disruption-alpha-tact
2021-04-17 11:21:31 - 3682759 - Apple could launch new iPad Pro, iMac models at Spring Loaded event …
```
> Improve seekingalpha news

- ROADMAP.md
- gamestonk_terminal/due_diligence/README.md
- gamestonk_terminal/due_diligence/dd_controller.py
- gamestonk_terminal/due_diligence/sec_view.py
First attempt at providing fails-to-deliver data from SEC as proposed in #362.
Load ticker, go into `dd` menu, use `ftd` command.
```
(✨) (dd)> ftd -h
usage: ftd [-n N_NUM] [-h]
Prints latest fails-to-deliver data. [Source: SEC]
optional arguments:
-n N_NUM, --num N_NUM
number of latest fails-to-deliver being printed
-h, --help            show this help message
```
By default return 10 latest dates with FTD data.
```
(✨) (dd)> ftd
Date  Quantity
2021-03-31     14031
2021-03-30     17841
2021-03-29     86859
2021-03-26     62109
2021-03-25     20295
2021-03-24     38387
2021-03-23     83058
2021-03-22     17163
2021-03-19       637
2021-03-18     32220
```
No support for custom start date as it complicates things for lazy me today.
> Add fails-to-deliver data

- gamestonk_terminal/options/chains_view.py
Nice to have vega and gamma aslo displayed in the options chain, as these greeks are quite important when making choices.
> Add vega, gamma and theta to option chains display

- README.md
This is a small note addition to the readme on 
following a request from discord chat
> Add a hint on adding the reddit api credentials

- .readthedocs.yaml
- docs/Makefile
- docs/code.rst
- docs/conf.py
- docs/index.rst
- docs/make.bat
- docs/requirements.txt
- gamestonk_terminal/forex/fx_controller.py
- requirements-full.txt
The PR includes configuration files and text templates for building autogenerated documentation with Sphinx. This implementation uses the Read-the-docs theme. A yaml config is provided to enable automatic building of the documentation on readthedocs.io
> Add sphinx based documentation

- .pre-commit-config.yaml
- .secrets.baseline
- README.md
The following PR is a successor of #404. I messed things up, and it was easier to create a new PR then wrestle with git-diffs. 
This PR contains pre-commit-hooks for:
1.  `black`
2.  `flake8`
3.  `codespell`
4. `mypy` (should be compatible with `black` now)
5.  `pylint`
6.  `detect-secrets` (I've added a `.secrets-baseline` file, which the pre-commit hooks compares the codebase against)
> Adding pre-commit-hooks 

- gamestonk_terminal/README.md
- gamestonk_terminal/government/README.md
- gamestonk_terminal/government/gov_controller.py
- gamestonk_terminal/government/quiverquant_model.py
- gamestonk_terminal/government/quiverquant_view.py
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/main_helper.py
- gamestonk_terminal/screener/finviz_view.py
- gamestonk_terminal/screener/screener_controller.py
- gamestonk_terminal/screener/yahoo_finance_view.py
- terminal.py
This PR does:
* Fix absolute path to access screeners. This way the user can run terminal from anywhere, as presets folder is assessed relatively.
* Add Senate and House trading, and not only Congress.
* Add possibility to saw last days of transactions for a particular ticker for senate, house, and both (congress).
* Fix view command for subsequent tickers
> Government menu to also have house and senate trading

- pyproject.toml
Hi, this let run the command `gst` from anywhere in the `virtualenv` instead of having to call `terminal.py`
> Make `gst` executable

- .github/workflows/test.yml
Speaking about Python versions.
Should we drop python 3.6? What about FBProphet 0.6?
> Add Python 3.9 remove Python 3.7

- poetry.lock
- pyproject.toml
- requirements-full.txt
- requirements.txt
Fix PR - https://github.com/GamestonkTerminal/GamestonkTerminal/pull/461.
Tensorflow version was updated, however tensorflow was erroneously pulled as a main dependency.
In pyproject.toml
Incorrect - 
```
tensorflow = "2.5"
```
Correct -
```
tensorflow = {version = "2.5.0", optional = true}
```
To update versions of specific optional packages the process is the following
1. Remove the old dependency with poetry:
```
poetry remove tensorflow 
```
2. Add a new version with poetry as optional:
```
poetry add --optional tensorflow==2.5.0
```
3. Regenerate requirements with poetry:
```
poetry export -f requirements.txt  -o requirements.txt --without-hashes
poetry export -f requirements.txt  -o requirements-full.txt --extras prediction --without-hashes
```
> Move tensorflow into optional

- README.md
`conda create --file environment.yml -n gst` won't work. This command tries to parse every line in the `environment.yml` as a package name.
You should use` conda env create --file environment.yml -n gst`.
> Fixing conda environment creating command

- gamestonk_terminal/main_helper.py
- gamestonk_terminal/options/presets/README.md
- gamestonk_terminal/options/presets/template.ini
- gamestonk_terminal/options/syncretism_view.py
- gamestonk_terminal/screener/presets/README.md
- gamestonk_terminal/screener/screener_controller.py
This PR:
* Adds **How to add preset** sections to the **Screener/presets** and **Options/presets** READMEs. 
* Updates Options screener based on Syncretism API update. The owner contacted us on Discord to say he liked the terminal, and let us know about the change and the future data we'll be able to extract from his website: https://ops.syncretism.io
> Add How to add preset README sections

- gamestonk_terminal/behavioural_analysis/twitter_view.py
- gamestonk_terminal/comparison_analysis/ca_controller.py
- gamestonk_terminal/comparison_analysis/finbrain_view.py
- gamestonk_terminal/discovery/disc_controller.py
- gamestonk_terminal/fundamental_analysis/yahoo_finance_view.py
- gamestonk_terminal/government/quiverquant_view.py
- gamestonk_terminal/options/presets/template.ini
- gamestonk_terminal/options/syncretism_view.py
- gamestonk_terminal/papermill/README.md
- gamestonk_terminal/papermill/papermill_controller.py
- gamestonk_terminal/residuals_analysis/ra_controller.py
This PR contains following bugixes (reported by @octoshrimpy):
- Add darkpool command in help, which was missing
- Call help after picking model on Residual Analysis
- Add another check in gov/house to see if there's no recent data
- op screener README improved + empty dataframe error message
- Fail gracefully when no fa/sust data
- Fail straight when wrong twitter API key provided
- ca/sentiment to still work if last ticker doesn't exist
It also adds a README file to papermill, since some users didn't know how to use it.
> A bunch of bugfixes

- gamestonk_terminal/due_diligence/market_watch_view.py
Due diligence `warnings --debug` output multiplies long-term debt by 5 rather than net income [as specified by Sean Seah](https://www.drwealth.com/gone-fishing-with-buffett-by-sean-seah/comment-page-1/).
The actual test used to generate warnings is correct, so this patch updates debug output to print the same computations.
> Fix dd warnings debug output

- .gitattributes
This should avoid the project being considered as 20% HTML, without having to remove the example files. @aia 
Relied on this: https://stackoverflow.com/questions/34713765/github-changes-repository-to-wrong-language
> This should make so that the project is considered as python only

- .gitignore
- gamestonk_terminal/README.md
- gamestonk_terminal/economy/README.md
- gamestonk_terminal/economy/econ_controller.py
- gamestonk_terminal/economy/wsj_model.py
- gamestonk_terminal/economy/wsj_view.py
- gamestonk_terminal/etf/README.md
- gamestonk_terminal/etf/etf_controller.py
- gamestonk_terminal/etf/screener_model.py
- gamestonk_terminal/etf/wsj_model.py
- gamestonk_terminal/etf/wsj_view.py
- gamestonk_terminal/wsj_functions.py
- poetry.lock
Based on a discord request, which was the have some kind of global market menu based on https://www.tradingview.com/markets/ .  
Instead of a new menu, I am just adding functions to the econ menu. This PR scrapes and prints the different data available on wsj.com/market-data.
It also includes movers for ETFs/mutual funds which I included in the etf menu.
Given the architecture change that is going on, I just put all the wsj functions in a 'common' file that lives in /gamestonk_terminal/.    I can change the file structure to be more consistent with what has been done
> Add market overview - type data form WSJ

- terminal.py
This is just to avoid weird issues if the user is somehow without internet connection.
> Test user internet connection

- gamestonk_terminal/config_terminal.py
I was having the issue that `load_dotenv()` wasn't reading the only .env file in the current directory.  
I just made a quick fix that points to the .env file if it is present
> Specify the path to .env file for using dotenv

- gamestonk_terminal/README.md
- gamestonk_terminal/discovery/README.md
- gamestonk_terminal/discovery/disc_controller.py
- gamestonk_terminal/economy/finnhub_view.py
Title.
- Changed events sorting so it displays closest events first
- Deleted disc->ratings from options.  Marketbeat code still there.
> Change `events` sorting and make `ratings` legacy

- gamestonk_terminal/common/exploratory_data_analysis/rolling.py
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/stocks/exploratory_data_analysis/eda_controller.py
A small proposal here: Using pandas_ta to include rolling metrics in eda. Though it could be on ta menu, I think it is more suitable to place it in eda as these calculations are definitely not exclusive to ta discourse. Besides, it aligns better with the existing calculations in eda. 
Let me know what you guys think before I go further with this subsection
> add rolling metrics to eda

- tests/test_portfolio_optimization/test_optimizer_view.py
Temporarily disable problematic tests.
test_efficiet_return is failing on Windows with:
```
Windows fatal exception: access violation
Current thread 0x00002038 (most recent call first):
File "c:\Users\av\git\GamestonkTerminal\gamestonk_terminal\portfolio\portfolio_optimization\optimizer_view.py", line 682 in efficient_return
File "c:\Users\av\git\GamestonkTerminal\tests\test_portfolio_optimization\test_optimizer_view.py", line 63 in test_efficient_return
...
```
test_show_ef is failing with:
```
......Windows fatal exception: code 0xc0000374
Current thread 0x00003b04 (most recent call first):
File "C:\Users\av\anaconda3\envs\gst388\lib\site-packages\pypfopt\plotting.py", line 248 in plot_efficient_frontier
File "c:\Users\av\git\GamestonkTerminal\gamestonk_terminal\portfolio\portfolio_optim …
```
> Disabling tests that result in access violations

- DOCKER_ADVANCED.md
- README.md
This PR adds the documentation for pulling the latest tag from the ghcr.io and running.
The DOCKER_ADVANCED goes into the env_files and the X Server.  My description of setting up the x server may be kind of confusing, but I could not get it to work with a single DISPLAY env variable, so feel free to PR on this with alternative approaches.
> Add docker documentation

- gamestonk_terminal/forex/forex_controller.py
- terminal.py
This addresses #746 and allows for (example) s to be input instead of stocks.
Also commented out forex eda stuff so that the menu doesn't crash. Added TODO of incorporating common qa menu.
#750 was not on main branch so I am doing this instead.
> Allow for shorthand menu input

- gamestonk_terminal/stocks/stocks_controller.py
Instead of searching for the term "COST", "AAPL", ... on the news, which may lead to incorrect articles popping. We get the name of the company from the ticker, and search for that on the news instead. This leads to a better search.
> Improve news to address #767

- gamestonk_terminal/options/syncretism_model.py
There was a bug in options screener when a ticker was provided.
The issue was in how I tested in the ticker was okay.  When reading in key, value fro the config parser, the value was actually `'"AMC"'` not just `"AMC"`, so I passed eval(Ticker) into the finance to check its valid.
> Fix options scr bug

- gamestonk_terminal/portfolio/portfolio_optimization/optimizer_helper.py
- gamestonk_terminal/portfolio/portfolio_optimization/optimizer_model.py
- gamestonk_terminal/portfolio/portfolio_optimization/optimizer_view.py
- gamestonk_terminal/portfolio/portfolio_optimization/po_controller.py
The portfolio maxsharpe command assumed a risk-free rate of 2%, but I updated it to be a risk-free rate determined by the scraping the current US T-Bill rate. 
Note: while doing this I found an existing error. Using any rate other than 0.02, whether through my new formula or specifying -r, throws an error:
`/Users/colindelahunty/Desktop/GamestonkTerminal/env/lib/python3.8/site-packages/pypfopt/efficient_frontier/efficient_frontier.py:409: UserWarning: The risk_free_rate provided to portfolio_performance is different to the one used by max_sharpe. Using the previous value.` 
I could not find a solution to this error after 1.5 hours of searching. And left the print statements showing the values are the same so you guys could see what I was talking about. This issue also arrises in main, so …
> Updated Portfolio Rf rate.

- gamestonk_terminal/stocks/due_diligence/ark_model.py
- gamestonk_terminal/stocks/due_diligence/ark_view.py
- gamestonk_terminal/stocks/due_diligence/dd_controller.py
Asked for on discord.  Added `load` to dd (still requiring a ticker to enter menu).
Also added some empty returns to my command from yesterday.
@DidierRLopes We need to add some kind of printing/exceptions to _models as this function has a few things that could go wrong, but since I can't print in _model I just print out a generic "Something went wrong" which helps nobody.
> Add load to dd and add empty returns to arktrades

- gamestonk_terminal/stocks/stocks_controller.py
Similarly to what was done before, this does the import of a controller module when the user selects such menu. This takes some load from the stocks context menu.
> Improve terminal speed for stocks context

- TROUBLESHOOT.md
This includes a guide how to switch off the experimental installer that
can break the installation process on macOS
> Update poetry troubleshoot docs

- gamestonk_terminal/stocks/due_diligence/finviz_view.py
- terminal.py
@colin99d your quit issue "kind of" gets fixed. I say "kind of" because now you can quit the terminal after multiple resets, BUT you'll receive multiple goodbye messages (one per reset to be more precise).
This is because of line 268 of terminal.py where we call that command after resetting the terminal, which in turn will call that command again, every time we `reset`. This creates a `stack` of returns from that reset function, one per reset. 
I spent a couple of minutes trying a workaround and couldn't find anything. I've had a similar issue in the past but don't remember how I solved it. @aia do you know how to solve this problem?
> Fixes 2 minor issues

- gamestonk_terminal/portfolio/brokers/degiro/degiro_model.py
- gamestonk_terminal/portfolio/brokers/degiro/degiro_view.py
**Reason**
In the requirement files `degiro-connector` was set to a fixed version :
``` toml
degiro-connector = "1.0.0"
```
Somehow today is was upgraded like this :
``` toml
degiro-connector = "^2.0.3"
```
Which seems to make `portfolio` command crash.
**Consequence**
This Pull Request fixes the code to accommodate the version upgrade.
> Fix portfolio : degiro-connector had been upgraded but not the code

- gamestonk_terminal/stocks/dark_pool_shorts/sec_model.py
Bug in ftd,  For whatever reason the most recent ftd wasn't working with the default encoding.  Changed it to iso8859 and it works fine
> Fix ftd encoding bug

- gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py
The additional argument on `parse_known_args_and_warn` is to avoid adding an export everywhere.
Having both makes the code crash as there are 2 arguments with same indicator and variable saved.
> fix sentiment cmds

- gamestonk_terminal/stocks/discovery/disc_controller.py
- gamestonk_terminal/stocks/discovery/financedatabase_view.py
- website/content/stocks/discovery/fds/_index.md
I made a change in the Finance Database that categorises the Market Cap number to either Small Cap, Mid Cap or Large Cap. This is based on [this article](https://www.investopedia.com/investing/market-capitalization-defined/). Could have also added Nano Cap, Micro Cap and Mega Cap but I think for now this is fine and makes more sense.
> Added Market Cap categorisation for the fds function

- gamestonk_terminal/stocks/government/quiverquant_view.py
This should fix #948.  
The umber from quiver quant says ">$5,000,000", so I replaced that with "$5,000,001-$5,000,001".  I wasn't sure what range to use with something that high ¯\_(ツ)_/¯
> fix quiverquant top functions

- gamestonk_terminal/stocks/fundamental_analysis/av_model.py
Addressed #939.
Not sure why, but "Payout ratio" was not in the list of what was pulled down from AV.
> Remove payout ratio from key

- gamestonk_terminal/stocks/dark_pool_shorts/dps_controller.py
- gamestonk_terminal/stocks/dark_pool_shorts/nyse_model.py
- gamestonk_terminal/stocks/dark_pool_shorts/nyse_view.py
- poetry.lock
- pyproject.toml
- requirements-full.txt
- requirements.txt
- website/content/stocks/dark_pool_shorts/volexch/_index.md
- website/data/menu/main.yml
As per Danglewoods request, I have scraped https://ftp.nyse.com/ShortData/ to get data by exchange.
Since there is a lot of data, I only scrape 2021 data and I am currently storing it on mongoldb using my personal free tier (the atlas connection is read only), so I added a note on _view that users should ping me on discord if there are issues (since I can imagine a couple that pop up).
The database will update nightly at some random time (these seem to get posted around midnight).  Also took the approach of having an interactive chart (with a matplotlibflag)  :)
> Add short data by exchange

- gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
- gamestonk_terminal/stocks/stocks_controller.py
Another bug/improvement.  This PR addresses 2 things
1.  `load` was listed in the menu but not implemented.  Now implemented.
2. yahoo finance allows looking at fa stuff using the suffix convention (ie glxy.to).  I now pass through the suffix so that just the yahoo finance can be used.  As shown in screenshot, I add a disclaimer and dim the unusable functions.
> Update fa to account for suffix,  add load

- .github/workflows/test.yml
- .pre-commit-config.yaml
**Reason**
Filling the gap between :
- `pre-commit` : inside `.pre-commit-config.yaml`
- `worklows` : inside `.github/workflows`
**Consequences**
- Merging arguments for the commands : `mypy` and `codespell`
- Sorting alphabetically some arguments
- Adding : `*.txt` skipping for `codespell`
> Updating tests : workflows

- .github/workflows/test.yml
- .pre-commit-config.yaml
**Reason**
- By default `pre-commit run` only checks on staged files.
Executing `pre-commit run --all-files` : there are some unwanted behaviors.
This `Pull Request` is to allow running `pre-commit` on all the files of the project.
- Fixing a bug on `mypy`
**Consequences**
- `trailing-whitespace` and `end-of-file-fixer` : excluding file types
- `mypy` properly exclude `setup.py` files
> Updating tests : workflows + pre-commit

- .pre-commit-config.yaml
This upgrades the pre-commits for
- black
- mypy
- flake8
- pyupgrade
Note this does not fix the local mypy hook issue (even though there is an init file): 
```
gamestonk_terminal/common/prediction_techniques/regression_model.py: error: Duplicate module named "gamestonk_terminal.common.prediction_techniques.regression_model" (also at "./gamestonk_terminal/common/prediction_techniques/regression_model.py")
gamestonk_terminal/common/prediction_techniques/regression_model.py: note: Are you missing an __init__.py? Alternatively, consider using --exclude to avoid checking one of them.
```
> Update pre-commit hooks to be up to date for linter

- gamestonk_terminal/common/prediction_techniques/arima_view.py
- gamestonk_terminal/common/prediction_techniques/ets_view.py
- gamestonk_terminal/common/prediction_techniques/knn_view.py
- gamestonk_terminal/common/prediction_techniques/mc_view.py
- gamestonk_terminal/common/prediction_techniques/neural_networks_view.py
- gamestonk_terminal/common/prediction_techniques/pred_helper.py
- gamestonk_terminal/common/prediction_techniques/regression_view.py
- gamestonk_terminal/cryptocurrency/crypto_controller.py
- gamestonk_terminal/cryptocurrency/cryptocurrency_helpers.py
- gamestonk_terminal/cryptocurrency/prediction_techniques/pred_controller.py
Been losing money using the stock prediction?  Well now you can lose even more when the markets are closed or just cuz.
This PR integrates the common prediction functions into crypto stuff.
Some notes:
- The crypto loading is still a bit of a mystery to me, so I am defaulting to loading from CoinGecko when entering the prediction menu.  This is a clear TODO.
- All of the prediction views got a time_res added to them so that timestamps that are less than daily can be plotted.  Another TODO is to integrate these with intraday stock data.  Not in the scope here.
- Kind of roundabout, but to do smaller timestamps, the user can `load` in the prediction menu.  Since I limit to just cg, I didn't think it made sense to add this to load, also since other sources can specify a resolution, but for …
> (Finally) add prediction abilities to crypto

- gamestonk_terminal/stocks/comparison_analysis/ca_controller.py
- gamestonk_terminal/stocks/comparison_analysis/finbrain_model.py
- gamestonk_terminal/stocks/comparison_analysis/finbrain_view.py
- gamestonk_terminal/stocks/comparison_analysis/finviz_compare_view.py
- gamestonk_terminal/stocks/comparison_analysis/marketwatch_view.py
- gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_model.py
- gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_view.py
- gamestonk_terminal/stocks/screener/screener_controller.py
- gamestonk_terminal/stocks/sector_industry_analysis/financedatabase_view.py
- gamestonk_terminal/stocks/sector_industry_analysis/sia_controller.py
- gamestonk_terminal/stocks/stocks_controller.py
This PR refactors comparison analysis menu to not be dependent on a ticker, this allows that we can enter in there easily from screener (will implement after this gets merged) or sector and industry analysis.
Also, I made this menu a bit more robust and improved user experience. Towards a beast of a Gamestonk Terminal 1.0 🚀
> Improve comparison analysis controller to not depend on main ticker

- discordbot/economy/economy_menu.py
Fixes discord error:
```
discord.ext.commands.errors.ExtensionFailed: Extension 'economy.economy_menu' raised an error: ImportError: cannot import name 'feargreed_command' from partially initialized module 'discordbot.economy.feargreed' (most likely due to a circular import) (/Users/james/PycharmProjects/GamestonkTerminal/discordbot/economy/feargreed.py)
```
> Discord : fix ImportError

- gamestonk_terminal/stocks/stocks_controller.py
- gamestonk_terminal/stocks/stocks_helper.py
This PR adds a small improvement to `candle`.  When a ticker is loaded with intraday data, I add range breaks to plotly to only show M-F 930AM-4PM.
Need someone to test that plotly doesn't get weird with timezones...
Was:
Now:
> Improve UI for intraday plotly candle

- pytest.ini
- tests/README.md
- tests/conftest.py
- tests/gamestonk_terminal/stocks/prediction_techniques/conftest.py
- tests/gamestonk_terminal/stocks/prediction_techniques/test_pred_controller.py
- tests/gamestonk_terminal/stocks/prediction_techniques/txt/test_pred_controller/test_menu_quick_exit.txt
- tests/gamestonk_terminal/stocks/prediction_techniques/txt/test_pred_controller/test_menu_system_exit.txt
- tests/gamestonk_terminal/stocks/prediction_techniques/txt/test_pred_controller/test_print_help.txt
- tests/gamestonk_terminal/stocks/prediction_techniques/txt/test_pred_controller/test_switch_help.txt
**Reasons**
- Add test coverage on the package :
- `gametonk_terminal.stocsk.prediction_techniques`
- Fix error in documentation
**Side effects**
- Pytest configuration file were added/updated to skip `prediction` tests by default :
- `tests/conftest.py`
- `tests/gamestonk_terminal/prediction_techniques/conftest.py`
> Tests : Stock > Prediction Techniques + Doc

- gamestonk_terminal/reports/reports_controller.py
- scripts/test_reports.gst
- scripts/test_reports_base.gst
- terminal.py
Upgraded and refactored "reports" context.
Checklist for the menu:
- ~~[ ] usage of export data on parse_known_args_and_warn rather than adding an argument (EXPORT_..)~~ (not applicable)
- ~~[ ] when we can specify a limit of rows or so, always use `-l` or `--limit`~~ (not applicable)
- ~~[ ] when there is a main argument inputing the arg flag can be optional~~ (not applicable)
> Ux upgrade for reports context

- gamestonk_terminal/stocks/backtesting/bt_controller.py
- gamestonk_terminal/stocks/backtesting/bt_view.py
- scripts/test_stocks_bt.gst
- tests/gamestonk_terminal/stocks/backtesting/txt/test_bt_controller/test_print_help.txt
- website/content/stocks/backtesting/whatif/_index.md
- website/data/menu/main.yml
```
(✨) /stocks/bt/ $ whatif
IPO date selected by default.
If you had acquired 1 share of TSLA on 2010-06-29 with a cost of 4.78.
This would be worth 1063.05. Which represents an increase of 22248.85%. 
(✨) /stocks/bt/ $ whatif -n 2.34
IPO date selected by default.
If you had acquired 2.34 shares of TSLA on 2010-06-29 with a cost of 11.18.
These would be worth 2486.98. Which represents an increase of 22243.83%. 
(✨) /stocks/bt/ $ whatif 2021-01-01
If you had acquired 1 share of TSLA on 2021-01-01 with a cost of 729.77.
This would be worth 1062.81. Which represents an increase of 145.64%. 
```
> Add whatif scenario feature

- gamestonk_terminal/feature_flags.py
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/stocks/stocks_controller.py
- gamestonk_terminal/stocks/stocks_helper.py
- gamestonk_terminal/timezone.gst
- poetry.lock
- pyproject.toml
- requirements-full.txt
- requirements.txt
- terminal.py
- tests/gamestonk_terminal/stocks/dark_pool_shorts/test_sec_view.py
This PR does 3 main things:
* When loading a ticker, retrieve exchange, timezone, currency and date time of exchange
* Allows the user to specify it's timezone (either through a command or directly in file) and show it, e.g.
* Adding the date time information before the flair (this is a feature flag)
> improve usage of timezone in terminal

- gamestonk_terminal/common/quantitative_analysis/qa_view.py
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/stocks/quantitative_analysis/qa_controller.py
This allows to add random lines in charts and write text on it. See
Can use this to test `python terminal.py stocks/load aapl/qa/pick adjclose/line`
> interactive line chart and annotation

- gamestonk_terminal/economy/fred/fred_view.py
- gamestonk_terminal/stocks/sector_industry_analysis/sia_controller.py
- tests/gamestonk_terminal/stocks/options/test_yfinance_model.py
Bug in `sia controller` due to `exclude_exchanges` being spelled as `exclude_exhanges`.
Tested that I could access SIA controller.
Remaining, not applicable.
> Fix silly issue with sia controller

- gamestonk_terminal/decorators.py
- terminal.py
I removed terminal.py setting the DEBUG_MODE to "false" if --debug is not included. This allows DEBUG_MODE to be sent as an environment variable. ALSO, I added a print out if there is an error. I think it is important for a user to know there was an error, and personally with the current setup I am often left wondering if there was an error or if the function just lacks output.
Ran the terminal with and without --debug mode for functions that cause errors.
> Improved Debugging

- gamestonk_terminal/jupyter/dashboards/stocks.ipynb
Fixes an issue that does not show one day intraday information on the stocks dashboard.
Fixed the ability to see the information.
> Fixed intraday tickers

- gamestonk_terminal/decorators.py
Allows to use `log_start_end` decorator to controller methods and log only other_args list of arguments.
By testing the top gainers command and see the expected output.
> Methods logging for controllers

- gamestonk_terminal/stocks/stocks_helper.py
Added show_index to the stocks quote function.
Ran pytest.
> Fixed quote bug

- gamestonk_terminal/etf/stockanalysis_view.py
- gamestonk_terminal/stocks/fundamental_analysis/av_view.py
Showed index for `stocks/fa/key` and `etf/holdings`. 
Seeing the index shown.
> Added show_index

- tests/conftest.py
Improved Brotli warning wording to eliminate confusion.
Ran tests.
> Brotli Wording

- discordbot/requirements.txt
- poetry.lock
- pyproject.toml
- requirements-full.txt
- requirements.txt
Look like `pytest-cov` was missing from `dev-dependencies`
With `poetry install` command
> Dev-dependencies : adding pytest-cov

- gamestonk_terminal/common/behavioural_analysis/sentimentinvestor_view.py
Sentiment Investor's API request returned 3 less columns than expected. This caused an error on our side. I made fixes so it's robust against any future missing columns
- [x ] Screenshot of the feature or the bug before/after fix, if applicable.
- [x ] Relevant motivation and context. 
- [x ] List any dependencies that are required for this change.
> Fix bug Sentiment Investment Trend

- gamestonk_terminal/portfolio/portfolio_optimization/optimizer_view.py
- gamestonk_terminal/portfolio/portfolio_optimization/po_controller.py
- tests/gamestonk_terminal/portfolio/portfolio_optimization/test_po_controller.py
#1385 
- Changed some of the legend stuff regarding pypfopt
#1377 
- Added returns after the check if there are 2 tickers of less
#1370
- Add try/except to the portfolio optimization that would catch and display a better error message if the optimization did not work
- I could not reproduce the specific bug but found this while trying to reproduce this one
> Portfolio optimization bugs

- bots/requirements.txt
- poetry.lock
- pyproject.toml
- requirements-full.txt
- requirements.txt
Bumps tensorflow from 2.7.0 to 2.7.1 based on dependabot's recommendations.
> Bump tensorflow version to mitigate vulnerabilities

- bots/requirements.txt
- build/conda/conda-3-8-env-full.yaml
- build/conda/conda-3-8-env.yaml
- poetry.lock
- pyproject.toml
- requirements-full.txt
- requirements.txt
tensorflow 2.7 -> 2.8
statsmodel 1.2 -> 1.3
scipy 1.7 -> 1.8
charset-normalizer 2.0.11 -> 2.0.12
pandas-market-calendars has breaking changes introduced by version 3.3 so the version is locked as "~3.2"
> Bump all deps following breaking changes in multiple libraries

- gamestonk_terminal/stocks/options/syncretism_view.py
Fixes #1426 
- Change colors of two lines so they are distinctively different
- Set limit for x axis
- Fix y labels crowding the scale
> Fix plot stocks/options/grhist

- gamestonk_terminal/stocks/dark_pool_shorts/__init__.py
@piiq noticed this warning when using the API in the Jupyter notebook.
This is due to a controller module being imported to the API wrapper.
> Fix bug "Warning: Input is not a terminal" when using API

- gamestonk_terminal/keys_controller.py
Fixed #1340 
- It's currently throwing another error, which we then thought due to Invalid API Key
> Fix bug setting CMC api key not working under keys menu

- gamestonk_terminal/jupyter/dashboards/dashboards_controller.py
- website/content/jupyter/dashboards/chains/_index.md
- website/content/jupyter/dashboards/correlations/_index.md
- website/content/jupyter/dashboards/shortdata/_index.md
- website/content/jupyter/dashboards/stocks/_index.md
- website/content/jupyter/dashboards/vsurf/_index.md
Added a dark mode. Does not always look great, but that is something we can address in the future. For now this gives users an easy way to interact with voila's --theme=dark argument.
> Added dark mode

- gamestonk_terminal/stocks/comparison_analysis/ca_controller.py
- tests/gamestonk_terminal/stocks/comparison_analysis/test_ca_controller.py
Very easy fix.
The flag wasn't working properly because of the argparse argument used.
> fix no normalization in historical comparison analysis

- gamestonk_terminal/cryptocurrency/defi/llama_view.py
Axis on `gdapps` commands are switched:
PR fixes this by switching Y axis with X axis:
> [Bug] Fixes axis in gdapps command

- .github/workflows/mergestat-data-sync.yml
Same issue as here: https://github.com/GamestonkTerminal/GamestonkTerminal/pull/1446 try reducing again
> MergeStat data sync, reduce per-page to `15` to avoid rate-limit issue

- gamestonk_terminal/alternative/covid/covid_view.py
- gamestonk_terminal/helper_funcs.py
- terminal.py
The `exe` command is able to run:
* exe routines/example_with_inputs.gst -i tsla,fb,goog
* exe example_with_inputs.gst -i tsla,fb,goog
* exe routines/example.gst
* exe example.gst
@Chavithra @LBolte29 do you want to tackle the logging on top of this command? Not sure how you want to tackle it :)
> Add execute routines command to main menu

- gamestonk_terminal/feature_flags.py
- gamestonk_terminal/helper_funcs.py
- gamestonk_terminal/keys_controller.py
- gamestonk_terminal/stocks/due_diligence/dd_controller.py
- gamestonk_terminal/terminal_helper.py
- terminal.py
This should allow to export to any folder regardless of it being:
* Relative path to terminal, e.g. routine_monday
* Absolute path to terminal, e.g. /Users/DidierLopes/Documents/GamestonkTerminal/routine_monday
* Path containing environment var, e.g. ~/Documents/GamestonkTerminal/routine_monday
The export folder is then updated as feature flag and will last for next time terminal is booted up.
If the user provides this path, then the commands are saved like this:
`date_time_context_menu_command.TYPE`
if the user doesn't provide path and is default, commands are saved like this:
`exports/context/menu/command_date_time.TYPE`
This is because if a user selects a folder he is interested in having all data in order of creation in the same place.
In a next PR I will add the user selecting the …
> Customisable export

- .github/workflows/mac.yml
- .github/workflows/test.yml
- .github/workflows/windows.yml
Tests now fail because they do not install bots dependencies.
Unfortunately we can only test this live!!! (Fortunately this only affects Github Actions and not the actual terminal).
> Fixing tests

- gamestonk_terminal/log/collection/log_sender.py
- gamestonk_terminal/log/collection/s3_sender.py
- gamestonk_terminal/log/generation/directories.py
- gamestonk_terminal/loggers.py
- Specific error message : for macOS users who tried to open GST directly from DMG file.
- Handle edge case for Discord Bot log sending.
> Logging : masOS+DiscordBot

- openbb_terminal/common/behavioural_analysis/reddit_view.py
Fixes #1597.
The bug is there :
- File : `openbb_terminal\common\behavioural_analysis\reddit_view.py`
- Function : print_and_record_reddit_post
By running each command related to this function in `/stocks/ba/`.
> Bug : fix #1597

- openbb_terminal_web/README.md
Rename to OpenBB Terminal in web version
N/A
N/A
The project was renamed
None
N/A
Didn't do any of that
Nope
Nope
IDK
IDK
> Rename Gamestonk Terminal to OpenBB Terminal in the web version

- openbb_terminal/forex/forex_controller.py
- openbb_terminal/forex/forex_helper.py
- openbb_terminal/forex/oanda/oanda_controller.py
- openbb_terminal/keys_controller.py
Comment-out not needed checks for `to` and `from` currency.
Add `oanda` forex source in dictionary.
Fix #1608
Can not login using Oanda valid info.
None.
Insert proper environment variables, run terminal in debug mode, and use forex/oanda menu
Try set the account type using `-t`. Now it's renamed to `-at` that stands for account type
Working Oanda account.
No tests, as this is very simple fix, and I'm not sure, if you follow with my reasoning.
Again, it's basic. Enables only login.
No.
No. I have commented out, in my opinion, not needed part of checking for valid currency pair **before** entering Oanda submenu …
> Get into oanda submenu

- .github/workflows/test.yml
- Remove second lintings in further tests to shorten run time.
- Run general linting concurrently with base tests
Ran tests with new setup.
> Shorten CI Time

- openbb_terminal/etf/screener/screener_model.py
There was an issue in reading the `.ini` because the `.ini` was never added to the path this made it so that the results obtained where always the same and thus there was no filtering capability.
Fixes #1704. @deeleeramone
> Fix ETF screener #1704

- openbb_terminal/README.md
Fixing small spelling mistakes
> Fixing sudo command

- openbb_terminal/stocks/stocks_helper.py
I'm the guy on top of the truck.
> minor output formatting

- openbb_terminal/cryptocurrency/onchain/ethplorer_view.py
- openbb_terminal/keys_controller.py
Pylint (at least locally) keeps on complaining about several issues. In this PR I have addressed some of them. If you look at them, it makes sense that pylint complains :)
> Fix some linting errors

- openbb_terminal/cryptocurrency/prediction_techniques/pred_controller.py
#1756 issue fix
In case of stock pred mc command -n arg has type casting by check_positive, but crpto pred mc is not.
So I added it and confirmed issue's error is resolved.
> crypto pred mc command number arg error fix

- openbb_terminal/parent_classes.py
#1729 fix
self.stock.index has pandas datetime and it can be changed to native datetime using to_pydatetime().
becuase of self.start.strftime('%Y-%m-%d'), controller.start must to be set in datetime not str. So I fixed it and confirmed issue's error is resolved.
> controller start set in datetime when load data from iex source

- openbb_terminal/cryptocurrency/defi/coindix_model.py
#1784 fix
Coindix api call has 2 errors. first is SSL error in the issue's screenshot and second is Coindix check user-agent to block python requests(with 403 Forbidden code).
So I changed SSL verify option and user-agent in headers.
SSL error occurred by coindix ssl certificate that only certified api.coindix.com not apiv2.coindix.com. you can check it in your browser.
> fix coindix api call error

- openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
In #1794, it is reported that trying to load cryptos with Binance using small caps letters (e.g. btc vs BTC) for the crypto name, generates an error. This is due to Binance not accepting small caps letters for crypto names. This PR fixes that.
`$> crypto`
`$ crypto> load -c btc --source bin
> Fix crypto loading for Binance

- openbb_terminal/etf/etf_controller.py
- openbb_terminal/mutual_funds/mutual_fund_controller.py
- openbb_terminal/parent_classes.py
Instead of adding the smart attempt at loading everywhere that `load` exists, only restrict it to stocks, crypto, funds and etfs.
> Tidy up autoloading in places

- openbb_terminal/stocks/dark_pool_shorts/dps_controller.py
- tests/openbb_terminal/stocks/dark_pool_shorts/test_dps_controller.py
- tests/openbb_terminal/stocks/dark_pool_shorts/txt/test_dps_controller/test_print_help.txt
- website/data/menu/main.yml
As pointed out in #1836, the volexch function is broken.
The reason for the breaking is that the data was stored on my personal mongodb account which has limited free tier storage.  I have simply run out of storage to keep updating it.
This PR deprecates that function by commenting it out.  This can be added back when a better storage option is found.
> Deprecate stocks/dps/volexch

- openbb_terminal/stocks/backtesting/bt_model.py
- openbb_terminal/stocks/backtesting/bt_view.py
Resolves #1782 and prevents from doing backtesting on intraday data (for now)
the issue in 1782 was that polygon returns dates in GMT timezone and yfinance in ET timezone
> Fix backtesting tz

- openbb_terminal/stocks/options/yfinance_view.py
> Added the legend

- openbb_terminal/helper_funcs.py
- openbb_terminal/reports/equity.ipynb
- openbb_terminal/reports/reports_controller.py
- openbb_terminal/stocks/due_diligence/marketwatch_model.py
We can now early exit a notebook report when an input is not valid. And this logic can all be handled within terminal.
This is how we can do it.
Extra: Fixes `stocks/dd/sec` command and also `openbb.stocks.fa.models.yahoo_finance.get_info`.
> Allow for reports an easy exit when something fails and other fixes

- README.md
I think we should make the Hugo documentation link more clear in the README
This could also be a hyperlink, but I just did this as an idea.
> Make documentation link front and center in readme

- website/content/terminal/stocks/quote/_index.md
The current link for the loaded stocks page is invalid and goes to a 404 page. This is because the URL is incorrect.
I have visited the URL https://openbb-finance.github.io/OpenBBTerminal/terminal/stocks/load/ and confirmed it does not 404.
> Fix a broken link to the load page

- i18n/en.yml
- openbb_terminal/featflags_controller.py
- openbb_terminal/feature_flags.py
- openbb_terminal/parent_classes.py
As per a request on discord, I am hiding the attempt at smart loading (ie user can do `/stocks/aapl` instead of `/stocks/load aapl)  behind a new feature flag.
This allows users to not have to see `trying load canlde` when they mistype candle if they want.
> Add on feature flag for 'smart' loading

- openbb_terminal/stocks/fundamental_analysis/financial_modeling_prep/fmp_view.py
- tests/openbb_terminal/stocks/fundamental_analysis/financial_modeling_prep/txt/test_fmp_view/test_check_output[False-display_enterprise-kwargs_dict2].txt
- tests/openbb_terminal/stocks/fundamental_analysis/financial_modeling_prep/txt/test_fmp_view/test_check_output[True-display_enterprise-kwargs_dict2].txt
This PR re-organizes the rows in the enterprise value report so that they are more logically presented. They previously were presented directly in the order as the data provider returned them, which wasn't great for human consumption. This meant that tickers were down at the bottom of the list and the values that sum to compute EV were not in any reasonable order and the EV itself was intermixed with other numbers, making it hard to identify.
This PR puts the stock ticker and price first, then it puts all the rows below it that sum to be the enterprise value, with the EV at the bottom.
The command is reached with `/stocks/fa/fmp/enterprise` while a ticker has been loaded.
I've tested the change locally and ran it several time with different tickers. The `pre-commit` tests all passed as …
> Clarify values by re-ordering rows in enterprise value report

- openbb_terminal/stocks/stocks_helper.py
This PR enables filtering stock searches by US based exchanges.
The logic on line 213 defaults to USA if there is no exchange symbol present, so the market coverage suffix should use the same logic. This enables filtering by exchange to work correctly.
Without this PR:
With this PR:
I tried several `stocks search <ticker> -e USA` commands.
> Match to USA if no exchange suffix is present

- website/content/terminal/portfolio/load/_index.md
Update the docs with more info about what needs to be in the portfolio files
> Update docs for the load command

- openbb_terminal/stocks/dark_pool_shorts/finra_model.py
Fixed #1886 by changing from append to concat to get rid of future warnings. Tested with:
`pytest tests/openbb_terminal/stocks/dark_pool_shorts/test_finra_model.py --rewrite-expected` 
This did not rewrite any files, so only modifying one file: finra_model.py
> Fixing future warnings bug by switching from append to concat.

- openbb_terminal/parent_classes.py
- terminal.py
Fixes #1945. cntrl+d now exits in an appealing way.
Pressing cntrl+d inside the terminal.
> Fixed cntrld issue

- openbb_terminal/helper_funcs.py
Fixes #1906
This bug stems from trying to calculate the Interest Coverage Ratio but the calculation return inf if it does not have the variables needed for the calculation, which  occurs if the website we are scraping the data from does not have certain data points. This PR addresses this by adding functionality to the `lambda_int_or_round_float` function by identifying if there is an 'inf' and denoting it as '~' when viewing table.
Due to the function being within the `helper_funcs.py` file there was no testing run.
> Fixed warnings bug which does not display data if there is an inf value data point

- openbb_terminal/helper_funcs.py
- openbb_terminal/stocks/comparison_analysis/marketwatch_model.py
- openbb_terminal/stocks/comparison_analysis/marketwatch_view.py
- openbb_terminal/stocks/fundamental_analysis/market_watch_model.py
- openbb_terminal/stocks/fundamental_analysis/market_watch_view.py
This PR gracefully handles errors when certain tickers can't be loaded as part of `/stocks/ca` commands. This can happen for certain tickers like SPY. When a ticker can't be loaded, it is removed from the comparison set and the command continues if possible. An example of what happens is in the screenshot below.
Manual testing and pytest
> Handle errors when tickers can't be loaded

- openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
Fixes stock price and metrics by reversing the dataframe being loaded from #1993 . Note that candle has already been fixed
Before:
After:
> Fixes stock price and metrics in #1993

- i18n/en.yml
Changed menu so that users know what command to use to add a new api key. Specifically told users to see the help dialogue for each key because some keys need optional arguments such as the reddit api which needs client id, client secret, etc.
> Changing menu dialogue for keys menu to be more apparent on how to add an api key

- README.md
- openbb_terminal/README.md
The point of the new one is:
- It's faster (x2) making it easier for users to see everything that is available.
- It shows more functionalities. It does skip Crypto though but the previous one also had limited options over there! @minhhoang1023, might need to re-do if you got some suggestions from commands that look interesting in a GIF? Preferences?
- It is completely up to date with the latest release.
Added this one since it's also going to be in the presentation for Open Source Finance Forum 2022.
Also did some misc fixes:
- README of installation on GitHub was outdated with broken links
- Refreshed the "First step is to star" image
> Add in a new GIF that better demonstrates the terminal

- i18n/en.yml
- openbb_terminal/economy/economy_controller.py
- openbb_terminal/economy/fred_model.py
- openbb_terminal/economy/yfinance_view.py
- openbb_terminal/reports/equity.ipynb
- openbb_terminal/reports/reports_controller.py
- tests/openbb_terminal/economy/txt/test_economy_controller/test_print_help.txt
I have refactored a bit economy menu, waiting for feedback.
> Improve economy menu

- openbb_terminal/stocks/fundamental_analysis/fa_controller.py
Adds a warning telling users we do not get quarterly data with yfinance.
Made sure message was displayed.
> Fix yf FA quarterly issue

- .github/workflows/intel_macos_build.yml
Changed workflow to be `workflow_dispatch` and added integration tests.
> Adding integration tests to intel mac workflow

- openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
- openbb_terminal/cryptocurrency/due_diligence/glassnode_view.py
Fixes labels in #2018 and updates default dates for plots to from 2 years ago to 1 year ago (wherever the free glassnode api only allows fetching data with a 1y lag)
Before:
After:
> Fixes #2018 and updates default dates in dd_controller.py

- data_sources_default.json
- tests/openbb_terminal/stocks/dark_pool_shorts/test_dps_controller.py
#2052
Updates stocks submenus to have a default source in the json.
Ran load in all submenus.  Crypto submenus were working though....
> Update data sources json to allow submenu loading

- terminal.py
#2054
This code served no purpose but to mess with us
```
if obbff.ENABLE_EXIT_AUTO_HELP and len(t_controller.queue) > 1:
t_controller.queue = t_controller.queue[1:]
```
Also:
> Stop consuming first element of list

- i18n/en.yml
- openbb_terminal/portfolio/brokers/degiro/degiro_controller.py
- openbb_terminal/portfolio/brokers/degiro/degiro_model.py
- openbb_terminal/portfolio/brokers/degiro/degiro_view.py
- tests/openbb_terminal/portfolio/brokers/degiro/test_degiro_controller.py
- tests/openbb_terminal/portfolio/brokers/degiro/txt/test_degiro_controller/test_print_help.txt
- tests/openbb_terminal/portfolio/brokers/degiro/txt/test_degiro_view/test_help_display.txt
Trying to implement a CSV export that could be used from PA Menu.
Setting Degiro credentials.
Then running:
`portfolio/bro/degiro/paexport --start 2022-01-01`
> Portoflio : add pa export command for Degiro

- README.md
The 'OpenBB-finance/OpenBBTerminal' repository doesn't contain the 'openbb_terminal/CONTRIBUTING.md' path in 'main'.
CONTRIBUTING.md link was pointed to openbb_terminal folder, when it was supposed to be pointed to the main folder
Also both are pointing to master folder, and they are being redirected via "Branch not found, redirected to default branch." :
Maybe update to https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/CONTRIBUTING.md ?
but either way https://github.com/OpenBB-finance/OpenBBTerminal/tree/master/CONTRIBUTING.md would still redirect correctly
At least for me clicking the link in the current repo goes to the wrong link
Current link
https://github.com/OpenBB-finance/OpenBBTerminal/tree/main/openbb_terminal/CONTRIBUTING.md
-> wrong path
New link Options …
> Fast Merge - Updating README.md from top folder, CONTRIBUTING.md wrong link

- i18n/en.yml
- openbb_terminal/portfolio/portfolio_controller.py
- tests/openbb_terminal/portfolio/txt/test_portfolio_controller/test_print_help.txt
In the 'portfolio' context for the 'po' category it read "optimal your portfolio weights efficiently". It would be better/more clear to say "optimize your portfolio weights efficiently". There is no issue or bug related to this as it is purely a wording update.
* All three locations/files where this wording occurred have been checked and confirmed to be correct and matching.
* Ran tests/portfolio/test_portfolio_controller.py and all tests (most importantly test_print_help) passed
* No features were added. Only text change. 
* None
> Corrected wording

- openbb_terminal/common/quantitative_analysis/qa_view.py
- openbb_terminal/stocks/quantitative_analysis/qa_controller.py
its a small / extra small feature
Simple change to  VaR function for stocks, this will allow users to use data ranges for the analysis
This way you wont need to load amazon 3 times, to make the analysis from 2019 to today, this month and this week
Check Command Documentation..............................................Passed
check yaml...........................................(no files to check)Skipped
fix end of files.....................................(no files to check)Skipped
trim trailing whitespace.............................(no files to check)Skipped
check for merge conflicts................................................Passed
detect private key.......................................................Passed
black................................................................... …
> adding data range for VaR

- openbb_terminal/portfolio/portfolio_model.py
- openbb_terminal/portfolio/portfolio_view.py
- tests/openbb_terminal/portfolio/txt/test_portfolio_controller/test_print_help.txt
Fixes the "Could not preprocess orderbook." message on portfolio help menu being displayed by default.
> Fixes error message on portfolio menu help

- openbb_terminal/econometrics/econometrics_controller.py
- openbb_terminal/reports/equity.ipynb
* Fixes #2081
* Fixes #2096 - it was a quick one
> Make sec fillings link clickable in report

- openbb_terminal/economy/economy_controller.py
- website/content/terminal/economy/fred/_index.md
changed 'seaarch' to 'search' in two places for the economy help message. because this seemed like a typo to me.
> fix typo - change 'seaarch' to 'search'

- .gitignore
Adds jupyterlab build folders to .gitignore. Currently the build process when setting up creates build folders when following [jupyterlab instructions](https://github.com/OpenBB-finance/OpenBBTerminal/blob/main/jupyterlab/README.md).
Resolves #2121 
Personal testing. This is just a git addition and affects development operations.
> [Feature] (XS DevOps) Add jupyterlab build folders to .gitignore.

- openbb_terminal/economy/economy_controller.py
- openbb_terminal/economy/fred_model.py
- openbb_terminal/economy/fred_view.py
This PR fixes the --raw and --export outputs when `ycrv --source FRED --raw --export csv` is used. Currently, those flags only work for the default source `investpy`. If user picks FRED he cannot display raw data or export it to csv. 
Test:
ycrv --source FRED -d 2021-01-04  --raw --export csv
> Fix ycrv to allow raw display and export when source is FRED

- website/content/terminal/economy/_index.md
- Just replaced "https://openbb-finance.github.io/OpenBBTerminal/terminal/common/quantitative_analysis/" by "https://openbb-finance.github.io/OpenBBTerminal/terminal/common/qa/"
> Fix link for Quantitative Analysis

- openbb_terminal/README.md
- Add a line about how to fix SyntaxError while running the command to start terminal
- I faced this issue when I tried to open the terminal for the first time
> improve readme file for terminal

- openbb_terminal/economy/econdb_model.py
rm line 500 because spaces cannot be parsed from the command line anyway.
now it's able to match for keywords like "denmark" instead of "Denmark" to the dictionary.
same as "parameter". parsing "ppi" now will be "PPI", matching the dictionary.
> better match for econ param parse to dict

- bots/telegram/run_telegram.py
Just made small improvements in Telegram bot script to make variables more clear.
> Small improvement in Telegram script

- openbb_terminal/stocks/fundamental_analysis/dcf_view.py
> Fixed DCF Handling

- openbb_terminal/stocks/fundamental_analysis/av_view.py
- openbb_terminal/stocks/fundamental_analysis/fa_controller.py
- tests/openbb_terminal/stocks/fundamental_analysis/test_fa_controller.py
The stocks/fa/key call does not handle the `--export` parameter even though it is documented.
**Before**
**After**
Running `stocks` >> `load goog` >> `fa` >> `key --export xlsx` after the change saves an export file which does not get exported without this change.
Running `stocks` >> `load goog` >> `fa` >> `key --export xlsx`, no file is exported.
N/a
> [Bugfix/Stocks/KeyMetricsExport] Add export call to FA key metrics controller

- openbb_terminal/economy/economy_api.py
- openbb_terminal/stocks/quantitative_analysis/beta_model.py
Fixes #2138
Gave fix to user and then it worked.
> Added ycrv command

- openbb_terminal/stocks/quantitative_analysis/beta_model.py
- Fixes TypeError when importing openbb in Python or trying to load qa module in terminal
- Solves #2189
- Manually checking that no errors are raised for:
```python
from openbb_terminal import api as openbb
```
>  \>>
```bash
python terminal.py
stocks
load AAPL
qa
```
>  $
> Fix TypeError in /stocks/quantitative_analysis/beta_model

- openbb_terminal/keys_controller.py
- tests/openbb_terminal/test_keys_controller.py
Fixes #2186
@deeleeramone I have no way of testing this, can you please see if it fixes.
By Darren (:.
> Added fixes for coinbase

- openbb_terminal/stocks/due_diligence/fmp_model.py
- openbb_terminal/stocks/due_diligence/fmp_view.py
- tests/openbb_terminal/stocks/due_diligence/txt/test_fmp_view/test_rating.txt
Fixes #2195 by showing what the error received and makes the chart that is printed show in color (removed a TODO)
> Improved verbosity of dd rating failure, and add color to the chart

- openbb_terminal/stocks/behavioural_analysis/ba_controller.py
- tests/openbb_terminal/stocks/behavioural_analysis/txt/test_ba_controller/test_print_help.txt
> Fixed Jim Cramer

- openbb_terminal/economy/economy_controller.py
- openbb_terminal/economy/investingcom_model.py
> Fixes ecocal command

- i18n/en.yml
- openbb_terminal/stocks/comparison_analysis/ca_controller.py
- openbb_terminal/stocks/comparison_analysis/marketwatch_model.py
- openbb_terminal/stocks/options/screen/screener_controller.py
- openbb_terminal/stocks/screener/screener_controller.py
- openbb_terminal/stocks/stocks_controller.py
- tests/openbb_terminal/stocks/comparison_analysis/test_ca_controller.py
- tests/openbb_terminal/stocks/comparison_analysis/txt/test_ca_controller/test_print_help.txt
- tests/openbb_terminal/stocks/options/test_screener_controller.py
- tests/openbb_terminal/stocks/options/txt/test_screener_controller/test_print_help.txt
- tests/openbb_terminal/stocks/screener/test_screener_controller.py
- tests/openbb_terminal/stocks/screener/txt/test_screener_controller/test_print_help.txt
* Fixes #2257
* Remove `po` shortcut from `ca` controller
> Remove portfolio optimisation shortcut

- website/content/terminal/common/qa/_index.md
This updates the Quantitative Analysis section of the documentation.
> Adds Intro Guide to QA menu

- .pre-commit-config.yaml
Pylint was in our pre-commit twice. Removing the second time.
> Removed second copy of pylint

- .github/release-drafter.yml
- .github/workflows/draft.yml
Creates a draft release on demand. To run, navigate 'Release Drafter' in Github Actions and click 'Run Workflow'. The draft release includes:
- Title with new version
- New version tag
- List of contributors
- List of commits/changes
- Links to socials/website/etc
Individuals completing the release process simply need to attach the correct release files and proof-read the draft.
> Adding draft release workflow

- openbb_terminal/stocks/insider/insider_controller.py
- openbb_terminal/stocks/insider/openinsider_view.py
Fixes #2274 
Ran the export and saw the results.
> Fixes insider stats export

- .github/workflows/test.yml
> fix x-small: pyupgrade --py38-plus

- openbb_terminal/mutual_funds/avanza_model.py
- openbb_terminal/mutual_funds/avanza_view.py
- openbb_terminal/mutual_funds/investpy_model.py
- openbb_terminal/mutual_funds/investpy_view.py
- openbb_terminal/mutual_funds/mutual_fund_controller.py
- openbb_terminal/mutual_funds/yfinance_model.py
- openbb_terminal/mutual_funds/yfinance_view.py
> Fund refactor

- website/content/terminal/stocks/options/_index.md
- website/content/terminal/stocks/options/hist/_index.md
- website/content/terminal/stocks/options/load/_index.md
- website/content/terminal/stocks/options/oi/_index.md
- website/content/terminal/stocks/options/voi/_index.md
- website/content/terminal/stocks/options/vol/_index.md
Website documentation fixes:
1. `-s` does not exist for stocks/options, must use --source
2. per _data_sources_default.json_, fixed incorrect references to sources in the options module:
-`tr`  must be full name: `tradier`
-`ce` must be full name: `chartexchange`
3. Whitespace removal (end of line, etc.)
Functions and `--help` information are already correct, we just needed to correct the website docs
- docs don't match actual behavior (difficult for new users)
- Tradier no longer offers developer-only licenses, brokerage accounts are required, so Yahoo finance may be a preference
- none
* viewed the relevant markdown files in github after pushing to my fork
* Please also list …
> [docs] removed -s flag from documentation

- routines/fa_demo.openbb
Fixes #2398: Updates Fundamental Analysis Demo Routine to allow for refactoring of menu. 
One adjustment has been made to require a ticker argument, `-i ticker`.
`exe fa_demo.openbb -i MS`
> Updates Fundamental Analysis Demo Routine - Routine now requires ticker argument

- .pre-commit-config.yaml
- openbb_terminal/dashboards/correlation.ipynb
- openbb_terminal/dashboards/shortdata.ipynb
- tests/openbb_terminal/core/log/generation/test_formatter_with_exceptions.py
`pre-commit autoupdate ; pre-commit run --all-files`
Avoid `fwe` because `codespell` treats it as a typo.
> feat x-small: pre-commit autoupdate ; pre-commit run --all-files

- routines/fa_demo.openbb
- terminal.py
I believe #2399 has been fixed, but I realised that if the user run a script that expected parameters this was not flagging as an issue, neither if the number of parameters was under the number of params required by the script. 
So I added this.
> Makes running exe files more robust 

- openbb_terminal/helper_funcs.py
- openbb_terminal/parent_classes.py
With the forward slash fix (@piiq), the access to the root directly using "/" was lost, and also to fast switching menus, e.g. "/crypto/load btc/dd". This PR fixes that.
> Allow home access "/" from anywhere

- openbb_terminal/settings_controller.py
- website/content/_index.md
* Fix #2345 and allows to export custom folder
> Improve export folder to custom one

- openbb_terminal/portfolio/portfolio_optimization/optimizer_view.py
Fixes #2372. The issue was with stocks with corrupted data also being added to the frontier df causing a mismatch in sizes between returns and frontier dfs
ef of SP500 portfolio
> Fix: issue #2372

- openbb_terminal/portfolio/portfolio_model.py
During portfolio loading, adds last traded date in historical prices if last date isn't available. This is a very odd time dependent off by 1 error, so testing this might be difficult.
#2450 
> Bug: Fix same-day error for portfolio historical trades.

- openbb_terminal/config_terminal.py
- styles/default/light.mplrc.json
This 👆
To validate you can run the following in a notebook:
> Fix light terminal stylesheet that would prevent using it in notebooks

- data_sources_default.json
- openbb_terminal/reports/equity.ipynb
- openbb_terminal/stocks/fundamental_analysis/fa_controller.py
- openbb_terminal/stocks/fundamental_analysis/yahoo_finance_model.py
- openbb_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
- tests/openbb_terminal/stocks/fundamental_analysis/test_fa_controller.py
- tests/openbb_terminal/stocks/fundamental_analysis/txt/test_fa_controller/test_print_help.txt
Here ya go dangle
#2485 
```
Historical Earnings for AAPL                     
┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Earnings Date          ┃ EPS Estimate ┃ Reported EPS ┃ Surprise(%) ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ Oct 26, 2022, 4 PMEDT  │ 1.26         │ nan          │ nan         │
├────────────────────────┼──────────────┼──────────────┼─────────────┤
│ Jul 28, 2022, 12 PMEDT │ 1.16         │ 1.2          │ +3.27       │
├────────────────────────┼──────────────┼──────────────┼─────────────┤
│ Apr 28, 2022, 12 PMEDT │ 1.43         │ 1.52         │ +6.44       │
├────────────────────────┼──────────────┼──────────────┼─────────────┤
│ Jan 27, 2022, 11 AMEST │ 1.89         │ 2.1          │ +11.17      │ …
```
> Add yf for fa/earnings

- openbb_terminal/cryptocurrency/discovery/discovery_controller.py
Fixed argument mismatch in display_cmc_top_coins() and changed --descend default to false.
> [bug] fixes cmc top coins issue #2470

- build/pyinstaller/terminal.spec
Fixes #2524. Seems like some modules can seemingly get lost in translation when using pyinstaller. Will have to look out for similar bugs like this in the future if they arise.
> Adding feedparser to spec file

- openbb_terminal/common/feedparser_model.py
News command does not run every time. This patches it by making the command run until either data is returned from feedparser or it hits a timeout.
> Patching news command 

- openbb_terminal/api.py
- openbb_terminal/config_terminal.py
- openbb_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
- openbb_terminal/stocks/stocks_helper.py
This PR fixes some small details on the api and reverts default plot style to boring
openbb.economy.get_ycrv_countries()
openbb.economy.get_events_countries()
import datetime
openbb.stocks.candle("GME", add_trend=True, ma=[20, 50, 100], start_date=datetime.datetime(2020, 10, 18), asset_type="This is")
> Minor fixes in API usage

- openbb_terminal/stocks/discovery/disc_helpers.py
- use manipulation of returned HTML string via regex to clean up yahoo HTML request. The radio button gives an extra 'Select TICKER' prompt (see screenshot) 
- import module re
- replace whole `class=\"Fz\(0\)\" span` from HTML request
Tested functions on local machine in jupyter notebook with  `python 3.10.5` and `pandas 1.4.3`.
> fix get_df for output in stocks/disc

- openbb_terminal/config_plot.py
Fixes #2676 - although the variable was being written to the user_env_file, it didn't load the user_env_file while setting the variables in the terminal
> fix: error #2676

- openbb_terminal/economy/econdb_model.py
Scale of China's population given in Tens of thousands, which is missing in SCALES list. 
https://www.econdb.com/series/context/?tickers=popcn
> fix: bug #2691

- i18n/en.yml
- openbb_terminal/parent_classes.py
- terminal.py
https://user-images.githubusercontent.com/25267873/193699845-a8225906-67ed-4391-b90f-8996333f5a84.mp4
> Add record session into routine capabiltiies

- openbb_terminal/cryptocurrency/discovery/dappradar_model.py
- openbb_terminal/cryptocurrency/discovery/dappradar_view.py
- tests/openbb_terminal/cryptocurrency/discovery/txt/test_dappradar_view/test_call_func[display_top_dexes-kwargs2].txt
- tests/openbb_terminal/cryptocurrency/discovery/txt/test_dappradar_view/test_call_func[display_top_nfts-kwargs0].txt
- tests/openbb_terminal/cryptocurrency/discovery/txt/test_dappradar_view/test_call_func_empty_df[display_top_dapps-kwargs3-get_top_dapps].txt
- tests/openbb_terminal/cryptocurrency/discovery/txt/test_dappradar_view/test_call_func_empty_df[display_top_dexes-kwargs2-get_top_dexes].txt
- tests/openbb_terminal/cryptocurrency/discovery/txt/test_dappradar_view/test_call_func_empty_df[display_top_games-kwargs1-get_top_games].txt
- tests/openbb_terminal/cryptocurrency/discovery/txt/test_dappradar_view/test_call_func_empty_df[display_top_nfts-kwargs0-get_top_nfts].txt
Fixes #2701 
- `python terminal.py crypto/disc/drdapps`
> Improved error handling for crypto commands

- openbb_terminal/core/config/paths_helper.py
- openbb_terminal/feature_flags.py
- terminal.py
Fixes bug where installer cannot utilize the `data_sources_dafeault.json` within `OpenBBUserData` because it is empty. This solution copies either the git repositories data sources file or installer data sources file into `OpenBBUserData`. This means users can keep their data sources when they update the repo or the installer.
To recreate the issue, remove the `OpenBBUserData` folder and try to run a previous installer.
> Data Sources Default Installer Bug Fix

- openbb_terminal/rich_config.py
- openbb_terminal/sources_controller.py
Previously, the installer was running into an error where it was not loading in the `data_sources_default.json` correctly. 
The file is located in `OpenBBUserData` folder on the user's machine, however it is empty. This is on purpose. If the user does not purposefully populate this file in some way, then the terminal *should* use the default sources provided by OpenBB. This bug demonstrates that this is not the case for the installer. It always looks at the sources file in the user data folder. This PR fixes this by always opening the provided default sources from the correct location first (in the case of the installer`.OpenBB/`) and then if there is content within the user data sources file, then it will utilize that.
This has been tested by creating an installer and doing the …
> Data Sources Fix for Installer: Second Try

- i18n/en.yml
- openbb_terminal/common/technical_analysis/momentum_model.py
- openbb_terminal/common/technical_analysis/momentum_view.py
- openbb_terminal/stocks/technical_analysis/ta_controller.py
- tests/openbb_terminal/stocks/technical_analysis/txt/test_ta_controller/test_print_help[None].txt
- tests/openbb_terminal/stocks/technical_analysis/txt/test_ta_controller/test_print_help[start0].txt
- website/content/terminal/common/ta/demark/_index.md
- website/data/menu/main.yml
This will fix #2249 and by fix, I mean this will implement the demark indicator.
This plot is pretty busy and I chose to use the ohlc instead of candle in mpf intentionally.  This results in a less busy plot as mentioned in the discussion in that thread.
> Add demark indicator to stocks/ta

- openbb_terminal/helper_funcs.py
When running python through command line I get this error when trying to `screenshot` a plot:
This PR fixes it by being explicit about the images locations. This do not occurs in VScode level.
*Open terminal on command line
*Create any random plot
*`screenshot`
> Fix screenshot not finding images

- i18n/en.yml
- openbb_terminal/mutual_funds/investpy_model.py
- openbb_terminal/mutual_funds/mutual_fund_controller.py
Fixes #2820 and allows users to type `forecast` to move the data into the forecast menu.
> Fix fund bug and add forecast menu command

- i18n/en.yml
- openbb_terminal/forex/forex_controller.py
- openbb_terminal/stocks/stocks_controller.py
- tests/openbb_terminal/forex/txt/test_forex_controller/test_print_help.txt
As request by @DidierRLopes, people can now load forex data right into the forecast menu. Also did some minor refactoring.
> Improves the forex menu to include the `forecast` command

- .github/workflows/gh-pages.yml
- openbb_terminal/dashboards/voila/stocks.ipynb
Fixes #2839 
The report was running into issues because yfinance only includes time zone information if the interval is less than one day. I fixed this issue by always removing the timezone from the data.
Note: I also updated the gh-pages yaml to avoid issues with our CI, however I do not see this affecting our codebase adversely (the version of Ubuntu now matches that in every other pipeline)
- Ran `python terminal.py dashboards/stocks -n` and set interval to `1h`
- No need, this does not affect the api
- No need, this does not affect reports
> Fixed stocks dashboard tz issue

- openbb_terminal/forecast/forecast_controller.py
If user has imported an earlier version of `darts`, notify them to update so that they can continue using the menu.
> Notify users of old `darts` version

- openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
The controller for `crypto/dd/mkt` was using invalid parameter names. I fixed this by changing `symbol` -> `from_symbol` and `currency` -> `to_symbol`. 
Fixes #2846 
Testing was limited due to the small scope of this change.
- Ran `python terminal.py crypto/load btc/dd/mkt`
- Ran the following lines in jupyter-lab:
- `from openbb_terminal.api import openbb`
-  `openbb.crypto.dd.mkt()`
- Ran `python terminal.py reports/crypto eth`
> Fixed `crypto/dd/mkt` controller uses bad parameter names

- openbb_terminal/terminal_helper.py
Fixes #2776 
Currently this command checks the obff.VERSION against our current release number on Github. The issue is that we add an "m" the obff.VERSION after we modify the installer. However we do not add an "m" to the release. To fix this I replaced the "m" with "". In the future it would be better to increment the minor release number.
- Ran `python terminal.py` to ensure the terminal still works
- Not directly affected, ran `from openbb_terminal.api import openbb` to ensure the api still works
- Not directly affected, did not test.
> Attempting to improve accuracy of latest version message

- openbb_terminal/econometrics/econometrics_controller.py
Previously running `OLS -h` or `panel -h` before loading any data would throw an error.
This initializes the self.choices["regressions"] so that we can do OLS -h or panel -h
> Initialize econonmetrics choices so that -h can be used

- openbb_terminal/terminal_controller.py
Since the update does not do anything on installer, can we hide it?
> Eliminate `update` for packaged app

- .github/workflows/intel_macos_build.yml
- .github/workflows/m1_macos_build.yml
- .github/workflows/windows10_build.yml
The location of the scripts folder was changed, so I am updating the path for build automations.
This image demonstrates that the scripts folder is not running all of the scripts. They were moved to `openbb_terminal/miscellaneous/scripts/`.
> Updating Integration Tests Path

- openbb_terminal/forecast/forecast_controller.py
- openbb_terminal/forecast/forecast_model.py
Now files exported during the current session can be imported into the forecast menu. This is done by switching the variable for all files into a function, which means we are always getting up to date information.
This PR should have minimal affects on the rest of the terminal. However, it does affect a controller and a model, so testing need to be done to ensure this functionality still works.
- `python terminal.py "stocks/load AAPL --export csv"' -> `q` -> `forecast/ load [name of csv from above]`
- `from openbb_terminal.api import openbb`
- `openbb.forecast.load("chavi.csv")`
- `python terminal.py reports/forecast tsla`
> Allow for newly exported files to be loaded

- .github/workflows/test.yml
- .pre-commit-config.yaml
- openbb_terminal/miscellaneous/data_sources_default.json
- openbb_terminal/miscellaneous/i18n/en.yml
- openbb_terminal/mutual_funds/mutual_fund_controller.py
Fixes al_swe poriton of #2913. Basically just did find/replace all instances of al_swe with alswe. No-regeneration of documentation because of the command being ignored by pre-commit hooks.
> Alswe command name change

- openbb_terminal/stocks/quantitative_analysis/qa_controller.py
Fixes #2966 
Also fixed the choices for the "pick" autocomplete so that they are actually the names of the columns
```
stocks
load aapl
qa
acf -l 3  (The warning appears)
pick adjclose (Notice here the autocomplete options)
acf -l 3 (The warning does not appear. The plot shows adjclose data instead of returns)
```
> Fix "Target not AdjClose" warning incorrectly appearing

- openbb_terminal/miscellaneous/data_sources_default.json
- openbb_terminal/miscellaneous/i18n/en.yml
- openbb_terminal/miscellaneous/scripts/test_stocks_ba.openbb
- openbb_terminal/sdk.py
- openbb_terminal/stocks/behavioural_analysis/ba_controller.py
- tests/openbb_terminal/stocks/behavioural_analysis/test_ba_controller.py
- tests/openbb_terminal/stocks/behavioural_analysis/txt/test_ba_controller/test_print_help.txt
- website/content/SDK/stocks/ba/spacc/_index.md
- website/content/terminal/common/ba/spacc/_index.md
- website/data/menu/main.yml
Changing name from spac_c to spacc. Updated test files using --rewrite-expected.
Command working:
> Spacc command name change (part 2)

- openbb_terminal/stocks/government/quiverquant_view.py
Updated the table helper function to be called with explicit float precisions
Fixes #2953
> fix for #2953 Qty and Year showing up as floats instead of int

- openbb_terminal/cryptocurrency/due_diligence/binance_view.py
- Fixes: https://github.com/OpenBB-finance/OpenBBTerminal/issues/2997
- Checking dataframe using `not df` raises error. Replace it with condition `df is None`
> Fixed bug giving exception when calling balance in crypto

- openbb_terminal/config_terminal.py
- openbb_terminal/core/log/generation/settings.py
- openbb_terminal/sdk.py
> SDK to be logged as config parameter

- openbb_terminal/futures/futures_helper.py
- openbb_terminal/futures/yfinance_view.py
- openbb_terminal/sdk.py
Fixes #3005 
The futures menu was importing some incorrect paths in the SDK, and the charts shown in the SDK were not formatted properly. This PR fixes this.
- `python terminal.py futures/search`
- `python terminal.py historical TRM`
- `python terminal.py historical TRM,CL`
- `python terminal.py curve TRM`
- `openbb.futures.search(chart=True)`
- `openbb.futures.historical(["NG", "ALI"], chart=True)`
- `openbb.futures.historical(["NG"], chart=True)`
- `openbb.futures.curve("NG", chart=True)`
> Fixed issues with Futures menu

- openbb_terminal/etf/etf_controller.py
- openbb_terminal/helper_funcs.py
- openbb_terminal/stocks/stocks_controller.py
This makes it much easier to grab data when we want to use it within forecasting menu (fyi @martinb-bb @colin99d )
Also fixes export image, the `export_data` func needs to be called at the end after png is created (fyi @piiq )
> Improve export to be all in same folder

- openbb_terminal/alternative/covid/covid_controller.py
- openbb_terminal/economy/alphavantage_view.py
- openbb_terminal/futures/futures_controller.py
- openbb_terminal/futures/yfinance_model.py
- openbb_terminal/futures/yfinance_view.py
- openbb_terminal/sdk.py
Okay so what I got is small
- Fixes #3149 
```
2022 Oct 31, 21:38 (🦋) /futures/ $ curve
usage: curve -t Futures symbol [-h] [--export EXPORT] [--raw]
curve: error: the following arguments are required: -t/--ticker
```
- Fixes #3147 (not the auto complete part)
```
2022 Oct 31, 21:38 (🦋) /futures/ $ historical -h
usage: historical [-t TICKER] [-s START] [-e EXPIRY] [-h] [--export EXPORT] [--raw]
Display futures historical. [Source: YahooFinance]
optional arguments:
-t TICKER, --ticker TICKER
Future ticker to display timeseries separated by comma when multiple, e.g.: BLK,QI (default: )
-s START, --start START
Initial date. Default: 3 years ago (default: 2019-11-01 21:39:35.833968)
-e EXPIRY, --expiry EXPIRY
Select future expiry date with format YYYY-MM (default: )
-h, --help            show …
```
> Spoooooky bugs - Futures menu ++

- website/content/terminal/futures/_index.md
Attempting to resolve this:
Proposed solution is an additional line between content and embedded image.
> Formatting, first image is not given a new line.

- website/data/menu/main.yml
Fixes #3262
Renamed the duplicate NFT section to OV.
`cd website/`
`hugo server -D`
> Fixed docs

- openbb_terminal/reports/reports_controller.py
Fixes #3123
Replaced the link from sdk to SDK.
I installed the terminal without the forecast dependencies and then tried to run the forecasting menu. I clicked the link that was created as a result.
> Fixed links

- openbb_terminal/economy/economy_controller.py
- website/content/terminal/economy/plot/_index.md
Fixes #2974
Removed the --raw option from the plot function on economy. If users want to see the raw data they can navigate to qa/raw. 
`python terminal.py "economy/plot -h"`
> Removed the --raw option from economy/plot

- openbb_terminal/custom_prompt_toolkit.py
This is definitely not the hard work of @andrewkenreich spending hours debugging prompt toolkit :)
This seems to address some of the issues in #3128
> Reset the auto-complete options in custom prompt

- openbb_terminal/base_helpers.py
- openbb_terminal/config_plot.py
- openbb_terminal/config_terminal.py
- openbb_terminal/feature_flags.py
Fixes #2865
Currently an environment variable with an incorrect type can cause the entire terminal not load This is a big issue for non technical users who will not be able to manually edit the environment variables. This PR fixes that by replacing any bad keys with the defaults we have already decided on. 
I also added `openbb_terminal/base_helpers.py`. This file is a place for helper functions that do not need to import other modules from inside the terminal, preventing the circular import error.
ALSO, while I was fixing this I found an issue with `python terminal.py source/get`, so I also fixed that.
If this PR does something incorrect it could have large negative affects on the entire terminal. To test the PR itself works I gathered every environment variable that had its type …
> Handle Bad Environment Variables

- openbb_terminal/custom_prompt_toolkit.py
- openbb_terminal/stocks/options/screen/syncretism_model.py
- openbb_terminal/stocks/options/screen/syncretism_view.py
Fixes #3282 
This pr adds error handling for someone sending a string instead of a float for the strike price. It also handles a strike price being provided that is not valid.
Also allows`view_screener_output` to handle bad greek options gracefully.
Fixes #3276
Adds handling for when the limit is a string and not an integer. Also forces the argparse for limit to be an integer. Lastly, it adds the datetimeindex to the output of raw.
Also adds some minor styling updates
- `python terminal.py "stocks/load gme/options/exp 2/grhist -s 22.5"`
- `python terminal.py "stocks/load spy/options/exp 1/grhist --strike 450.0 -g …
> Improves Error Handling for option.grhist

- build/conda/conda-3-9-env-full.yaml
- poetry.lock
- pyproject.toml
No need to set it. Darts now checks for the latest (1.2.0)
> removing explicit `statsforecast` version from conda and fixing numpy

- pyproject.toml
Adding some additional links to our website, docs, and repo to `pyproject.toml` based off of https://python-poetry.org/docs/pyproject/. Additionally updating the pyproject "readme" to point to  `openbb_terminal/SDK_README.md` instead of the regular `README.md`.
N/A. Changes will be reflected next time we publish to Test-PyPi.
> Small pyproject changes

- openbb_terminal/common/technical_analysis/momentum_view.py
fix #2963 - changes legend size here to fit better on macd and a few others - I haven't tested this when a user changes their stuff
> fixing macd and a few others

- openbb_terminal/forecast/expo_model.py
- openbb_terminal/forecast/forecast_controller.py
- website/content/terminal/forecast/autoets/_index.md
- website/content/terminal/forecast/brnn/_index.md
- website/content/terminal/forecast/expo/_index.md
- website/content/terminal/forecast/linregr/_index.md
- website/content/terminal/forecast/nbeats/_index.md
- website/content/terminal/forecast/nhits/_index.md
- website/content/terminal/forecast/regr/_index.md
- website/content/terminal/forecast/rnn/_index.md
- website/content/terminal/forecast/tcn/_index.md
- website/content/terminal/forecast/tft/_index.md
- website/content/terminal/forecast/theta/_index.md
- website/content/terminal/forecast/trans/_index.md
Users can use the `-h` command on any of the models and show the link to the docs.
Very simple.
This is intended to allow users to understand where underlying model comes from and also the inner workings of it if they choose to explore the docs.
> [UX improvement] Adding in docs URL to help commands on terminal

- openbb_terminal/dashboards/voila/crypto.ipynb
- openbb_terminal/dashboards/voila/currencies.ipynb
- openbb_terminal/dashboards/voila/forecast.ipynb
- openbb_terminal/dashboards/voila/vsurf.ipynb
> fix dashboard imports

- openbb_terminal/miscellaneous/library/trail_map.csv
- openbb_terminal/stocks/fundamental_analysis/fmp_model.py
- openbb_terminal/stocks/fundamental_analysis/sdk_helpers.py
WIP
This PR: changes some SDK mappings.  Check the jira tickets
Makes fa.income 1 command instead of many.
> SDK mapping refactors + FA refactor 

- tests/openbb_terminal/test_sdk.py
This just adds a quick check to make sure the import works.  Will avoid issues in trail map with commas.
> Add a single unit test to check sdk import

- .github/workflows/test.yml
This attempts to stop the tests workflow if there are only changes in the  website folder:
Using this as reference:
> Make docs go fast....maybe?

- openbb_terminal/etf/etf_controller.py
- openbb_terminal/stocks/comparison_analysis/yahoo_finance_model.py
Fixes #3517 by clearing the etf holdings that are shown if the user loads in a new etf. Additionally addresses the "not in index" error , which occurs on the `ca/volume` command and arises by trying to graph *all* of the holding data. However sometimes certain holding data is returned `NaN` by yfinance and as a result, we remove it from the dataframe that we want to graph. 
Load fix
`ca/volume` "not in index" fix
> Small etf bug fixes for `load` and `ca/volume`

- openbb_terminal/miscellaneous/library/trail_map_optimization.csv
This endpoint `openbb.portfolio.po.hcp` was only available in previous po version. I'm removing it to avoid confusing users.
It's not available in the terminal either
> Remove hcp endpoint from SDK

- openbb_terminal/helper_funcs.py
- openbb_terminal/parent_classes.py
See below.  After changing the choices, we get something like in #3508.  The reason is that the refactoring for choices forces the input to be a file type.
By removing this we have the following:
```
2022 Nov 29, 11:56 (🦋) /stocks/ $ load aapl --export aapl1.csv
Loading Daily data for AAPL with starting period 2019-11-25.
Company:  Apple Inc.
Exchange: NASDAQ/NMS (GLOBAL MARKET)
Currency: USD
AAPL Performance                                          
┏━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ 1 Day   ┃ 1 Week  ┃ 1 Month ┃ 1 Year ┃ YTD     ┃ Volatility (1Y) ┃ Volume (10D avg) ┃ Last Price ┃
┡━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩
│ -4.53 % │ -4.67 % │ -0.24 % │ -7.5 % │ …
```
> remove export choices on export argument

- openbb_terminal/cryptocurrency/due_diligence/dd_controller.py
- openbb_terminal/economy/economy_controller.py
- openbb_terminal/economy/fred_model.py
- openbb_terminal/economy/fred_view.py
- openbb_terminal/stocks/behavioural_analysis/ba_controller.py
- tests/openbb_terminal/economy/test_economy_controller.py
Fixes #3670 (Also changes the sdk function slightly)
Fixes #3674
> Bug fixing

- openbb_terminal/stocks/options/op_helpers.py
- openbb_terminal/stocks/options/yfinance_model.py
Closes #3660 and also makes the code a bit more readable & versatile. There is _no_ error with the IV normalization, since this command can only take the data from yahoo finance that already annualizes the IV.
Tried the command with several values and compared the results with https://ops.syncretism.io and https://www.cboe.com/optionsinstitute/tools/options_calculator/.
> Fixing the greeks calculations

- openbb_terminal/forecast/autoarima_model.py
- openbb_terminal/forecast/autoces_model.py
- openbb_terminal/forecast/autoets_model.py
- openbb_terminal/forecast/autoselect_model.py
- openbb_terminal/forecast/mstl_model.py
- openbb_terminal/forecast/rwd_model.py
- openbb_terminal/forecast/seasonalnaive_model.py
When using pre-commit hooks, pylint was snagged by the following errors: 
```
************* Module openbb_terminal.forecast.mstl_model
openbb_terminal/forecast/mstl_model.py 114: E1101 Instance of 'StatsForecast' has no 'cross_validation' member (no-member)
openbb_terminal/forecast/mstl_model.py 123: E1101 Instance of 'StatsForecast' has no 'forecast' member (no-member)
************* Module openbb_terminal.forecast.autoarima_model
openbb_terminal/forecast/autoarima_model.py 101: E1101 Instance of 'StatsForecast' has no 'cross_validation' member (no-member)
openbb_terminal/forecast/autoarima_model.py 110: E1101 Instance of 'StatsForecast' has no 'forecast' member (no-member)
************* Module openbb_terminal.forecast.autoselect_model
openbb_terminal/forecast/autoselect_model.py 147: …
```
> Forecasting Pylint Pre-Commit Error Fixes

- openbb_terminal/stocks/tradinghours/bursa_model.py
append method deprecated. pandas suggest replacing with concat. 
Fixes issue #3707 
load any exchange in the following menu
`/stocks/th/exchange`
future warning no longer shows after method replaced.
> replaced deprecated df.append method with pd.concat

- website/generate_sdk_markdown.py
> [Docs] Fix SDK "openbb..news"

- website/generate_sdk_markdown.py
- website/generate_terminal_markdown.py
- website/package.json
- website/src/theme/CodeBlock/Content/String.js
enables passing `wordwrap` to markdown code block to wordwrap it by default
> fix: wordwrap

- openbb_terminal/stocks/insider/sdk_helper.py
- openbb_terminal/stocks/options/yfinance_model.py
1) Fix the greek calculation in `chains` where we were using .seconds instead of .total_seconds
2) Change the time to expiration calculation in options to be 4PM instead of midnight am (hence the + 16 hours)
3) Fix the typo I reverted from @hjoaquim
> Small options fix + docstring

- openbb_terminal/forecast/forecast_controller.py
- openbb_terminal/forecast/forecast_model.py
Fixes adding True Range command found when using SDK.
`data= openbb.forecast.atr(dataset=data,close_column='Adj Close',high_column='High',low_column='Low')
`
`print(data.head())`
```
Open       High        Low      Close  Adj Close     Volume  \
date                                                                           
2019-12-12  66.945000  68.139999  66.830002  67.864998  66.485832  137310400   
2019-12-13  67.864998  68.824997  67.732498  68.787498  67.389549  133587600   
2019-12-16  69.250000  70.197502  69.245003  69.964996  68.543144  128186000   
2019-12-17  69.892502  70.442497  69.699997  70.102501  68.677849  114158400   
2019-12-18  69.949997  70.474998  69.779999  69.934998  68.513741  116028400   
true_range  
date                    
2019-12-12    1.309998  
2019-12-13 …
```
> hot fix: True Range Feature 

- website/content/terminal/quickstart/installation.md
`docker-compose.yaml` service name was changed to `openbb` from `poetry` but documentation was not updated for all platforms
> Docker installation used wrong service

- openbb_terminal/stocks/options/yfinance_model.py
This makes the greeks calculations in the chains command (with YahooFinance) accurate. Closes #3779. There will still exist a difference between the sources due to different IV values, current asset prices (when the market is open) and so on ..., namely due to the data given.
Running the command and comparing results with Nasdaq, Tradier and the greeks command.
> Fix the greeks calculations of the chain command

- openbb_terminal/helper_funcs.py
overrideing the get_user_timezone() so that the updated timezone variable is used. Previsously openbb needed to be restarted to reflect the change 
https://github.com/OpenBB-finance/OpenBBTerminal/issues/3863
https://user-images.githubusercontent.com/32000834/210728647-83eb69ef-5c30-41ab-8e63-e074ae7854d3.mp4
> Fixing timezone not updating within same terminal session

- openbb_terminal/stocks/quantitative_analysis/beta_model.py
- openbb_terminal/stocks/quantitative_analysis/qa_controller.py
Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/3868
Also solves a small bug when using `--target` to select the field in `qa` menu
> Fix Stocks/QA/beta

- openbb_terminal/economy/economy_controller.py
- openbb_terminal/economy/plot_view.py
- openbb_terminal/miscellaneous/scripts/economy/test_economy.openbb
Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/3838
nance/OpenBBTerminal/issues/3838
Test:
`economy`
`fred SOFR,AMERIBOR`
`eval spread=SOFR-AMERIBOR`
`plot spread`
> Fix plot look when using eval and add query to choices

- .github/workflows/linting.yml
- .github/workflows/unit-test.yml
- tests/test_helpers.py
> Testing Gitflow

- .github/workflows/test.yml
- .pre-commit-config.yaml
Locking ruff at version 0.0.212 for right now, we can bump it regularly.
> Lock ruff version so that new lints dont break our CI

- openbb_terminal/miscellaneous/scripts/economy/test_economy.openbb
Every PR being moved from `main` to `develop` has a conflict with this file. Trying to fix that so we can update those branches
> Rebase develop?

- .github/workflows/branch-name-check.yml
- .github/workflows/unit-test.yml
> Minor Fix for branch name check

- openbb_terminal/forecast/helpers.py
- tests/openbb_terminal/forecast/test_forecast_model.py
Conflict with underlying pytorch-lightning library. 
```Error: Trainer was configured with `enable_progress_bar=False` but found `TQDMProgressBar` in callbacks list.```
Simple fix to avoid conflicts.
> [FIX] Pytorch-lightning trainer conflict with TQDM progress bar

- website/content/sdk/guides/intros/stocks/comparison-analysis.md
Git Flow yelled at me for having a bad branch name, trying again. 
Companies have not finished reporting F/Y 2022 earnings, including `timeframe='2021'` ensures that results are returned.
> SDK Docs: Clarifies the `Stocks.CA.Balance` example by including, `timeframe = '2021'`

- website/generate_terminal_markdown.py
> Adding CMD Flags to Docs Generation

- openbb_terminal/portfolio/portfolio_engine.py
When running the report of the portfolio one thing is very noticable being the close price. For example, Google's price is about 100 and not 150. This was due to a sorting issue when creating a MultiIndex.
<div>
Date | Ticker | Type | Sector | Industry | Country | Region | Price | Quantity | Fees | Premium | Investment | Side | Currency | ISIN | Signal | yf_Ticker | Portfolio Investment | Close | Portfolio Value | Portfolio % Return | Abs Portfolio Return
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- |
2010-05-03 | GOOGL | STOCK | Communication Services | Internet Content & Information | United States | North America | 13.27 | 2 | 5 | 6 | 31.54 | Buy | USD | NaN | 1 | NaN | 31.54 | 154.500000 | 309.000000 | 8.797083 | …
> Fix portfolio engine assigning close values to the wrong tickers

- generate_sdk.py
- openbb_terminal/sdk.py
- openbb_terminal/sdk_core/sdk_helpers.py
- openbb_terminal/sdk_core/trailmap.py
- tests/openbb_terminal/test_sdk.py
> Hotfix/SDK Version Dunder

- openbb_terminal/stocks/stocks_controller.py
Closes #4278 
Fixes the `--help` parameter for the following commands `stocks/candle`, `stocks/tob` and `stocks/news`.
Running the commands following commands:
* `stocks/candle --help`
* `stocks/tob --help`
* `stocks/news --help`
> Fix `--help` for `stocks/candle`, `stocks/tob` and `stocks/news`

- openbb_terminal/portfolio/portfolio_controller.py
Closes #4290 
The error was that the commands name is `om` and not `os`. This was only an error on the portfolio menu help message
Running the command.
> Fix spelling mistake in portfolio menu help message

- .github/workflows/unit-test.yml
- openbb_terminal/SDK_README.md
@jmaslek The issue was that you changed the `uses: actions/checkout@v1` to `uses: actions/checkout@v3`
A current bug within `git` doesn't allow the `diff` command to work with the updated checkout command versions.
> Fix Unit Test

- openbb_terminal/economy/economy_controller.py
- website/content/terminal/reference/economy/eval.md
Closes #4238 by making the `--query` arg in `economy/eval` required. Bug was caused by `ns_parser` not being `NoneType` even if no argument was passed. Given that `--query` has no default value and is dependent on loaded data, it makes sense to require it.
> Set query arg in economy/eval as required

- openbb_terminal/core/log/generation/directories.py
> Hotfix/File Exists Error on `test_directories`

- openbb_terminal/miscellaneous/library/trail_map.csv
- openbb_terminal/sdk_core/controllers/stocks_sdk_controller.py
- openbb_terminal/sdk_core/models/stocks_sdk_model.py
- openbb_terminal/stocks/options/options_sdk_helper.py
Closes #3491 
Adds the option greeks calculations to the SDK.
Running the following SDK code:
```
from openbb_terminal.sdk import openbb
a = openbb.stocks.options.chains("AAPL", source="YahooFinance")
aapl_last_price = openbb.stocks.options.last_price("AAPL")
print(openbb.stocks.options.greeks(aapl_last_price, a, a.iloc[0, 2]))
```
```
from openbb_terminal.sdk import openbb
a = openbb.stocks.options.chains("AAPL", source="Tradier")
aapl_last_price = openbb.stocks.options.last_price("AAPL")
print(openbb.stocks.options.greeks(aapl_last_price, a, a.iloc[0, 2]))
```
> Add options greeks to the SDK

- openbb_terminal/forex/forex_controller.py
Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4095
> Add reverse fx choices to forex load

- openbb_terminal/economy/econdb_model.py
- openbb_terminal/fixedincome/oecd_model.py
Saw this:
```
(🦋) /fixedincome/ $ treasury --long portugal
Error: local variable 'df_short' referenced before assignment
(🦋) /fixedincome/ $ treasury --long portugal
Error: local variable 'df_short' referenced before assignment
(🦋) /fixedincome/ $ treasury --short australia
Error: local variable 'df_long' referenced before assignment
```
So fixed it. Also saw this:
```
(🦋) /economy/ $ macro CPI --transform TPOP
Error: 'CPIUS~TPOP'
Error: not enough values to unpack (expected 2, got 0)
Error: not enough values to unpack (expected 3, got 0)
```
So fixed it.
> Fix long/short issue and fix transform issue

- openbb_terminal/stocks/fundamental_analysis/dcf_view.py
- openbb_terminal/stocks/fundamental_analysis/fa_controller.py
> Fix dcf messages for non-us companies

- CONTRIBUTING.md
- openbb_terminal/core/integration_tests/integration_controller.py
- openbb_terminal/core/log/collection/log_sender.py
- openbb_terminal/core/models/preferences_model.py
^
Change the name of the flag on the user preferences to `LOG_COLLECT` to avoid asking people to change it to the new one.
> Fix the log collection preference name

- openbb_terminal/core/log/generation/settings_logger.py
^
Removes the UserModel from the logs in order to not log sensitive information.
> Patch UserModel on logs

- openbb_terminal/account/account_controller.py
- openbb_terminal/core/models/credentials_model.py
- openbb_terminal/core/models/preferences_model.py
- openbb_terminal/core/plots/backend.py
- openbb_terminal/core/session/credentials_handler.py
- openbb_terminal/core/session/env_handler.py
- openbb_terminal/core/session/preferences_handler.py
- openbb_terminal/featflags_controller.py
- openbb_terminal/keys_model.py
- openbb_terminal/settings_controller.py
- openbb_terminal/terminal_helper.py
> Prefix OPENBB_ for .env vars

- openbb_terminal/loggers.py
^
**Benefit** of having the SessionId as a UUID instead of the UNIX timestamp: avoid having users with the same UserId/AppId with the same SessionId - this would happen in the case of the user launching two terminal instances **exactly** at the same time.
**Side effect**: log files names change from `gst_1678795847.2023-03-14_12.log` to `gst_5b698cdc-4d4d-4b2f-983a-2660cba0ea97-1678795471.2023-03-14_12.log` - this comes with no other consequences, since for the logging etl we're filtering those files using `LastModified` S3 param.
> Decided to add a time based component in the `get_session_id` function to double ensure uniqueness.
> Change `SessionId` to uuid-like format

- openbb_terminal/account/account_controller.py
- openbb_terminal/core/session/hub_model.py
- tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args0-False].txt
- tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args1-True].txt
- tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args2-True].txt
- tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args3-False].txt
- tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args4-True].txt
- tests/openbb_terminal/session/test_hub_model.py
* Fixes `sync` command showing `True`, `False` instead of ON/OFF
* Fixes `logout` command request
* Fixes `list` command choices
* Fix `account` menu autocompletion
> Authentication QA fixes

- openbb_terminal/helper_funcs.py
> Hotfix - `get_monitors()` error when no enumerators available

- openbb_terminal/helper_funcs.py
- openbb_terminal/parent_classes.py
- openbb_terminal/stocks/stocks_helper.py
Fixes: #4280 
The error above will STILL happen because we still NEED to include a ticker symbol, but I did improve:
- Allow `--help` to be used with `load`
- Allow `xlsx` files to be used
> Improve Loading Custom Files

- openbb_terminal/reports/reports_controller.py
Fixes #3127 
Currently the equity report has an ugly exit if there is a "." in the ticker. I added a check in the controller to make the issue more clear.
> Improve handling for dot in ticker

- openbb_terminal/stocks/options/op_helpers.py
- openbb_terminal/stocks/options/options_controller.py
- openbb_terminal/stocks/options/options_sdk_helper.py
- tests/openbb_terminal/stocks/options/test_op_helpers.py
Fixes #3454 
Fixes #4515 
This adds common sense error handling to the options class.
This is going to be VERY time specific, but if you run greeks on TSLA at expo 0 here is what you got before and after this PR:
> Adds Error Handling to the options class

- README.md
> Update Readme for new install links

- openbb_terminal/helper_funcs.py
* Closes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4385
> Catch tweetnews exceptions

- tests/openbb_terminal/alternative/oss/record/http/test_github_model/test_get_github_data.yaml
- tests/openbb_terminal/alternative/oss/record/http/test_github_model/test_search_repos.yaml
> Re-record unit test

- openbb_terminal/parent_classes.py
- website/content/terminal/usage/intros/stocks/index.md
It looks like the yfinance does not work here, so there is no reason to provide a broken option.
> Removes `exchange` option from `stocks/load`

- openbb_terminal/account/account_controller.py
- openbb_terminal/core/session/constants.py
- openbb_terminal/core/session/env_handler.py
- openbb_terminal/core/session/hub_model.py
- openbb_terminal/core/session/session_controller.py
- openbb_terminal/core/session/session_model.py
- openbb_terminal/keys_controller.py
- openbb_terminal/keys_model.py
- tests/openbb_terminal/session/test_hub_model.py
- tests/openbb_terminal/session/txt/test_session_controller/test_display_welcome_message.txt
* Fallback to .env if keys not in hub
* Display correct source (.env(s), hub) hierarchy for keys
* Keys changed in the terminal are only written in the .env
* Point login prompt support link to https://my.openbb.dev/app/terminal/support
> Hub | Fallback to .env + don't upload keys + update support link

- openbb_terminal/core/session/session_model.py
- openbb_terminal/helper_funcs.py
- openbb_terminal/stocks/fundamental_analysis/fa_controller.py
* Makes sure that `exe --file` choices are updated right after login
Test:
* login with `openbb --login` and `account/login` and check that `exe --file` command on `home` menu displays the hub routines (default and personal)
> Fix `exe --file` choices on login

- openbb_terminal/terminal_controller.py
Make the "intro" command calling https://docs.openbb.co/terminal/usage/basics - will also work for first time users.
This provides a better experience to the user instead of reading instructions from within terminal.
We just need to ensure all content that was on the intro is in some way, shape or form in that page.
> make intro spin up pywry window with usage basics

- openbb_terminal/common/technical_analysis/custom_indicators_model.py
- openbb_terminal/core/plots/plotly_ta/plugins/custom_indicators_plugin.py
Fixes #4862. 
Updates `data.index.get_loc` to `data.index.get_indexer`. Converts datetime object to pandas datetime object before calling `to_pydatetime` in fib plotting.
> Fix stocks/ta/fib datetime plotting

- build/pyinstaller/macOS_package_assets/OpenBB Terminal/OpenBB Terminal
- website/content/terminal/installation/docker.md
- website/content/terminal/installation/macos.md
- website/content/terminal/installation/pypi.md
- Point download links for environment and docker artifacts to main instead of a blob
- Clean-up debug echo in macos launcher script
> Update installation docs for release

- openbb_terminal/common/technical_analysis/overlap_view.py
> Fix `stocks/ta/vwap`

- openbb_terminal/core/models/system_model.py
^
So that version shows up no the logs.
Before:
```
SYSTEM: {"OS": "Linux", "PYTHON_VERSION": "3.9.13", "PLATFORM": "my-platform", "LOGGING_APP_ID": "my-app-id", "LOGGING_APP_NAME": "gst", "LOGGING_COMMIT_HASH": "REPLACE_ME", "LOGGING_FREQUENCY": "H", "LOGGING_HANDLERS": "file", "LOGGING_ROLLING_CLOCK": false, "LOGGING_VERBOSITY": 20, "LOGGING_SUB_APP": "terminal", "LOGGING_SUPPRESS": false, "LOG_COLLECT": false, "DISABLE_STREAMLIT_WARNING": true, "DISABLE_FORECASTING_WARNING": true, "DISABLE_OPTIMIZATION_WARNING": true, "TEST_MODE": false, "DEBUG_MODE": false, "ENABLE_AUTHENTICATION": true, "HEADLESS": false} 
```
After:
```
SYSTEM: {"OS": "Linux", "PYTHON_VERSION": "3.9.13", "PLATFORM": "my-platform", "VERSION": "3.0.0", "LOGGING_APP_ID": "my-app-id", "LOGGING_APP_NAME": "gst", …
```
> Adds type to the version on the SystemModel

- website/content/terminal/usage/guides/api-keys.md
This PR makes one very small change to the docs pages, changing the title of the API Keys guide.  The motivation is because the page contains only information on API keys, the title should not be "Settings & API Keys".
> hotfix/docs-api-keys-title - Changes title of page from "Settings & API Keys" to "Setting API Keys"

- openbb_terminal/stocks/stocks_controller.py
Cosmetic fix that replaces the text in the help dialogue under the `--ticker` argument.
Before:
After:
> Hotfix/stocks quote help description: replaces help dialogue description for `--ticker`.

- openbb_terminal/stocks/screener/finviz_model.py
- openbb_terminal/stocks/screener/finviz_view.py
- tests/openbb_terminal/stocks/screener/csv/test_finviz_model/test_get_screener_data[overview].csv
- tests/openbb_terminal/stocks/screener/csv/test_finviz_model/test_get_screener_data_no_limit.csv
- tests/openbb_terminal/stocks/screener/txt/test_finviz_view/test_screener[False].txt
- tests/openbb_terminal/stocks/screener/txt/test_finviz_view/test_screener[True].txt
- tests/openbb_terminal/stocks/screener/txt/test_finviz_view/test_screener_sort_matches[MOCK_SORT].txt
- tests/openbb_terminal/stocks/screener/txt/test_finviz_view/test_screener_sort_matches[Ticker].txt
Resolves #4946
This PR removes commas from the Company field, in the stocks screener results, which were being read as a new column when the raw data was exported. 
Before:
After:
This also addresses an unreported issue where the list of tickers was failing to populate after running a screen.  An error would print to the Terminal screen:
```
(🦋) /stocks/scr/ $ overview
Error: 'Ticker'
```
Upon investigation, this was being caused by the Ticker column having artifacts attached, `\n\n`.
This has been patched in the model.
The list now populates as expected.
> hotfix/stock-screener-remove-delimiter: Gets rid of commas in Company column.

- website/content/terminal/faqs/launching.md
Added: 
Incompatible library version: libtiff.6.dylib requires version 10.0.0 or later, but liblzma.5.dylib provides version 8.0.0
This issue can be resolved by following the steps below.
- Show hidden files
- Command + Shift + . (period)
- Then go to Applications folder > OpenBB Terminal > .OpenBB
- Find the file "liblzma.5.dylib" and remove it.
- Relaunch the terminal.
> Docs/Terminal FAQ: adds libzlma workaround.

- openbb_terminal/forecast/forecast_controller.py
This PR fixes #4931 
Before:
After:
The are no tests to update for this command.
> hotfix/forecast-export: Fixes Forecast Menu's Export Command.

- openbb_terminal/stocks/fundamental_analysis/fmp_view.py
This PR removes 3 instances of `pd.set_option("display.max_colwidth", None)` from the file, `openbb_terminal/stocks/fundamental_analysis/fmp_view.py`.
> Removes Instances of Global Pandas Display Setting Being Set in `fmp_view`

- .github/workflows/integration-test.yml
- .github/workflows/macos-build.yml
- .github/workflows/windows10_build.yml
> Fix windows integration coverage workflow

- openbb_terminal/parent_classes.py
- openbb_terminal/stocks/stocks_controller.py
This PR closes #4965 and adds a way to preserve the stock ticker suffix. Please double confirm that I didn't break other things :D
> Preserve stock ticker suffix 

- website/content/terminal/installation/pypi.md
- website/content/terminal/installation/source.md
This PR adds a note to the source and PyPI installation pages that references the `yaml` files for Python 3.8 and 3.10. 
resolves #5062
> Install Page: adds reference to the YAML files for Python 3.8 and 3.10

- openbb_terminal/stocks/comparison_analysis/finbrain_view.py
This PR fixes #5095
Before:
After:
> hotfix/ca-sentiment-raw-date: Fixes #5095

- openbb_terminal/miscellaneous/integration_tests_scripts/stocks/test_fa.openbb
This fixes a bunch of bad syntax that was in the `stocks/fa` integration test file.  Oddly enough, when I execute the test locally, it returns an error for an item that is not actually in the test. 
Removing any reference to `balance` and `YahooFinance` creates a new error, which again is never referenced in the test file. 
Every command in the `.openbb` file works and produces an output, so this is half bug report and half PR. :P
> fixes stocks/fa integration test file

- openbb_terminal/helper_funcs.py
When running `etf/search` the user is met with a pandas warning
Apparently even if we use the pattern the warning proposes pandas still can't figure out if the operation is made on the original df or a copy.  My current understanding is that this happens because the df is passed into the function.
This PR creates a copy of the dataframe that we will manipulate explicitly so that pandas doesn't have to guess
> Avoid pandas' SettingWithCopyWarning

- openbb_terminal/stocks/fundamental_analysis/yahoo_finance_model.py
- openbb_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
This PR fixes #5088, making it the same as all the other sources.
Before:
After:
> hotfix/fa-yfinance-plot - makes `stocks/fa/income --plot` output match everything else.

- openbb_terminal/core/log/generation/settings_logger.py
- openbb_terminal/loggers.py
> feature/ Set profile on identify

- CONTRIBUTING.md
just made a small typo fix in contributing guidelines. 
typo : "... return a datatframe..."
fix : "...return a dataframe..."
> small typo fix in contributing guidlines

- openbb_terminal/stocks/screener/finviz_model.py
This PR fixes #5135.  The problem was that the Ticker column was labelled, `Ticker\n\n`, but only sometimes.
> hotfix/fix-screener: Fix for #5135

- openbb_terminal/stocks/stock_statics.py
This should close #5114 by adding column names that were missing to the balance sheet. A part of this issue was addressed in this PR #5137
> Fix balance sheet

- frontend-components/plotly/src/components/Chart.tsx
- frontend-components/plotly/src/components/ResizeHandler.tsx
> hotfix/ Change theme fails if `trace.marker.color` isn't an array

- website/content/sdk/faqs/developer_issues.md
- website/content/terminal/faqs/data_sources.md
- website/content/terminal/faqs/developer_issues.md
This PR updates the FAQ page to include debug mode instructions for both Terminal and SDK.
> hotfix/docs-faq-debug-mode: Adds debug mode instructions for Terminal and SDK

- openbb_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
This fixes the `shrs --major` output table by adding column names. It closes #5159.
> Fix shrs table

- openbb_terminal/stocks/options/options_chains_model.py
- tests/openbb_terminal/stocks/options/json/test_options_chains_model/test_OptionsChains_9.json
The column, `Skew`, in `get_skew()`, was supposed  to be a subtraction of the `(IV @ Strike) - (IV @ ATM)`, but instead of subtracting the ATM value, it was being copied.  This PR fixes that by dedicating a column to the ATM IV value prior to performing the math operation and setting the value.
> hotfix/fix-options-skew: Fixes columns not subtracting

- openbb_terminal/economy/yfinance_model.py
- tests/openbb_terminal/economy/txt/test_economy_controller/test_show_indices.txt
This PR adds six more entries to the curated index list in `/economy/yfinance_model.py`
> hotfix/economy-index-list: Adds Six Indices to the `economy/index` List

- website/content/terminal/usage/guides/scripts-and-routines.md
This PR updates the Scripts and Routines Guide to include a note indicating the minimum version of OpenBB required to use loops and relative time keywords.
> adds note indicating V3.1.0 is required for loops and keywords

- openbb_sdk/sdk/core/openbb_core/app/static/filters.py
The ``filter_call`` decorator was missing the ``functools.wraps`` decorator on the inner function. The result of this is that the decorated method can't be inspected properly at runtime as it only has the generic signature from the inner funciton.
Before:
```
>>> help(obb.stocks.load)
Help on method inner in module openbb_core.app.static.filters:
inner(*args, **kwargs) method of openbb_core.app.static.package.stocks.CLASS_stocks instance
```
After:
```
>>> help(obb.stocks.load)
Help on method load in module openbb_core.app.static.package.stocks:
load(symbol: str, start_date: Union[datetime.date, NoneType, str] = None, end_date: Union[datetime.date, NoneType, str] = None, chart: bool = False, provider: Optional[Literal['fmp', 'polygon']] = None, **kwargs) -> …
```
> Add missing wraps decorator in filter_call

- website/content/sdk/usage/basics/index.md
Issue where a formatting property was in a code block:
> hotfix/docs-sdk-basics-headTitle: fix headTitle

- openbb_terminal/reports/templates/economy.ipynb
This PR fixes a duplicated table in the economy report.
> hotfix/economy-report-duplicate-table: fixes duplicate tables.

- openbb_terminal/core/plots/no_import.py
- openbb_terminal/dashboards/streamlit_run.py
> Hotfix/ locking when deploying streamlit app

- openbb_terminal/core/session/hub_model.py
- openbb_terminal/helper_funcs.py
> Fixed the request function

- openbb_terminal/core/session/hub_model.py
- openbb_terminal/settings_controller.py
We were calling the frontend for backend endpoints:
Also, I removed the parameter for base_url. There is no reason to have it, and the default gets set in the beginning, so if the value changes (like when we set dev mode, the parameter does not change).
> Fixed URL for uploading to the hub

- openbb_terminal/stocks/stocks_controller.py
- openbb_terminal/stocks/stocks_helper.py
- tests/openbb_terminal/stocks/test_stocks_controller.py
- tests/openbb_terminal/stocks/test_stocks_helper.py
- tests/openbb_terminal/stocks/txt/test_stocks_controller/test_print_help.txt
- tests/openbb_terminal/stocks/txt/test_stocks_helper/test_search[False].txt
- tests/openbb_terminal/stocks/txt/test_stocks_helper/test_search[True].txt
Currently, if you use the SDK and `stocks.search()`, it will open a PyWry window while simultaneously returning a DataFrame.  This takes care of that.
> hotfix/fix-stocks-search-sdk3: Fixes the stocks search so that it doesn't `print_rich_table()` for SDK.

- openbb_sdk/providers/cboe/openbb_cboe/utils/helpers.py
- openbb_sdk/sdk/core/openbb_core/app/logs/models/logging_settings.py
- openbb_sdk/sdk/core/openbb_core/app/logs/utils/system_utils.py
- openbb_sdk/sdk/core/openbb_core/app/model/system_settings.py
> move get_branch request to logging_settings

- openbb_sdk/sdk/core/openbb_core/app/command_runner.py
- openbb_sdk/sdk/core/openbb_core/app/env.py
- openbb_sdk/sdk/core/openbb_core/app/model/charts/charting_settings.py
- openbb_sdk/sdk/core/openbb_core/app/model/system_settings.py
- openbb_sdk/sdk/core/openbb_core/app/router.py
- openbb_sdk/sdk/core/openbb_core/app/service/system_service.py
- openbb_sdk/sdk/core/tests/app/model/charts/test_chart_settings.py
This allow setting `debug_mode` before loading `SystemSettings` from `os.environ` or `.env` file.
It is useful for example to suppress import time warnings, like missing models in the routers.
> move debug_mode out of system settings

- openbb_sdk/providers/fred/openbb_fred/models/ameribor_rates.py
- openbb_sdk/providers/fred/openbb_fred/models/cpi.py
- openbb_sdk/providers/fred/openbb_fred/models/estr_rates.py
- openbb_sdk/providers/fred/openbb_fred/models/fed_projections.py
- openbb_sdk/providers/fred/openbb_fred/models/fed_rates.py
- openbb_sdk/providers/fred/openbb_fred/models/iorb_rates.py
- openbb_sdk/providers/fred/openbb_fred/models/sofr_rates.py
- openbb_sdk/providers/fred/openbb_fred/models/sonia_rates.py
- openbb_sdk/providers/fred/openbb_fred/models/us_yield_curve.py
- openbb_sdk/providers/fred/openbb_fred/utils/fred_helpers.py
- openbb_sdk/sdk/core/openbb_core/app/static/package/economy.py
- openbb_sdk/sdk/provider/openbb_provider/abstract/fetcher.py
- openbb_sdk/sdk/provider/openbb_provider/registry_map.py
If the developer wants to return nested return types, it should be set as a property in the fetcher `data_type` so that we don't fail to infer the data type from the second generic argument.
Usually this should not be needed, but is a more reliable way to get the data type and helps fix mypy errors.
> Add @classproperty to fetcher for nested return types

- openbb_sdk/providers/intrinio/openbb_intrinio/models/options_chains.py
- openbb_sdk/providers/intrinio/openbb_intrinio/utils/helpers.py
Two small fixes:
- Bad API key response for querying symbol directory
- Correct DTE calculation because `now` is within the `date` field, +1 is for when `now` == datetime.now()
Then removes the functions in `helpers` that were moved from `helpers` to `options_chains`
> Fix/provider-bugs-intrinio: fix bad API key response for options symbols

- openbb_terminal/stocks/stocks_helper.py
- openbb_terminal/stocks/stocks_model.py
Fixes #5392
Currently, in the /stocks/load command, if yahoo finance does not find data it doesn't print any indication to the user.
This PR adds a message if yahoo finance does not find data：
> Print message if yahoo finance load fails

- openbb_sdk/providers/cboe/openbb_cboe/models/major_indices_historical.py
- openbb_sdk/providers/cboe/openbb_cboe/models/stock_historical.py
- openbb_sdk/providers/fmp/openbb_fmp/models/crypto_historical.py
- openbb_sdk/providers/fmp/openbb_fmp/models/forex_historical.py
- openbb_sdk/providers/fmp/openbb_fmp/models/major_indices_historical.py
- openbb_sdk/providers/fmp/openbb_fmp/models/stock_historical.py
- openbb_sdk/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_crypto_historical_fetcher.yaml
- openbb_sdk/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_forex_historical_fetcher.yaml
- openbb_sdk/providers/intrinio/openbb_intrinio/models/stock_historical.py
- openbb_sdk/providers/polygon/openbb_polygon/models/crypto_historical.py
- openbb_sdk/providers/polygon/openbb_polygon/models/forex_historical.py
- openbb_sdk/providers/polygon/openbb_polygon/models/major_indices_historical.py
- openbb_sdk/providers/polygon/openbb_polygon/models/stock_historical.py
- openbb_sdk/providers/polygon/openbb_polygon/utils/helpers.py
- openbb_sdk/providers/yfinance/openbb_yfinance/models/crypto_historical.py
- openbb_sdk/providers/yfinance/openbb_yfinance/models/forex_historical.py
- openbb_sdk/providers/yfinance/openbb_yfinance/models/major_indices_historical.py
- openbb_sdk/providers/yfinance/openbb_yfinance/models/stock_historical.py
- openbb_sdk/providers/yfinance/tests/record/http/test_yfinance_fetchers/test_y_finance_futures_historical_fetcher.yaml
- openbb_sdk/providers/yfinance/tests/record/http/test_yfinance_fetchers/test_y_finance_stock_historical_fetcher.yaml
- openbb_sdk/providers/yfinance/tests/test_yfinance_fetchers.py
- openbb_sdk/sdk/provider/openbb_provider/standard_models/crypto_historical.py
- openbb_sdk/sdk/provider/openbb_provider/standard_models/forex_historical.py
- openbb_sdk/sdk/provider/openbb_provider/standard_models/major_indices_historical.py
This PR allows `date` and `datetime` of all formats for **only** the `StockHistorical`, `MajorIndicesHistorical`, `CryptoHistorical`, and `ForexHistorical` models. 
This is achieved using `dateutil.parser` that removes the need for validators that check whether its a `date` or `datetime` of specific format(s). The only requirement is that the object should be of class `datetime`, `dateutil` or `pd.Timestamp`.
> Standardize `date` and `datetime` for all historical models

- reviewpad.yaml
This pull request introduces two changes:
- A refactor to the Reviewpad configuration to follow the latest releases of [Reviewpad](https://reviewpad.com/).
- A new rule called `should-run-reviewpad` that ignores a pull request if it contains the label `reviewpad-ignore`.
This was tested using [Reviewpad playground](https://reviewpad.com/playground).
> refactor: reviewpad configuration

- openbb_terminal/forecast/helpers.py
- openbb_terminal/forecast/timegpt_model.py
This might not be the *best* way to go about it, but it appears to work and would resolve a long-standing issue.  The charts are lacking range breaks when intraday, so a bit of love is needed there.
This removes the process which was formatting everything as `%Y-%m-%d`, and changes the frequency setting to default as `D` instead of `B`.
Before:
After:
This does not work with TimeGPT because it doesn't use the helpers or common params the rest of the menu uses. @DidierRLopes, any insight here how we can get intraday to work there?
Actually found a way to make it work where it resamples to Hourly:
- Format dates as `%Y-%m-%d %H%M%S` instead of stripping the time.
- Use `freq=H` for the command.
- Daily, `freq=D` for the command.
The TimeGPT command could use a bit of cleanup to make default …
> hotfix/forecast-make-intraday-work: An attempt to make intraday data work with forecast functions

- openbb_platform/extensions/ta/openbb_ta/ta_helpers.py
- openbb_platform/extensions/ta/openbb_ta/ta_router.py
This PR fixes two functions in the TA extension, `cones` and `demark`.
- Both were clipping the index from the response.
- Remove `dropna()` from Demark which removed the entire column if one NaN was present.
- set `asint` and `show_all` to default as True.
> hotfix/v4-fix-cones - Bug fixes for ta.cones() and ta.demark()

- .github/pull_request_template.md
> Change template to add platform considerations

- openbb_platform/openbb/package/crypto.py
- openbb_platform/openbb/package/econometrics.py
- openbb_platform/openbb/package/economy.py
- openbb_platform/openbb/package/fixedincome.py
- openbb_platform/openbb/package/forex.py
- openbb_platform/openbb/package/futures.py
- openbb_platform/openbb/package/news.py
- openbb_platform/openbb/package/qa.py
- openbb_platform/openbb/package/stocks.py
- openbb_platform/openbb/package/stocks_ca.py
- openbb_platform/openbb/package/stocks_fa.py
- openbb_platform/openbb/package/stocks_options.py
- openbb_platform/openbb/package/ta.py
- openbb_platform/platform/core/tests/api/test_auth/test_user_auth.py
- openbb_platform/platform/provider/openbb_provider/standard_models/crypto_historical.py
- openbb_platform/platform/provider/openbb_provider/standard_models/forex_historical.py
Standardizes the symbol input for the Crypto and Forex Historical standard models.
Accepted formats - `CURR1CURR2` ; `CURR1-CURR2`
> Standard convention for multi-ticker symbols 

- noxfile.py
- openbb_platform/dev_install.py
- openbb_platform/extensions/economy/integration/test_economy_api.py
- openbb_platform/platform/core/integration/test_obbject.py
- openbb_platform/platform/core/tests/app/model/test_obbject.py
- openbb_platform/platform/provider/openbb_provider/abstract/fetcher.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/options_chains.py
> obbject tests

- openbb_platform/providers/alpha_vantage/tests/test_alpha_vantage_fetchers.py
- openbb_platform/providers/benzinga/tests/test_benzinga_fetchers.py
- openbb_platform/providers/cboe/tests/test_cboe_fetchers.py
- openbb_platform/providers/fmp/tests/test_fmp_fetchers.py
- openbb_platform/providers/fred/tests/test_fred_fetchers.py
- openbb_platform/providers/intrinio/tests/test_intrinio_fetchers.py
- openbb_platform/providers/oecd/tests/test_oecd_fetchers.py
- openbb_platform/providers/polygon/tests/test_polygon_fetchers.py
- openbb_platform/providers/quandl/tests/test_quandl_fetchers.py
- openbb_platform/providers/tests/utils/unit_tests_generator.py
- openbb_platform/providers/tradingeconomics/tests/test_tradingeconomics_fetchers.py
- openbb_platform/providers/yfinance/tests/test_yfinance_fetchers.py
^
Before and after (removes the deprecation warning introduced by pydantic v2):
> change to model_dum() instead

- openbb_terminal/stocks/stocks_helper.py
- tests/openbb_terminal/stocks/txt/test_stocks_helper/test_search[False].txt
- tests/openbb_terminal/stocks/txt/test_stocks_helper/test_search[True].txt
Fixes #5505
---
Added the following new columns to `stocks/search`
```
isin, cusip, figi, composite_figi, shareclass_figi
```
Screenshot of the feature
Before:
After:
> Add columns to `stocks/search`

- openbb_terminal/keys_controller.py
- openbb_terminal/miscellaneous/models/all_api_keys.json
- website/content/terminal/usage/guides/api-keys.md
> Updating Ultima urls

- openbb_terminal/stocks/fundamental_analysis/fmp_model.py
- Fixes warning caused by setting a value on copy of a DataFrame by explicitly creating a copy.
- Link #5582
> fix: A value is trying to be set on a copy of a slice from a DataFrame

- openbb_platform/dev_install.py
- openbb_platform/extensions/etf/integration/test_etf_api.py
- openbb_platform/extensions/etf/integration/test_etf_python.py
- openbb_platform/extensions/tests/utils/integration_tests_api_generator.py
- openbb_platform/extensions/tests/utils/integration_tests_generator.py
I've added py.typed markers to extensions throughout the repo so that mypy in the IDE would not be expecting stubs
> Clean up the newly created ETF extension

- website/src/components/Icons/Twitter.tsx
attached the after logo update screenshot for reference below
> FIX #5600 Updated the Twitter logo to X logo

- openbb_platform/platform/core/openbb_core/app/model/obbject.py
Allows you to do 
- obbject.to_dict(orient = " ") just has to be valid arg
- obbject.to_records() -> gives the json type stuff
Remove polars so that can be an extension
> Add didiers to_records method

- .github/workflows/platform-api-integration-test.yml
^
Result: 
See here:
https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/6771428709/job/18401799864
> Fix installation of dependencies in Platform integration tests

- openbb_terminal/stocks/government/quiverquant_view.py
This PR fixes #5650.  For V4 the API queries should get some attention to improve reliability (some requests fail to connect), but this gets us back to working.
Before:
```
/stocks/gov/load AMT/histcont
```
```console
(🦋) /stocks/gov/ $ histcont
Error: unsupported operand type(s) for /: 'str' and 'int'
```
After:
> hotfix/fix-gov-histcont: Fix #5650 - /stocks/gov/histcont

- openbb_terminal/stocks/screener/screener_controller.py
This PR fixes #5671 by removing a space that didn't belong in the regex column filter.  The `e` on the other side of the `/` made the problem worse by activating `e` for `exit`.
Before:
After:
> hotfix/stock-screener-sort:  Fix for #5671 - sort by `fwdp/e` in Stock Screener

- openbb_platform/providers/fmp/openbb_fmp/models/market_snapshots.py
This PR reverses a change that made fields not optional in the FMP model, which created validation errors.
Before:
```python
obb.stocks.market_snapshots(market = "NYSE", provider="fmp")
ValidationError: 1 validation error for FMPMarketSnapshotsData
name
Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
For further information visit https://errors.pydantic.dev/2.4/v/string_type
```
After:
> Hotfix/fix-fmp-market-snapshots - make fields optional again.

- openbb_platform/platform/provider/openbb_provider/standard_models/bond_prices.py
- openbb_platform/platform/provider/openbb_provider/standard_models/bond_reference.py
- openbb_platform/platform/provider/openbb_provider/standard_models/bond_trades.py
- openbb_platform/platform/provider/openbb_provider/utils/descriptions.py
This PR adds three standard models:
- BondReference
- BondPrices
- BondTrades
> Feature/files-for-igor: Adding a few standard models for Igor

- openbb_platform/dev_install.py
- openbb_platform/extensions/devtools/README.md
- openbb_platform/extensions/devtools/openbb_devtools/__init__.py
- openbb_platform/extensions/devtools/pyproject.toml
What this does is adds a package that has the developer tools we use. It's a package that has no logic in it and that's being installed only as a part of the dev_install script
> Add devtools metapackage

- openbb_platform/extensions/equity/integration/test_equity_api.py
- openbb_platform/extensions/equity/integration/test_equity_python.py
- openbb_platform/extensions/equity/openbb_equity/fundamental/fundamental_router.py
- openbb_platform/platform/provider/openbb_provider/standard_models/balance_sheet.py
- openbb_platform/platform/provider/openbb_provider/standard_models/cash_flow.py
- openbb_platform/platform/provider/openbb_provider/standard_models/financial_attributes.py
- openbb_platform/platform/provider/openbb_provider/standard_models/income_statement.py
- openbb_platform/platform/provider/openbb_provider/standard_models/search_financial_attributes.py
- openbb_platform/platform/provider/openbb_provider/utils/descriptions.py
- openbb_platform/providers/intrinio/openbb_intrinio/__init__.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/balance_sheet.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/cash_flow.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/financial_attributes.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/income_statement.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/search_financial_attributes.py
- openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_financial_attributes.yaml
- openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_search_financial_attributes.yaml
- openbb_platform/providers/intrinio/tests/test_intrinio_fetchers.py
> Seprate Intrinio financials data tags into a different command

- website/generate_platform_v4_markdown.py
> docs/ fix `\n` in field descriptions breaks markdown table

- openbb_platform/core/openbb_core/app/model/credentials.py
- openbb_platform/core/openbb_core/app/router.py
- openbb_platform/core/openbb_core/provider/registry.py
<details>
</details>
<details>
</details>
> Warn loading error instead of raising

- website/src/theme/SearchBar/index.js
<details>
</details>
<details>
</details>
> Second attempt to fix search on docs

- .github/workflows/linting.yml
This PR should fix mypy raising errors about v3 code that has not been touched within the scope of a PR
> Limit mypy v3 linting to only the diff of the PR

- .github/pull_request_template.md
- openbb_platform/providers/fred/openbb_fred/models/hqm.py
Little improvement on the `hqm` command output, so that it contains the series ID and doesn't have unnecessary columns.
NA
Before:
After:
:bug: :skull_and_crossbones: 
NA
<details>
<summary>### How has this been tested?</summary>
NA
NA
NA
NA
NA
NA
NA
</details
> Changes to the `obb.fixedincome.corporate.hqm()` output

- .github/workflows/linting.yml
There is a rogue pylint failing on an untouched terminal file.  This should not raise that error.
> separate pylint between platform + terminal

- .secrets.baseline
- website/content/platform/installation.md
- website/content/platform/usage/index.md
- website/content/platform/usage/rest_api.md
This PR moves the FastAPI docs to a dedicated page in the Usage section.
Also removes/cleans up minor things here and there
> Add REST API docs page with advanced settings configuration

- openbb_platform/providers/fmp/openbb_fmp/models/price_performance.py
This PR fixes:
Although now that the market has opened, and data exists for YTD, the bug is not reproducible anymore. A `model_validator` is applied to all fields except 'symbol' that replaces 0 with None.
This also converts percent values to be normalized values - /100.
> hotfix/fmp-price-performance-zeros: Replace returned zero with None and normalize percent values.

- openbb_platform/extensions/derivatives/integration/test_derivatives_api.py
- openbb_platform/extensions/derivatives/integration/test_derivatives_python.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/equity_historical.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/futures_historical.py
- openbb_platform/providers/yfinance/openbb_yfinance/utils/futures.csv
- openbb_platform/providers/yfinance/openbb_yfinance/utils/helpers.py
This PR fixes the yfinance provider for better symbol handling and multi-ticker support. It will only attempt to create an expiration symbol where there is no `.` in the supplied ticker.  When there is no expiration supplied, it will not add `=F` to the symbol if there is a `.` in the symbol.
You can now compare the continuation chart against individual contracts from the same underlying.
Also adds Heating Oil to the CSV file, HO.
Before:
```python
obb.derivatives.futures.historical(["RB","CL"])
```
```console
OpenBBError: RB,CL=F: No timezone found, symbol may be delisted
```
```python
obb.derivatives.futures.historical(symbol="CLZ24.NYM")
```
```console
OpenBBError: CLZ24.NYM=F: No timezone found, symbol may be delisted
```
After:
with expiration:
mixing continuation symbols with a …
> hotfix/yf-futures-historical: yfinance historical futures multi-ticker support and symbol parsing

- openbb_platform/core/openbb_core/app/provider_interface.py
To add information about unit measurements pass a dictionary to the `json_schema_extra` Pydantic model field.
```
class SomeData(Data):
value: Optional[float] = Field(
default=None, description="Some value.",
json_schema_extra={"unit_measurement": "percent"}
)
```
> Add json_schema_extra to openapi.json

- website/content/platform/development/index.md
This PR fixes the URL in the Development page that pointed to the standard models.  The link now directs to the `data_models` page in the docs.
Links to the GitHub repo paths have also been updated to reflect the provider interface path change.
https://docs.openbb.co/platform/development
> docs/data-models-url: Fix URLs on Development Page

- openbb_platform/providers/intrinio/openbb_intrinio/models/equity_quote.py
^^
This PR updates the validator to regex out any and all UTF-8 control characters being returned by Intrinio to the "sales_condition" field in `obb.equity.quote()`.
Example:
```
In: obb.equity.price.quote("SPY", provider="intrinio").results[0].sales_conditions
Out: '\x17\x1e\x7f'
```
Which ends up creating a huge field of empty spaces from `to_df()`.
This is replaced by `None`.
> hotfix/intrinio-strip-control-characters: regex out any invisible control character from sales_conditions field

- openbb_platform/pyproject.toml
Removes `yfinance` from the `extras` group in the platform's toml file.
This was an unintended leftover when making yfinance a part of the official packages.
> Minor platform pyproject fix

- openbb_platform/extensions/technical/pyproject.toml
- openbb_platform/pyproject.toml
- openbb_platform/tests/test_pyproject_toml.py
^
- Intends to fix the typo in the `pyproject.toml` that accidentally removes `openbb-yfinance` bc it's still mentioned on the extras.
- Bump `openbb-technical` to v`1.1.2` - adds `pandas-ta` to dependencies
- Adds a unit test to ensure correctness of the `pyproject.toml`
> Release OpenBB Platform v`4.1.3`

- website/content/platform/extensions/data_extensions.md
- website/content/platform/extensions/toolkit_extensions.md
This PR updates the extensions pages in the documentation with:
- Move stuff around to reflect current reality of what's shipped at the core level.
- Add note for Econometrics installation indicating that a C compiler needs to be present on the system.
> docs/extensions-list: Update the Extension Descriptions Pages

- openbb_platform/core/openbb_core/api/router/commands.py
Custom headers get added to all endpoints in `/docs` on Platform api docs
> hotfix/ `custom_headers` as args in openapi schema

- openbb_platform/core/openbb_core/app/static/package_builder.py
- website/content/platform/development/contributor-guidelines/deprecating_endpoints.md
- website/content/platform/development/contributor-guidelines/write_code_commit.md
- website/generate_platform_v4_markdown.py
Adds a deprecation warning in the reference docs:
> [!NOTE] 
> I tried to make it strike-through the title (fastapi style), but it's not trivial - if we want do also do it, we'll need to allocate more time to it!
> [!IMPORTANT] 
> I needed to bring back some retired methods on the `PackageBuilder` - this might need some revision - added to backlog.
> Deprecation warning on the reference docs

- openbb_platform/core/openbb_core/app/router.py
- openbb_platform/core/openbb_core/provider/registry_map.py
Please go the the `Preview` tab and select the appropriate PR sub-template:
* [OpenBB Platform](?expand=1&template=platform_pull_request_template.md)
* [OpenBB Terminal](?expand=1&template=terminal_pull_request_template.md)
* [OpenBB Developers](?expand=1&template=obb_developer_pull_request_template.md)
> fix openapi schema fields `to_snake`, tag for empty list/dict

- .github/workflows/unit-test.yml
0. **Dont run bases tests with v4 label**:
- Format: [Type] - Brief Description (e.g., [Hotfix] - Improve Calculation Accuracy).
- PRs blocked by failing v3 tests
- Check if v4 label before running v3 base tests
- Tests not running
- Add or remove v4 label in the PR
> Dont run base tests with v4 label

- openbb_platform/core/openbb_core/app/command_runner.py
- openbb_platform/core/openbb_core/app/model/preferences.py
- website/content/platform/usage/index.md
1. **Why**?
- Warnings were hidden inside `OBBject.warnings`
- @mnicstruwig pointed the issue
2. **What**?
- Show warnings given user preference
3. **Impact**:
- No relevant impact
Toggle the preference and check if a warning is raised
```python
obb.user.preferences.show_warnings = True
obb.equity.fundamental.income("AAPL,MSFT").to_df()
```
> [Feature] - Display warnings based on user preference

- openbb_platform/extensions/econometrics/openbb_econometrics/econometrics_router.py
1. Why?
To have a better UX of the econometrics router commands.
2. What?
Improved the docstrings of the commands on the econometrics router by satisfying pydocstyle and introducing more verbosity where needed.
3. Impact:
The docstrings that are shown on the documentation pages will change. Minimal impact.
4. Testing:
Tested that the examples work.
5. Reviewer notes
The panel commands don't feature an example as we don't yet have a command that returns a multi-index result.
> [Enhancement] - Improve the econometrics router docstrings

- openbb_platform/extensions/economy/openbb_economy/economy_router.py
- openbb_platform/providers/oecd/openbb_oecd/models/long_term_interest_rate.py
- openbb_platform/providers/oecd/openbb_oecd/models/short_term_interest_rate.py
The router for the function, `obb.economy.long_term_interest_rate`, was defined incorrectly and was a duplicate of `short_term_interest_rate`.
- Mapped the correct model in the router.
- Replaced `nan` values with None which were creating validation errors.
`obb.economy.long_term_interest_rate` now works.
The data returned is from the correct series, and no validation errors occur.
6. **Any other information** (optional)
> [BugFix] Fix OECD Long Term Interest Rate

- openbb_platform/core/openbb_core/provider/standard_models/cpi.py
- openbb_platform/openbb/package/economy.py
- openbb_platform/providers/tradingeconomics/openbb_tradingeconomics/models/economic_calendar.py
- openbb_platform/providers/tradingeconomics/openbb_tradingeconomics/utils/countries.py
- openbb_platform/providers/tradingeconomics/openbb_tradingeconomics/utils/url_generator.py
1. **Why**?
- Consistency with other country inputs
2. **What**?
- Change country to `str` instead of `List[str]`
3. **Impact**
- Terminal Pro calendar
```python
obb.economy.calendar(country="japan,united_states", provider="tradingeconomics")
```
> [Bugfix] - Fix economic calendar country

- openbb_platform/extensions/quantitative/openbb_quantitative/quantitative_router.py
- The examples had a bug that misled users.
- Changed all data that is passed to QA commands to dataframes.
- Only changes the docstrings.
- Tested the QA commands.
> [BugFix] - Fix QA Examples

- .github/workflows/branch-name-check.yml
- .github/workflows/linting.yml
- CONTRIBUTING.md
…pushes to branches outside PRs
Please go the the `Preview` tab and select the appropriate PR sub-template:
* [OpenBB Platform](?expand=1&template=platform_pull_request_template.md)
* [OpenBB Terminal](?expand=1&template=terminal_pull_request_template.md)
* [OpenBB Developers](?expand=1&template=obb_developer_pull_request_template.md)
> [Feature] - Ensure Bugfix branches can only do PRs to `develop` branches

- openbb_platform/core/openbb_core/app/static/package_builder.py
- openbb_platform/extensions/econometrics/openbb_econometrics/econometrics_router.py
- openbb_platform/extensions/quantitative/openbb_quantitative/quantitative_router.py
- openbb_platform/extensions/technical/openbb_technical/technical_router.py
- The POST commands should follow the same convention as other router commands when adding examples for consistency.
- Moved POST command router examples from docstring to the command decorator.
- Fixed a bug where the POST examples wouldn't be added to the static assets docstrings.
- Will change the look of the router files and add `examples` to the `openapi.json`. Shouldn't change anything substantial as these extension aren't yet widely used.
- Ensured that the examples are indeed on the static assets as expected.
> [BugFix] - Fix POST docstring examples

- openbb_platform/core/openbb_core/provider/standard_models/eu_yield_curve.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_api.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_python.py
- openbb_platform/providers/ecb/openbb_ecb/models/eu_yield_curve.py
- openbb_platform/providers/ecb/openbb_ecb/utils/yield_curve_series.py
- The `date` parameter was not working.
- The request took a really long time to execute.
- The returned data was not formatted like the US Yield Curve data.
- `date` parameter now works, it will return the nearest date to the user-provided date, defaulting to today.
- Downloads are now made asynchronously.
- The format of returned data is now like the US Yield Curve data.
- Choices for `rating` parameter now have more clarity - "aaa" or "all_ratings".
- Adds `json_schema_extra={"unit_measurement": "percent", "frontend_multiply": 100}`
- Community provider, does not impact pro.
- Recaptured unit test cassette, …
> [BugFix] Fix ECB Yield Curve

- openbb_platform/core/openbb_core/env.py
1. **Why**?:
- Since the charting extension is now an OBBject extension (and the former ChartingService infra was removed), there is no need to have this env variable anymore.
2. **What**?:
- Removed the env var handling from the `Env` singleton.
3. **Impact**:
- No impact - it's not being used anywhere in the code base.
- NA
> [BugFix] Remove charting extension env var

- openbb_platform/openbb/package/equity_fundamental.py
- openbb_platform/openbb/package/equity_price.py
- openbb_platform/openbb/package/news.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/key_metrics.py
- The `yfinance` provider was missing the flag to allow multiple symbols.
- `__json_schema_extra__ = {"symbol": ["multiple_items_allowed"]}`
- Update static files.
- This was already working before the new validator was imposed, so back to normal.
> [BugFix] Allow Multiple Symbols in `equity.fundamental.metrics()` from `yfinance`

- openbb_platform/providers/tmx/openbb_tmx/models/etf_info.py
- Multiple symbols are supported for `etf.info()`
- Adds: `    __json_schema_extra__ = {"symbol": ["multiple_items_allowed"]}`
- N/A
- Multiple symbols now work.
- `obb.etf.info("COMM.TO,DISC.TO", provider="tmx")`
> [BugFix] Multiple Symbols Allowed, `etf.info(provider="tmx")`

- openbb_terminal/miscellaneous/sources/openbb_default.json
Why? (1-3 sentences or a bullet point list):
EconDB should be displayed same as other data sources
What? (1-3 sentences or a bullet point list):
Add EconDB to openbb_default.json 
Impact (1-2 sentences or a bullet point list):
terminal.py economy main screen, associate EconDB source with macro command
Testing Done:
Manually launch terminal application and observe change has desired effect and run several "macro \<args\>" commands.
> [BugFix] Display EconDB as source for macro

- openbb_platform/extensions/equity/integration/test_equity_api.py
- openbb_platform/extensions/equity/integration/test_equity_python.py
- openbb_platform/openbb/package/crypto.py
- openbb_platform/openbb/package/crypto_price.py
- openbb_platform/openbb/package/currency.py
- openbb_platform/openbb/package/currency_price.py
- openbb_platform/openbb/package/derivatives_options.py
- openbb_platform/openbb/package/economy.py
- openbb_platform/openbb/package/economy_gdp.py
- openbb_platform/openbb/package/equity.py
- openbb_platform/openbb/package/equity_calendar.py
- openbb_platform/openbb/package/equity_compare.py
- openbb_platform/openbb/package/equity_discovery.py
- openbb_platform/openbb/package/equity_estimates.py
- openbb_platform/openbb/package/equity_fundamental.py
- openbb_platform/openbb/package/equity_ownership.py
- openbb_platform/openbb/package/equity_price.py
- openbb_platform/openbb/package/equity_shorts.py
- openbb_platform/openbb/package/etf.py
- openbb_platform/openbb/package/fixedincome.py
- openbb_platform/openbb/package/fixedincome_corporate.py
- openbb_platform/openbb/package/fixedincome_government.py
- openbb_platform/openbb/package/fixedincome_rate.py
- openbb_platform/openbb/package/fixedincome_spreads.py
- openbb_platform/openbb/package/index.py
- openbb_platform/openbb/package/news.py
- openbb_platform/openbb/package/regulators_sec.py
- openbb_platform/providers/intrinio/openbb_intrinio/__init__.py
- openbb_platform/providers/intrinio/tests/test_intrinio_fetchers.py
1. **Why**?
To disable the Intrinio endpoint because it is unreliable currently.
2. **What**?
Disables the fetcher in the provider init, tests, and equity API and Python interface tests.
3. **Impact**
- Minimal
- Impact Analysis breakdown:
- _UX_ = 1
- _Performance_ = 0
- _Compatibility_ = 1
- _Security_ = 1
- _Scalability_ = 0
- _Maintenance_ = 1
- _Compliance_ = 0
- _Dependency_ = 1
- **Total Impact Score** = 5
Tested by checking the `obb.coverage.providers`, `obb.coverage.commands` and the fetcher and unit tests.
6. **Any other information** (optional)
All static files are updated due to a minor tweak in the package builder. This tweak is adding an extra space after `:` in the `Returns` section.
> [BugFix] Disable Intrinio `InstitutionalOwnership` model

- website/content/excel/data-connectors.md
- website/content/excel/data-slicer.md
- website/content/excel/faqs.md
- website/content/excel/getting-started/_category_.json
- website/content/excel/help.md
- website/controller_doc_classes.py
- website/generate_excel_markdown.py
1. **Why**?
- Need for help page to suggest fixes for excel issues
2. **What**?
- Creates https://docs.openbb.co/excel/help
3. **Impact**:
- NA
- `cd website` > `npm start` and check how it looks
> [Feature] - Excel help page

- openbb_platform/core/tests/app/model/charts/test_chart.py
- openbb_platform/extensions/tests/conftest.py
- openbb_platform/extensions/tests/test_integration_tests_api.py
- openbb_platform/extensions/tests/test_integration_tests_python.py
- openbb_platform/extensions/tests/utils/helpers.py
- openbb_platform/obbject_extensions/charting/integration/test_charting_api.py
- openbb_platform/obbject_extensions/charting/integration/test_charting_python.py
1. **Why**? 
- `openbb_charting` integration tests were skipped
- any obbject extension would be skipped in the future
2. **What**?
- Include obbject in the set of parametrize extensions
3. **Impact**:
- Tests run again
- Install the `openbb_charting` extension and run integration tests
> [Bug fix] - Run charting tests again

- openbb_platform/providers/intrinio/openbb_intrinio/models/balance_sheet.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/cash_flow.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/equity_historical.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/income_statement.py
- As per @minhhoang1023, we are moving a couple of items in Intrinio's cashflow statement to be on top of Net Income:
- Net Income Continuing Operations
- Net Income Discontinued Operations
- Move those in fields up in the model definition.
- Some linting things.
- Corrected order of fields, no impact on the operation.
Before:
After:
> [Enhancement] Slightly Change The Order of intrinio Cash Flow

- openbb_platform/core/openbb_core/app/static/package_builder.py
- openbb_platform/core/openbb_core/app/static/utils/decorators.py
- openbb_platform/core/openbb_core/app/static/utils/filters.py
- openbb_platform/core/openbb_core/provider/standard_models/spot.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_api.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_python.py
- openbb_platform/extensions/tests/utils/helpers.py
- openbb_platform/openbb/package/equity_estimates.py
- openbb_platform/openbb/package/fixedincome_corporate.py
- openbb_platform/openbb/package/news.py
- openbb_platform/providers/fred/openbb_fred/models/spot.py
- openbb_platform/providers/fred/openbb_fred/utils/fred_helpers.py
1. **Why**?
- Multiple items only support str type
- fields with type `str` is converted to `Union[str, List[str]]`
- fields with type `float/int` should be converted to `Union[float/int, List[float/int]]`
2. **What**?
- Use `List[<original_type>]` instead of `List[str]`
- Update `obb.fixedincome.corporate.spot_rates` accordingly
- Fixes `@handle_exceptions` bug when `original` attribute is not present
- Removes dangerous default `[10.0]` from `maturity`
- Removes dangerous default `["spot_rate"]` from `category`
- Use comma separated string for both `maturity` and `category`
3. **Impact**:
- Arbitrary types allowed for multiple items
* Run integration tests added in this PR
Also,
```python
obb.fixedincome.corporate.spot_rates().to_df() …
```
> [Bug fix] - Handle multiple items with arbitrary type

- openbb_platform/core/openbb_core/app/static/utils/decorators.py
1. **Why**?
To provide complete information about the argument when handling `ValidationError` in non-debug mode.
2. **What**?
Fixes the issue of not showing the complete argument details for `ValidationError` in non-debug mode.
3. **Impact**:
Minimal (Score = 4)
Tested with various function calls when debug mode is off
5. **Any other information**:
* Before - ![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/88149434/45929cf0-282d-4db8-96b9-c02a455b0fd9)
* After - ![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/88149434/21345097-19c2-4ebf-8e4b-57f5dc87a26f)
> [BugFix] Fix incomplete argument display when debug mode is off for `ValidationError`

- openbb_platform/tests/test_extension_map.py
- openbb_platform/tests/test_pyproject_toml.py
- Ensure that developers aren't pushing non-required static assets by mistake.
- Adds a test that makes sure that developers aren't pushing non-required static assets by mistake.
- Ensures quality, shouldn't be a breaking change.
- Made sure the tests work.
> [Feature] - Create static asset tests

- openbb_platform/providers/nasdaq/openbb_nasdaq/models/economic_calendar.py
1. **Why**?:
- While doing some testing in Colab, I noticed the economic calendar from Nasdaq wasn't returning, but all the other calendars are. Locally, was fine, but not on Colab. 
2. **What**? :
- It was using a different schema for the request headers, changed it to be like the other ones.
3. **Impact** :
- N/A
- Could only test locally, will not know for certain until a nightly build, but still works locally!
> [BugFix] Update Nasdaq Econ Calendar Headers

- openbb_platform/core/openbb_core/app/model/preferences.py
- Deprecated user preference.
2. **What**?:
-  Remove charting extension preference from user settings
3. **Impact**:
- NA
- Launching the Platform 
- Checking user preferences
> [BugFix] Remove charting extension preference from user settings

- openbb_platform/core/openbb_core/provider/abstract/fetcher.py
- Fetcher test errors confused people not acquainted with them by not having an Explicit enough message.
- 
- Added explicit messages on what is wrong.
- Will help the end-user, with no impact on performance or execution.
- Tested that the errors show up.
> [Enhancement] - Improve fetcher test error messages

- openbb_platform/core/openbb_core/app/static/package_builder.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity_calendar.py
- openbb_platform/openbb/package/equity_price.py
- openbb_platform/openbb/package/news.py
- openbb_platform/providers/benzinga/openbb_benzinga/models/price_target.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/calendar_ipo.py
- openbb_platform/providers/polygon/openbb_polygon/models/equity_nbbo.py
- website/generate_platform_v4_markdown.py
1. **Why**? 
Consistent information between `reference.json` and package docstring
2. **What**?
- `"None"` is now saved as `None` type in `QueryParams` and `Data` fields to be leverage on the Platform CLI
- Field types with Pydantic models are processed to show only the model name resulting in cleaner type
- `OBBject` return data fields are now stored as a list of dictionaries in the `reference.json` for consistency with the `data` and `parameters` fields in the `reference.json`. Updated logic is used to create the markdown content in the `create_reference_markdown_returns_section` function.
- Fixed provider models to reflect correct field type and description
- Updated static to reflect the new changes
3. **Impact** 
- Minor impact on docs, major impact in CX/DX
- `reference.json` is not …
> [Enhancement] Sync `reference.json` and Platform function docstring

- openbb_platform/obbject_extensions/charting/integration/test_charting_api.py
- openbb_platform/obbject_extensions/charting/integration/test_charting_python.py
- openbb_platform/obbject_extensions/charting/openbb_charting/__init__.py
- openbb_platform/obbject_extensions/charting/openbb_charting/charting_router.py
- openbb_platform/obbject_extensions/charting/openbb_charting/query_params.py
- openbb_platform/providers/fred/openbb_fred/models/series.py
- To add instant charts for FRED series.
- `obb.economy.fred_series("DGS10", provider="fred", chart=True)`
- Only works with `provider=fred`, raises an error when it is not.
- Creates a `query_params.py` file under `openbb_charting`.
- This is proposing a way to store, and get at, all valid **kwargs for the `to_chart()` method.
```
FRED Series Chart Query Params.
kwargs
------
data : List[Data], optional
Filtered versions of the data contained in the original results.
Example use is to reduce the number of columns or the length of data to plot.
To supply additional columns, set `allow_unsafe = True`.
title : str, optional
Title of the chart.
y1title : str, optional
Right Y-axis title. …
```
> [Feature] Add Charts For FRED Series

- openbb_platform/core/openbb_core/app/static/utils/decorators.py
1. **Why**?
- Autocompletion broken in Jupyter for functions with kwargs passed to `@validate(...)` decorator, such as `@validate(config=dict(arbitrary_types_allowed=True))`
2. **What**?
- Proper typing fixes the issue
3. **Impact**
- Minimal
- Typing a command and stopping at `...()`
Before
After
> [BugFix] - @validate with args breaks autocompletion

- openbb_platform/core/openbb_core/app/static/package_builder.py
- Passing kwargs was broken for POST endpoints which hindered the development and user experience.
- Handles the kwargs parameter and type hint on the package builder. Now kwargs can be passed and used.
- No noticeable impact. Allows for kwargs being passed when defined on the router.
- Tested that the kwargs work and are being passed.
> [BugFix] - Allow kwargs on POST endpoints

- openbb_platform/obbject_extensions/charting/openbb_charting/core/backend.py
- openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py
- When exporting an image, if the `loop` was already closed the `process_image()` method couldn't complete causing it do doesn't export at all.
- Check if we need to initialize a new `loop` and if yes, do it.
- None: all stays the same.
- Exporting the image: `res.chart.fig.show(export_image="test.png")`
Warning/Failure I was getting:
```bash
/OpenBBTerminal/openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py:928: UserWarning:
Failed to show figure with backend: Event loop is closed
```
> [BugFix] No event loop when exporting images

- openbb_platform/core/openbb_core/api/router/commands.py
- openbb_platform/core/openbb_core/app/command_runner.py
- openbb_platform/core/openbb_core/app/static/package_builder.py
- openbb_platform/core/tests/app/static/test_package_builder.py
- openbb_platform/core/tests/app/test_command_runner.py
1. **Why**?
- Untyped `VAR_KEYORD` arguments in endpoints like `**kwargs` are not supported
- Warning that checks `extra_params` is raising by mistake whenever `extra_params` exists
2. **What**?
- Warn only if `extra_params` is of type `ExtraParams`
- `validate_kwargs` allows untyped arguments like `**kwargs` to pass validation as `Any`
- In the API signature wrapper make sure that `VAR_KEYWORD` arguments always come last
- In the package builder generalises `VAR_KEYWORD` argument names to any name and makes sure they always come last
3. **Impact**
- We can now use `VAR_KEYWORD` parameters (`**kwargs`) in the endpoints, although this is has some non obvious caveats in the API - it will make the `VAR_KEYWORD` a required URL parameter, since `**` parameters cannot have a default, thus …
> [BugFix] - Untyped variadic keyword arguments break during execution

- .github/workflows/gh-pages.yml
1. **Why**?:
- When the docs pages were deployed, the static assets were built before generating the reference markdown files.
2. **What**?:
- Adds: `poetry run python -c "import openbb; openbb.build()"` after `dev_install.py -e`.
3. **Impact**:
- Documentation site should now show all routers and models.
- Tested the sequence of actions locally.
- Example: "Validated with historical market data and simulated scenarios."
> [BugFix] Docs: Build Static Assets Before Generating Markdown Files

- openbb_platform/obbject_extensions/charting/tests/test_charting.py
1. **Why**?:
- Test was a false positive due to a wrong implementation.
- Properly mock the dataframe and OBBject attributes.
- NA
- `pytest openbb_platform/obbject_extensions/charting/tests/test_charting.py`
> [BugFix] Fix tests for charting

- openbb_platform/obbject_extensions/charting/integration/test_charting_python.py
- equity.fundamental.multiples chart does not exist, test was removed from API integration tests, but not Python.
- Yeeted
- N/A
- Run tests.
> [Bugfix] Removes Charting Integration Test For Chart That Doesn't Exist

- openbb_platform/providers/yfinance/openbb_yfinance/models/etf_info.py
1. **Why**?:
- In some instances, ETF info data does not contain the `fundInceptionDate` field and this caused a validation error because it was missing.
- If that field is not present, use `firstTradeDateEpochUtc` instead.
3. **Impact**:
- Improves exception handling for edge case symbols.
- Before/After: `obb.etf.info("JJEB", provider="yfinance")`
> [BugFix] yFinance ETF Info: Try Different Field When Missing fundInceptionDate

- openbb_platform/core/openbb_core/api/router/commands.py
- openbb_platform/core/openbb_core/provider/registry_map.py
1. **Why**?
- API responses are excluding the symbol response field when multiple symbols are passed into `symbol` query parameter
2. **What**?
- Serialising the response before FastAPI prevents Pydantic from dropping extra fields, thus dropping `symbol` from API response
- This was present before https://github.com/OpenBB-finance/OpenBBTerminal/pull/6024, but discriminated unions require us to pass the provider field in the model
3. **Impact**
- Behaviour is consistent in both interfaces
- It also returns the provider where the data comes from, removing this in both interfaces introduces unnecessary complexity since the information can be ignored by frontend
> [BugFix] - Serialise response before FastAPI

- openbb_platform/core/openbb_core/app/router.py
- openbb_platform/core/openbb_core/app/static/package_builder.py
- openbb_platform/openbb/assets/reference.json
1. **Why**?
- Package builder was not dumping router descriptions if no command is at main router level, like `/derivatives` or `/regulators`. E.g.
```python
/derivatives
/options
/futures
```
2. **What**?
- Loop through the full route path looking for descriptions
- Avoid adding same router twice
3. **Impact**
NA
- Add descriptions to sub-routers, rebuild and check they are dumped into reference.json
> [BugFix] - Fix nested router descriptions

- openbb_platform/core/openbb_core/app/static/utils/filters.py
- openbb_platform/core/openbb_core/app/utils.py
- Multiple symbol check not working for many endpoints.
- Root cause was that if no `info` i.e., if there is no provider declaring `__json_schema_extra__` for the endpoint, no info will be there - this doesn't mean that we don't need to perform the check for multiple items.
- Added an `else` statement when no `info` is available that will evaluate the `kwargs` and verify that there aren't any multiple items.
- This presents a moderate impact as all the endpoints go through `filter_inputs()` function.
- Running multiples endpoints:
```python
obb.equity.estimates.historical(["AAPL","MSFT"], …
```
> [BugFix] Fix the multiple items check

- openbb_platform/core/openbb_core/provider/utils/helpers.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/equity_profile.py
- Having a negative timestamp would break the model validation, thus corrupting the command response.
- Used `datetime.timedelta` for a safe timestamp converstion when on Windows platform.
- NA - done at the provider level, allowing users to use the affected endpoint.
- Running the identified command that was running into issues for all the available providers: `obb.equity.profile("IBM", provider="yfinance").to_df()`.
- If the reviewer can't test on Windows:
- Before:
- After:
> [BugFix] Handling negative timestamps on Windows

- openbb_platform/providers/benzinga/openbb_benzinga/models/analyst_search.py
1. **Why**?:
- Fields are being returned from Benzinga that are undocumented - 'smart_score' and 'success_rate' over different intervals.
- Reference: https://docs.benzinga.io/benzinga-apis/calendar/get-analysts
- Added fields to the data model. FYI, @andrewkenreich
- Mystery fields will now have be defined in `open_api.json`
- Doesn't change anything, just adds model definitions.
Before:
After:
> [BugFix] Undocumented Benzinga Fields In API Response

- openbb_platform/providers/yfinance/openbb_yfinance/utils/helpers.py
1. **Why**?:
- When an end date is requested, handling for intraday was also adjusting the target date for non-intraday, resulting in an extra day being added.
- Set flag so that if `intraday`, then add 719 minutes to capture all intraday values inclusive of the `end_date`.
- No more unexpected extra date.
March 31, 2024 is a good test case because it is a Sunday, and we should not be getting April 1 when the data is daily/weekly/monthly.
- obb.equity.price.historical("BTC-USD", start_date="2024-03-01", end_date="2024-03-31", provider="yfinance", interval="15m"
- obb.equity.price.historical("QQQ", start_date="2024-01-01", end_date="2024-03-31", …
> [BugFix] Fix yFinance end_date filter when not intraday.

- openbb_platform/core/openbb_core/app/model/metadata.py
- openbb_platform/core/tests/app/model/test_metadata.py
- openbb_platform/core/tests/app/test_command_runner.py
- Metadata in a wrong format (namely json string) causes a poor UX.
- Fixed iteration on the arguments so that the length of each argument is properly accessed.
- No impact (metadata is optional).
- Running any endpoint with several arguments (before and after):
```python
res = obb.equity.price.historical("AAPL,MSFT", provider="fmp", start_date="2022-01-01")
res.extra["metadata"]
```
- NA
6. **Any other information** (optional)
Before:
After:
> [BugFix] Fix metadata creation

- openbb_platform/core/openbb_core/app/model/metadata.py
1. **Why**?:
- The API completely broke.
- `metadata.py` is not unpacking the nested objects.
```console
AttributeError: 'LTIR' object has no attribute 'items'
```
- The API works.
Before:
After:
5. **Reviewer Notes**:
- Please run all the tests yourself.
> [BugFix] Fixes the API

- openbb_platform/core/openbb_core/provider/standard_models/etf_holdings.py
- openbb_platform/extensions/etf/openbb_etf/etf_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity_estimates.py
- openbb_platform/openbb/package/etf.py
- openbb_platform/providers/fmp/openbb_fmp/models/etf_holdings.py
- openbb_platform/providers/fmp/openbb_fmp/models/etf_holdings_performance.py
- openbb_platform/providers/fmp/openbb_fmp/models/price_performance.py
- openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_etf_holdings_performance_fetcher.yaml
- openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_price_performance_fetcher.yaml
- openbb_platform/providers/fmp/tests/test_fmp_fetchers.py
1. **Why**?:
- For the endpoint: `obb.equity.price.performance(provider="fmp")` the URL string could be too long when passed a large list of symbols.
- This PR chunks the URL into groups of 200 symbols.
- Add `to_upper()` validator for the symbol parameter of `obb.etf.holdings()`.
- Clear "-" as a symbol from FMP response of ETF holdings, replacing with `None`.
- Large lists of symbols can be passed to the endpoint, with FMP as the provider.
- Upper case symbols are not required for ETF Holdings any more.
- Deprecate `obb.etf.holdings_performance()` in favour of making the user define the list of symbols themselves and use `equity.price.performance()` instead. …
> [BugFix] Chunk FMP Price Performance URL For Large Lists

- openbb_platform/providers/nasdaq/openbb_nasdaq/models/calendar_earnings.py
- openbb_platform/providers/nasdaq/openbb_nasdaq/models/historical_dividends.py
1. **Why**?:
- A couple of fetchers were missing `require_credentials=False`.
2. **What**?:
- Added, ^
3. **Impact**:
- These will now work without dummy credentials.
- Remove API key from user_settings.json
> [BugFix] Add Missing require_credentials=False In Nasdaq Fetchers

- openbb_platform/extensions/devtools/poetry.lock
- openbb_platform/extensions/devtools/pyproject.toml
1. **Why**?
- `openbb-core` uses `ruff ^0.1.6`
- `openbb-devtools` uses `ruff ^0.1.5`
2. **What**?
- Update `openbb-devtools` to `ruff ^0.1.6`
3. **Impact**
- NA
- NA
> [BugFix] - Sync ruff in dev_tools with openbb_core

- openbb_platform/providers/intrinio/openbb_intrinio/models/balance_sheet.py
- openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_balance_sheet_fetcher.yaml
1. **Why**?:
- A check that is used in the other statements to set the `period` shouldn't exist here because that is handled by a field validator. This made the line always validate to False because the value had already been mapped.
- Removed line.
- More better now.
- Balance sheet, annual and quarter.
> [BugFix] Intrinio Balance Sheet Period

- openbb_terminal/openbb_terminal/argparse_translator/argparse_translator.py
- Unexpected results on command execution within the CLI.
- Track the provider parameters name while parsing the groups so that those can be checked against later, instead of signature only (since provider parameters are not on the signature).
- NA - UX improvement on the CLI.
- Running `screener --exchange asx --sector Energy` on the CLI before and after and observe that the sector is now being properly filtered.
> [BugFix] Filtered provider arguments 

- openbb_terminal/openbb_terminal/controllers/utils.py
- Enhance UX, broken results look bad.
- Ensure everything on the dataframe is a text before sending it to be displayed by the backend.
- NA: UX improvement.
- Running the following on the CLI: world/news ; world/company ; coverage/command_schemas
> [BugFix] Empty views on the CLI

- openbb_platform/providers/intrinio/openbb_intrinio/models/equity_historical.py
1. **Why**?:
- Response is returning empty with no error messages.
2. **What**?:
- Raise the error message and do not return empty.
3. **Impact**:
- Actionable information now in the response instead of Empty.
Before:
```
[]
```
After:
```
OpenBBError: Intrinio Error Message -> API Access Denied: You do not have sufficient access to view this data
```
> [BugFix] Intrinio EquityPriceHistorical - Return Error Message When Invalid Key

- cli/openbb_cli/config/completer.py
- cli/openbb_cli/config/menu_text.py
- cli/openbb_cli/session.py
- The command history was saved locally with the login details not sanitized which could result in a security issue.
- Introduces sanitization to protected keywords `email`, `password` and `pat`.
- The user can still use the upper arrow key to get his command unsanitized while the session is still lasting. After restarting the CLI, it can't be grabbed anymore in an unsanitized form.
- Fix long command names not showing providers
- Higher security.
- Ensured it works by calling the `login` command and checking the local file.
> [Enhancement] - Sanitize sensitive data from `.cli.his`

- website/content/platform/development/standardization.md
1. **Why**?:
- Fixing broken URLs in docs pages.
> [HotFix] Fix broken URLs in docs page.

- openbb_platform/obbject_extensions/charting/openbb_charting/__init__.py
1. **Why**?:
- The basic theme for charts was relying on the `plotly.html` file to set the theme as light/dark mode. For users relying on inline display, the result was a figure with an unset background.
Before:
This can be observed from, `res.chart.fig`
- Insert a method that reads the user preference for `chart_style` and then sets the `paper_bgcolor` and `font_color` accordingly.
- Add a simple class method for toggling this choice on a generated figure.
- This ensures that the inline renders display correctly.
```
data = obb.equity.price.historical("AAPL", chart=True)
data.chart.fig
```
After:
This will update the figure to be the reverse of the `chart_style` …
> [BugFix] Set Chart Style Before Output

- website/content/platform/development/standardization.md
- website/content/pro/data-connectors/native-integrations.md
This PR has code that is a result of merging main into develop
> Sync main and develop

- openbb_platform/providers/sec/poetry.lock
- openbb_platform/providers/sec/pyproject.toml
1. **Why**?:
- This provider is now using aiohttp-client-cache, `toml` file was not reflecting this.
2. **What**?:
- Update the `toml` and `lock` files.
> [BugFix] Update SEC pyproject.toml

- openbb_platform/core/openbb_core/app/command_runner.py
- Creating a chart shouldn't break the whole creation of the `OBBject` (unless in debug mode).
- Encapsulate in a try/except block.
- NA / minor UX.
- Run any chart - manually insert an exception for testing purposes.
> [Feature] Update chart creation so it doesn't break the command execution

- openbb_platform/core/openbb_core/app/model/obbject.py
- So that the `to_df()` method doesn't break if the results are a string.
- Wraps the string in a list so that it's data framable.
- Minor UX improvement.
- `res = obb.equity.price.historical(...)`
- `res.results = "Hello!"`
- `res.to_df()`
> [Feature] Fallback to to_df() method when results are a string

- assets/extensions/provider.json
- openbb_platform/core/openbb_core/app/model/credentials.py
- openbb_platform/core/openbb_core/app/service/hub_service.py
- openbb_platform/providers/polygon/openbb_polygon/__init__.py
1. **Why**?
- User might want to specify their key names in uppercase
2. **What**?
- Create uppercase alias in the `Credentials` model
3. **Impact**:
- Locally `~/.openbb_platform/user_settings.json` allows uppercase credential name
- OpenBB Hub, same as above
Local test (user_settings.json)
```python
obb.user.credentials.show()
```
Hub test
```python
%env OPENBB_HUB_BACKEND=https://payments.openbb.dev
obb.account.login(pat="...")
obb.user.credentials.show()
```
> [BugFix] - Case insensitive credentials

- assets/extensions/obbject.json
- assets/extensions/provider.json
- assets/extensions/router.json
- assets/scripts/generate_extension_data.py
- openbb_platform/core/openbb_core/app/service/hub_service.py
- openbb_platform/core/openbb_core/provider/abstract/provider.py
- openbb_platform/providers/benzinga/openbb_benzinga/__init__.py
- openbb_platform/providers/biztoc/openbb_biztoc/__init__.py
- openbb_platform/providers/cboe/openbb_cboe/__init__.py
- openbb_platform/providers/ecb/openbb_ecb/__init__.py
- openbb_platform/providers/econdb/openbb_econdb/__init__.py
- openbb_platform/providers/federal_reserve/openbb_federal_reserve/__init__.py
- openbb_platform/providers/finra/openbb_finra/__init__.py
- openbb_platform/providers/finviz/openbb_finviz/__init__.py
- openbb_platform/providers/fmp/openbb_fmp/__init__.py
- openbb_platform/providers/fred/openbb_fred/__init__.py
- openbb_platform/providers/government_us/openbb_government_us/__init__.py
- openbb_platform/providers/intrinio/openbb_intrinio/__init__.py
- openbb_platform/providers/nasdaq/openbb_nasdaq/__init__.py
- openbb_platform/providers/oecd/openbb_oecd/__init__.py
- openbb_platform/providers/polygon/openbb_polygon/__init__.py
- openbb_platform/providers/sec/openbb_sec/__init__.py
- openbb_platform/providers/seeking_alpha/openbb_seeking_alpha/__init__.py
- openbb_platform/providers/stockgrid/openbb_stockgrid/__init__.py
- openbb_platform/providers/tiingo/openbb_tiingo/__init__.py
- openbb_platform/providers/tmx/openbb_tmx/__init__.py
- openbb_platform/providers/tradier/openbb_tradier/__init__.py
- openbb_platform/providers/tradingeconomics/openbb_tradingeconomics/__init__.py
- openbb_platform/providers/wsj/openbb_wsj/__init__.py
- openbb_platform/providers/yfinance/openbb_yfinance/__init__.py
1. **Why**?
- Logos not relevant anymore
2. **What**?
- Remove `logo_url` key from providers.json
- Flag optional packages to display those keys by default
3. **Impact**
NA
NA
> [BugFix] - Remove logos

- cli/openbb_cli/cli.py
- cli/poetry.lock
- cli/pyproject.toml
- cli/tests/test_cli.py
- openbb_platform/dev_install.py
1. **Why**?
- `dev_install.py` uses `toml` which needs to be manually installed in each environment, it's not in the dependency tree
2. **What**?
- Replace it with `tomlkit` which is used by `poetry`, thus it's already in the dependency tree
- Added a `Loading...` print statement to cli `main` since the application cold start takes a while and looks hanged
3. **Impact**
- No need to `pip install toml` anymore, `pip install poetry` and it will work
- `python dev_install.py`
- `python dev_install.py -e`
> [BugFix] - `dev_install.py` updates

- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity_fundamental.py
- openbb_platform/providers/fmp/openbb_fmp/models/key_metrics.py
1. **Why**?:
- Fixes issues using `with_ttm` parameter.
- Fixes field name aliases - we actually need both `__alias_dict__` and `alias` in the Field definition.
2. **What**?:
- General model clean-up.
- Identify more fields that are `%` values, and add `json_schema_extra` to the Field definition.
3. **Impact**:
- Expands a few field names to be more verbose.
- `roe` -> `return_on_equity`
- Multiple symbols
- `quarter` and `annual`, `with_ttm` True/False
> [BugFix] FMP Key Metrics

- openbb_platform/core/openbb_core/app/model/credentials.py
- openbb_platform/core/openbb_core/app/service/user_service.py
- openbb_platform/core/openbb_core/app/static/account.py
- openbb_platform/core/openbb_core/app/static/coverage.py
- openbb_platform/core/tests/app/service/test_user_service.py
1. **Why**?
- Login resets the user preferences to their default
- If the user changes some preference in `user_settings.json` file and then logs in, it ignores the file changes and uses defaults instead
2. **What**?
- Make sure only credentials are updated (merged with local credentials) when login
3. **Impact**
- NA
- Change preferences in `user_settings.json`. Login into the Hub with different credentials than you have in `user_settings.json`. Confirm no preferences were updated and local credentials were updated with values set in the hub.
> [BugFix] Only update credentials on login

- .github/workflows/general-linting.yml
- .pre-commit-config.yaml
- openbb_platform/core/poetry.lock
- openbb_platform/core/pyproject.toml
- openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py
* `general-linting.yaml` workflow might fail in unchanged files when linters have new versions (allowed by `openbb-devtools`). Just happened with ruff v0.4.5, where a file I didn't touch breaks new ruff version 
file: openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py
action: https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/9206586424/job/25324754940
* Use more permissive version of ruff in `openbb-core` to avoid conflicts with `openbb-devtools`
* Update `ruff` in pre-commit hooks. v0.4.5 was released and `openbb-devtools` allows it
* `mypy` was deleted from workflow checks in the release, it's added here
* linters were not running for `cli/`
> Run linters on changed files only

- website/docusaurus.config.ts
* Some READMEs like https://pypi.org/project/openbb-fmp/, have dead url https://docs.openbb.co/platform/development/contributing
* Redirect this url to [/platform/developer_guide/contributing](https://docs.openbb.co/platform/developer_guide/contributing)
* Only works in prod, not locally, see warnings [here](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects)
> [Docs] Redirect contributing URL

- cli/tests/test_models_settings.py
- openbb_platform/core/integration/test_obbject.py
- openbb_platform/core/tests/app/service/test_hub_service.py
- openbb_platform/extensions/economy/integration/test_economy_python.py
- openbb_platform/extensions/economy/openbb_economy/economy_router.py
- openbb_platform/obbject_extensions/charting/openbb_charting/__init__.py
- openbb_platform/obbject_extensions/charting/tests/test_charting.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/economy.py
> [BugFix] Pre release fixes

- openbb_platform/core/openbb_core/provider/standard_models/bond_indices.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_api.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_python.py
- openbb_platform/extensions/fixedincome/openbb_fixedincome/corporate/corporate_router.py
- openbb_platform/extensions/fixedincome/openbb_fixedincome/fixedincome_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/fixedincome.py
- openbb_platform/openbb/package/fixedincome_corporate.py
- openbb_platform/providers/fred/openbb_fred/__init__.py
- openbb_platform/providers/fred/openbb_fred/models/bond_indices.py
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_bond_indices_fetcher.yaml
- openbb_platform/providers/fred/tests/test_fred_fetchers.py
1. **Why**?:
This PR proposes major enhances to `fixedincome.corporate.ice_bofa` in the form of a new endpoint, `fixedincome.bond_indices`.
- This data set represents more than the corporate bond universe, and is not limited to the US.
- Implementation does not have parameter validation, leading to many empty requests.
2. **What**?:
- Curated series IDs defined in the Python files, no external CSV.
- Deprecate `fixedincome.corporate.ice_bofa`
- Improved type hinting and schema.
- Improved validation errors with actionable messages.
- Complete parameter validation
- Transforms and frequency aggregation added.
- `category` parameter with choices: "us", "emerging_markets", "high_yield"
- `index` parameter for selecting the specific (multiple items allowed) index within the category.
- …
> [Feature] ICE BofAML Bond Indices (FRED)

- cli/openbb_cli/argparse_translator/utils.py
- cli/openbb_cli/controllers/base_controller.py
- cli/openbb_cli/models/settings.py
- cli/tests/test_models_settings.py
- Removing unnecessary setting - controllers don't hold variables any more so doesn't make sense to have this setting anymore - controllers should be only created once since they hold no state.
- Removed setting and did the necessary adjustments-
- NA
- Run a few commands on CLI and check that everything works as before.
> [Feature] Remove remember contexts setting

- openbb_platform/core/openbb_core/provider/standard_models/mortgage_indices.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_api.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_python.py
- openbb_platform/extensions/fixedincome/openbb_fixedincome/fixedincome_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/fixedincome.py
- openbb_platform/providers/fred/openbb_fred/__init__.py
- openbb_platform/providers/fred/openbb_fred/models/mortgage_indices.py
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_bond_mortgage_fetcher.yaml
- openbb_platform/providers/fred/tests/test_fred_fetchers.py
1. **Why**?:
- Expand the data in the fixed income menu.
2. **What**?:
- Adds new endpoint: `obb.fixedincome.mortgage_indices()`
- Data is from FRED, published by Optimal Blue.
- Daily indices of US mortgage rates.
3. **Impact**:
- No breaking changes.
- Additional maintenance of endpoints and models.
- Unit/Integration
- CLI
> [Feature] Add Mortgage Indices

- openbb_platform/providers/fmp/openbb_fmp/models/economic_calendar.py
1. **Why**?:
- Error message that is slipping through from this end point.
2. **What**?:
- Raises OpenBBError encapsulating the error message from the status 200 response.
3. **Impact**:
- Better error message.
> [BugFix] Raise on  "Error Message" with FMP Econ Calendar

- cli/openbb_cli/controllers/base_platform_controller.py
^ (same as #6545, but branched off of main)
>  [Hotfix] Fixing local variable 'export' referenced before assignment 

- openbb_platform/core/openbb_core/app/logs/logging_service.py
- openbb_platform/core/openbb_core/app/logs/models/logging_settings.py
- openbb_platform/core/tests/app/logs/handlers/test_posthog_handler.py
- openbb_platform/core/tests/app/logs/test_logging_service.py
Re-opened PR from, #6548
1. **Why**?:
- Error with message creation where None was cast as a string.
- Posthog Handler tests were failing.
2. **What**?:
- `exec_info[1]` will be `None` instead of `"None"`
3. **Impact**:
- Should allow "CMD" to bucketed.
- The logs tests now all pass.
- Inspect locally
> [HotFix] Fix Logging Service, Fix Posthog Handler Tests

- cli/pyproject.toml
- openbb_platform/dev_install.py
- openbb_platform/extensions/devtools/poetry.lock
- openbb_platform/extensions/devtools/pyproject.toml
- openbb_platform/extensions/econometrics/poetry.lock
- openbb_platform/extensions/econometrics/pyproject.toml
- openbb_platform/extensions/technical/poetry.lock
- openbb_platform/extensions/technical/pyproject.toml
- openbb_platform/pyproject.toml
A few toml files still had <3.12 specified as supported python versions. This PR fixes them and bumps lineramodels
> Bump supported python version in toml files

- .github/scripts/noxfile.py
- .github/workflows/test-unit-cli.yml
- .github/workflows/test-unit-platform.yml
- openbb_platform/core/openbb_core/app/static/utils/decorators.py
- openbb_platform/core/tests/app/test_command_runner.py
- openbb_platform/extensions/derivatives/integration/test_derivatives_api.py
- openbb_platform/extensions/derivatives/integration/test_derivatives_python.py
- openbb_platform/extensions/derivatives/openbb_derivatives/futures/futures_router.py
- openbb_platform/extensions/tests/utils/helpers.py
- openbb_platform/obbject_extensions/charting/integration/test_charting_python.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/options_snapshots.py
- openbb_platform/providers/polygon/openbb_polygon/models/currency_snapshots.py
- openbb_platform/pyproject.toml
> [BugFix] Release fixes

- openbb_platform/core/openbb_core/app/model/charts/chart.py
- openbb_platform/core/tests/app/model/charts/test_chart.py
- openbb_platform/obbject_extensions/charting/integration/test_charting_api.py
- openbb_platform/obbject_extensions/charting/integration/test_charting_python.py
- openbb_platform/obbject_extensions/charting/openbb_charting/charting.py
- Charting integration tests breaking.
- Remotes the default value for the `Chart.format` and outsource that responsibility for the extension.
- The extension explicitly says what's the format during chart creating (`obbject.chart = Chart(...)`)
- NA
- Running integration tests.
- Running endpoints with and without charting implementation (python + api)
> [BugFix] Charting Integration Tests

- openbb_platform/core/openbb_core/provider/standard_models/personal_consumption_expenditures.py
- openbb_platform/extensions/economy/integration/test_economy_api.py
- openbb_platform/extensions/economy/integration/test_economy_python.py
- openbb_platform/extensions/economy/openbb_economy/economy_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/economy.py
- openbb_platform/providers/fred/openbb_fred/__init__.py
- openbb_platform/providers/fred/openbb_fred/models/personal_consumption_expenditures.py
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_personal_consumption_expenditures_fetcher_urllib3_v1.yaml
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_personal_consumption_expenditures_fetcher_urllib3_v2.yaml
- openbb_platform/providers/fred/tests/test_fred_fetchers.py
1. **Why**?:
- PCE is the Federal Reserve's preferred inflation index, and is a key component in the Board's interest rate policy.
2. **What**?:
- Data is from FRED.
- `obb.economy.pce()`
- The results can be turned to look exactly as they do in the release tables: https://fred.stlouisfed.org/release?rid=54
- Each date and category is one API call, the example below calls the default, "personal_income".
3. **Impact**:
- More data to maintain
- Unit/integration
```python
data = obb.economy.pce(date="2024-05-01,2023-05-01,2024-04-01")
df = data.to_df(index=None).pivot(columns="date", index=["line", "level", "element_id", "parent_id", "children", "symbol", "name", "units"], values="value")
df = df[df.columns[::-1]]
df
```
5. **Reviewer Notes** …
> [Feature] Add PCE (Personal Consumption Expenditures) reports to Economy

- openbb_platform/extensions/commodity/poetry.lock
- openbb_platform/extensions/crypto/poetry.lock
- openbb_platform/extensions/economy/poetry.lock
- openbb_platform/extensions/etf/poetry.lock
- openbb_platform/extensions/index/poetry.lock
- openbb_platform/extensions/quantitative/poetry.lock
1. **Why**?:
- Missed a few of the extension lock files in #6580
> [BugFix] Update Missed Lock Files for `certifi 2024.7.4`

- openbb_platform/extensions/fixedincome/openbb_fixedincome/fixedincome_views.py
1. **Why**?:
- A targeted column was having its name dropped by `reset_index()` and was causing the chart to not draw.
2. **What**?:
- Applied the column name change after the `reset_index()` operation.
3. **Impact**:
- Chart should draw properly now.
- Chart draws normally.
> [BugFix] Yield Curve Chart: Fix Syntax Where Pandas Drops Column Name After `reset_index()`

- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/economy.py
- openbb_platform/providers/fred/openbb_fred/models/search.py
1. **Why**?:
- ^
- API does not like an empty data response and will return a confusing 500 error.
2. **What**?:
- `raise EmptyDataError()` when the search results return nothing.
3. **Impact**:
- Will now `raise` instead of returning an empty list.
- Observed the error is being raised as expected.
> [BugFix] Raise EmptyDataError When No Results Returned From `obb.economy.fred_search()`

- openbb_platform/core/openbb_core/provider/standard_models/fred_release_table.py
- openbb_platform/extensions/economy/integration/test_economy_api.py
- openbb_platform/extensions/economy/integration/test_economy_python.py
- openbb_platform/extensions/economy/openbb_economy/economy_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/economy.py
- openbb_platform/providers/fred/openbb_fred/__init__.py
- openbb_platform/providers/fred/openbb_fred/models/release_table.py
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_release_table_fetcher_urllib3_v1.yaml
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_release_table_fetcher_urllib3_v2.yaml
- openbb_platform/providers/fred/tests/test_fred_fetchers.py
1. **Why**?:
- This feature adds a function similar to `obb.economy.fred_series`, but for the economic release tables.
- Generic endpoint that returns relational table data for a specific release and date(s).
- This function also serves as a discovery mechanism for individual FRED Series IDs that would otherwise be difficult to curate.
2. **What**?:
- New route: `obb.economy.fred_release_table()`
- Required parameter is `release_id`.
- Found via `obb.economy.fred_search()`, or from the FRED/Federal Reserve websites.
- `element_id` is the specific table from the release.
- When not supplied the top-level sections/tables are returned with IDs that can be used for drill-down.0
- Release and Element IDs are entered as strings, despite being numeric.
- Frequency selection is not possible via …
> [Feature] Add Fred Release Tables

- openbb_platform/core/openbb_core/app/command_runner.py
- openbb_platform/core/openbb_core/provider/standard_models/tips_yields.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_api.py
- openbb_platform/extensions/fixedincome/integration/test_fixedincome_python.py
- openbb_platform/extensions/fixedincome/openbb_fixedincome/government/government_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/fixedincome_government.py
- openbb_platform/providers/fred/openbb_fred/__init__.py
- openbb_platform/providers/fred/openbb_fred/models/tips_yields.py
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_tips_yields_fetcher_urllib3_v1.yaml
- openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_tips_yields_fetcher_urllib3_v2.yaml
- openbb_platform/providers/fred/tests/test_fred_fetchers.py
1. **Why**?:
- Expand the fixed income data with more daily benchmark items.
- TIPS (Treasury Inflation Protected Securities) provide investors with a gauge for an inflation-adjusted, risk-free, rate of return.
2. **What**?:
- Adds a new endpoint and data from FRED.
- obb.fixedincome.government.tips_yields()
- Historical data represents the current issue ("name") from inception.
3. **Impact**:
- More data to maintain.
- Unit/integration tests.
- CLI
- Various start/end date & maturity combinations.
> [Feature] Add TIPS Yields (to maturity)

- openbb_platform/extensions/equity/integration/test_equity_api.py
- openbb_platform/extensions/equity/integration/test_equity_python.py
- openbb_platform/extensions/etf/integration/test_etf_api.py
- openbb_platform/extensions/etf/integration/test_etf_python.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/economy.py
- openbb_platform/openbb/package/equity_price.py
- openbb_platform/openbb/package/etf.py
- openbb_platform/providers/alpha_vantage/openbb_alpha_vantage/models/equity_historical.py
- openbb_platform/providers/alpha_vantage/openbb_alpha_vantage/utils/helpers.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/equity_historical.py
1. **Why**?:
- Fields have been deprecated since 4.1.5.
2. **What**?:
In "yfinance" and "alpha_vantage":
- "adjusted" -> "adjustment"
In "yfinance": 
- "prepost" -> "extended_hours"
3. **Impact**:
- Old keys will no longer do anything except raise 'param not found' warning.
- Should be no impact otherwise.
> [Feature] Remove Deprecated Fields From Equity Historical

- openbb_platform/providers/fmp/openbb_fmp/models/etf_info.py
1. **Why**?:
- Percentage value not correctly reflected in `expense_ratio` field.
2. **What**?:
- Apply `field_validator`.
3. **Impact**:
- Value is stored as-expected now.
- `obb.etf.info("VOO", provider="fmp")`
> [BugFix] Fix Rogue Percent Value In FMP ETF Info

- openbb_platform/providers/fred/openbb_fred/models/release_table.py
1. **Why**?:
- Function fails to parse returned dates formatted as "Q1 2024".
2. **What**?:
- Adds additional logic for this variation.
3. **Impact**:
- Tables currently raising `JSONDecodeError` should now return properly.
```
obb.economy.fred_release_table(release_id="53", element_id="18673").to_df()
```
> [BugFix] FRED Release Table: Fix Date Parsing For Format Variation

- openbb_platform/core/openbb_core/provider/standard_models/equity_performance.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/economy.py
- openbb_platform/openbb/package/equity.py
- openbb_platform/openbb/package/equity_discovery.py
- openbb_platform/providers/tmx/openbb_tmx/models/gainers.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/gainers.py
- openbb_platform/providers/yfinance/openbb_yfinance/utils/helpers.py
- openbb_platform/providers/yfinance/tests/test_yfinance_helpers.py
1. **Why**?:
- Percent values not returned consistent with the rest of the Platform.
2. **What**?:
- Fixes in the helper function.
- Updates model definitions.
- Rebuilt statics.
3. **Impact**:
- More consistent output.
- Increased clarity in the schemas.
- Before/after with "percent_change" field.
> [BugFix] Fix Yfinance Discovery Percent Values

- openbb_platform/providers/cboe/openbb_cboe/utils/vix.py
1. **Why**?:
- In, `obb.derivatives.futures.curve("VX", provider="cboe")`, a column was unexpectedly being renamed as "index" after being reset.
2. **What**?:
- Renames the "index" column where it should already have been "symbol". 
3. **Impact**:
- Unclear if this is actually the expected behavior from Pandas. 
- Before/After: `obb.derivatives.futures.curve("VX", provider="cboe")`
> [BugFix] VIX Curve - fixes `reset_index` erasing the name of the field.

- openbb_platform/extensions/derivatives/openbb_derivatives/derivatives_views.py
1. **Why**?:
```
obb.derivatives.futures.curve("vx", chart=True)
/openbb_platform/extensions/derivatives/openbb_derivatives/derivatives_views.py:110: FutureWarning:
errors='ignore' is deprecated and will raise in a future version. Use to_datetime without passing `errors` and catch exceptions explicitly instead
```
2. **What**?:
- Use `col.apply(to_datetime)` instead.
> [BugFix] Fix Pandas FutureWarning In `derivatives.futures.curve` Chart

- openbb_platform/core/openbb_core/api/router/commands.py
- openbb_platform/core/openbb_core/provider/abstract/fetcher.py
1. **Why**?:
- Instances where Pydantic syntax has not been updated for V2.
```
PydanticDeprecatedSince20: The `__fields__` attribute is deprecated, use `model_fields` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.8/migration/
```
- Warning is raised when using `pytest` with provider fetchers.
2. **What**?:
- Use `model_fields` instead of `__fields__`.
- `fetcher.py`
-  `commands.py`
3. **Impact**:
- Resolves the warning.
- Recording a provider fetcher test, warning no longer being broadcast.
> [BugFix] `__fields__` is deprecated, use `model_fields` instead

- openbb_platform/core/openbb_core/provider/standard_models/equity_search.py
- openbb_platform/extensions/equity/integration/test_equity_api.py
- openbb_platform/extensions/equity/integration/test_equity_python.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity.py
- openbb_platform/providers/cboe/openbb_cboe/models/equity_search.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/equity_search.py
- openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_equity_search_fetcher_urllib3_v1.yaml
- openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_equity_search_fetcher_urllib3_v2.yaml
- openbb_platform/providers/nasdaq/openbb_nasdaq/models/equity_search.py
- openbb_platform/providers/sec/openbb_sec/models/equity_search.py
1. **Why**?:
- OpenAPI prefers `bool` when it is not an `Optional[bool]`.
- `use_cache` shouldn't be a standard param.
2. **What**?:
- Move `use_cache` to the provider models.
- Remove Optional from the boolean arguments
3. **Impact**:
- More consistent schema.
- Should have no impact real impact other than better `openapi.json` representations.
> [BugFix] Replace `Optional[bool]` with `bool` as type in Equity Search

- openbb_platform/providers/yfinance/openbb_yfinance/utils/helpers.py
1. **Why**?:
- This fixes an edge case where something in the Google Colabs environment is inserting UTC TZ to the output of `yfinance.download` which is raising errors because of unexpected formatting.
- This behavior seems to be specific to Colab.
2. **What**?:
- At the direct output of `yfinance.download`, adds a check for the index to remove the TZ, if it is there.
3. **Impact**:
- Historical prices from `openbb-yfinance` in Colab environment works.
- This can only be tested directly in Colab, by editing the files - use OPENBB_DEBUG_MODE='true' - to enable traceback.
This screenshot demonstrates the difference in dType between expected and Colab. Note the "x" in the Colab cell that fails because of unexpected TZ information when filtering for date ranges.
This …
> [BugFix] Fix Date In Output Of `yfinance.download` For Google Colab

- openbb_platform/providers/econdb/openbb_econdb/models/economic_indicators.py
1. **Why**?:
- Allows lowercase symbols through - i.e, 'gdp'.
2. **What**?:
- Ensure that a lowercase symbol is not scoped into the actual symbol formation stage.
3. **Impact**:
- Allows lowercase symbols - `gdp` - to be entered.
- Other behavior remains the same.
Before:
```python
obb.economy.indicators(symbol="gdp")
```
```
OpenBBError: No valid combination of indicator symbols and countries were supplied.
Valid countries for 'gdp' are: None
If the symbol - gdp - is missing a country code. Please add the two-letter country code or use the country parameter.
If already included, add '~' to the end of the symbol.
```
After:
> [BugFix] Allow lowercase `symbol` for EconDB EconomicIndicators

- openbb_platform/core/openbb_core/app/model/defaults.py
1. **Why**?:
- Adds clarity and actionable information to the warning.
- Suppressed if "routes" is actually empty and/or when `show_warnings` is set to `false`.
3. **Impact**:
- Annoying warning will no longer display if the user happens to have a legacy `user_settings.json` file with this key.
- The warning will be broadcast only when `routes` is actually populated
- Play around with `user_settings.json` to show and suppress the warning.
> [BugFix] Improve Warning For Invalid Defaults Key In `user_settings.json`

- openbb_platform/core/openbb_core/api/exception_handlers.py
- openbb_platform/providers/bls/openbb_bls/utils/helpers.py
1. **Why**?:
- Resolves #6661, #6662
2. **What**?:
- Sanitize the invalid API key error message from BLS.
- Handle `Field required` error in the API as 422.
3. **Impact**:
- Better privacy handling and improved exception handling for required fields in the API.
Resolves #6661:
Resolves #6662:
> [BugFix] Fix BLS Error and API Exception Handling - Resolves #6661 and #6662

- openbb_platform/extensions/derivatives/openbb_derivatives/derivatives_views.py
- openbb_platform/extensions/economy/openbb_economy/economy_views.py
- openbb_platform/extensions/fixedincome/openbb_fixedincome/fixedincome_views.py
- openbb_platform/extensions/technical/openbb_technical/technical_views.py
- openbb_platform/obbject_extensions/charting/openbb_charting/charts/generic_charts.py
- openbb_platform/obbject_extensions/charting/openbb_charting/charts/price_historical.py
1. **Why**?:
- The charting extension is relying on the output at runtime to set the user preference theme, this was excluding the API from being set by this preference.
2. **What**?:
- Sets `plot_bgcolor`, `paper_bgcolor` and `font_color` as white/black according to the user-defined preference in `user_settings.json`, "chart_style".
- This is done at the chart function level, prior to the `layout_kwargs` entry at output, and remains settable at runtime.
3. **Impact**:
- Charts output from the API should now be consistent with the Python output.
- Define the preference in `user_settings.json` and created the different charts from endpoints.
> [BugFix] Enforce User Preference For Dark/Light Mode In Chart Output To API

- openbb_platform/obbject_extensions/charting/openbb_charting/charts/generic_charts.py
- openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py
1. **Why**?:
- Bar charts in Jupyter were always being set as "overlay" every time `figure.show()` was run.
- `hovertemplate` and `width` were inaccessible from the `bar_kwargs` entry in the Generic Charts because those values were defined by default.
2. **What**?:
- Removes the lines that updated the figure layout as "overlay" when `isatty` was False.
- Prioritizes the user-supplied `hovertemplate` and `width` in `openbb_charting.charts.generic_charts.bar_chart` so that multiple values are not sent to the params.
3. **Impact**:
- More better.
Before:
After:
> [BugFix] Bar Chart Fixes

- openbb_platform/providers/bls/openbb_bls/utils/helpers.py
1. **Why**?:
- Resolves #6688
2. **What**?:
- Error created by concatenating a title string that does not exist.
- Skips if title is None
3. **Impact**:
- BLS series that do not have catalogue metadata are being handled correctly.
```python
obb.economy.survey.bls_series("JTS000000000000000QUR")
```
After:
> [BugFix] Fixes #6688 BLS Title String Concactenation

- openbb_platform/core/openbb_core/provider/standard_models/options_chains.py
- openbb_platform/core/openbb_core/provider/utils/options_chains_properties.py
1. **Why**?:
- This handles a KeyError from OptionsChainsProperties when skew cannot be calculated from a given expiry.
- Error will mostly be contained to VIX and similar chains, or when new weekly expiries are opened and IV is reported as 0, resulting in an unexpectedly empty DataFrame.
2. **What**?:
- Adds checks before accessing the potentially empty DFs and raises an error accordingly.
3. **Impact**:
- Improved error handling.
- Kind of hard to recreate, you might need to use VIX from Cboe, after hours, or when a new expiry is opened.
Before:
After:
> [BugFix] Handle Options Skew Error From Zero/Empty IV Value

- openbb_platform/core/openbb_core/build.py
- openbb_platform/core/poetry.lock
- openbb_platform/core/pyproject.toml
1. **Why**?:
- The build script does not ship with `openbb-core` and this is a problem for creating pip-installable packages with a minimal footprint. `--no-deps` is not something that can be included in `pyproject.toml` or `requirements.txt`, it requires a script.
2. **What**?:
- Adds a command line script - `openbb-build` - that ships with the `openbb-core` package and installs the `openbb` meta package if it is not already installed.
3. **Impact**:
- Enhanced ability to easily configure minimalist OpenBB app and API configurations.
- Eliminates the need to create, publish, and maintain some `openbb-empty` package to accomplish this task.
- Simplifies the static asset build procedure by reducing it to a command line executable.
- Bumps the minimum version of Ruff in `openbb-core` to …
> [Feature] Add An `openbb-build` Script To `openbb-core` Package

- openbb_platform/providers/yfinance/openbb_yfinance/models/futures_historical.py
1. **Why**?:
- Start/End dates were not being filtered from the `openbb-yfinance` provider in `obb.derivatives.futures.historical`
```python 
obb.derivatives.futures.historical(symbol='es',start_date='2024-09-20',end_date='2024-09-30').to_df()
```
2. **What**?:
- It was passing an inner function param name instead of the out function's.
3. **Impact**:
- Just this one fetcher.
- Before/After.
After:
| date       |    open |    high |     low |   close |      volume |
|:-----------|--------:|--------:|--------:|--------:|------------:|
| 2024-09-20 | 5714.75 | 5717.25 | 5699.25 | 5699.99 | 1.62366e+06 |
| 2024-09-23 | 5762    | 5784.5  | 5745.25 | 5776.75 | 1.07794e+06 |
| 2024-09-24 | 5774    | 5794.25 | 5754.75 | 5792    | 1.18122e+06 |
| 2024-09-25 | 5792.25 | …
> [BugFix] `obb.derivatives.futures.historical`: Fix Start/End Filters Not Being Applied.

- openbb_platform/core/openbb_core/provider/standard_models/bond_prices.py
- openbb_platform/core/openbb_core/provider/standard_models/bond_reference.py
- openbb_platform/core/openbb_core/provider/standard_models/bond_trades.py
- openbb_platform/core/openbb_core/provider/standard_models/treasury_auctions.py
- openbb_platform/core/openbb_core/provider/standard_models/treasury_prices.py
- openbb_platform/providers/government_us/openbb_government_us/models/treasury_auctions.py
- openbb_platform/providers/tmx/openbb_tmx/models/bond_prices.py
1. **Why**?:
- This adds to the continuing efforts towards identifying and standardizing percent fields, as well as communicating them via `Field(json_schema_extra={"x-unit_measurement": "percent", "x-frontend_multiply": 100})` 
2. **What**?:
- Updates some lesser-trafficked standard models with only community providers servicing them.
- Transforms the output of `GovernmentUSTreasuryAuctions` to comply with the metadata.
3. **Impact**:
- Improved consistency and standardization.
- This was tested by using the `openbb-platform-api` extension from #6587 to generate `widgets.json`.
> [Enhancement] Add `x-unit_measurement` To A Few Items

- openbb_platform/core/openbb_core/api/router/commands.py
- openbb_platform/core/openbb_core/app/model/defaults.py
- openbb_platform/core/openbb_core/app/static/container.py
1. **Why**?:
- The "defaults" section of the `user_settings.json` was not able to cope with anything other than "provider".
- The app fails to import if the defaults configuration is incorrect.
2. **What**?:
- Fixes the `Defaults` class so that validation errors don't happen when supplying other parameters.
- Issue here was being unnecessarily, overly, specific with type hints.
- Applies any defaults in the `Container`/`Command` classes if they are not supplied at runtime.
- In the API: Default params will only work where the API has a default of None for the parameter.
- Resolves #6686 via bypassing Provider Fallback if there is only one provider. Not a full solution, but will cover most scenarios in the custom router/provider world.
3. **Impact**:
- Improved configurability.
- The API …
> [BugFix] Make User Preferences -> Defaults Work With Any Parameter

- examples/streamlit/news.py
- examples/usdLiquidityIndex.ipynb
- openbb_platform/providers/biztoc/openbb_biztoc/models/world_news.py
1. **Why**?:
- In, `obb.news.world(provider="biztoc")`, `term` was not being passed correctly because the following block needed to be `elif` instead of `if`.
- Streamlit example has some broken syntax from changes introduced by the Biztoc API that were not reflected in this example.
2. **What**?:
- Updates the block in `BiztocWorldNewsFetcher`.
- Updates the code in the `/examples/streamlit/news.py` file.
3. **Impact**:
- Fixes bugs.
```python
obb.news.world(term="earnings", provider="biztoc")
```
- Running the Streamlit example with the Biztoc extension installed in "develop-mode".
> [BugFix] Fix Biztoc `term` Field Not Working & Fix Streamlit News Dashboard Example

- ruff.toml
1. **Why**?:
- Lint rules are being based on the Python 3.8, which is no longer supported.
2. **What**?:
- Updates the minimum version in ruff.toml
- Adds temporary ignores for typing.Dict and typing.List deprecations.
3. **Impact**:
- Lint rules will now reflect the supported versions of Python.
- Creates future work to update primitive type hints with their core library class
- I've been working off this locally for some time now, and have not run into any associated complications.
> [BugFix] Update `ruff.toml` To Use Python 3.9 As Minimum Supported Version

- openbb_platform/providers/fmp/openbb_fmp/models/etf_holdings.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/etf_holdings.py
1. **Why**?:
- Fields in `IntrinioEtfHoldings` and `FmpEtfHoldings` are missing percent identifiers for frontend display.
2. **What**?:
- Adds the missing `x-unit_measurement` items to the fields.
- Normalize the `coupon` field from Intrinio.
3. **Impact**:
- Consistency with the rest of the Platform.
- Before/After with `obb.etf.holdings("JNK", provider="intrinio")`
> [BugFix] Add Missing Percent Identifiers to Intrinio and FMP EtfHoldings

- openbb_platform/providers/sec/openbb_sec/models/company_filings.py
1. **Why**?:
- When attempting to filter for Form 4 resulted in other types of forms with '4' in it.
- Unexpected nan values from empty dates.
2. **What**?:
- Filters the `form_type` using "isin" instead of "contains".
- Moves `nan` replace to the bottom, immediately before the output.
3. **Impact**:
- Improved precision in the results.
- Bug fix.
```python
obb.equity.fundamental.filings("CRM", form_type='4,144,S-4', limit=0, provider="sec")
obb.equity.fundamental.filings("CRM", form_type='4', limit=0, provider="sec").to_df().report_type.unique()
```
> [BugFix] SecCompanyFilings: Purge `nan` Values & Make `form_type` Match 

- openbb_platform/extensions/equity/integration/test_equity_api.py
- openbb_platform/extensions/equity/integration/test_equity_python.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity.py
- openbb_platform/providers/intrinio/openbb_intrinio/__init__.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/historical_market_cap.py
- openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_historical_market_cap_urllib3_v1.yaml
- openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_historical_market_cap_urllib3_v2.yaml
- openbb_platform/providers/intrinio/tests/test_intrinio_fetchers.py
1. **Why**?:
- Adding coverage to an endpoint.
2. **What**?:
- Adds `intrinio` as a provider to, `obb.equity.historical_market_cap`
3. **Impact**:
- Expands provider coverage.
- Unit/integration tests.
5. **Reviewer Notes**:
- Data only exists from Intrinio where a corresponding 10-K/Q exists, which limits to start of the time series to about 2008.
> [Feature] Add Intrinio to `equity.historical_market_cap`

- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/historical_market_cap.py
1. **Why**?:
- For whatever reason now, I can get the daily granularity now where I wasn't this morning.
2. **What**?:
- Add "day" to the interval choices.
Note: In the screenshot below, it's unclear why there are two entries for November 5 from FMP
> [BugFix] Intrinio Historical Market Cap Daily Now Working

- openbb_platform/core/openbb_core/provider/standard_models/latest_financial_reports.py
- openbb_platform/extensions/equity/integration/test_equity_api.py
- openbb_platform/extensions/equity/integration/test_equity_python.py
- openbb_platform/extensions/equity/openbb_equity/discovery/discovery_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity_discovery.py
- openbb_platform/providers/sec/openbb_sec/__init__.py
- openbb_platform/providers/sec/openbb_sec/models/latest_financial_reports.py
- openbb_platform/providers/sec/tests/record/http/test_sec_fetchers/test_sec_latest_financial_reports_fetcher_urllib3_v1.yaml
- openbb_platform/providers/sec/tests/record/http/test_sec_fetchers/test_sec_latest_financial_reports_fetcher_urllib3_v2.yaml
- openbb_platform/providers/sec/tests/test_sec_fetchers.py
1. **Why**?:
- The SEC has an RSS feed for the latest financial reports, but is limited to only 200 results. You could easily miss an item because you weren't checking every ten minutes. This is a take on extending that to be able to include the entire day.
2. **What**?:
- Adds new endpoint:
- `obb.equity.discovery.latest_financial_reports`
- Supported providers: `sec`
- Other providers could jump in on this as well.
- The response provides key information and URLs to the documents.
- Optionally, a `report_type` - i.e, "8-K, 10-K", and a date for looking back.
- Multiple items allowed for, `report_type`.
3. **Impact**:
- Improved visibility for important filings made today across the provider universe.
- Unit/integration
- Non-weekday dates.
> [Feature] Add Endpoint For The Latest Financial Reports Filed With The SEC

- openbb_platform/core/poetry.lock
- openbb_platform/core/pyproject.toml
1. **Why**?:
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1749
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1753
2. **What**?:
- Bumps the minimum version of aiohttp to 3.10.11 in `openbb-core`
- Updates the `poetry.lock` file.
4. **Impact**:
- A full release is required to complete the patch, this is the first step.
> [Security] Bump `aiohttp` To V3.10.11

- openbb_platform/core/openbb_core/provider/standard_models/form_13FHR.py
- openbb_platform/providers/sec/openbb_sec/models/form_13FHR.py
- openbb_platform/providers/sec/openbb_sec/utils/helpers.py
- openbb_platform/providers/sec/openbb_sec/utils/parse_13f.py
1. **Why**?:
- This fixes an issue in, `obb.equity.ownership.form_13f`, where aggregation silently failed because of unfilled NaN values in a string field.
- Observable in when the 'asset_class' contained both options and share classes. Results would only aggregate the options positions.
2. **What**?:
- Fills the NaN with a string value to allow the group aggregation, then replaces on output.
- Renames a misnamed optional field to align with the definition, "voting_authority_other" -> "voting_authority_none"
- General maintenance with some code cleanup.
3. **Impact**:
- Fixes missing output
- Slightly better performance
- This was generally focused around a very large file (25MB text) that takes a long time to process.
- …
> [BugFix] Fix Parsing Error In SEC Form13F

- openbb_platform/providers/yfinance/openbb_yfinance/models/balance_sheet.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/cash_flow.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/income_statement.py
1. **Why**?:
- Resolves #6954
2. **What**?:
- Applies to `balance`,  `cash`, and `income`.
- Add `le=5` to the yFinance model definition.
- Filter out the response if limit < 5.
3. **Impact**:
- For `provider='yfinance'`, a validation error will raise when the limit is more than 5.
> [BugFix] Fix Limit Param For yFinance Financials

- build/conda/installer/assets/openbb_platform_installer/openbb_platform_installer/__init__.py
- build/conda/installer/assets/openbb_platform_installer/pyproject.toml
- build/conda/installer/construct.yaml
- build/conda/installer/post_install.bat
- build/conda/installer/post_install.sh
1. **Why**?:
- Resolves #7001
2. **What**?:
- Forces 1.8.5 in the `post_install` script so it doesn't crash while trying to downgrade itself.
- Taking this approach until the main library is updated for Poetry 2.0
- Fixes failing Windows installers.
- Locally built.
> [BugFix] Installer: Force lower version of `poetry` in `post_install` script.

- openbb_platform/providers/imf/openbb_imf/models/economic_indicators.py
1. **Why**?:
- This fixes an issue where the series title was not being mapped in, `obb.economy.indicators(provider="imf")`
2. **What**?:
- Maps it from the symbols static asset, in `transform_data`
3. **Impact**:
- More clarity and better presentation.
- "title" field now returned when `provider="imf"`
> [BugFix] Fix Missing 'title' In IMF Economic Indicators

- openbb_platform/extensions/platform_api/README.md
- openbb_platform/extensions/platform_api/openbb_platform_api/main.py
- openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
- openbb_platform/extensions/platform_api/tests/mock_widgets.json
1. **Why**?:
- Updating the `openbb-platform-api` package to include hover readout for table column headers, and to add a route for `templates.json`
2. **What**?:
- For Workspace tables, all field descriptions will now display on hover.
- `templates.json` is served from a local file, `~/OpenBBUserData/workspace_templates.json`
- If the file does not exist, an empty JSON will be generated.
- Add exported dashboard templates to the list in that file.
3. **Impact**:
- Improved UX.
- Ability to use the custom templates functionality with the Platform backend.
- Test by launching via, `openbb-api`
> [Feature] openbb-platform-api:  Add column header tooltips and templates.json route.

- openbb_platform/providers/fmp/openbb_fmp/models/equity_profile.py
1. **Why**?:
- In, `obb.equity.profile(provider='fmp')`, an untraded symbol created an error where the high/low was attempting to access a field that did not exist.
2. **What**?:
- Add check to the `split`.
3. **Impact**:
- Fixes a bug.
```python
obb.equity.profile("FB", provider="fmp").to_dict("records")
```
```sh 
[{'symbol': 'FB',
'name': 'Meta Platforms, Inc.',
'cik': '0001326801',
'cusip': '30303M102',
'isin': 'US30303M1027',
'stock_exchange': 'NASDAQ Global Select',
'long_description': "Meta Platforms, Inc. develops products that enable people to connect and share with friends and family through mobile devices, personal computers, virtual reality headsets, wearables, and in-home devices worldwide. It operates in two segments, Family of Apps and Reality Labs. The …
```
> [BugFix] `obb.equity.profile(provider='fmp')` - Fix 'NoneType' object has no attribute 'split' where symbol is untraded.

- frontend-components/plotly/src/components/Chart.tsx
1. **Why**?:
- Resolves #6567
2. **What**?:
- Removes a function that attempted to limit the x-range in candlestick charts. 
- CLI and other consumers via PyWry affected.
This now works, no crashing or glitch-out.
```python
data = obb.equity.price.historical("AAPL", start_date="2000-01-01", provider="yfinance", chart=True)
data.show()
```
> [BugFix] Remove Crashing Elements That Attempt To Limit X-Range Displayed In Candles

- openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
- openbb_platform/extensions/platform_api/openbb_platform_api/utils/widgets.py
1. **Why**?:
- Provides a way to define some, or all, widget configuration settings that will override the automatically-generated content.
2. **What**?:
- Reads a dictionary supplied in the `@router.command` decorator and updates the generated widget entry with the supplied settings.
3. **Impact**:
- Improves developer experience.
- Requires knowing the nested dictionary structure that is `widgets.json`. 
- Some router extension, and change the "type".
```python
"""Empty Router Extenision for OpenBB Platform."""
from datetime import datetime
from typing import Annotated
from fastapi import Query
from fastapi.responses import JSONResponse
from openbb_core.app.router import Router
router = Router(prefix="", description="A custom OpenBB router extension.") …
```
> [Feature] `openbb-platform-api`: Adds Configurations Supplied In Router Decorator To `widgets.json`

- openbb_platform/core/openbb_core/provider/standard_models/calendar_events.py
- openbb_platform/extensions/equity/integration/test_equity_api.py
- openbb_platform/extensions/equity/integration/test_equity_python.py
- openbb_platform/extensions/equity/openbb_equity/calendar/calendar_router.py
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/equity_calendar.py
- openbb_platform/providers/fmp/openbb_fmp/__init__.py
- openbb_platform/providers/fmp/openbb_fmp/models/calendar_events.py
- openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_calendar_events_fetcher_urllib3_v1.yaml
- openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_calendar_events_fetcher_urllib3_v2.yaml
- openbb_platform/providers/fmp/tests/test_fmp_fetchers.py
1. **Why**?:
- Corporate events that are not covered by the current calendar endpoints.
2. **What**?:
- Adds new endpoint:
- `obb.equity.calendar.events`
- Data is from FMP, but easily expandable.
3. **Impact**:
- Increases the type of corporate event information available.
```json
{
"symbol": "MSTR",
"exchange": "NASDAQ",
"time": "09:00",
"when": "pre market",
"date": "2024-11-19",
"publicationDate": "2024-11-18",
"title": "MicroStrategy Announces Proposed Private Offering of $1.75 Billion of Convertible Senior Notes",
"url": "https://www.businesswire.com/news/home/20241118315372/en/MicroStrategy-Announces-Proposed-Private-Offering-of-1.75-Billion-of-Convertible-Senior-Notes/"
}
```
- Unit/integration tests
**Note**: Default lookahead is 3-days, not what is showing …
> [Feature] Company Events Calendar

- openbb_platform/providers/yfinance/openbb_yfinance/utils/helpers.py
1. **Why**?:
- YFinance functions in `obb.equity.discovery` and `obb.equity.screener` were subjected to a duplicated line creating double results from the first page of results.
2. **What**?:
- Fixes the bad code.
3. **Impact**:
- Fixes duplicate results.
- Before/After - i.e, `obb.equity.discovery.aggressive_small_caps`, etc.
> [BugFix] `openbb-yfinance`: Remove Duplicated Line In Screener Causing Double Results For First Pass

- openbb_platform/extensions/platform_api/openbb_platform_api/utils/widgets.py
- openbb_platform/extensions/platform_api/tests/mock_widgets.json
1. **Why**?:
- Somewhere along the way the chart widget lost its "type" setting, this restores it.
2. **What**?:
- Overwrites the default, "table".
- Briefly note the expected outcome or any potential risks and share the Impact Analysis score.
- Can be checked by generating widgets from Platform API, built locally, and opening a chart.
> [BugFix] Fix Chart Widgets Not Overwriting '{"type": "table"}'

- openbb_platform/core/openbb_core/api/router/commands.py
1. **Why**?:
- This PR corrects the API command wrapper for the desired behavior.
- `no_validate=True` in the @command decorator is for discarding all output response models entirely.
- Setting as True will defeat the automatic generation of `columnsDefs` by `openbb-platform-api` 
- The default, False, retains the response models and allows any type to be defined - i.e, `-> dict` or `-> SomeModel` or `-> OBBject`.
2. **What**?:
- Basically just reverses what the check was to look for instance of `OBBject` before acting.
3. **Impact**:
- Most notably impacted are the data processing routers.
```python
@router.command(methods=["GET"])
async def some_metric(
symbol: str,
) -> dict:
"""Some metric for a stock."""
return {
"label": "P/E",
"value": 600,
"delta": "",
}
```
> [BugFix] API: Reverse Output Of Wrapper Checking Object To Pass Custom Response Model

- openbb_platform/core/openbb_core/app/model/credentials.py
- openbb_platform/core/tests/app/service/test_hub_service.py
1. **Why**?:
- Items defined in `user_settings["credentials"]` only populate if they are in the ProviderInterface, this is not ideal.
2. **What**?:
- Populates the Credentials model with any leftover key:value pairs from `user_settings.json`, if it exists.
3. **Impact**:
- Improved developer experience, more freedom.
- Arbitrary keys being defined have no real consequence, but greatly improve the flexibility - like incorporating Hub configurations with completely custom APIs and apps that are authorized by a remote script.
> [Feature] Allow Arbitrary Credentials From `user_settings.json` To Populate Credentials Model

- openbb_platform/providers/fmp/openbb_fmp/models/etf_info.py
1. **Why**?:
- A string containing only "Error Message" was not raising UnauthorizedError.
2. **What**?:
- Raises UnauthorizedError when returned with that 
- Fixes #7043 
```python
[Error] -> Unauthorized FMP request -> Exclusive Endpoint : This endpoint is not available under your current subscription agreement, please visit our subscription page to upgrade your plan or contact us at https://site.financialmodelingprep.com/developer/docs/pricing
```
> [BugFix] Surface FMP Error Message In `etf.info`

- openbb_platform/extensions/platform_api/README.md
- openbb_platform/extensions/platform_api/openbb_platform_api/utils/api.py
- openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
- openbb_platform/extensions/platform_api/openbb_platform_api/utils/widgets.py
- openbb_platform/extensions/platform_api/pyproject.toml
1. **Why**?:
- Self-inflicted wound, the intention was to delete `$.` references after being transferred to the correct place. The reality was the it was being removed from the schema entirely, so the next iteration of that widget definition was missing those components.
2. **What**?:
- Use dict comprehension instead of removing key from original.
3. **Impact**:
- When more than 1 PDF widget was created, this became an issue.
> [!TIP]
> Refer to the Impact Analysis confluence (internal) document for more information.
- Make multiple PDF widgets in a custom backend.
> [BugFix] `openbb-platform-api` - Fix `$.` References Being Deleted Outside Of Loop

- openbb_platform/obbject_extensions/charting/poetry.lock
- openbb_platform/obbject_extensions/charting/pyproject.toml
1. **Why**?:
- In Plotly 6, when a Figure is serialized as JSON and converted back to a Figure, the chart may-or-may-not display with the content on the top layer.
- The "data" is now a different format, something is getting lost in translation while rendering in the browser.
- I'm pretty sure that I checked for this exact scenario when bumping to V6, and it appears to be some sort of conditional element to it, so I'm not entirely sure why it is like it is.
2. **What**?:
- Downgrades to 5.24.1 to ensure compatibility and consistent output.
- Will monitor for changes..
You can make this chart by adding this to the `user_settings.json`
```json
{
"defaults": {
"commands": {
"/equity/price/historical": {
"provider": "yfinance",
"chart": true,
"chart_params": { …
```
> [BugFix] Downgrade Plotly To 5.24.1 For JSON Output Formatting

- openbb_platform/providers/sec/openbb_sec/models/sec_filing.py
1. **Why**?:
- Filings having no associations with trading symbols were failing because the local was assigned in an indented block.
2. **What**?:
- Moves the assignment of local to the top of the block.
3. **Impact**:
- Recreate with a filing like a S-1 - https://www.sec.gov/Archives/edgar/data/2011286/000162828025011468/0001628280-25-011468-index.htm
- After:
> [BugFix] `obb.regulators.sec.filing_headers` Fix Accessing Local Before Assignment

- openbb_platform/providers/yfinance/openbb_yfinance/utils/helpers.py
1. **Why**?:
- End date not being captured properly, need to advance the end_date when data is intraday.
2. **What**?:
- Fixes in helper `yf.down_download`
3. **Impact**:
- More better
- Before:
- After:
> [BugFix] Fix yFinance Intraday "end_date" Filter

- openbb_platform/core/openbb_core/app/command_runner.py
- openbb_platform/core/openbb_core/app/model/preferences.py
- openbb_platform/providers/biztoc/openbb_biztoc/models/world_news.py
1. **Why**?:
- Resolves #7042
- Symptoms are a hung interpreter when warnings are cast in `CommandRunner`.
- Seems to be an issue with Colab, specifically.
2. **What**?:
- Moves the handling for `showwarning`, and appending the list of warnings to the `OBBject`, to outside of the `catch_warnings` context block.
3. **Impact**:
- No changes expected.
- Sets `show_warning` user preference to default as `False`.
- You can test by editing code in a remote Colab environment.
- Ran the `openbb-core` tests.
> [BugFix] Move `showwarning` To Outside `catch_warnings` Context Block

- .github/scripts/noxfile.py
- cli/openbb_cli/argparse_translator/argparse_translator.py
- openbb_platform/core/openbb_core/api/router/commands.py
- openbb_platform/core/openbb_core/app/static/package_builder.py
- openbb_platform/extensions/econometrics/openbb_econometrics/econometrics_router.py
- openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
- openbb_platform/extensions/platform_api/tests/mock_openapi.json
- openbb_platform/extensions/platform_api/tests/mock_widgets.json
- openbb_platform/extensions/platform_api/tests/test_openapi_utils.py
- openbb_platform/extensions/quantitative/openbb_quantitative/performance/performance_router.py
- openbb_platform/extensions/quantitative/openbb_quantitative/quantitative_router.py
- openbb_platform/extensions/quantitative/openbb_quantitative/rolling/rolling_router.py
- openbb_platform/extensions/quantitative/openbb_quantitative/stats/stats_router.py
- openbb_platform/extensions/technical/openbb_technical/technical_router.py
- openbb_platform/extensions/technical/openbb_technical/technical_views.py
1. **Why**?:
- Changes introduced to package builder broke the logic for docstring generation.
2. **What**?:
- Refactor `DocstringGenerator`
- Fixes CLI where type discovery failed
- Fixes openbb-platform-api utils tests, and a key error.
3. **Impact**:
- Missing descriptions from the `extra_params` items are now back.
- Improved docstrings for custom extensions.
Before:
```sh
"""Get historical price data for a given stock. This includes open, high, low, close, and volume.
Parameters
----------
symbol : Union[str, List[str]]
Symbol to get data for. Multiple comma separated items allowed for provider(s): alpha_vantage, cboe, fmp, polygon, tiingo, tmx, tradier, yfinance.
start_date : Union[date, None, str]
Start date of the data, in YYYY-MM-DD format.
end_date : …
```
> [BugFix] Fixes Docstring Generator Broken By #7066

- openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
- openbb_platform/providers/tmx/openbb_tmx/models/etf_countries.py
- openbb_platform/providers/tmx/openbb_tmx/models/etf_holdings.py
- openbb_platform/providers/tmx/openbb_tmx/models/etf_search.py
- openbb_platform/providers/tmx/openbb_tmx/models/etf_sectors.py
- openbb_platform/providers/tmx/openbb_tmx/models/index_sectors.py
1. **Why**?:
- KeyError caused by empty result.
- Found a widget `columnDef` being defined as a date when it is a percent.
2. **What**?:
- Fixes KeyError
- Narrows scope of date-like field type definitions by `openbb-platform-api`
3. **Impact**:
- Fixes bugs and improves accuracy. 
- You can check with:
- `obb.etf.sectors("CASH", provider="tmx")
- `obb.etf.info("CASH", provider="tmx")
- Workspace backend widget, "Return YTD", was missing from a bar chart created by `etf.info`
- `etf.sectors` was not returning None cleanly.
> [BugFix] `etf.sectors(provider='tmx')` - Fix Key Error When No Info Found

- openbb_platform/core/openbb_core/api/router/commands.py
- openbb_platform/core/openbb_core/app/router.py
- openbb_platform/core/openbb_core/app/static/package_builder.py
1. **Why**?:
- There were a couple of spots where `openapi_extra` was being accessed as a dictionary when the value was None.
2. **What**?:
- Fixes those instances to include the None check.
3. **Impact**:
- Custom extensions, Platform endpoints will have items in the openapi_extra slot.
- Custom Router extension, create the function by directly accessing APIRouter instance.
`@router._api_router.get("/get_data_choices")`
> [BugFix] Safely Access `openapi_extra` When None

- openbb_platform/core/openbb_core/app/static/package_builder.py
- openbb_platform/core/openbb_core/build.py
- openbb_platform/core/poetry.lock
- openbb_platform/core/pyproject.toml
- openbb_platform/openbb/assets/reference.json
- openbb_platform/openbb/package/__extensions__.py
- openbb_platform/openbb/package/fixedincome_government.py
Sometimes building the static assets is resulting in missing examples in the docstring. This PR resolves that inconsistency.
Example:
Then the second time building:
> [HotFix] Fix Missing Docstring Examples

- openbb_platform/core/openbb_core/build.py
This PR will address the missing examples section in the documentation pages, and docstrings.
The problem was that the build script was being run in separate processes, while `import openbb` in the main thread was also engaging it. 
The fix is to move the initial `import openbb` statement into a subprocess and monitor the stdout for confirmation if a build happened on import.
If a build has not happened, then `openbb-build` will then trigger a rebuild event in the main thread.
This makes sure that all actions involving writing to the static assets are contained to the same thread.
This can be tested by watching the static asset files and running `openbb-build` from the command line with `openbb-core`
> [BugFix] Fix missing docstring examples from `openbb-build` script.

- openbb_platform/core/openbb_core/app/model/obbject.py
- openbb_platform/core/tests/app/model/test_obbject.py
- openbb_platform/obbject_extensions/charting/openbb_charting/charts/helpers.py
1. **Why**?:
- `to_dataframe()` was struggling when an oddly-shaped model was being passed in.
This would result in various ValueErrors:
```python
ValueError: All arrays must be of the same length
ValueError: If using all scalar values, you must pass an index. Ensure the data format matches the expected format.
```
2. **What**?:
- This fix involves creating a Pandas Series from the content instead of a DataFrame, and then using `to_frame()`.
- If the object is of BaseModel-type, the column will be named using the class.
- If the object is a dictionary, we test for "orient" and then fallback on creating a Series where the column is named, "values".
Additionally, this handles a FutureWarning in the charting library, silenced with,`fill_method=None`
3. **Impact**:
- Fewer conversion errors, …
> [BugFix] Handle Dictionaries & Single Model Results Better In `to_dataframe`

- openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py
- openbb_platform/obbject_extensions/charting/openbb_charting/core/plotly_ta/data_classes.py
- openbb_platform/providers/intrinio/openbb_intrinio/models/market_snapshots.py
- openbb_platform/providers/nasdaq/openbb_nasdaq/models/equity_search.py
This PR resolves the following warnings:
```sh
/openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py:1133: UserWarning:
no explicit representation of timezones available for np.datetime64
/openbb_platform/obbject_extensions/charting/openbb_charting/core/plotly_ta/data_classes.py:391: FutureWarning:
DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
/openbb_platform/providers/intrinio/openbb_intrinio/models/market_snapshots.py:234: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
/openbb_platform/providers/nasdaq/openbb_nasdaq/models/equity_search.py:146: FutureWarning:
Downcasting object dtype arrays on …
```
> [BugFix] Fixes For FutureWarning Items

- openbb_platform/extensions/platform_api/openbb_platform_api/assets/default_apps.json
- openbb_platform/extensions/platform_api/openbb_platform_api/main.py
- openbb_platform/extensions/platform_api/openbb_platform_api/response_models.py
- openbb_platform/extensions/platform_api/openbb_platform_api/utils/api.py
- openbb_platform/providers/federal_reserve/openbb_federal_reserve/models/fomc_documents.py
This PR restores the FOMC Documents Workspace app from a breaking change upstream, and changes a couple of default apps' images so they fit in the box.
You can test by opening the widget in a Workspace dashboard. Before, no API call made to get the actual choices of documents.
> [BugFix] Fix FOMC Minutes App and Default App Images

- openbb_platform/providers/yfinance/openbb_yfinance/models/balance_sheet.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/cash_flow.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/company_news.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/equity_profile.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/equity_quote.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/etf_info.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/historical_dividends.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/income_statement.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/key_executives.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/key_metrics.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/options_chains.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/price_target_consensus.py
- openbb_platform/providers/yfinance/openbb_yfinance/models/share_statistics.py
- openbb_platform/providers/yfinance/openbb_yfinance/utils/helpers.py
- openbb_platform/providers/yfinance/poetry.lock
- openbb_platform/providers/yfinance/pyproject.toml
1. **Why**?:
- yFinance has changed their session object to use `curl-cffi`
- All yFinance functions are broken under normal conditions. 
2. **What**?:
- Uses `curl-adapter` to mount the Requests Session object for use with the new framework.
3. **Impact**:
- `curl-adapter` maintains the complete functionality of Requests, so all user-defined session attributes should remain intact.
- https://curl-cffi.readthedocs.io/en/latest/advanced.html#as-a-urllib3-requests-adapter
- You can tell it's working because the functions don't return a Rate Limit Error.
> [BugFix] Patch yFinance For The Change To `curl-cffi`

- openbb_platform/core/openbb_core/app/model/obbject.py
1. **Why**?:
- The fix in #7099 failed to account for the case in OptionsChainsData.
- This single model serializes as a `list[dict]`, but the logic handled as `dict[str, Any]`
- Fixes #7108 
2. **What**?:
- Apply conditional checks to the dumped model to handle `list[dict]` and `dict[str, list]` from a single model.
3. **Impact**:
- Restores expected output from `obb.derivatives.options.chains(...).to_df()`
> [BugFix] Fix `to_df` in `OptionsChainsData`
