OpenBB-finance/OpenBB

README.md

fix config_terminal.txt -> config_terminal.py

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
README.md

WIP, do not merge (improvements from #31)

Readme improvements + github issue draft

---

.github/workflows/test.yml
gamestonk_terminal/sentiment/reddit_api.py
tests/test_sentiment_reddit_api.py

New look:
```
> popular -n 20 -s wallstreetbets -l 100 -d 5
Search for latest tickers under 100 'wallstreetbets' posts
209 potential tickers found.
The following TOP 20 tickers have been mentioned in the last 5 days:
Mentions Ticker                                            Company                  Sector   Price  Change Perf Month                                   URL
0         29    GME                                     GameStop Corp.       Consumer Cyclical  140.99   6.53%     47.06%   https://finviz.com/quote.ashx?t=GME
1          5   SPXS                                          Financial    Exchange Traded Fund   35.18  -5.46%      2.54%  https://finviz.com/quote.ashx?t=SPXS
2          5   SQQQ                                          Financial    Exchange Traded Fund   15.02 …
```

Improvements for Sentiment / popular

---

gamestonk_terminal/dataframe_helpers.py
gamestonk_terminal/discovery/alpha_vantage_api.py
gamestonk_terminal/discovery/disc_menu.py
gamestonk_terminal/discovery/fidelity_api.py
gamestonk_terminal/discovery/finviz_api.py
gamestonk_terminal/discovery/seeking_alpha_api.py
gamestonk_terminal/discovery/short_interest_api.py
gamestonk_terminal/discovery/simply_wallst_api.py
gamestonk_terminal/discovery/spachero_api.py
gamestonk_terminal/discovery/unusual_whales_api.py
gamestonk_terminal/discovery/yahoo_finance_api.py
gamestonk_terminal/due_diligence/business_insider_api.py
gamestonk_terminal/due_diligence/dd_menu.py
gamestonk_terminal/due_diligence/financial_modeling_prep_api.py
gamestonk_terminal/due_diligence/finviz_api.py
gamestonk_terminal/due_diligence/market_watch_api.py
gamestonk_terminal/due_diligence/quandl_api.py
gamestonk_terminal/due_diligence/reddit_api.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/reddit_helpers.py

So far this PR does:
- Ultra cleanup + General refactoring of Discovery directory
- Ultra cleanup + General refactoring of Due Diligence directory
- Fix price target (pt) on DD
- Fix warnings on DD
I'll keep cleaning all directories, and improve overall coding

Ultra cleanup + General refactoring + Bug fixes

---

gamestonk_terminal/fundamental_analysis/fa_menu.py

This PR was created by running `pyupgrade --py36-plus **/*.py`
* https://github.com/asottile/pyupgrade

pyupgrade to py36-plus syntax

---

.github/workflows/test.yml
terminal.py

https://realpython.com/the-most-diabolical-python-antipattern/
https://www.python.org/dev/peps/pep-0008/

PEP8: Do not use bare 'except'

---

gamestonk_terminal/fundamental_analysis/alpha_vantage_api.py
gamestonk_terminal/fundamental_analysis/business_insider_api.py
gamestonk_terminal/fundamental_analysis/fa_menu.py
gamestonk_terminal/fundamental_analysis/financial_modeling_prep_api.py
gamestonk_terminal/fundamental_analysis/finviz_api.py
gamestonk_terminal/fundamental_analysis/market_watch_api.py
terminal.py

- Refactor overall FA code (according to #26 and #53)
- Fix all Market Watch web scraping commands
- Fix quote FMP API call

Refactor FA folder

---

.github/workflows/test.yml
gamestonk_terminal/fundamental_analysis/market_watch_api.py
gamestonk_terminal/prediction_techniques/arima.py
gamestonk_terminal/prediction_techniques/fbprophet.py
gamestonk_terminal/prediction_techniques/knn.py
gamestonk_terminal/prediction_techniques/pred_menu.py
gamestonk_terminal/prediction_techniques/regression.py
gamestonk_terminal/prediction_techniques/sma.py
gamestonk_terminal/sentiment/reddit_api.py
gamestonk_terminal/sentiment/stocktwits_api.py
gamestonk_terminal/technical_analysis/momentum.py
gamestonk_terminal/technical_analysis/trend.py
gamestonk_terminal/technical_analysis/volatility.py
gamestonk_terminal/technical_analysis/volume.py

Fix flake8 F302 so our code is in alignment with PEP8.

Two blank lines before function or class definitions

---

.github/workflows/test.yml
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/sentiment/twitter_api.py

https://mypy.readthedocs.io/en/stable/

GitHub Actions: Make mypy a mandatory test

---

gamestonk_terminal/fundamental_analysis/business_insider_api.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/prediction_techniques/arima.py
gamestonk_terminal/technical_analysis/momentum.py
gamestonk_terminal/technical_analysis/overlap.py
gamestonk_terminal/technical_analysis/ta_menu.py
gamestonk_terminal/technical_analysis/trend.py
gamestonk_terminal/technical_analysis/volatility.py
gamestonk_terminal/technical_analysis/volume.py

- Improve plotting of TA menu, i.e. a plot is non-blocking. When the user inserts another command, the plot is closed automatically
- Refactor overall TA code to avoid duplications

Improve TA plotting, dont block plots

---

gamestonk_terminal/helper_funcs.py
gamestonk_terminal/prediction_techniques/arima.py
gamestonk_terminal/prediction_techniques/fbprophet.py
gamestonk_terminal/prediction_techniques/knn.py
gamestonk_terminal/prediction_techniques/neural_networks.py
gamestonk_terminal/prediction_techniques/pred_menu.py
gamestonk_terminal/prediction_techniques/regression.py
gamestonk_terminal/prediction_techniques/sma.py
tests/test_pred_neural_networks.py

- Code refactoring
- Remove unused arguments
- Colouring on prediction share price based on last price

Improve prediciton Menu

---

gamestonk_terminal/fundamental_analysis/yahoo_finance_api.py
gamestonk_terminal/reddit_helpers.py
gamestonk_terminal/sentiment/google_api.py
gamestonk_terminal/sentiment/reddit_api.py
gamestonk_terminal/sentiment/stocktwits_api.py
gamestonk_terminal/sentiment/twitter_api.py
terminal.py

This PR concludes the work to "rebase" both #53 and #29.
It includes:
- Cleaning of Yahoo Finance in FA menu (overlooked previously
- Sentiment folder cleaning
- executable script caller refactoring

Hopefully last big refactoring

---

.github/workflows/test.yml
gamestonk_terminal/discovery/fidelity_api.py
gamestonk_terminal/due_diligence/market_watch_api.py
gamestonk_terminal/fundamental_analysis/alpha_vantage_api.py
gamestonk_terminal/fundamental_analysis/yahoo_finance_api.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/sentiment/sen_menu.py
terminal.py

https://github.com/asottile/pyupgrade

GitHub Actions: make pyupgrade mandatory and max-line-length=122

---

gamestonk_terminal/README.md
terminal.py

- Improving code around export feature
- Add export feature to README

Improve export feature

---

gamestonk_terminal/main_helper.py
terminal.py

This should implement improvement mentioned on #124

Remove -t flag requirement from load command (#124)

---

.github/workflows/test.yml
gamestonk_terminal/__init__.py
gamestonk_terminal/discovery/__init__.py
gamestonk_terminal/papermill/__init__.py
tests/test_dd_financial_modeling_prep_api.py
tests/test_dd_finviz_api.py
tests/test_discovery_fidelity_api.py
tests/test_discovery_short_interest_api.py
tests/test_fa_business_insider_api.py
tests/test_fa_market_watch_api.py
tests/test_fa_yahoo_finance_api.py
tests/test_pred_neural_networks.py
tests/test_sentiment_reddit_api.py
tests/test_sentiment_twitter_api.py

Remove unused imports or mark them with `# noqa: F401`

Fix module imported but not used

---

README.md
ROADMAP.md

@aia something along these lines?

Add ROADMAP to the project

---

Dockerfile

Hi, just tried to run this on docker and it seems it's calling the wrong .py file in the CMD call. This is just a quick fix that fixed it for me :)

Update Dockerfile, correct CMD

---

gamestonk_terminal/discovery/disc_menu.py
gamestonk_terminal/menu.py
requirements-full.txt
requirements-old.txt
requirements-win.txt
requirements.txt
terminal.py

Hello all,
I just spent a few minutes prototyping a terminal using the `prompt-toolkit` (https://python-prompt-toolkit.readthedocs.io/).
We can do a proper autocompletion with nested options...
This was just 15 mins of my time. Let me know if you want to go ahead with this.
Thanks

Better terminal with autocompletion + history

---

gamestonk_terminal/sentiment/reddit_api.py

I added some error handling inside the while loops to prevent the run from being aborted.
I noticed that, sometimes, the post would be missing the author, for example, and it would throw an exception and abort the command.
This should take care of the issue

Wrapping the reddit loop logic in try catch blocks

---

README.md
gamestonk_terminal/comparison_analysis/ca_menu.py
gamestonk_terminal/comparison_analysis/yahoo_finance_api.py
gamestonk_terminal/fundamental_analysis/market_watch_api.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/sentiment/sen_menu.py
terminal.py

Following improvements are contained in this PR:
- Add comparison analysis option to main menu
- Fix help flag in case of Market Watch commands
- Add help flag to comparison analysis menu
- Prediction prints to have flag to use or not use color
- Fix name of file to set ENABLE PREDICTION
- Remove unnecessary comments
- Update readm with polygon API key

Couple of fixes here and there

---

gamestonk_terminal/fundamental_analysis/market_watch_api.py
gamestonk_terminal/helper_funcs.py

Add colors to financial market watch data, similarly to website

---

poetry.lock
pyproject.toml

Fix for #164 
Signed-off-by: Martin Sand <martin.sand.dev@gmail.com>

Adding seaborn dependency to pyproject.toml

---

ROADMAP.md
gamestonk_terminal/fundamental_analysis/alpha_vantage_api.py
gamestonk_terminal/fundamental_analysis/fa_menu.py
gamestonk_terminal/fundamental_analysis/financial_modeling_prep_api.py
gamestonk_terminal/fundamental_analysis/market_watch_api.py

Remove AV and FMP commands from main FA menu, and refactor it into sub-menus

Refactor FA menu

---

terminal.py

Added a check for ticker when calling candle and view.
Calling candle without the check crashes the program, calling view just opens up a empty window.

Checking for ticker before calling view and candle

---

gamestonk_terminal/prediction_techniques/knn.py
gamestonk_terminal/prediction_techniques/regression.py

This fixes kNN when no backtesting is needed + regression when no polynomial value is selected (needed to catch SystemExit exception).

Fix knn regression

---

README.md
gamestonk_terminal/res_menu.py
gamestonk_terminal/sentiment/reddit_api.py

- Fixes bug when Reddit API Keys are wrongly configured
- Add stockanalysis to research menu as requested by #172 
- Improves README based on @aia discussion

Fix wrong reddit api key and others

---

gamestonk_terminal/sentiment/reddit_api.py

Changed the reddit search functions to catch specific praw response exceptions rather than general exceptions.

Made use of prawcore.exceptions.ResponseException

---

gamestonk_terminal/config_terminal.py
gamestonk_terminal/main_helper.py
gamestonk_terminal/portfolio/README.md
gamestonk_terminal/portfolio/port_menu.py
gamestonk_terminal/portfolio/rh_api.py
poetry.lock
pyproject.toml
terminal.py

I added the option to view current RH holdings and also to plot your historical portfolio.
This could easily be extended to other brokers besides RH, but that is what I have to test with.  The robin_stocks also offers a tda package, so the functions will likely be the same.
I did not add any buy/sell options as I figure that may be on the roadmap for dealing with the tickers.

RH Portfolio

---

gamestonk_terminal/thought_of_the_day.py
terminal.py

Add a thought of the day

---

requirements-full.txt

Full requirements is missing fredapi.

Added missing fredapi to requirements

---

README.md
notebooks/templates/econ_data.ipynb
requirements-win.txt

Multiple Updates
- Added FRED API env variable to README
- Added fredapi to requirements-win
- Added materials sector/industry to econ data summary for papermill. This tracks the industry that deals with basic materials required in an economy such as plastic, paper, concrete, metals, etc.

Multiple Updates

---

requirements-full.txt
requirements-old.txt
requirements-win.txt
requirements.txt

need updated alpaca versions + added robin stocks to whichever didn't have it

requirement files updated

---

ROADMAP.md
gamestonk_terminal/portfolio/README.md
gamestonk_terminal/portfolio/alp_api.py
gamestonk_terminal/portfolio/port_controller.py

This PR adds alpaca broker with the same hold and historical portfolio functions.  
Note I haven't invested in this account enough to show the alphist.  I just bought some penny stocks to test out, so I can update the readme in like a week with all the loss porn.

Add Alpaca Broker

---

gamestonk_terminal/behavioural_analysis/twitter_view.py

Twitter commands sentiment/infer to fail smoothly when wrong API Key

---

.github/workflows/test.yml
tests/data/fa_market_watch_api.yaml
tests/test_fa_market_watch_api_unit.py

Another unit test example for you.
With helpers and mocks things are very easy.

Adding MarketWatch unit test

---

ROADMAP.md
gamestonk_terminal/portfolio/README.md
gamestonk_terminal/portfolio/ally_api.py
gamestonk_terminal/portfolio/alp_api.py
gamestonk_terminal/portfolio/port_controller.py
gamestonk_terminal/portfolio/portfolio_helpers.py
gamestonk_terminal/portfolio/rh_api.py
notebooks/templates/due_diligence.ipynb
poetry.lock
pyproject.toml
requirements-full.txt
requirements-old.txt
requirements-win.txt
requirements.txt

In this PR, I added another broker (Ally Invest) and the ability to view holdings across all logged in brokers.
At the time, the Ally Invest does not offer historical portfolio data, so I have not made a "Merged: hist" option.

Add Ally Invest + Merge Portfolios

---

gamestonk_terminal/options/op_controller.py

@lolrenx I refactored a bit the expiry date command.
The difference between what was done previously is.
Before: exp command invoked a "loop" that obligated user to select a valid index in order to exit such, regardless if user wanted to call help, quit options menu, exit terminal, or even just see available dates.
Now: Exp command can be used as:
`exp -h` - To see helper
`exp` - Just to see available dates
`exp 3` - Selects expiry date with index 3
And if user does `exp 123123` it raises an error that such index doesn't exist.
Example:
Let me know what you think

Improve expiry date cmd in op menu

---

README.md
ROADMAP.md
gamestonk_terminal/cryptocurrency/README.md
gamestonk_terminal/cryptocurrency/coin_api.py
gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/cryptocurrency/crypto_helper.py
gamestonk_terminal/main_helper.py
poetry.lock
pyproject.toml
requirements-full.txt
requirements-old.txt
requirements-win.txt
requirements.txt
terminal.py

In this PR, I added a crypto menu using the CoinGecko API.  
Tried to keep the calls similar to the loading/viewing of stock tickers.   Obviously a lot more work can be done., but this is a start.

Add a crypto menu

---

.github/workflows/test.yml
ROADMAP.md
gamestonk_terminal/exploratory_data_analysis/README.md
gamestonk_terminal/exploratory_data_analysis/eda_api.py
gamestonk_terminal/exploratory_data_analysis/eda_controller.py
gamestonk_terminal/main_helper.py
poetry.lock
pyproject.toml
requirements-full.txt
requirements-old.txt
requirements-win.txt
requirements.txt
terminal.py

See https://github.com/DidierRLopes/GamestonkTerminal/pull/289/files#diff-2c691a7b3561ce9bf53b7943c6fdb70aea69ca4b7dfe15a492f544042b689e6e for more information

Exploratory Data Analysis Menu

---

.github/workflows/test.yml
ROADMAP.md
gamestonk_terminal/main_helper.py
gamestonk_terminal/residuals_analysis/README.md
gamestonk_terminal/residuals_analysis/ra_controller.py
gamestonk_terminal/residuals_analysis/residuals_api.py
gamestonk_terminal/residuals_analysis/residuals_model.py
terminal.py

See https://github.com/DidierRLopes/GamestonkTerminal/pull/292/files?short_path=3ead0ca#diff-3ead0ca235d522c512efed8374cdd25e27b0ff4a5a1ecf6095af22a3c08d6790

Add residual analysis menu for statistical modelling

---

ROADMAP.md
gamestonk_terminal/technical_analysis/README.md
gamestonk_terminal/technical_analysis/finbrain_view.py
gamestonk_terminal/technical_analysis/ta_controller.py
gamestonk_terminal/technical_analysis/tradingview_view.py
poetry.lock
pyproject.toml
requirements-full.txt
requirements-old.txt
requirements-win.txt
requirements.txt

See https://uk.tradingview.com/widget/technical-analysis/
Yet another library :)

Tradingview recommendation based on technical indicators

---

ROADMAP.md

I have some great ideas to work during Easter. Hopefully by Monday I'll have all of these done :)

Add easter features to roadmap

---

gamestonk_terminal/behavioural_analysis/reddit_view.py

I discovered that the program would crash if your Reddit password is incorrect and you try to run the popular function. I was going to add a specific exception for OAuthException but all other Reddit functions just had a catch-all for this. The error message from prawcore is a bit ambiguous but at least it's consistent for all functions.

Exception handling for wsb popular function

---

ROADMAP.md
gamestonk_terminal/discovery/README.md
gamestonk_terminal/discovery/disc_controller.py
gamestonk_terminal/discovery/finviz_view.py
poetry.lock
pyproject.toml

See added commands to discovery to analyse sectors, industries, and countries. 
https://github.com/DidierRLopes/GamestonkTerminal/pull/315/files?short_path=59d424e#diff-59d424ec7c96510d978b29eaca2f3890d0474bc0408796dde88c5feec519a74e

Add sector/industry/country valuation/performance/spectrum

---

README.md
gamestonk_terminal/README.md
gamestonk_terminal/main_helper.py
terminal.py

Refactor main README, and add `update` section. Fixes #265
Added a comment for Indian tickers working with ".NS" at end, which closes #256 
Fixed the "view" cmd for indian tickers, because it was re-loading tickers from Alpha Vantage.
Refactored loading intraday data from yfinance because I found out that it's possible, and also load before/after market hours

Address bugs

---

gamestonk_terminal/discovery/disc_controller.py

Discovery controller to close figures when in menu

---

README.md
gamestonk_terminal/config_terminal.py
gamestonk_terminal/feature_flags.py
gamestonk_terminal/options/README.md
gamestonk_terminal/options/chains_view.py
gamestonk_terminal/options/op_controller.py
gamestonk_terminal/options/volume_view.py

Addressing #272.
This PR adds in the ability to pull options chains from Tradier and it displays them in table form.

add in option chains :)

---

ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/discovery/README.md
gamestonk_terminal/discovery/disc_controller.py
gamestonk_terminal/discovery/marketbeat_model.py
gamestonk_terminal/discovery/marketbeat_view.py

@hinxx was struggling to do a PR to your marketbeat branch, this was the easiest way.
Hope that's fine!
This PR replaces #350 because I'm a noob :)

introduce latest ratings changes from MarketBeat 

---

poetry.lock
pyproject.toml

address statsmodels on poetry #295

---

ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/due_diligence/README.md
gamestonk_terminal/due_diligence/dd_controller.py
gamestonk_terminal/due_diligence/finra_view.py

Add dark pools (ATS) vs Non-ATS data over time

---

README.md
gamestonk_terminal/README.md
gamestonk_terminal/due_diligence/README.md
gamestonk_terminal/due_diligence/sec_view.py
gamestonk_terminal/options/README.md
gamestonk_terminal/options/chains_view.py
gamestonk_terminal/options/op_controller.py
gamestonk_terminal/options/volume_view.py
terminal.py

This PR includes:
* fix bug for yahoo finance tickers from other markets (e.g. SBIN.NS) 
* Add discord server to readme
* Option README improved

improvements and bugfixes

---

ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/discovery/README.md
gamestonk_terminal/discovery/disc_controller.py
gamestonk_terminal/discovery/finra_ats_view.py
gamestonk_terminal/due_diligence/finra_view.py

Add disc/darkpool command

---

README.md

Think I figured out why the discord link was changing

updated permanent discord link

---

ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/cryptocurrency/README.md
gamestonk_terminal/fundamental_analysis/README.md
gamestonk_terminal/fundamental_analysis/fa_controller.py
gamestonk_terminal/fundamental_analysis/financial_modeling_prep_view.py
gamestonk_terminal/options/README.md
gamestonk_terminal/options/op_scrape_view.py
poetry.lock
pyproject.toml
requirements.txt

This should address #379 by adding a fundamental analysis score metric.
Refactoring:
* Refactor images in cryptocurrency and options README
* Update ROADMAP
* Update features  
* Fix op/info command although browser pops up to get the info

Add fundamental analysis score

---

gamestonk_terminal/behavioural_analysis/reddit_view.py

Add the most important thread to reddit behaviour analysis

---

README.md

Suggested by charles in discord.
https://github.com/dgibbs64/discord-banners was used.

Added discord shield at the top of README.md

---

README.md
TROUBLESHOOT.md

I spent all day yesterday helping users install the terminal.
I've gathered the most common issues, and added them into a README page.
Hopefully this will help going forward.

Troubleshoot page to help new users install the terminal

---

gamestonk_terminal/config_terminal.py
gamestonk_terminal/feature_flags.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/papermill/due_diligence_view.py
gamestonk_terminal/papermill/econ_data_view.py

As requested by users, this PR does 2 things:
- Adds a feature flag to clear command history
- Adds a config of the port for the jupyter notebooks
As @aia would say, these are examples of bikeshedding :)

Improve user experience

---

Gamestonk Terminal.bat
README.md

Changed readme to include optional process to speed up the terminal opening in the future, by using a simple batch file

Easy open for Gamestonk Terminal following install

---

Gamestonk Terminal.bat

Makes for a cleaner experience with echo off

Small change to turn off echo

---

gamestonk_terminal/discovery/fidelity_model.py
gamestonk_terminal/options/chains_view.py
gamestonk_terminal/options/volume_helper.py
gamestonk_terminal/options/volume_view.py

As per #402, this addresses the incorrect calculation
I think I also addressed a bug in disc->Fidelity when the top orders table is missing entries (at least in the price change column).  I raised #408 with this.

Fix max pain calculation

---

gamestonk_terminal/fundamental_analysis/market_watch_model.py
gamestonk_terminal/fundamental_analysis/market_watch_view.py

Fix empty financials from marketwatch

---

gamestonk_terminal/fundamental_analysis/yahoo_finance_view.py

Change sustainability check

---

ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/discovery/README.md
gamestonk_terminal/discovery/disc_controller.py
gamestonk_terminal/discovery/finnhub_view.py

Add IPOs calendar to discovery menu

---

README.md

Added twitter shield to README

---

README.md
ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/comparison_analysis/README.md
gamestonk_terminal/comparison_analysis/ca_controller.py
gamestonk_terminal/government/README.md
gamestonk_terminal/government/gov_controller.py
gamestonk_terminal/government/quiverquant_model.py
gamestonk_terminal/government/quiverquant_view.py
gamestonk_terminal/main_helper.py
gamestonk_terminal/portfolio_optimization/README.md
gamestonk_terminal/portfolio_optimization/po_controller.py
gamestonk_terminal/resource_collection/README.md
gamestonk_terminal/resource_collection/rc_controller.py
gamestonk_terminal/screener/README.md
gamestonk_terminal/screener/screener_controller.py
terminal.py

This PR does the following:
* Adds congress data to government menu
* Add Finnhub source to get similar companies
* Allow screener to view filters applied in specific preset
* minor cosmetic improvements

Add government menu, in particular congress data

---

gamestonk_terminal/main_helper.py
terminal.py

As required per @jmaslek this should allow to reset the terminal.
This way the user can change/add config keys, and not quit and execute terminal again.

add reset command to terminal

---

ROADMAP.md
gamestonk_terminal/main_helper.py
terminal.py

This should allow the user to simply do 
```
update
```
to get latest features.
Also, I get a hash from the poetry.lock file, and compare it against the new poetry.lock file. If the hash has changed, it means that a new dependency has been added, and hence, it also runs "poetry install"

add update command

---

ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/cryptocurrency/README.md
gamestonk_terminal/cryptocurrency/binance_model.py
gamestonk_terminal/cryptocurrency/crypto_controller.py

Add the ability to load crypto data frame and use it with the ta menu.
Note that Binance is better for this since it gives candles, so coin gecko data will only work on indicators that use close data only

Add option to go to ta menu from crypto

---

ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/government/README.md
gamestonk_terminal/government/gov_controller.py
gamestonk_terminal/government/quiverquant_model.py
gamestonk_terminal/government/quiverquant_view.py
gamestonk_terminal/prediction_techniques/arima_view.py
gamestonk_terminal/prediction_techniques/ets_view.py
gamestonk_terminal/prediction_techniques/knn_view.py
gamestonk_terminal/prediction_techniques/regression_view.py

This PR includes:
* Fix #45 for all prediction techniques
* Implement contracts commands

Add gov-contracts

---

gamestonk_terminal/discovery/finviz_view.py

Fix bug #456

---

.github/workflows/Mac.yml
.github/workflows/test.yml
.github/workflows/windows.yml
gamestonk_terminal/econ/fred_view.py
poetry.lock
pyproject.toml
requirements-full.txt

Fix #465 where the incorrect variable was being imported

update incorrect fred key from config file

---

gamestonk_terminal/etf/etf_controller.py
gamestonk_terminal/etf/stockanalysis_model.py

- `overview` command now works with lower case symbols
- `web` command will open to page for specific etf if symbol is provided. Otherwise it will default to https://stockanalysis.com/etf/.

Minor improvements to ETF menu

---

README.md
gamestonk_terminal/econ/fred_view.py
requirements-full.txt

Fix FRED API KEY name #465

---

gamestonk_terminal/README.md
gamestonk_terminal/main_helper.py
terminal.py

Adds a main menu option `quote` that shows a table of the current price for a stock.

Add menu option 'quote'

---

gamestonk_terminal/screener/presets/buffett_like.ini
gamestonk_terminal/screener/presets/cheap_bottom_dividend.ini
gamestonk_terminal/screener/presets/cheap_dividend.ini
gamestonk_terminal/screener/presets/cheap_oversold.ini
gamestonk_terminal/screener/presets/death_cross.ini
gamestonk_terminal/screener/presets/golden_cross.ini
gamestonk_terminal/screener/presets/heavy_inst_ins.ini
gamestonk_terminal/screener/presets/modified_dreman.ini
gamestonk_terminal/screener/presets/modified_neff.ini
gamestonk_terminal/screener/presets/rosenwald.ini
gamestonk_terminal/screener/presets/rosenwald_gtfo.ini
gamestonk_terminal/screener/presets/sexy_year.ini
gamestonk_terminal/screener/presets/template.ini
gamestonk_terminal/screener/presets/undervalue.ini
gamestonk_terminal/technical_analysis/finviz_view.py
gamestonk_terminal/technical_analysis/ta_controller.py

Thanks @piiq for showing how to improve Finviz view code :)

Fix Screener View and Improve TA Finviz View

---

gamestonk_terminal/portfolio/port_controller.py
terminal.py

Something along these lines @aia

Only comment degiro and not entire portfolio menu

---

build/conda/conda-3-7-env-full.yaml
build/conda/conda-3-8-env-full.yaml
build/conda/conda-3-8-env.yaml
poetry.lock
pyproject.toml
requirements-full.txt
requirements.txt

jupyter_client is apparently a problematic package. Conda tags jupyter_client version 6.2.0 and 6.1.13 as broken.

Pin jupyter_client==6.1.12

---

gamestonk_terminal/helper_funcs.py
gamestonk_terminal/main_helper.py

This should fix #487.  Things that were done
- Fix dataframe slicing (this is where the error was)
- Print correct intraday interval to the command line (yf intraday was not redefining s_interval)
- Update the width of `plt.bar` to be the resolution.  This way it doesn't get messy with too little (much) data.
- Added types and docstrings to most functions in main_helper and helper_funcs.

Fix error with intraday plotting

---

gamestonk_terminal/screener/finviz_view.py
gamestonk_terminal/screener/presets/sexy_year.ini
gamestonk_terminal/screener/presets/template.ini

Fix screener for General.Order and General.Signal

---

ROADMAP.md
gamestonk_terminal/discovery/stockgrid_view.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/portfolio/CUSTOM_PORT.md
gamestonk_terminal/portfolio/custom_model.py
gamestonk_terminal/portfolio/custom_portfolio/portfolio.csv
gamestonk_terminal/portfolio/port_controller.py

Based off #497 
* Add csv option (with default template)
* Add a function to groupby selected column
Also fixed an issue with dark short percent not getting multiplied by 100.

Add csv option for portfolio

---

README.md
ROADMAP.md
gamestonk_terminal/README.md
gamestonk_terminal/economy/README.md
gamestonk_terminal/economy/cnn_view.py
gamestonk_terminal/economy/econ_controller.py
gamestonk_terminal/technical_analysis/ta_controller.py
poetry.lock
pyproject.toml
requirements-full.txt
requirements.txt
terminal.py

Adding this because it was a feature request by a user.

Add Fear And Greed Index command to Economy menu

---

gamestonk_terminal/backtesting/bt_controller.py
gamestonk_terminal/behavioural_analysis/ba_controller.py
gamestonk_terminal/brokers/bro_controller.py
gamestonk_terminal/brokers/degiro/degiro_controller.py
gamestonk_terminal/comparison_analysis/ca_controller.py
gamestonk_terminal/cryptocurrency/binance/binance_controller.py
gamestonk_terminal/cryptocurrency/coingecko/pycoingecko_controller.py
gamestonk_terminal/cryptocurrency/coinmarketcap/coinmarketcap_controller.py
gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/discovery/disc_controller.py
gamestonk_terminal/due_diligence/dd_controller.py
gamestonk_terminal/economy/econ_controller.py
gamestonk_terminal/etf/etf_controller.py
gamestonk_terminal/exploratory_data_analysis/eda_controller.py
gamestonk_terminal/forex/fx_controller.py
gamestonk_terminal/fundamental_analysis/alpha_vantage/av_controller.py
gamestonk_terminal/fundamental_analysis/fa_controller.py
gamestonk_terminal/fundamental_analysis/financial_modeling_prep/fmp_controller.py
gamestonk_terminal/government/gov_controller.py
gamestonk_terminal/options/op_controller.py
gamestonk_terminal/papermill/papermill_controller.py
gamestonk_terminal/portfolio_analysis/pa_controller.py
gamestonk_terminal/portfolio_optimization/po_controller.py
gamestonk_terminal/prediction_techniques/pred_controller.py
gamestonk_terminal/research/res_controller.py
gamestonk_terminal/residuals_analysis/ra_controller.py
gamestonk_terminal/resource_collection/rc_controller.py
gamestonk_terminal/screener/screener_controller.py
gamestonk_terminal/technical_analysis/ta_controller.py
terminal.py

This PR does the following:
- Allows user to use "Enter" as a line separator
- Allows user to use "cls" to clear screen
- Allows user to use "?" as "help"

Improve menu UX

---

gamestonk_terminal/README.md
gamestonk_terminal/due_diligence/README.md
gamestonk_terminal/due_diligence/csimarket_view.py
gamestonk_terminal/due_diligence/dd_controller.py

Add suppliers and customers features to DD menu

Add supply and customer feature

---

gamestonk_terminal/backtesting/bt_helper.py
gamestonk_terminal/backtesting/bt_view.py
gamestonk_terminal/etf/README.md
pyproject.toml

Small fixes
- Changed pyproject script so that I can be lazy and just run get (was looking for def main() but was replaced with def terminal() )
- Fixed bt html error.  Error was in bt.get, not sure why now, but I just did a custom download of yf data.

Small bugs

---

gamestonk_terminal/discovery/stockgrid_view.py
gamestonk_terminal/due_diligence/stockgrid_dd_view.py
gamestonk_terminal/helper_funcs.py

@jmaslek can you have a look at the concept of exporting. What do you think?
We could add this piece of code to the bottom of all commands, so that all data could be exported from an user perspective.

Data export new concept

---

.gitignore
gamestonk_terminal/README.md
gamestonk_terminal/config_terminal.py
gamestonk_terminal/due_diligence/README.md
gamestonk_terminal/due_diligence/dd_controller.py
gamestonk_terminal/due_diligence/sec_view.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/main_helper.py
poetry.lock
pyproject.toml
requirements-full.txt
requirements.txt
terminal.py

I went over the credits of IEX. I don't think it has a great free tier.
But anyway, it has a lot of stuff that we can perhaps integrate at some point. So probably worth having this as a starting point. See https://github.com/iexcloud/pyEX/blob/main/examples/all.ipynb
This PR includes:
* IEX daily and intradaily data
* Fix view help
* Fix load help
* View function to allow to print raw data
* Remove export function and refactor it into a flag in view function
* Add exports/ folder to gitignore
* Improve FTD command by allowing to select a start/end date + plotting share price

Allow to load data from IEX

---

gamestonk_terminal/insider/README.md
gamestonk_terminal/insider/insider_controller.py
gamestonk_terminal/insider/openinsider_view.py
terminal.py

Implements several screeners from http://openinsider.com/
I want to add the possibility of a set preset here. As shown here:
But will leave this for another day :)

Open insider menu

---

requirements-full.txt

Forgot to update requirements-full.txt in the previous pull request.

Updating requirements-full.txt

---

gamestonk_terminal/README.md
gamestonk_terminal/config_terminal.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/main_helper.py
terminal.py

In this PR:
- Add argparse ability to candle function.  Also now allows to specify the starting date instead of only doing 6months.
- Add a quick terminal command that checks which keys the user has defined (grouped certain api's that require multiple key information)
-  Continue documenting some functions, mostly in the helper file

Backlog updates: `candle` and api keys

---

gamestonk_terminal/discovery/yahoo_finance_view.py

Fix "No table found" - https://github.com/pandas-dev/pandas/issues/6393

Use requests with pd.read_html for gainers/losers discovery

---

gamestonk_terminal/fundamental_analysis/fa_controller.py
gamestonk_terminal/fundamental_analysis/market_watch_view.py
gamestonk_terminal/papermill/README.md
gamestonk_terminal/papermill/papermill_controller.py

This should remove the need to call it from outside the terminal, where most users were struggling.
I think you gonna like this one @aia :)

Run papermill kernel from python.

---

terminal.py

Change test for internet connection to avoid bug

---

gamestonk_terminal/README.md
gamestonk_terminal/main_helper.py
gamestonk_terminal/technical_analysis/README.md
gamestonk_terminal/technical_analysis/custom_indicators_view.py
gamestonk_terminal/technical_analysis/momentum.py
gamestonk_terminal/technical_analysis/overlap.py
gamestonk_terminal/technical_analysis/ta_controller.py
gamestonk_terminal/technical_analysis/volatility.py
gamestonk_terminal/technical_analysis/volume.py

In this PR:
- Added a fibonocci level indicator (under 'custom')
- Redid VWAP to look at daily chart only
- Rewrote ta plots
- Added doctstring/type hinting to ta menus

Add fibonacci level indicator. Improve TA menu in general.

---

gamestonk_terminal/discovery/marketbeat_model.py
gamestonk_terminal/discovery/marketbeat_view.py
gamestonk_terminal/papermill/crypto_market_view.py
gamestonk_terminal/papermill/dark_pool_view.py
gamestonk_terminal/papermill/due_diligence_view.py
gamestonk_terminal/papermill/econ_data_view.py

Users will need MarketBeat All Access to benefit the most out of this feature now, because their change their data output, AND now only show a little preview... :(
PS: This PR also prints a message to say where the reports are exported. It was a user request.

Fix MarketBeat disc/ratings scraping. 

---

gamestonk_terminal/economy/README.md
gamestonk_terminal/economy/econ_controller.py
gamestonk_terminal/economy/fred_view.py

Allow multiple plotting for economy/fred

---

gamestonk_terminal/README.md
gamestonk_terminal/options/README.md
gamestonk_terminal/options/fdscanner_model.py
gamestonk_terminal/options/fdscanner_view.py
gamestonk_terminal/options/op_controller.py
gamestonk_terminal/options/presets/high_IV.ini
gamestonk_terminal/options/presets/template.ini
gamestonk_terminal/options/syncretism_view.py

As the title says, this PR:
- Scrapes https://app.fdscanner.com/unusualvolume for unusual options
- Adds checks to all options variables to warn about bad entries

Add unusual options activity + option screener checks

---

gamestonk_terminal/cryptocurrency/coinpaprika/coinpaprika_view.py

Address the failing tests by throwing the coinpaprika functions in a try block.

Hotfix for jsondecode error in coinpaprika

---

gamestonk_terminal/comparison_analysis/yahoo_finance_view.py

There was an issue in `hcorr` where 'dataframe objects are mutable'.  Issue was looping through dictionary.items when it should have just been the keys

Fix bug in ca->hcorr 

---

gamestonk_terminal/portfolio/portfolio_controller.py
gamestonk_terminal/portfolio/portfolio_optimization/po_controller.py

Because of recent changes, portfolio opt no longer works from stock screener menu

make po work again for stock screener menu

---

.coveragerc
.pre-commit-config.yaml
gamestonk_terminal/__init__.py
gamestonk_terminal/common/exploratory_data_analysis/eda_api.py
gamestonk_terminal/common/residuals_analysis/residuals_api.py
gamestonk_terminal/forex/fx_view.py
gamestonk_terminal/menu.py
gamestonk_terminal/portfolio/brokers/degiro/degiro_model.py
gamestonk_terminal/portfolio/brokers/degiro/degiro_view.py

Added __init__ files, updated .coveragerc, and made fx_view work with pylint.

Added __init__ files and updated files for pylint

---

gamestonk_terminal/common/technical_analysis/momentum.py
gamestonk_terminal/stocks/technical_analysis/ta_controller.py

See if it works for you guys. Let me know if theres anything that should be modified

add fisher transform to ta menu

---

gamestonk_terminal/options/options_controller.py
gamestonk_terminal/stocks/stocks_controller.py
terminal.py

It does what it says it does :)

Allow to switch between stocks and options contexts

---

CONTRIBUTING.md

The test that fails here is fixed on the main, so it's in a state ready to merge.
Still needs more developments, but this can be a start

Contributing Document

---

gamestonk_terminal/stocks/dark_pool_shorts/dps_controller.py
gamestonk_terminal/stocks/dark_pool_shorts/yahoofinance_model.py
gamestonk_terminal/stocks/dark_pool_shorts/yahoofinance_view.py
gamestonk_terminal/stocks/discovery/disc_controller.py
gamestonk_terminal/stocks/discovery/yahoofinance_model.py
gamestonk_terminal/stocks/discovery/yahoofinance_view.py
gamestonk_terminal/stocks/screener/screener_controller.py
gamestonk_terminal/stocks/screener/yahoofinance_model.py
gamestonk_terminal/stocks/screener/yahoofinance_view.py

using refactor setup for the new code. Let me know if it's fine

add yahoofinance most shorted & undervalued screener

---

.github/workflows/gh-pages.yml

When this is accepted, and if the server is correctly deployed I'll get rid of master and stable.

Fix deploy action

---

tests/test_fa/test_fa_excel.py

Not sure what exactly is failing in the test.  looks like VCR again

Comment out fa_excel test

---

gamestonk_terminal/stocks/comparison_analysis/marketwatch_view.py

without tabulate, the text alignment is off

reuse patch_pandas_text_adjustment in ca stocks menu

---

gamestonk_terminal/resources/resources_controller.py

No submenus so just switched all the prints to a single docstring print

Simple resources menu refactor

---

gamestonk_terminal/common/newsapi_view.py
gamestonk_terminal/stocks/stocks_controller.py

I added an argument to specify date start for the news command, as was described in the ```# TODO```.

Added start date argument to newsapi

---

gamestonk_terminal/common/newsapi_view.py
gamestonk_terminal/stocks/README.md
gamestonk_terminal/stocks/due_diligence/README.md
gamestonk_terminal/stocks/stocks_controller.py
website/content/stocks/news/_index.md

I added an argument that allows filtering of news by source, as was mentioned in the ```#TODO```.

Added sources argument to the news command

---

gamestonk_terminal/portfolio/brokers/bro_controller.py
gamestonk_terminal/portfolio/portfolio_controller.py
gamestonk_terminal/resources/resources_controller.py

@lunarnautics you gonna like this one

Add Econiverse to resources

---

gamestonk_terminal/helper_funcs.py
gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py

@jmaslek what do you think having it like this?

Refactor export functionality concept

---

gamestonk_terminal/stocks/quantitative_analysis/factors_model.py
gamestonk_terminal/stocks/quantitative_analysis/factors_view.py

Turns out just using R2 is much simpler and provides slightly more accurate results.

Simplified formula

---

gamestonk_terminal/stocks/due_diligence/ark_model.py
gamestonk_terminal/stocks/due_diligence/ark_view.py
gamestonk_terminal/stocks/due_diligence/dd_controller.py
website/content/stocks/due_diligence/arktrades/_index.md
website/data/menu/main.yml

FR from #779 
Adds ark trades based on ticker into DD menu (made sense in terms of location).

Add ark trades based on ticker

---

discordbot/discordbot.py

Add protection against user typos or wrong commands

---

discordbot/economy/economy_menu.py
discordbot/generic_commands.py
discordbot/stocks/dark_pool_shorts/dps_menu.py

Improve discord help command

---

discordbot/README.md
discordbot/config_discordbot.py
discordbot/economy/currencies.py
discordbot/economy/economy_menu.py
discordbot/economy/feargreed.py
discordbot/economy/futures.py
discordbot/economy/glbonds.py
discordbot/economy/indices.py
discordbot/economy/overview.py
discordbot/economy/performance.py
discordbot/economy/usbonds.py
discordbot/economy/valuation.py
discordbot/stocks/dark_pool_shorts/dpotc.py
discordbot/stocks/dark_pool_shorts/dps_menu.py
discordbot/stocks/dark_pool_shorts/ftd.py
discordbot/stocks/dark_pool_shorts/hsi.py
discordbot/stocks/dark_pool_shorts/pos.py
discordbot/stocks/dark_pool_shorts/psi.py
discordbot/stocks/dark_pool_shorts/shorted.py
discordbot/stocks/dark_pool_shorts/sidtc.py
discordbot/stocks/dark_pool_shorts/spos.py

This PR refactors massively the discord architecture.
Next, I'll follow up with a contributing guideline so everyone can start helping out building this bot!
@northern-64bit

Major improvements to discord architecture

---

discordbot/README.md
gamestonk_terminal/stocks/fundamental_analysis/eclect_us_view.py
gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py

Add permission picture in readme for discord bot
Fix fa type for eclect.us
Change the print message for eclect.us when filing not found.

Discord doc

---

gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/forex/forex_controller.py
website/content/cryptocurrency/headlines/_index.md
website/content/cryptocurrency/sentiment/_index.md
website/data/menu/main.yml

As per didiers request:
- rename crypto - fibrain command
- Comment out forex/ba menu

Rename finbrain command to not use source and comment out forex/ba menu

---

discordbot/CONTRIBUTING.md

@northern-64bit could you provide feedback if you have time?

Add contributing document to discord

---

.github/workflows/test.yml
.pre-commit-config.yaml
gamestonk_terminal/forex/av_forex_currencies.csv
gamestonk_terminal/forex/av_model.py
gamestonk_terminal/forex/av_view.py
gamestonk_terminal/forex/forex_controller.py
gamestonk_terminal/forex/oanda/oanda_controller.py
gamestonk_terminal/forex/oanda/oanda_model.py
gamestonk_terminal/forex/oanda/oanda_view.py
website/content/forex/candle/_index.md
website/content/forex/load/_index.md
website/content/forex/quote/_index.md
website/content/forex/select/_index.md
website/data/menu/main.yml

- Moved Oanda into own submenu
-    I don't have an account for testing what works or doesn't
- Added simple ability to load forex pairs and view candle using alpha vantage api

Redo some forex menu with basic commands

---

.gitignore
gamestonk_terminal/portfolio/portfolio_controller.py
gamestonk_terminal/portfolio/portfolio_helper.py
gamestonk_terminal/portfolio/portfolio_model.py
gamestonk_terminal/portfolio/portfolio_optimization/optimizer_view.py
gamestonk_terminal/portfolio/portfolio_view.py
gamestonk_terminal/portfolio/portfolios/example.csv
gamestonk_terminal/portfolio/reportlab_helpers.py
gamestonk_terminal/portfolio/yfinance_model.py
website/content/portfolio/rmr/_index.md

Financial reports are useful because the provide a wealth of data, with meaningful explanations of what the data means. This PR adds those explanations, and also includes refactoring to improved future expansion.

Added Report Text

---

gamestonk_terminal/options/op_helpers.py
gamestonk_terminal/options/options_controller.py
gamestonk_terminal/options/yfinance_view.py
gamestonk_terminal/portfolio/portfolios/cash.csv
gamestonk_terminal/portfolio/portfolios/james.csv
gamestonk_terminal/portfolio/portfolios/market.csv
website/content/options/add/_index.md
website/content/options/rmv/_index.md
website/content/options/rnval/_index.md
website/content/options/show/_index.md
website/data/menu/main.yml

This PR lets the user add different estimates for a stock's price at the given expiration and the probability of that price happening. The user can use this to compare their estimated options value with current options values. 
**Note:** I have NOT added Hugo documentation yet because I am assuming you guys will have me chance stuff.

Risk neutral options valuation

---

gamestonk_terminal/portfolio/portfolio_model.py

Small PR to validate loaded data.

Validate loaded data

---

gamestonk_terminal/nft/nft_controller.py
gamestonk_terminal/nft/nftcalendar_model.py
gamestonk_terminal/nft/nftcalendar_view.py
terminal.py
website/content/nft/newest/_index.md
website/content/nft/ongoing/_index.md
website/content/nft/today/_index.md
website/content/nft/upcoming/_index.md
website/data/menu/main.yml

Uses this website https://nftcalendar.io/ from a video recommended by @aia

Yup, incoming NFT context

---

gamestonk_terminal/stocks/stocks_helper.py

Just for @danglewood
Fixed trend colors and made volume not black

Candle colors

---

discordbot/discordbot.py
discordbot/economy/economy_menu.py
discordbot/stocks/dark_pool_shorts/dps_menu.py
discordbot/stocks/due_diligence/analyst.py
discordbot/stocks/due_diligence/arktrades.py
discordbot/stocks/due_diligence/customer.py
discordbot/stocks/due_diligence/dd_menu.py
discordbot/stocks/due_diligence/est.py
discordbot/stocks/due_diligence/pt.py
discordbot/stocks/due_diligence/sec.py
discordbot/stocks/due_diligence/supplier.py

This pr adds the due diligence commands, which don't require api keys, to the discord bot.

Adding the due diligence context

---

gamestonk_terminal/stocks/discovery/disc_controller.py
gamestonk_terminal/stocks/discovery/nasdaq_model.py
gamestonk_terminal/stocks/discovery/nasdaq_view.py
website/content/stocks/discovery/rtat/_index.md
website/data/menu/main.yml

Title.  This adds the new NASDAQ datalink retail trader set to disc menu.

Add NASDAQ datalink retail trader dataset

---

gamestonk_terminal/economy/NASDAQ_CountryCodes.csv
gamestonk_terminal/economy/economy_controller.py
gamestonk_terminal/economy/nasdaq_model.py
gamestonk_terminal/economy/nasdaq_view.py
website/content/economy/bigmac/_index.md
website/data/menu/main.yml

Its Friday night.  Im hungry.  Nuff said.

Add the Big Mac index :)

---

gamestonk_terminal/cryptocurrency/defi/defipulse_model.py
gamestonk_terminal/etf/wsj_view.py
gamestonk_terminal/forex/fx_view.py
gamestonk_terminal/forex/oanda/oanda_view.py
gamestonk_terminal/stocks/discovery/marketbeat_view.py
gamestonk_terminal/stocks/fundamental_analysis/av_model.py
gamestonk_terminal/stocks/fundamental_analysis/av_view.py
gamestonk_terminal/stocks/fundamental_analysis/market_watch_view.py
gamestonk_terminal/stocks/insider/openinsider_view.py
gamestonk_terminal/terminal_helper.py
tests/test_fa/test_fa_av_view.py

It looks like the Alpha Vantage API is returning a lot of Nones, where there should not be. This is a small patch to tell the user that data cannot currently be returned if we get Nones that we should not. Not sure why Alpha Vantage is having this issue.

Fraud error

---

TROUBLESHOOT.md
gamestonk_terminal/etf/financedatabase_view.py

Fix etf/fds function

---

gamestonk_terminal/stocks/options/fdscanner_model.py
gamestonk_terminal/stocks/options/fdscanner_view.py
gamestonk_terminal/stocks/options/options_controller.py
gamestonk_terminal/stocks/options/syncretism_view.py

Fixed:
- Options `vol`
- Options `disc` 
- Options `unu` timezone

Patches from discord #bugs

---

gamestonk_terminal/economy/economy_controller.py
gamestonk_terminal/economy/finviz_view.py
gamestonk_terminal/stocks/comparison_analysis/ca_controller.py
gamestonk_terminal/stocks/discovery/ark_view.py
gamestonk_terminal/stocks/discovery/disc_controller.py
gamestonk_terminal/stocks/options/fdscanner_model.py
gamestonk_terminal/stocks/options/fdscanner_view.py
gamestonk_terminal/stocks/options/options_controller.py
website/content/economy/performance/_index.md
website/content/stocks/discovery/arkord/_index.md
website/content/stocks/options/unu/_index.md

General user experience upgrades based on discord chatwith some filtering/sorting abilities for the following functions
- options>unu (will close #818 )
- disc - arkord
- economy-performance
Also threw in a quick fix for ca where the user selects the same symbol.  Uses a set to only take unique inputs.

General UI improvements with sorting/filtering on some functions

---

.pre-commit-config.yaml
gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_model.py
gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_view.py

As the title says:
- Improve NaN handling for ca (mostly for discord user that wants to add futures to the ca menu)
- Change the pre-comit for pylint to rely on local installed version

Improve ca NaN handling + update pre-commit

---

gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py

All choices were not added to the controller.

Add nested completer to all ba functions

---

gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/economy/economy_controller.py
gamestonk_terminal/etf/etf_controller.py
gamestonk_terminal/forex/forex_controller.py
gamestonk_terminal/portfolio/portfolio_controller.py
gamestonk_terminal/reports/reports_controller.py
gamestonk_terminal/stocks/backtesting/bt_controller.py
gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py
gamestonk_terminal/stocks/comparison_analysis/ca_controller.py
gamestonk_terminal/stocks/dark_pool_shorts/dps_controller.py
gamestonk_terminal/stocks/discovery/disc_controller.py
gamestonk_terminal/stocks/due_diligence/dd_controller.py
gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
gamestonk_terminal/stocks/government/gov_controller.py
gamestonk_terminal/stocks/insider/insider_controller.py
gamestonk_terminal/stocks/options/options_controller.py
gamestonk_terminal/stocks/prediction_techniques/pred_controller.py
gamestonk_terminal/stocks/quantitative_analysis/qa_controller.py
gamestonk_terminal/stocks/research/res_controller.py
gamestonk_terminal/stocks/screener/screener_controller.py
gamestonk_terminal/stocks/stocks_controller.py
gamestonk_terminal/stocks/technical_analysis/ta_controller.py
terminal.py

Idk about all y'all but I type the wrong stuff all the time (when prompt is off that is).
I went through the controllers and added a suggestion just like the discord bot.

Add difflib to controllers

---

gamestonk_terminal/reports/similar_analysis.ipynb
gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_model.py
gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_view.py

Create comparison analysis report

---

gamestonk_terminal/common/prediction_techniques/regression_model.py
gamestonk_terminal/stocks/due_diligence/ark_model.py

This fixes #998.  Issue was that the indexes were different date time objects.  Beats me why it randomly stopped working.
Also fixed an error where the tsxv package is no longer imported, so the prediction crashes.

Arktrade Bug

---

gamestonk_terminal/stocks/screener/finviz_model.py
gamestonk_terminal/stocks/screener/finviz_view.py
gamestonk_terminal/stocks/screener/screener_controller.py
gamestonk_terminal/stocks/screener/yahoofinance_view.py

@deeleeramone has brought to my attention that the screener could be improved in order for a more dynamic filtering which could allow for better content on our twitter.
I've improved the menu a bit by combining default presets (from finviz) and custom ones (from users) and allowing to sort by one of the columns of the table.
Next step could be taking these to comparison analysis menu. But I think that menu should be refactored a bit to not depend on a "main" ticker and rather perform the comparison of tickers provided.

Screener controller big improvements

---

gamestonk_terminal/etf/stockanalysis_model.py

Fixes bug with etf> search and holdings

Update etf endpoint for stockanalysis.com

---

README.md

This PR adds a documentation badge to the project readme. Because it's Saturday...

Add documentation badge to the readme

---

gamestonk_terminal/stocks/fundamental_analysis/av_model.py

This closes #1014.
When I refactored I didn't remove unused function.

Remove unused function in av_model

---

gamestonk_terminal/stocks/stocks_helper.py

fixes #1023 
I goofed and didn't triple check before merge.

add back end date for `load`

---

gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py

Fix incorrect type on num argument for dividend command

---

gamestonk_terminal/cryptocurrency/nft/nft_controller.py
gamestonk_terminal/stocks/due_diligence/finviz_model.py
gamestonk_terminal/stocks/due_diligence/finviz_view.py

Fix finviz news

---

gamestonk_terminal/stocks/fundamental_analysis/eclect_us_model.py
gamestonk_terminal/stocks/fundamental_analysis/market_watch_view.py

**Reasons**
- Fixing Stocks > Fundamental Analysis > Eclect US :
Module : `gamestonk_terminal/stocks/fundamental_analysis/eclect_us_model.py`
Function `get_filings_analysis`
Issue : non deterministic behaviour.
- Fixing Stocks > Fundamental Analysis > Market Watch :
Module : `gamestonk_terminal.stocks.fundamental_analysis.market_watch_view`.
Function : `display_sean_seah_warnings`
Issue : it crashes when `gtff.USE_TABULATE_DF` is disabled

Fix stocks

---

gamestonk_terminal/config_terminal.py
gamestonk_terminal/economy/alphavantage_view.py
gamestonk_terminal/economy/economy_controller.py
gamestonk_terminal/economy/finviz_view.py
gamestonk_terminal/economy/fred_model.py
gamestonk_terminal/economy/fred_view.py
gamestonk_terminal/economy/nasdaq_view.py

No new features.  
- Cleaned up the finviz commands to allow for sorting on all commands
- Improved some plots
- Added a `--codes` to BigMac so user can see available option
- Improved Fred search command and changed to tablulate

Improve economy menu

---

gamestonk_terminal/forex/behavioural_analysis/ba_controller.py
gamestonk_terminal/reports/dark_pool.ipynb
gamestonk_terminal/reports/similar_analysis.ipynb
gamestonk_terminal/stocks/backtesting/bt_controller.py
gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py
gamestonk_terminal/stocks/dark_pool_shorts/dps_controller.py
gamestonk_terminal/stocks/due_diligence/dd_controller.py
gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
gamestonk_terminal/stocks/government/gov_controller.py
gamestonk_terminal/stocks/insider/insider_controller.py
gamestonk_terminal/stocks/prediction_techniques/pred_controller.py
gamestonk_terminal/stocks/quantitative_analysis/qa_controller.py
gamestonk_terminal/stocks/sector_industry_analysis/sia_controller.py
gamestonk_terminal/stocks/stocks_controller.py
gamestonk_terminal/stocks/stocks_helper.py
gamestonk_terminal/stocks/technical_analysis/ta_controller.py
tests/gamestonk_terminal/stocks/due_diligence/test_business_insider_view.py
tests/gamestonk_terminal/stocks/due_diligence/test_dd_controller.py
tests/gamestonk_terminal/stocks/test_stocks_helper.py

refactor load command

---

gamestonk_terminal/economy/economy_controller.py
gamestonk_terminal/economy/fred/fred_controller.py
gamestonk_terminal/paths.py
terminal.py
tests/simulator/test_econ.txt

I think I am doing this right.
Did Econ menu (with Fred).
Trying to merge into ux branch

Ux economy

---

gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
gamestonk_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
tests/gamestonk_terminal/stocks/fundamental_analysis/txt/test_fa_controller/test_menu_quick_exit.txt
tests/gamestonk_terminal/stocks/fundamental_analysis/txt/test_fa_controller/test_menu_system_exit.txt
tests/gamestonk_terminal/stocks/fundamental_analysis/txt/test_fa_controller/test_print_help.txt
tests/gamestonk_terminal/stocks/fundamental_analysis/txt/test_fa_controller/test_switch_help.txt

Adds line graph to stocks-->fa-->divs

Dividend History Chart

---

gamestonk_terminal/stocks/backtesting/bt_controller.py
gamestonk_terminal/stocks/stocks_controller.py
gamestonk_terminal/terminal_helper.py

hi didier
no tests in a .gst here

UX: stock/bt

---

discordbot/stocks/screener/historical.py
gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/cryptocurrency/defi/defi_controller.py
gamestonk_terminal/cryptocurrency/discovery/discovery_controller.py
gamestonk_terminal/cryptocurrency/due_diligence/dd_controller.py
gamestonk_terminal/cryptocurrency/nft/nft_controller.py
gamestonk_terminal/cryptocurrency/onchain/onchain_controller.py
gamestonk_terminal/cryptocurrency/overview/overview_controller.py
gamestonk_terminal/cryptocurrency/prediction_techniques/pred_controller.py
gamestonk_terminal/cryptocurrency/technical_analysis/ta_controller.py
gamestonk_terminal/helper_funcs.py
gamestonk_terminal/stocks/due_diligence/dd_controller.py
gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
gamestonk_terminal/stocks/prediction_techniques/pred_controller.py
gamestonk_terminal/stocks/research/res_controller.py
gamestonk_terminal/stocks/technical_analysis/ta_controller.py
terminal.py

Get rid of leading '/' in terminal and add some newlines on quits.

---

discordbot/stocks/screener/historical.py
gamestonk_terminal/stocks/fundamental_analysis/av_view.py
gamestonk_terminal/stocks/fundamental_analysis/dcf_view.py
gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
gamestonk_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
scripts/test_stocks_fa.gst
scripts/test_stocks_fa_base.gst
scripts/test_stocks_fa_fmp.gst
scripts/test_stocks_fa_fmp_base.gst
tests/gamestonk_terminal/stocks/fundamental_analysis/test_av_view.py

- replaced --num with --limit
- excluded unreliable/non-working functions from the choices list
- improved docstring compliance with numpy convention
- added test scenarios in .gst files

Upgrades for the UX upgrade for the fa and fa/fmp menus

---

discordbot/run_discordbot.py
discordbot/stocks/__init__.py
discordbot/stocks/options/calls.py
discordbot/stocks/options/expirations.py
discordbot/stocks/options/oi.py
discordbot/stocks/options/options_menu.py
discordbot/stocks/options/puts.py

Just looking at calls/puts and open interest.

Add some options commands to discord

---

build/conda/conda-3-8-env-full.yaml
build/conda/conda-3-8-env.yaml
discordbot/requirements.txt
poetry.lock
pyproject.toml
requirements-full.txt
requirements.txt

In addition to the version bump this PR adds pre-commit package to dev dependencies

Bump dependencies and resolve dependabot warnings

---

gamestonk_terminal/cryptocurrency/due_diligence/dd_controller.py
gamestonk_terminal/cryptocurrency/due_diligence/glassnode_model.py
gamestonk_terminal/cryptocurrency/due_diligence/glassnode_view.py
gamestonk_terminal/cryptocurrency/onchain/onchain_controller.py
scripts/test_crypto_dd.gst
website/content/cryptocurrency/due_diligence/eb/_index.md
website/content/cryptocurrency/due_diligence/nonzero/_index.md

* adds command to check the addresses with non-zero balance over time in a certain blockchain
___
Decided after a quick chat on [gamestonkterminal discord](https://discord.com/invite/Up2QGbMKHY) with @deeleeramone:

Feature: Adds new nonzero command

---

gamestonk_terminal/stocks/fundamental_analysis/dcf_view.py
gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
scripts/test_stocks_fa.gst

This fix updates an issue where a company with less than 10 years of historical data would cause issues. @piiq I saw the issue with AA, but it ran issue free with TSLA. My best guess is that the source website had temporary issues. If you have more insight feel free to share and I can dig in.

Fix to dcf command

---

gamestonk_terminal/economy/econ_data_helper.py
gamestonk_terminal/reports/due_diligence.ipynb

better late than never, it was still in 2021 😄

Revert DD report with pickle dataframe being stored

---

gamestonk_terminal/cryptocurrency/due_diligence/glassnode_model.py
gamestonk_terminal/cryptocurrency/due_diligence/glassnode_view.py
gamestonk_terminal/cryptocurrency/onchain/onchain_controller.py
scripts/test_crypto_onchain.gst
website/content/cryptocurrency/onchain/hr/_index.md
website/data/menu/main.yml

* adds new `hr` command to `onchain` menu: displays mean hashrate of ETH or BTC network

Feature(crypto): network hashrate

---

website/README.md
website/config.toml
website/content/common/quantitative_analysis/load/_index.md
website/content/stocks/candle/_index.md
website/content/stocks/comparison_analysis/load/_index.md
website/content/stocks/dark_pool_shorts/ftd/_index.md
website/content/stocks/insider/load/_index.md
website/content/stocks/news/_index.md
website/content/stocks/quote/_index.md

* Fixes hugo server docs
* Reverts URL to contain /GamestonkTerminal until fix is found

Fix Hugo server assets

---

website/content/funds/_index.md
website/themes/hugo-geekdoc/layouts/_default/baseof.html
website/themes/hugo-geekdoc/layouts/partials/site-footer.html
website/themes/hugo-geekdoc/static/main-5e7fc0c942.min.css
website/themes/hugo-geekdoc/static/main-cc3cbe901b.min.css

* Removes light mode temporarily

Hugo darkmode fix

---

gamestonk_terminal/stocks/technical_analysis/tradingview_model.py

**Reason**
Fixing bug in the module :
- `gamestonk_terminal.stocks.technical_analysis.tradingview_model`

Fixing bug : Technical Analysis > TradingView

---

gamestonk_terminal/alternative/alt_controller.py
gamestonk_terminal/alternative/covid/countries.txt
gamestonk_terminal/alternative/covid/covid_controller.py
gamestonk_terminal/alternative/covid/covid_model.py
gamestonk_terminal/alternative/covid/covid_view.py
gamestonk_terminal/config_terminal.py
gamestonk_terminal/helper_funcs.py
scripts/test_alt_covid.gst
terminal.py
website/content/alternative/_index.md
website/content/alternative/covid/_index.md
website/content/alternative/covid/cases/_index.md
website/content/alternative/covid/deaths/_index.md
website/content/alternative/covid/ov/_index.md
website/content/alternative/covid/rates/_index.md
website/content/alternative/covid/slopes/_index.md
website/data/menu/main.yml

As @DidierRLopes and I talked about offline, having alternative data nowadays is all the rage.
Here I add the context + a COVID menu.  Currently this will just show highest/lowest slopes and deaths/cases/death rate for the selected country.
The data is obtained from https://github.com/CSSEGISandData/COVID-19. which is the Johns Hopkins repo.

New alternative data context + first sub context (Covid)

---

routines/README.md
routines/didier_gme_job.gst

introduce routines concept

---

gamestonk_terminal/economy/fred/fred_controller.py

limit in parser shouldn't be capitalized

Bug in economy/fred -> plot

---

build/conda/conda-3-8-env-full.yaml
build/conda/conda-3-8-env.yaml
poetry.lock
pyproject.toml
requirements-full.txt
requirements.txt

testing for pygments fix

---

gamestonk_terminal/common/quantitative_analysis/qa_view.py

This should fix btc plotting as well 😄

improve log plot

---

README.md
tests/README.md

* Adds new section to installation docs: installing WSL on Windows before installing the terminal

Added installation docs section (WSL)

---

gamestonk_terminal/feature_flags.py
gamestonk_terminal/parent_classes.py
terminal.py

Its nice to not having to type `?` to see the help string every time we jump back to previous menu

print_help when jump back to previous menu

---

gamestonk_terminal/config_terminal.py

Changed the default debug mode back to False.

Updated Debug Mode

---

gamestonk_terminal/jupyter/dashboards/correlation.ipynb
gamestonk_terminal/jupyter/dashboards/stocks.ipynb

Adding labels to make the dashboards more user friendly. I want these dashboards to be much prettier than they are, but i'm not good at it myself and I can't find much online. If anyone has suggestions let me know.

Added labels

---

gamestonk_terminal/portfolio/portfolio_optimization/optimizer_view.py
gamestonk_terminal/portfolio/portfolio_optimization/po_controller.py
requirements.txt

2 Things here:
1. Fixed a bug where the efficient frontier was throwing an instantiation error because we changed the constraints by adding the maxsharpe to the curves
2. Add labels to individual assets (cough @deeleeramone )
3. (Not really a feature but change all default times to 1yr not 3month)
4. Colin forgot to update requirements

Fix + improve efficient frontier

---

gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/economy/economy_controller.py
gamestonk_terminal/etf/etf_controller.py
gamestonk_terminal/forex/forex_controller.py
gamestonk_terminal/mutual_funds/mutual_fund_controller.py
gamestonk_terminal/parent_classes.py
gamestonk_terminal/stocks/stocks_controller.py

Refactored call_resources to be a method on base class.
Terminal behavior did not change before and after refactor.

Refactored Call Resources

---

gamestonk_terminal/stocks/backtesting/bt_view.py

Currently the command doesn't work for decrease in value.

make whatif works for decrease as well

---

gamestonk_terminal/api.py
gamestonk_terminal/forex/forex_api.py
gamestonk_terminal/forex/oanda/oanda_api.py
gamestonk_terminal/mutual_funds/mutual_fund_api.py
gamestonk_terminal/portfolio/brokers/ally/ally_api.py
gamestonk_terminal/portfolio/brokers/bro_api.py
gamestonk_terminal/portfolio/brokers/bro_controller.py
gamestonk_terminal/portfolio/brokers/coinbase/coinbase_api.py
gamestonk_terminal/portfolio/brokers/degiro/degiro_api.py
gamestonk_terminal/portfolio/brokers/robinhood/robinhood_api.py
gamestonk_terminal/portfolio/portfolio_analysis/pa_api.py
gamestonk_terminal/portfolio/portfolio_api.py
gamestonk_terminal/portfolio/portfolio_optimization/po_api.py

Added the rest of the API. I did NOT include portfolio in the API because it seems like most of the functions could not be well used in a Jupyter lab. Let me know if you disagree @piiq.
Ran in a jupyterlab to confirm it works.

Finish API

---

gamestonk_terminal/stocks/due_diligence/business_insider_model.py

Fix Price Target Bug

---

gamestonk_terminal/stocks/stocks_helper.py

This just adds the ability to do the two finger scroll thingy on the apple trackpad for plotly candle

Add scroll zoom to plotly candle

---

tests/gamestonk_terminal/stocks/sector_industry_analysis/cassettes/test_financedatabase_model/test_get_companies_per_country_in_industry.yaml
tests/gamestonk_terminal/stocks/sector_industry_analysis/cassettes/test_financedatabase_model/test_get_countries[-Conglomerates].yaml
tests/gamestonk_terminal/stocks/sector_industry_analysis/cassettes/test_financedatabase_model/test_get_countries[-].yaml
tests/gamestonk_terminal/stocks/sector_industry_analysis/cassettes/test_financedatabase_model/test_get_countries[Uranium-].yaml
tests/gamestonk_terminal/stocks/sector_industry_analysis/cassettes/test_financedatabase_model/test_get_sectors[-France].yaml
tests/gamestonk_terminal/stocks/sector_industry_analysis/cassettes/test_financedatabase_model/test_get_sectors[-].yaml
tests/gamestonk_terminal/stocks/sector_industry_analysis/cassettes/test_financedatabase_model/test_get_sectors[Uranium-].yaml
tests/gamestonk_terminal/stocks/sector_industry_analysis/test_financedatabase_model.py

@aia detected some network calls from the tests.
This PR fixes these network calls.
These were cause by some missing `vcr` decorator in this module :
- `gamestonk_terminal.stocks.sector_industry_analysis`

Tests : Stocks > Sector Industry Analysis

---

gamestonk_terminal/config_plot.py
gamestonk_terminal/feature_flags.py
gamestonk_terminal/settings_controller.py
terminal.py

- Add settings menu
- Changing values and seeing them being changed on .env and then loaded properly when exiting terminal.

add settings menu

---

gamestonk_terminal/economy/fred/fred_controller.py
gamestonk_terminal/settings_controller.py
gamestonk_terminal/stocks/dark_pool_shorts/finra_model.py
gamestonk_terminal/stocks/dark_pool_shorts/finra_view.py
gamestonk_terminal/stocks/insider/businessinsider_view.py
gamestonk_terminal/stocks/stocks_controller.py
gamestonk_terminal/stocks/stocks_helper.py
tests/gamestonk_terminal/stocks/dark_pool_shorts/cassettes/test_sec_view/test_fails_to_deliver[False].yaml
tests/gamestonk_terminal/stocks/dark_pool_shorts/cassettes/test_sec_view/test_fails_to_deliver[True].yaml
tests/gamestonk_terminal/stocks/dark_pool_shorts/txt/test_sec_view/test_fails_to_deliver[False].txt
tests/gamestonk_terminal/stocks/dark_pool_shorts/txt/test_sec_view/test_fails_to_deliver[True].txt

* Fixed format of the additional info on a ticker
* Fixes #1286 which happened when the data didn't exist in Business Insider
* Add a try/except block around a possible issue in dps/prom. See #1277 
* Fix remove all series added bug, see #1256 
Tested the commands associated with the fixes.

Fix small issues

---

gamestonk_terminal/stocks/technical_analysis/ta_controller.py
tests/gamestonk_terminal/stocks/technical_analysis/cassettes/test_ta_controller/test_call_load.yaml
tests/gamestonk_terminal/stocks/technical_analysis/txt/test_ta_controller/test_print_help[None].txt
tests/gamestonk_terminal/stocks/technical_analysis/txt/test_ta_controller/test_print_help[start0].txt
website/content/common/technical_analysis/tv/_index.md
website/data/menu/main.yml

We all know that Trading View is amazing when it comes to technical analysis.
This PR adds a command to open trading view on the ticker directly.
Tried with the main tickers and worked fine.

Add tradingview command to ta controller

---

gamestonk_terminal/etf/stockanalysis_view.py

Added back index to ETF overview table.
Reran and saw index.

Fixed ETF overview table

---

gamestonk_terminal/custom/custom_controller.py
gamestonk_terminal/custom/custom_view.py
gamestonk_terminal/helper_classes.py
gamestonk_terminal/mutual_funds/investpy_view.py

funds + custom

---

gamestonk_terminal/alternative/covid/covid_view.py

External axes support for covid menu

Add external axes mode to covid charts

---

gamestonk_terminal/helper_classes.py
gamestonk_terminal/portfolio/portfolio_api.py
gamestonk_terminal/portfolio/portfolio_controller.py
gamestonk_terminal/portfolio/portfolio_optimization/optimizer_view.py
gamestonk_terminal/portfolio/portfolio_view.py
tests/gamestonk_terminal/portfolio/test_portfolio_controller.py
tests/gamestonk_terminal/portfolio/txt/test_portfolio_controller/test_print_help.txt

Add portfolio menu plots

---

gamestonk_terminal/common/behavioural_analysis/finbrain_view.py
gamestonk_terminal/common/behavioural_analysis/google_view.py
gamestonk_terminal/common/behavioural_analysis/sentimentinvestor_view.py
gamestonk_terminal/common/behavioural_analysis/twitter_view.py
gamestonk_terminal/stocks/behavioural_analysis/ba_api.py
tests/gamestonk_terminal/common/behavioural_analysis/test_sentimentinvestor_view.py
tests/gamestonk_terminal/common/behavioural_analysis/txt/test_sentimentinvestor_view/test_display_historical_empty_df.txt
tests/gamestonk_terminal/common/behavioural_analysis/txt/test_sentimentinvestor_view/test_display_historical_supported_ticker.txt
tests/gamestonk_terminal/common/behavioural_analysis/txt/test_sentimentinvestor_view/test_display_trending.txt
tests/gamestonk_terminal/common/behavioural_analysis/txt/test_sentimentinvestor_view/test_display_trending_empty_df.txt

Adds fancy plots to the common BA functions:
- finbrain ✅
- finhub - no plots
- reddit - no plots
- stocktwits - no plots
- twitter - ✅
- google - ✅
- sentimentinvestor - ✅

Plot updates in common BA

---

website/content/_index.md
website/content/bot/_index.md
website/content/bot/discord/_index.md
website/data/menu/main.yml

This pull requests adds the Discord Bot to the Hugo Server documentation and updates the placeholder copy on the main page.

Adds Discord Bot to Hugo Server Documentation

---

gamestonk_terminal/stocks/quantitative_analysis/qa_controller.py

I left a couple manual prints for debugging in the bug fixes

oopsy prints

---

gamestonk_terminal/parent_classes.py
gamestonk_terminal/stocks/comparison_analysis/finbrain_view.py
gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_model.py
gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_view.py
gamestonk_terminal/stocks/dark_pool_shorts/finra_view.py
gamestonk_terminal/stocks/dark_pool_shorts/nyse_view.py
gamestonk_terminal/stocks/dark_pool_shorts/sec_view.py
gamestonk_terminal/stocks/dark_pool_shorts/stockgrid_view.py
gamestonk_terminal/stocks/due_diligence/business_insider_view.py
gamestonk_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
gamestonk_terminal/stocks/government/quiverquant_view.py
gamestonk_terminal/stocks/insider/businessinsider_view.py
gamestonk_terminal/stocks/sector_industry_analysis/financedatabase_view.py
gamestonk_terminal/stocks/stocks_helper.py
styles/default/dark.mplstyle
tests/gamestonk_terminal/stocks/test_stocks_helper.py

Fixing the looks of some plots and graphs in the stocks context
Some example charts:
Before
After

Fix stocks asthetic style

---

gamestonk_terminal/cryptocurrency/crypto_controller.py
gamestonk_terminal/economy/fred/fred_controller.py
gamestonk_terminal/stocks/options/screener_controller.py
gamestonk_terminal/stocks/options/syncretism_view.py
tests/gamestonk_terminal/economy/fred/test_fred_controller.py

Feeling these today haha
#1390 
- Make the tickers a `list(set( Vals))`
#1389 
- Make the argparse the common way we do it
#1366 
- Fix the upper/lower case mismatches

Squishy the bugs

---

website/data/menu/main.yml

didn't check the main.yml fix close enough

extra ref in main

---

tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_address_history-kwargs4].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_address_info-kwargs1].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_token_decimals-kwargs0].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_token_historical_price-kwargs7].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_token_historical_price-kwargs8].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_token_history-kwargs6].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_token_history-kwargs7].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_token_info-kwargs5].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_top_token_holders-kwargs3].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_call_func[get_top_tokens-kwargs2].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_model/test_get_tx_info.yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_address_history-kwargs3].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_address_info-kwargs0].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_token_historical_prices-kwargs7].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_token_history-kwargs6].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_token_info-kwargs4].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_top_token_holders-kwargs2].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_top_tokens-kwargs1].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/cassettes/test_ethplorer_view/test_call_func[display_tx_info-kwargs5].yaml
tests/gamestonk_terminal/cryptocurrency/onchain/test_ethplorer_model.py
tests/gamestonk_terminal/cryptocurrency/onchain/test_ethplorer_view.py

Fix filtering issue on the test for the module :
- `gamestonk_terminal.cryptocurrency.onchain.ethplorer_model`

Tests : Cryptocurrency>Onchain>Ethplorer

---

gamestonk_terminal/stocks/comparison_analysis/yahoo_finance_view.py
gamestonk_terminal/stocks/screener/yahoofinance_view.py
gamestonk_terminal/stocks/sector_industry_analysis/sia_controller.py
gamestonk_terminal/stocks/sector_industry_analysis/stockanalysis_view.py
tests/gamestonk_terminal/stocks/sector_industry_analysis/txt/test_sia_controller/test_print_help.txt

Applies the charting style to sia/vis, ca/historical and scr/historical

Update sia and historical charts

---

gamestonk_terminal/common/behavioural_analysis/google_view.py
gamestonk_terminal/stocks/behavioural_analysis/ba_controller.py
scripts/test_stocks_ba.gst
tests/gamestonk_terminal/stocks/behavioural_analysis/txt/test_ba_controller/test_print_help.txt
website/content/stocks/behavioural_analysis/interest/_index.md
website/data/menu/main.yml

Interest from google trends correlated with stock price

---

gamestonk_terminal/keys_controller.py

On top of the links to retrieve API keys it fixed one bug with repeated code by accident and another one that wasn't allow me to get into the menu due to an exception being flagged on reddit keys being outside try/except block.

Add links to get API keys when no args provided and fix bugs

---

gamestonk_terminal/helper_funcs.py

As the name suggests, this allow to save files with a specified filename.

Allow for custom filename save

---

gamestonk_terminal/stocks/comparison_analysis/ca_controller.py
gamestonk_terminal/stocks/dark_pool_shorts/dps_controller.py
gamestonk_terminal/stocks/due_diligence/dd_controller.py
gamestonk_terminal/stocks/fundamental_analysis/fa_controller.py
gamestonk_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
routines/example_with_inputs_saved.gst
terminal.py

Try
```
python terminal.py routines/example_with_inputs_saved.gst -i AAL
```

Several bugfixes and routines allowed multiple calls to same arg

---

website/data/menu/main.yml

Fixes cryptocurrency menu not collapsing on hugo docs

---

.github/workflows/mac.yml
.github/workflows/test.yml
.github/workflows/windows.yml

Fixed a small mistake in my last pr.
We gotta test on live.

Fix main tests

---

gamestonk_terminal/helper_funcs.py

Allows to export when using installer

---

jupyterlab/documentation/yarn.lock
jupyterlab/openbb-settings/yarn.lock
jupyterlab/openbb/yarn.lock

Updating JupyterLab dependencies

---

openbb_terminal/README.md

Fix API Keys images not showing in README

---

.pre-commit-config.yaml
openbb_terminal/portfolio/portfolio_controller.py

Think this should address #1610

Edit portfolio `value` for add as well as  a spelling error

---

README.md

Add star history to the README page.

Add star history to readme page

---

openbb_terminal/keys_controller.py

[Bug] Incorrect log for reddit keys. #1733 fix

---

openbb_terminal/mutual_funds/avanza_fund_ID.csv

Adding more available funds for the avanza commands (only for swedish funds) in the mutual funds menu.
Checking multiple funds and using the avanza specific commands. This adds no new feature and makes no code changes.

Adding new funds to the avanza fund list

---

pyproject.toml

Bump project version to 1.2.0

---

openbb_terminal/helper_funcs.py
pyproject.toml

Applies the fix and bumps project version

Fix rich tables treating loss as a small value

---

openbb_terminal/helper_classes.py
openbb_terminal/helper_funcs.py
openbb_terminal/parent_classes.py

remove LineAnnotateDrawer in helper_func has duplicated class in helper_classes.
import console in helper_classes.visualize_output move out for using in LineAnnotateDrawer.

Duplicated code remove

---

openbb_terminal/cryptocurrency/discovery/dappradar_model.py

#1785 fix
Add referer on requests for avoid 403.
I don't have any idea for better error handling yet. So just for now, I commit only error fixed version.

fix crypto/disc/drnft error

---

README.md

Update README - Very minor grammatical typos

---

openbb_terminal/economy/economy_controller.py
openbb_terminal/economy/fred_view.py

There was an issue when running for example : `fred DGS10`
There is no longer an issue when running `fred DGS10`

Fix economy/fred bug

---

openbb_terminal/stocks/stocks_controller.py

Get rid of qa interval warning

---

openbb_terminal/reports/equity.ipynb

Fix trailing coma typo

---

openbb_terminal/portfolio/portfolio_controller.py

Fixes #1912.
Reran the terminal while setting a risk-free rate.

Fixed risk free bug

---

website/content/terminal/stocks/options/_index.md

A URL was pointing to a bad link, fixed.

Fixed bad URL to options screener intro

---

website/content/terminal/stocks/codes/_index.md

Fixed typo - SCI --> SIC

---

routines/dd_demo.openbb
website/content/terminal/stocks/due_diligence/_index.md

Adds Introduction Guide to DD menu.

Adds Stocks/DD Guide

---

i18n/en.yml
openbb_terminal/helper_funcs.py
openbb_terminal/settings_controller.py

Allow user to set flair - request from Twitter user @crisciceroe 

---

openbb_terminal/keys_controller.py

OANDA key menu was returning an error if both -a and -t were not supplied
fixed it

Fix oanda key issue

---

tests/openbb_terminal/stocks/fundamental_analysis/test_fa_controller.py

Issue is that the source needed to be specified because @DidierRLopes goofed <3

Fix FA tests

---

openbb_terminal/README.md

Changing with the times

---

jupyterlab/documentation/README.md
jupyterlab/openbb-settings/README.md
jupyterlab/openbb/README.md
website/README.md

Fixed a few typos

---

guess_game.json
openbb_terminal/economy/alphavantage_view.py
openbb_terminal/economy/econdb_model.py
openbb_terminal/settings_controller.py
openbb_terminal/stocks/dark_pool_shorts/yahoofinance_model.py

Looks like I have hit:
#2196 
#2193 
#2187 
okay fixed more but am done now
#2167 :
#2177

Small danglewood bugs

---

openbb_terminal/cryptocurrency/overview/coinbase_model.py
openbb_terminal/cryptocurrency/overview/coinbase_view.py

Beat you @colin99d 
This was pointed out in #2186 comments.  Looks like it was just a change in the cb api response. oops

Fix coinbase function in crypto/ov

---

openbb_terminal/stocks/insider/businessinsider_view.py

Fix insider

---

website/content/terminal/economy/index/_index.md

Updates documentation for `econ/index`. Fixes #2271 

Fix econ index documentation

---

openbb_terminal/stocks/discovery/yahoofinance_model.py
tests/openbb_terminal/stocks/discovery/csv/test_yahoofinance_model/test_call_func[get_gtech].csv
tests/openbb_terminal/stocks/discovery/csv/test_yahoofinance_model/test_call_func[get_ugs].csv

Fixes issues with scraping yfinance. Fixes #2272 
Reran all the commands.

Fixed bad yfinance urls

---

openbb_terminal/common/behavioural_analysis/twitter_model.py

Switch away from df append

---

website/content/_index.md

Adds missing API key information from the getting started guide.

updated API list to include Santiment and Crypto Panic

---

openbb_terminal/terminal_helper.py

Exit bot ad

---

.github/workflows/test.yml
.pre-commit-config.yaml
openbb_terminal/README.md
openbb_terminal/common/behavioural_analysis/reddit_model.py
openbb_terminal/common/quantitative_analysis/qa_model.py
openbb_terminal/economy/yfinance_model.py
openbb_terminal/forex/av_view.py
openbb_terminal/stocks/technical_analysis/tradingview_view.py
routines/example.openbb
website/content/terminal/common/qa/decompose/_index.md
website/content/terminal/common/ta/recom/_index.md
website/content/terminal/crypto/dd/_index.md
website/content/terminal/crypto/defi/_index.md
website/content/terminal/stocks/dd/_index.md
website/content/terminal/stocks/fa/fraud/_index.md
website/content/terminal/stocks/options/pricing/rnval/_index.md

Fixes Forex Quote

---

openbb_terminal/stocks/stocks_controller.py

Allow search to have multiple words

---

openbb_terminal/stocks/fundamental_analysis/fa_controller.py

mktcap start -> start date

---

openbb_terminal/stocks/dark_pool_shorts/dps_controller.py
openbb_terminal/stocks/dark_pool_shorts/sec_model.py
openbb_terminal/stocks/stocks_helper.py
tests/openbb_terminal/stocks/dark_pool_shorts/test_dps_controller.py

#2342 Changed to show price as two decimals
#2341 Was a leftover result of the api merge (datetime vs string convention)

Small change + small bug fix

---

openbb_terminal/portfolio/portfolio_optimization/yahoo_finance_model.py

Fixes #2319 by setting index to datetimeindex (although it already had date as an index, pandas didn't realise it)

fix: Issue #2319

---

openbb_terminal/common/behavioural_analysis/reddit_model.py

This PR tries to fix #2314 , which apparently was trying to access inexistant attribute 'name' when submission is 'None'. 
Run command stocks/ba/popular

Stocks/BA/Popular - Error: 'NoneType' object has no attribute 'name' Error: 'list' object has no attribute 'empty'

---

openbb_terminal/stocks/dark_pool_shorts/finra_view.py

More verbose error

---

i18n/en.yml
openbb_terminal/economy/commodity_view.py
openbb_terminal/economy/economy_controller.py
tests/openbb_terminal/economy/txt/test_economy_controller/test_print_help.txt
website/content/terminal/economy/edebt/_index.md
website/data/menu/main.yml

Changed cdebt to edebt with wording fixes

---

openbb_terminal/portfolio/portfolio_optimization/po_controller.py

Fixed blacklitterman export

---

openbb_terminal/cryptocurrency/due_diligence/messari_model.py

Fixed issue with crypto dd tk command

---

openbb_terminal/economy/economy_controller.py

This should have been added to #2421, @deeleeramone sorry I only saw your message after having merged. @jmaslek just forgot to push the controller file

Minor fix for FRED

---

.github/workflows/test.yml

https://www.python.org/download/pre-releases
Related to #2208

fix x-small: Add Python 3.10 and 3.11 release candidate to testing

---

openbb_terminal/forex/technical_analysis/ta_controller.py

Argument mismatch between common/technical_analysis/trend_indicators_view..py and forex/technical_analysis/ta_controller.py

fix ta command issues #2457

---

openbb_terminal/common/quantitative_analysis/qa_view.py
openbb_terminal/common/quantitative_analysis/rolling_view.py
openbb_terminal/cryptocurrency/quantitative_analysis/qa_controller.py
openbb_terminal/custom/quantitative_analysis/qa_controller.py
openbb_terminal/economy/quantitative_analysis/qa_controller.py
openbb_terminal/forex/quantitative_analysis/qa_controller.py
openbb_terminal/stocks/quantitative_analysis/qa_controller.py
tests/openbb_terminal/forex/quantitative_analysis/test_qa_controller.py
tests/openbb_terminal/stocks/quantitative_analysis/test_qa_controller.py

Fixes #2458. Issue was keyword arguments in controller and view not matching

fix: Issue 2458

---

openbb_terminal/econometrics/econometrics_controller.py
openbb_terminal/reports/equity.ipynb

Fix for #2479 
The load script had no "-f", so I added one if its not present

add -f to load if not present

---

openbb_terminal/stocks/fundamental_analysis/yahoo_finance_model.py
openbb_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
openbb_terminal/stocks/options/nasdaq_model.py
openbb_terminal/stocks/options/op_helpers.py
openbb_terminal/stocks/options/options_controller.py

#2423 
Added a helper to get the time to expiration so that we can eliminate the expirations in the past.  Can also be used for greeks calculations.
Also addressed #2285 but uncovered some issues while doing so that I will open a new issue for.

Get rid of option expirations in the past for Nasdaq + bugs

---

.github/workflows/m1_macos_build.yml

* Create m1_macos_build.yml
* Update m1_macos_build.yml
* Update m1_macos_build.yml
* Update m1_macos_build.yml
* Update m1_macos_build.yml
* Update m1_macos_build.yml
* Update m1_macos_build.yml
* taking out notarize and staple
includes codesigning tho
* changing prediction install
I am expecting a code sign error instead of a running the actual executable error. trying with -e prediction instead of -e prediction-m1-mac
* Changing prediction, keeping code signing
* Update m1_macos_build.yml
* Update m1_macos_build.yml
* taking out integration tests
* rerun
* Update m1_macos_build.yml
* adding pred back to turn to false
* making same as upstream release
* Update m1_macos_build.yml
* Update m1_macos_build.yml
* Update m1_macos_build.yml
Co-authored-by: Theodore Aptekarev …

M1 macos build system (#2504)

---

build/nsis/setup.nsi
openbb_terminal/feature_flags.py
pyproject.toml

reverting back a version until installer news bug is fixed.

Revert back version

---

openbb_terminal/cryptocurrency/defi/graph_view.py

This PR fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/2517

[Bug] Crypto/DeFi/pools - Error: display_uni_pools() got an unexpected keyword argument 'descend'

---

openbb_terminal/etf/etf_controller.py
tests/openbb_terminal/etf/txt/test_etf_controller/test_print_help.txt

My etf screener script has broken with stockanalysis updating their stuff.  Needs to be updated, so commenting this out until its replaced.
EDIT: ETF not options

Comment out etf screener for short term

---

openbb_terminal/common/feedparser_model.py

News seems to have a bug only when **DOWNLOADING** the installer. This adds notification to users if it fails.

adding warning to news

---

openbb_terminal/stocks/quantitative_analysis/qa_controller.py

Resolves #2536.
How to test : run the command `stocks/qa/rolling`

Fixing #2536

---

README.md

Update docs link to openbb.co/docs

---

openbb_terminal/common/behavioural_analysis/google_model.py

Added integration tests fixes

---

website/config.toml

Fix typo in config.toml

---

openbb_terminal/helpers_denomination.py

Fixes #2691. @deeleeramone please text this because I could not recreate your bug.

Fix key error bug

---

openbb_terminal/cryptocurrency/onchain/bitquery_view.py
openbb_terminal/cryptocurrency/onchain/onchain_controller.py

fix bitquery crypto funcs

---

openbb_terminal/core/config/paths_helper.py

Reverting changes in order to implement better fix.

Sources Bug Fix Revert

---

website/content/_index.md

screenshots way outdated, updated three of them.

refreshes some screenshots of the main menu on the core landing page.

---

website/content/_index.md
website/themes/hugo-geekdoc/layouts/partials/head/others.html

fix(docs): added margin between sections

---

i18n/en.yml
openbb_terminal/cryptocurrency/crypto_controller.py
openbb_terminal/economy/economy_controller.py
openbb_terminal/featflags_controller.py
openbb_terminal/feature_flags.py
openbb_terminal/terminal_helper.py
terminal.py

@piiq wanted to me to remove remnants of pred menu, so I removed it. @martinb-bb note here.

Cleaned out pred remenants

---

openbb_terminal/common/technical_analysis/momentum_model.py

The definition of this indicator is annualized expoential slope.  I was not doing the annualization so now I am

Annualize clenow momentum

---

openbb_terminal/api.py
openbb_terminal/keys_controller.py
openbb_terminal/keys_model.py
tests/openbb_terminal/cassettes/test_keys_controller/test_call_shroom[other1].yaml
tests/openbb_terminal/cassettes/test_keys_controller/test_call_tokenterminal[other1].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_shroom_key[args0-False-True-defined, test failed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_shroom_key[args1-False-False-defined, test failed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_shroom_key[args2-True-True-defined, test failed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_tokenterminal_key[args0-False-True-defined, test failed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_tokenterminal_key[args1-False-False-defined, test failed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_tokenterminal_key[args2-True-True-defined, test failed].yaml
tests/openbb_terminal/test_keys_controller.py
tests/openbb_terminal/test_keys_model.py
tests/openbb_terminal/txt/test_keys_model/test_set_shroom_key[args0-False-True-defined, test failed].txt
tests/openbb_terminal/txt/test_keys_model/test_set_shroom_key[args2-True-True-defined, test failed].txt
tests/openbb_terminal/txt/test_keys_model/test_set_shroom_key[args3-False-True-not defined].txt
tests/openbb_terminal/txt/test_keys_model/test_set_tokenterminal_key[args0-False-True-defined, test failed].txt
tests/openbb_terminal/txt/test_keys_model/test_set_tokenterminal_key[args2-True-True-defined, test failed].txt
tests/openbb_terminal/txt/test_keys_model/test_set_tokenterminal_key[args3-False-True-not defined].txt

* `tokenterminal` command not doing anything when called
* `shroom` command is always retrieving `not defined` on key setup
* Fix bugs, add keys to SDK and add unittests to recent changes 
Testing in terminal:
`keys` -> `tokenterminal -k test`
`keys` -> `shroom -k test`
Testing in SDK:
`keys.tokenterminal(key="test")`
`keys.shroom(key="test")`

Fix keys menu: tokenterminal & shroom bug fix

---

openbb_terminal/forecast/forecast_controller.py

Fixes bug with plotting the date column

---

website/content/api/stocks/_index.md

Adds an introduction guide for the Stocks SDK.

Introduction Guide for the Stocks SDK

---

openbb_terminal/economy/commodity_model.py
openbb_terminal/economy/nasdaq_model.py
openbb_terminal/economy/wsj_model.py

Fixes a host of unreported bugs in the economy menu.

Enhances error handling in economy menu

---

DOCKER_ADVANCED.md

The PR updates the docs on how to setup X11 forwarding

Clean up docker documentation

---

.github/workflows/labels.yml

installer + hacktoberfest labels

---

openbb_terminal/feature_flags.py

Fix internationalization dictionary not being loaded

---

openbb_terminal/miscellaneous/styles/default/dark.mplstyle

Revert some of didiers changes
Was:
Is:

Plot style

---

openbb_terminal/miscellaneous/i18n/en.yml
openbb_terminal/sdk.py
openbb_terminal/stocks/backtesting/bt_controller.py
openbb_terminal/stocks/backtesting/bt_model.py
openbb_terminal/stocks/backtesting/bt_view.py
tests/openbb_terminal/stocks/backtesting/cassettes/test_bt_model/test_emacross_strategy.yaml
tests/openbb_terminal/stocks/backtesting/cassettes/test_bt_view/test_display_emacross.yaml
tests/openbb_terminal/stocks/backtesting/test_bt_controller.py
tests/openbb_terminal/stocks/backtesting/test_bt_model.py
tests/openbb_terminal/stocks/backtesting/test_bt_view.py
tests/openbb_terminal/stocks/backtesting/txt/test_bt_controller/test_print_help.txt
website/content/SDK/stocks/bt/emacross/_index.md
website/content/terminal/stocks/bt/emacross/_index.md
website/data/menu/main.yml

Name changing the emacross command.
Do not update or merge yet!

Emacross name change part 2

---

openbb_terminal/forecast/forecast_view.py

to run `corr <DATASET>`
Old: 
New: 

Enhance look and readability of `corr` heatmap (UX)

---

website/content/terminal/stocks/ins/_index.md

Spelling, as per a comment in #2996

Spelling correction

---

website/content/terminal/crypto/_index.md
website/content/terminal/economy/_index.md
website/content/terminal/etf/_index.md
website/content/terminal/forex/_index.md
website/content/terminal/stocks/_index.md

Fix: replaced the prediction techniques links with foecasting menu links

---

website/content/_index.md

Token Terminal was not listed in the table.

Adds Token Terminal to list of API data sources.

---

website/content/terminal/common/ta/atr/_index.md
website/data/menu/main.yml

Fixes #3152 
soryy @minhhoang1023

Hugo for atr

---

website/content/SDK/common/ta/atr/_index.md
website/data/menu/main.yml

generate new doc

---

openbb_terminal/forecast/forecast_controller.py
openbb_terminal/forecast/forecast_view.py
website/content/terminal/forecast/_index.md
website/content/terminal/forecast/atr/_index.md
website/content/terminal/forecast/clean/_index.md
website/content/terminal/forecast/combine/_index.md
website/content/terminal/forecast/delete/_index.md
website/content/terminal/forecast/delta/_index.md
website/content/terminal/forecast/ema/_index.md
website/content/terminal/forecast/mom/_index.md
website/content/terminal/forecast/rename/_index.md
website/content/terminal/forecast/roc/_index.md
website/content/terminal/forecast/rsi/_index.md
website/content/terminal/forecast/show/_index.md
website/content/terminal/forecast/signal/_index.md
website/content/terminal/forecast/sto/_index.md

Several improvements on the forecasting menu - mostly in terms of usability

Improve forecast menu usability

---

openbb_terminal/stocks/sector_industry_analysis/sia_controller.py

Add clear -p and --param to autocomplete

---

openbb_terminal/base_helpers.py
openbb_terminal/config_plot.py
openbb_terminal/feature_flags.py

Adds Verbosity to Error Message Warnings and Fixes my Issue when No Variables Present.

---

openbb_terminal/stocks/options/options_controller.py

[Bug]stocks/options/unu needs the '/' treat #2939

---

openbb_terminal/cryptocurrency/overview/pycoingecko_view.py

#3290 fix heatmap make it pertyyy

---

openbb_terminal/futures/futures_controller.py

Fixes #3314
Added in flags
Fixed capitalization issue

`futures/curve` capitalization fix

---

.github/workflows/test.yml

This avoids some errors coming from 0.990

Pin mypy to 0.982 on GitHub workflows

---

OpenBB Terminal.bat

This feels unneeded now that we have some many ways to install the terminal.

Delete OpenBB Terminal.bat

---

openbb_terminal/forecast/forecast_controller.py
openbb_terminal/forecast/seasonalnaive_model.py
openbb_terminal/forecast/seasonalnaive_view.py
openbb_terminal/miscellaneous/i18n/en.yml
openbb_terminal/sdk.py
tests/openbb_terminal/forecast/test_seasonalnaive_model.py
tests/openbb_terminal/forecast/test_seasonalnaive_view.py
website/content/terminal/forecast/seasonalnaive/_index.md
website/data/menu/main.yml

This PR includes a new model for the forecast module. SeasonalNaive sets each forecast equal to the last observed value from the same season. [Here](https://otexts.com/fpp3/simple-methods.html#seasonal-na%C3%AFve-method)'s a reference for the model. Commonly used as a benchmark. Since StatsForecast is already included in the dependencies, it wasn't necessary to include it.
Here's a working example,

[FEAT] StatsForecast SeasonalNaive forecasting model

---

openbb_terminal/alternative/covid/covid_view.py

Fixes: https://github.com/OpenBB-finance/OpenBBTerminal/issues/3446

Fix for `covid` cases `export`

---

openbb_terminal/dashboards/voila/forecast.ipynb

Update sdk on forecast dashboard `_chart`

---

openbb_terminal/reports/templates/equity.ipynb
openbb_terminal/reports/templates/etf.ipynb

Thihs should 
- Fix #3506 
- Fix #3505 
These were sdk issues from me deleting commands.  oops

Report fixes

---

.github/workflows/gh-pages.yml
openbb_terminal/SDK_README.md
openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
openbb_terminal/stocks/options/chartexchange_model.py
openbb_terminal/stocks/options/options_sdk_helper.py
openbb_terminal/terminal_helper.py
pyproject.toml
website/content/sdk/quickstart/installation.md

We missed a lint rip
Gonna look into the deploy issue real quick
- Looks like it was not doing poetry -E optimization

Fix linter issue

---

openbb_terminal/cryptocurrency/overview/pycoingecko_model.py
openbb_terminal/cryptocurrency/overview/pycoingecko_view.py
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_pycoingecko_view/test_coin_stablecoins.yaml
tests/openbb_terminal/cryptocurrency/overview/test_pycoingecko_view.py
tests/openbb_terminal/cryptocurrency/overview/txt/test_pycoingecko_view/test_coin_stablecoins.txt

* Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/3549
Test:
```
openbb.crypto.ov.stables(sortby="Volume_[$]", ascend=True, limit=10)
openbb.crypto.ov.stables_chart(sortby="Volume_[$]", ascend=True, limit=5)
```

Fix [Bug] SDK - `openbb.crpyto.ov.stables` - Error: 'rank' (works in Terminal though)

---

openbb_terminal/core/library/trail_map.py
openbb_terminal/reports/reports_controller.py

Disable PO detection on SDK

---

openbb_terminal/core/library/breadcrumb.py

As requested in #3646 this just gets the verison from the feature flag

add version to sdk

---

.gitignore

This PR adds local artifacts produced by sonarqube static code analyzer to gitignore

Add sonarqube artifacts to ignore

---

website/content/sdk/guides/intros/quantitative-analysis.md

This one got missed when the other functions were updated, so making that change now.

Updated the list of functions. `so` --> `sortino`

---

website/content/terminal/guides/intros/stocks/index.md

Updates information, screenshots, and examples to be current for version 2.0

Updates Stocks Intro Guide for Terminal 2.0

---

website/content/sdk/guides/intros/stocks/trading-hours.md

Creates a new file, trading-hours.md, under the `Stocks` tree.

Creates Trading Hours SDK Guide

---

openbb_terminal/stocks/due_diligence/finviz_model.py
openbb_terminal/terminal_helper.py
tests/openbb_terminal/stocks/due_diligence/test_finviz_model.py
tests/openbb_terminal/stocks/due_diligence/test_finviz_view.py

This will 
- Fix reports crashing
- FIx #3728 
- Fix #3713 
I am waiting on a PR to be merged and the finviz package to be updated
Note: adding an ignore for the mypy failing.  Not sure why this happens all of a sudden when there is a version.LegacyVersion.

Temporary fix for finviz analyst function

---

openbb_terminal/helper_funcs.py

Fixes #3715 by changing `.OpenBB_openbb_terminal` to `OpenBBTerminal`

Small fix to export file name

---

CONTRIBUTING.md

This PR fixes minor typos and formatting issues in the CONTRIBUTING Readme.
This is a minor non-code change and therefore no tests have been performed.

Fixes minor typos in the contributing guidelines

---

openbb_terminal/stocks/stocks_controller.py

I lost my touch with coding and made a new branch which closes #3762. This issue arrises because we call files that are stored on GitHub. Some users apparently do not have access to this source which tells them that there was an error.
Error message will be:
_Note: Some datasets from GitHub failed to load. This means that the `search` command and the /stocks/sia menu will not work.  If other commands are failing please check your internet connection or communicate with your IT department that certain websites are blocked._
Also note that I make empty dictionaries otherwise the entire menu wouldn't work anymore.
You can reproduce this error by turning off your internet connection and then trying to enter the Stocks menu.
```
(obb) jeroenbouma@Jeroens-MacBook-Pro OpenBB Terminal % python …
```

Add fix for Stocks menu not loading

---

website/content/sdk/guides/advanced/api-keys.md
website/content/terminal/guides/advanced/api-keys.md

I finally decided I needed to grab API Keys from all sources we have and decided to go ham on the documentation at the same time. This PR includes guides on every single API key we have how to set it.

Significantly update the API Keys documentation for the OpenBB Terminal and OpenBB SDK

---

openbb_terminal/reports/templates/economy.ipynb

Makes the economy report work out of the box.
Fix #3758
Fix #3484

Out of the box economy report

---

openbb_terminal/miscellaneous/scripts/stocks/test_stocks_bt.openbb
openbb_terminal/stocks/stocks_model.py

Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/3777
* Updates `openbb_terminal/miscellaneous/scripts/stocks/test_stocks_bt.openbb`
Test this by running the script "openbb_terminal/miscellaneous/scripts/stocks/test_stocks_bt.openbb"

Fix emacross with Polygon as source

---

openbb_terminal/economy/economy_controller.py
openbb_terminal/economy/plot_view.py
openbb_terminal/miscellaneous/scripts/economy/test_economy.openbb

* convert index to datetime and update choices
* uncomment economy integration test
* fix treasury concat bug
* fix datasets concat on duplciates

Fix plot look when using eval and add query to choices (#3881)

---

.github/workflows/test.yml
.pre-commit-config.yaml
openbb_terminal/economy/economy_controller.py
openbb_terminal/economy/plot_view.py
openbb_terminal/miscellaneous/scripts/economy/test_economy.openbb

Main --> develop

---

.github/workflows/branch-name-check.yml
.github/workflows/linting.yml
.github/workflows/unit-test.yml

Gitflow -  Added manual trigger to Linting

---

.github/workflows/branch-name-check.yml
.github/workflows/linting.yml

Linting fix

---

website/content/sdk/reference/ta/vwap.md

incorrect type hint for vwap function

Update vwap.md - wrong type hint 

---

build/conda/conda-3-9-env-full.yaml
openbb_terminal/parent_classes.py

This is a super super small thing for @JerBouma that will just make the exports noticeable.
(kinda) Fixes #3994

Add ticker to the load export file

---

openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
openbb_terminal/cryptocurrency/defi/substack_model.py
openbb_terminal/cryptocurrency/onchain/bitquery_model.py
openbb_terminal/etf/etf_controller.py
openbb_terminal/portfolio/attribution_model.py
openbb_terminal/stocks/backtesting/bt_view.py
openbb_terminal/stocks/fundamental_analysis/yahoo_finance_model.py
openbb_terminal/stocks/fundamental_analysis/yahoo_finance_view.py
openbb_terminal/stocks/insider/openinsider_model.py
openbb_terminal/stocks/sector_industry_analysis/stockanalysis_model.py

Test: run the commands above or the respective integration test scripts
Will fix `watchlist` in another PR bc it might touch other Reddit commands

Fix integration tests bugs

---

openbb_terminal/core/config/paths.py
openbb_terminal/featflags_controller.py
openbb_terminal/feature_flags.py
openbb_terminal/helper_funcs.py
openbb_terminal/settings_controller.py
openbb_terminal/terminal_controller.py

This PR fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/3633
Reorders dot_env loading with the order, so user changes prevail:
1. Repository .env file
2. Package .env file
3. User .env file 
Test:
* Change settings/feature flags in git clone and check if they are correctly change in your `.openbb_terminal/.env`
* Build and test installer -> `build/README.md`

Change .env loading priority

---

openbb_terminal/session/sdk_session.py
openbb_terminal/session/session_controller.py
openbb_terminal/session/session_model.py

Fix login bug and decouple some logic

---

openbb_terminal/terminal_helper.py
tests/openbb_terminal/test_terminal_helper.py

Fix update check

---

.github/release-drafter.yml
.github/workflows/labels.yml

Add a "release" label
Exclude openbb team members from the release drafter as "new contributors"

Update labels and release drafter

---

tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_cls.yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_exit-queue0-expected_queue0].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_exit-queue1-expected_queue1].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_help-queue3-expected_queue3].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_home-queue2-expected_queue2].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_quit-queue4-expected_queue4].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_quit-queue5-expected_queue5].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_reset-queue6-expected_queue6].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_call_func_expect_queue[call_reset-queue7-expected_queue7].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_menu_with_queue[queue0-expected0].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_menu_with_queue[queue1-expected1].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_print_help.yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_switch[-expected_queue0].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_switch[-help-expected_queue1].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_switch[h-expected_queue4].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_switch[help-help-expected_queue2].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_switch[q-expected_queue3].yaml
tests/openbb_terminal/cryptocurrency/overview/cassettes/test_overview_controller/test_switch[r-expected_queue5].yaml
tests/openbb_terminal/cryptocurrency/overview/test_overview_controller.py

Rewrite crypto/ov controller cassettes

---

openbb_terminal/core/config/paths.py
openbb_terminal/sdk.py
openbb_terminal/terminal_controller.py

Fix sdk guest not loading keys

---

openbb_terminal/miscellaneous/library/trail_map.csv
openbb_terminal/miscellaneous/library/trail_map_optimization.csv

Fixed Trailmap errors, removed deprecated

Hotfix/sdk-trailmaps `portfolio.po` deprecated functions, fix `stocks.disc.filings`, `stocks.fa.sec_fmp`

---

openbb_terminal/terminal_controller.py

Block logout command if no auth enabled

---

website/docusaurus.config.js

Algolia fix

---

generate_sdk.py
openbb_terminal/forecast/forecast_view.py
openbb_terminal/sdk.py
openbb_terminal/sdk_core/models/forecast_sdk_model.py
openbb_terminal/sdk_core/trail_map_forecasting.csv
openbb_terminal/sdk_core/trailmap.py
tests/website/test_generate_docs.py
website/generate_sdk_markdown.py

Updated `website/generate_sdk_markdown.py` to use `sdk_core/trailmap.py`

Update SDK Docs Generation

---

README.md

Small typos on readme

---

openbb_terminal/reports/reports_model.py

fix variable name

---

build/pyinstaller/terminal.spec

frozendict removal for build

---

openbb_terminal/stocks/tradinghours/tradinghours_controller.py

Fix short name

---

openbb_terminal/economy/nasdaq_model.py
openbb_terminal/forex/polygon_model.py
openbb_terminal/stocks/options/options_controller.py
tests/conftest.py

Fix issue 4316

---

openbb_terminal/session/sdk_session.py

Fixing SDK login

---

.github/workflows/unit-test.yml

hotfix/Add needed libs to Full Test Suite workflows

---

openbb_terminal/helper_funcs.py
openbb_terminal/mutual_funds/mutual_fund_controller.py

Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4344
`funds` -> `country United_States`

Fix funds country choices

---

openbb_terminal/miscellaneous/data_sources_default.json

* Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/4340
* Went through the menus, reordered and deleted some deprecated commands from default sources file

Update default sources

---

openbb_terminal/helper_funcs.py

^
Fix #4385 by handling a different type of exception.

Fix ff breaking terminal

---

openbb_terminal/config_terminal.py
openbb_terminal/core/sdk/sdk_helpers.py
openbb_terminal/cryptocurrency/technical_analysis/ta_controller.py
openbb_terminal/sdk.py
terminal.py

Fix .env reading before loading

---

openbb_terminal/core/session/hub_model.py

Update routines upload

---

openbb_terminal/config_terminal.py
openbb_terminal/core/plots/backend.py

Hotfix/Temp Plots Backend html files

---

openbb_terminal/config_terminal.py
openbb_terminal/core/sdk/sdk_helpers.py
openbb_terminal/sdk.py
openbb_terminal/terminal_controller.py

Move start plot backend

---

.github/workflows/nightly-pypi.yml
build/docker/openbb.dockerfile

Fix documentation path for nightly build

Fix docs path for docker and pypi

---

website/content/terminal/guides/intros/crypto/defi.md

docs: fix typo

---

CONTRIBUTING.md
openbb_terminal/core/integration_tests/integration_controller.py
openbb_terminal/core/log/collection/log_sender.py
openbb_terminal/core/models/preferences_model.py

Patch flag for log collection

---

openbb_terminal/common/quantitative_analysis/qa_view.py

Fixes #4435 
I tried using .loc, and a deep copy. But neither of these made the issue go away, so I just hid the warning.

Fix Pandas Warning

---

openbb_terminal/core/models/preferences_model.py
openbb_terminal/core/session/preferences_handler.py
openbb_terminal/featflags_controller.py
openbb_terminal/miscellaneous/i18n/en.yml
openbb_terminal/stocks/stocks_view.py
tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args0-False].txt
tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args1-True].txt
tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args2-True].txt
tests/openbb_terminal/account/txt/test_account_controller/test_call_sync[other_args3-False].txt

`USE_INTERACTIVE_DF` to `featflags` menu, 
`console.print` changed value

Hotfix/Interactive in `featflags` menu

---

openbb_terminal/stocks/stocks_controller.py

Fixed the stock/load selection items

---

openbb_terminal/dashboards/voila/crypto.ipynb

Fixed crypto dashboard

---

openbb_terminal/helper_classes.py

Update "visualize_output" function

Update "visualize_output" function

---

tests/openbb_terminal/test_keys_model.py
tests/openbb_terminal/test_settings_controller.py

Fix pytest writing to .env

---

openbb_terminal/stocks/fundamental_analysis/sdk_helpers.py

Added sources

---

openbb_terminal/miscellaneous/i18n/en.yml
tests/openbb_terminal/cryptocurrency/overview/txt/test_overview_controller/test_print_help.txt

Fixes crypto ov issue

---

tests/openbb_terminal/cassettes/test_keys_controller/test_call_av[other1].yaml
tests/openbb_terminal/cassettes/test_keys_controller/test_call_av[other2].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_av_key[args0-False-True-defined, test passed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_av_key[args1-False-False-defined, test passed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_av_key[args2-True-True-defined, test passed].yaml
tests/openbb_terminal/cassettes/test_keys_model/test_set_av_key[args3-False-True-not defined].yaml
tests/openbb_terminal/test_keys_controller.py
tests/openbb_terminal/txt/test_keys_model/test_set_av_key[args0-False-True-defined, test passed].txt
tests/openbb_terminal/txt/test_keys_model/test_set_av_key[args2-True-True-defined, test passed].txt
tests/openbb_terminal/txt/test_keys_model/test_set_av_key[args3-False-True-not defined].txt

fix test keys written on .env file

---

CONTRIBUTING.md

This PR fixes a grammatical error in [`CONTRIBUTING.md`](https://github.com/OpenBB-finance/OpenBBTerminal/blob/develop/CONTRIBUTING.md).

Fix grammatical error in CONTRIBUTING.md

---

openbb_terminal/core/plots/plotly_helper.py
poetry.lock
pyproject.toml
requirements-full.txt
requirements.txt

bump pywry to 0.4.1

---

openbb_terminal/miscellaneous/data_sources_default.json
openbb_terminal/stocks/fundamental_analysis/finviz_model.py

Changes the order of source for `fa/overview`

---

website/content/sdk/index.md
website/content/terminal/index.md

hotfix/Update index.md

---

.github/workflows/macos_build.yml

Started the switch

---

openbb_terminal/terminal_helper.py

Enable auth by default

---

openbb_terminal/stocks/options/options_controller.py
openbb_terminal/stocks/options/options_view.py

hotfix/ `stocks/options/chains` - Single Window/`to_display` columns

---

openbb_terminal/core/models/preferences_model.py
openbb_terminal/helper_funcs.py

🐛 as default flair

---

openbb_terminal/core/plots/plotly_helper.py
openbb_terminal/core/session/hub_model.py
openbb_terminal/settings_controller.py

* warn user if no token found
* add spaces to settings menu cmds
* improve failing rich style message

Warn user when there is no personal access token

---

openbb_terminal/stocks/fundamental_analysis/eclect_us_model.py

Fixed the issue where the filings would return an empty dataframe (#4533).

Fix filings analysis

---

openbb_terminal/core/sdk/sdk_init.py
openbb_terminal/forecast/forecast_controller.py
openbb_terminal/reports/reports_controller.py
website/content/sdk/faqs/general_operation.md
website/content/sdk/usage/intros/stocks/fundamental-analysis.md
website/content/terminal/faqs/general_operation.md
website/content/terminal/usage/guides/data.md
website/content/terminal/usage/intros/common/ba.md
website/content/terminal/usage/intros/fixedincome.md
website/content/terminal/usage/intros/stocks/index.md

URL(404) fixes for multiple locations 

---

.github/workflows/pypi-nightly.yml

There was a typo in the documentation

Fix import statement for nightly PyPI readme page

---

openbb_terminal/stocks/options/options_sdk_helper.py

hotfix/ `options_sdk_helper.py`

---

website/src/css/custom.css

Adds min height to all docs pages

---

openbb_terminal/fixedincome/fred_view.py

Tested by executing the command in the terminal.

Fixed `/fixedincome/ecb --export` functionality

---

openbb_terminal/reports/templates/equity.ipynb
openbb_terminal/reports/templates/etf.ipynb
openbb_terminal/stocks/fundamental_analysis/fmp_model.py

Fixing some Equity Edge cases and adding some more ETF charts

reports fixing - equity / etf

---

openbb_terminal/core/plots/plotly_helper.py
openbb_terminal/core/plots/web/bar_menus.js
openbb_terminal/core/plots/web/css/style.css
openbb_terminal/core/plots/web/main.js
openbb_terminal/core/plots/web/popups.js

hotfix / Plots Performance

---

openbb_terminal/core/sdk/sdk_init.py
openbb_terminal/core/session/constants.py
openbb_terminal/core/session/session_controller.py
openbb_terminal/forecast/forecast_controller.py
openbb_terminal/helper_funcs.py
openbb_terminal/reports/reports_controller.py
openbb_terminal/terminal_helper.py
tests/openbb_terminal/session/txt/test_sdk_session/test_whoami.txt
tests/openbb_terminal/session/txt/test_sdk_session/test_whoami_guest.txt
tests/openbb_terminal/session/txt/test_session_controller/test_display_welcome_message.txt
tests/openbb_terminal/session/txt/test_user/test_whoami[True-True].txt
website/content/sdk/faqs/general_operation.md
website/content/terminal/faqs/general_operation.md

openbb.dev -> openbb.co

---

openbb_terminal/intro.json

Fix for #4869 
Plus slightly altered OpenBB Scripts text to something slightly better worded.

fixes #4869 intro dupe header numbering

---

openbb_terminal/core/session/constants.py

Update default routines url

---

openbb_terminal/account/account_controller.py
openbb_terminal/core/session/routines_handler.py
openbb_terminal/core/session/session_model.py

Handle bad results from default routines

---

frontend-components/tables/index.html
openbb_terminal/core/plots/table.html

hotfix / Post-Tables

---

website/src/theme/EditThisPage/index.js

Since reference for our products is auto generated doesnt make sense to show edit this page on the docs

Dont show edit page on reference

---

website/src/theme/Root.tsx

Docs error build

---

openbb_terminal/miscellaneous/models/hub_credentials.json
poetry.lock
pyproject.toml
requirements-full.txt
requirements.txt
tests/openbb_terminal/test_keys_controller.py

hotfix/ fix windows pyinstaller subprocess fail if space in path

---

openbb_terminal/miscellaneous/i18n/en.yml
tests/openbb_terminal/alternative/txt/test_alt_controller/test_print_help.txt
tests/openbb_terminal/cryptocurrency/txt/test_crypto_controller/test_print_help.txt
tests/openbb_terminal/etf/cassettes/test_etf_controller/test_call_load.yaml
tests/openbb_terminal/etf/txt/test_etf_controller/test_print_help.txt
tests/openbb_terminal/forex/cassettes/test_forex_controller/test_call_load[other_args0].yaml
tests/openbb_terminal/forex/cassettes/test_forex_controller/test_call_load[other_args1].yaml
tests/openbb_terminal/forex/txt/test_forex_controller/test_print_help.txt
tests/openbb_terminal/stocks/cassettes/test_stocks_controller/test_call_load.yaml
tests/openbb_terminal/stocks/txt/test_stocks_controller/test_print_help.txt

Removed the appearance of submenu commas inside the i18n. This closes #4950 issue.

Remove commas from i18n

---

openbb_terminal/keys_controller.py

Same as the old issue (#4707).

Fixed `--help` arg not working for some commands in `keys` menu

---

openbb_terminal/reports/templates/equity.ipynb

Changed `symbol` from `FRC` to `MSFT`.

Fixed equity report

---

website/content/terminal/installation/docker.md

Add linux docker launch command notes

---

website/content/terminal/usage/guides/keyboard-hotkey-macros.md

Moving Keyboard hotkey macros document to under docs

Keyboard hotkey macros to website docs

---

openbb_terminal/core/models/system_model.py

Hotfix / Fix `reset` command error force closing terminal

---

openbb_terminal/stocks/insider/openinsider_model.py

Remove \n from insider table

---

openbb_terminal/miscellaneous/integration_tests_scripts/fixedincome/test_fixedincome.openbb

This PR increases the integration testing coverage of the fixed income menu.

100% coverage for fixed income integration tests

---

openbb_terminal/miscellaneous/integration_tests_scripts/economy/test_economy.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/etf/test_ca.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/etf/test_etf.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/mutual_funds/test_mutual_fund.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/stocks/test_ca.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/stocks/test_disc.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/stocks/test_fa.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/stocks/test_stocks.openbb

This PR adds additional coverage to the integration tests of the controllers.

Increases Integration Tests Coverage

---

openbb_terminal/miscellaneous/integration_tests_scripts/fixedincome/test_fixedincome.openbb

This PR attempts to resolve this issue:
```
result.txt:199:FAILED fixedincome\test_fixedincome.openbb -> command: unknown
```

fix integration test for fixedincome controller

---

.gitignore
openbb_terminal/core/plots/plotly_helper.py
openbb_terminal/cryptocurrency/cryptocurrency_helpers.py
openbb_terminal/dashboards/stream/pages/Indicators.py
openbb_terminal/stocks/options/chartexchange_view.py
openbb_terminal/stocks/options/intrinio_view.py
openbb_terminal/stocks/options/tradier_view.py

hotfix/ Options Historical + Crypto candles

---

openbb_terminal/keys_controller.py

* Fixes https://github.com/OpenBB-finance/OpenBBTerminal/issues/5013

Fix  `/keys` status does not update after logging in

---

openbb_terminal/terminal_helper.py
tests/openbb_terminal/common/txt/test_ultima_newsmonitor_view/test_display_news[AAPL].txt
tests/openbb_terminal/common/txt/test_ultima_newsmonitor_view/test_display_news[FCX].txt
tests/openbb_terminal/common/txt/test_ultima_newsmonitor_view/test_display_news[TSLA].txt

Change the link when the current version < latest version to point at https://my.openbb.co/app/terminal/download

Update download link on update version text

---

openbb_terminal/dashboards/streamlit_run.py

hotfix/ Dashboards random issue with theme not loading

---

openbb_terminal/miscellaneous/integration_tests_scripts/stocks/test_insider.openbb
openbb_terminal/miscellaneous/integration_tests_scripts/stocks/test_screener.openbb

This PR fixes a couple of the integration tests:
- stocks/insider
- stocks/screener

hotfix/integration-test-fixes - patches integration tests: stocks/test_insider and test_screener

---

openbb_terminal/core/plots/plotly_helper.py

hotfix/ XAxis Dateindex format

---

openbb_terminal/terminal_controller.py

Fix help and question

---

.github/workflows/linting.yml
.pre-commit-config.yaml
openbb_terminal/miscellaneous/i18n/en.yml
openbb_terminal/portfolio/portfolio_optimization/po_view.py
openbb_terminal/stocks/databento_model.py
openbb_terminal/terminal_controller.py

Title says it all:
- Change askobb to appear as a cmd
- Change -q/--question to -q/--prompt
- Allow two words (ie aapl candle) as a prompt

Move askobb to cmd and change question to prompt

---

frontend-components/plotly/src/App.tsx
frontend-components/plotly/src/components/Dialogs/OverlayChartDialog.tsx

Fixes x column not setting default if dropdown is not interacted with
closes #5140

hotfix/ Chart Overlay x column not setting by default

---

openbb_terminal/stocks/fundamental_analysis/av_model.py

I added error handling to check the correspondence of fiscal dates in the balance sheet and income statement. issue #5087

added error handling

---

openbb_terminal/economy/finviz_view.py
openbb_terminal/economy/oecd_view.py
openbb_terminal/miscellaneous/i18n/en.yml
openbb_terminal/parent_classes.py
openbb_terminal/stocks/comparison_analysis/ca_controller.py
openbb_terminal/stocks/government/quiverquant_model.py
openbb_terminal/terminal_controller.py
tests/openbb_terminal/economy/txt/test_finviz_view/test_display_performance[False].txt
tests/openbb_terminal/economy/txt/test_finviz_view/test_display_performance[True].txt
tests/openbb_terminal/economy/txt/test_finviz_view/test_display_valuation[False].txt
tests/openbb_terminal/economy/txt/test_finviz_view/test_display_valuation[True].txt
tests/openbb_terminal/stocks/comparison_analysis/txt/test_ca_controller/test_print_help.txt

- Add a feedback option on askobb
- Couple small cosmetic changes from user feedback
- Fix an unreported bug in toplobbying function
- Fix #5085
- Cleans up ca ticker lists, i.e fix #4834

Small enhancements

---

openbb_terminal/helper_funcs.py
openbb_terminal/parent_classes.py

Add the ability to query askobb on api.openbb.co if user is logged in and no local openai

Query askobb on api openbb co

---

openbb_terminal/stocks/options/options_chains_model.py
tests/openbb_terminal/stocks/options/json/test_options_chains_model/test_OptionsChains_10.json
website/content/sdk/usage/intros/stocks/options-chains.md

This PR adds the SDK intro guide for Options Chains.  Also, makes one update to the skew function for accommodating SPX.

hotfix/options-chains-guide: Adds SDK intro guide for Options Chains

---

openbb_terminal/core/plots/plotly_ta/data_classes.py
tests/openbb_terminal/stocks/options/cassettes/test_nasdaq_model/test_load_options.yaml

hotfix / TA ma's empty if not enough data for window

---

openbb_terminal/stocks/screener/finviz_model.py

This PR fixes #5198
Before:
After:

hotfix/fix-stocks-screener: Fixes the random column header artifacts

---

openbb_terminal/core/plots/backend.py

Hotfix / Switch `download_plotly_js` to run in thread

---

openbb_terminal/common/technical_analysis/overlap_view.py
tests/openbb_terminal/stocks/government/txt/test_quiverquant_view/test_call_func[display_government_buys-kwargs_dict1].txt
tests/openbb_terminal/stocks/government/txt/test_quiverquant_view/test_call_func[display_government_sells-kwargs_dict2].txt

hotfix / Moving Averages Export

---

website/content/sdk/faqs/installation_updates.md
website/content/terminal/faqs/installation_updates.md
website/content/terminal/installation/source.md

This PR clarifies the process for getting the required packages within Microsoft C++ Build Tools.
Also added are explicit instructions for updating the installed version of Conda.

Adds details/image for installing C++ Build Tools

---

openbb_sdk/openbb/__init__.py
openbb_sdk/sdk/core/openbb_core/app/static/package_builder.py

Just helpful for me locally:
`openbb._rebuild_python_interface("/economy","/stocks/fa")`

Custom package builder paths

---

openbb_terminal/common/behavioural_analysis/reddit_view.py
openbb_terminal/fixedincome/fred_view.py
openbb_terminal/forecast/brnn_view.py
openbb_terminal/forecast/expo_view.py

hotfix/ conflict docstrings

---

openbb_terminal/economy/econdb_model.py

Adds more keys to the SCALES dictionary.
Fixes #5332

Fixes #5332

---

openbb_terminal/routine_functions.py
openbb_terminal/terminal_controller.py

hotfix / Allow routine args inside lists

---

website/content/sdk/usage/intros/stocks/stocks-screener.md

Fixes the URL pointing to the OpenBBUserData folder guide.

Fix URL in SDK Stock Screener Intro

---

openbb_sdk/openbb/__init__.py
openbb_sdk/sdk/core/openbb_core/app/static/account.py
openbb_sdk/sdk/core/openbb_core/app/static/app_factory.py

Key for autocomplete is to type hint the app object correctly so that Pylance gets the attributes.

Fix SDKv4 autocomplete

---

openbb_sdk/sdk/core/README.md
openbb_sdk/sdk/core/openbb_core/api/router/commands.py
openbb_sdk/sdk/core/openbb_core/env.py

Flag to disable API authentication

---

openbb_sdk/providers/cboe/openbb_cboe/models/options_chains.py
openbb_sdk/providers/cboe/openbb_cboe/models/stock_search.py
openbb_sdk/providers/fmp/openbb_fmp/models/balance_sheet_growth.py
openbb_sdk/providers/fmp/openbb_fmp/models/income_statement_growth.py
openbb_sdk/providers/fmp/openbb_fmp/models/major_indices_eod.py
openbb_sdk/providers/fmp/openbb_fmp/models/price_target.py
openbb_sdk/providers/fmp/openbb_fmp/models/stock_insider_trading.py
openbb_sdk/providers/fmp/openbb_fmp/models/stock_quote.py
openbb_sdk/sdk/provider/openbb_provider/abstract/data.py
openbb_sdk/sdk/provider/openbb_provider/standard_models/options_chains.py
openbb_sdk/sdk/provider/openbb_provider/standard_models/price_target.py
openbb_sdk/sdk/provider/openbb_provider/utils/helpers.py

Fix snake case

---

openbb_sdk/sdk/core/openbb_core/app/router.py

Same functionality, just splits some code into functions and fixes a small bug when return type hint is `OBBject[List]` .

Router cleanup

---

openbb_sdk/sdk/core/README.md
openbb_sdk/sdk/core/openbb_core/env.py
openbb_sdk/sdk/core/tests/app/logs/handlers/test_posthog_handler.py

Easier to change env vars without cloning the repo

Move .env location

---

openbb_sdk/providers/intrinio/openbb_intrinio/models/options_chains.py
openbb_sdk/providers/yfinance/openbb_yfinance/models/major_indices_historical.py
openbb_sdk/providers/yfinance/openbb_yfinance/models/stock_historical.py

Fix/yfinance-drop-index - Fix too many `reset_index()`

---

openbb_sdk/extensions/magics/openbb_magics/__init__.py

change magic code to display cell

---

openbb_sdk/sdk/core/openbb_core/app/command_runner.py

Quick addition of try-except on the metadata computing inside the command runner.

add try except on metadata computing

---

openbb_sdk/openbb/package/__extensions__.py
openbb_sdk/openbb/package/crypto.py
openbb_sdk/openbb/package/economy.py
openbb_sdk/openbb/package/fixedincome.py
openbb_sdk/openbb/package/forex.py
openbb_sdk/openbb/package/news.py
openbb_sdk/openbb/package/stocks.py
openbb_sdk/openbb/package/stocks_ca.py
openbb_sdk/openbb/package/stocks_fa.py
openbb_sdk/openbb/package/stocks_options.py
openbb_sdk/sdk/core/openbb_core/app/static/app_factory.py
openbb_sdk/sdk/core/openbb_core/app/static/package_builder.py

Include extensions in package __repr__

---

openbb_terminal/stocks/fundamental_analysis/av_model.py
openbb_terminal/stocks/options/tradier_model.py

This PR fixes 2 pylint errors, as shown here:
[https://github.com/OpenBB-finance/OpenBBTerminal/issues/5476#issuecomment-1742246560](https://github.com/OpenBB-finance/OpenBBTerminal/issues/5476#issuecomment-1742246560)
One of them was actually created by Black, reformatting a `# disable`, moving it to the wrong line.

hotfix/fix-pylint-errors: Fixes a couple of pylint errors

---

openbb_platform/platform/core/openbb_core/app/charting_service.py

try except ftw

---

.github/workflows/linting.yml
openbb_platform/EXTENSIONS.md
openbb_platform/PROVIDERS.md
openbb_platform/extensions/README.md
openbb_platform/providers/README.md

This PR moves the lists of available extensions and providers to an EXTENSIONS.md file in the platform root.
Outside contributors would be asked to add their extensions to the list in that file

Add EXTENSIONS.md

---

openbb_platform/platform/core/openbb_core/app/command_runner.py
openbb_platform/platform/core/tests/app/test_command_runner.py

Unit tests for `command_runner.py`

---

website/content/terminal/usage/guides/api-keys.md

Ultima Insights description update

---

website/content/sdk/showcase.md

Updating showcase page

---

openbb_platform/extensions/futures/integration/test_futures_api.py
openbb_platform/extensions/futures/integration/test_futures_python.py
openbb_platform/extensions/news/integration/test_news_api.py
openbb_platform/extensions/stocks/integration/test_stocks_api.py
openbb_platform/extensions/stocks/integration/test_stocks_python.py
openbb_platform/providers/cboe/openbb_cboe/models/options_chains.py
openbb_platform/providers/intrinio/openbb_intrinio/models/balance_sheet.py
openbb_platform/providers/intrinio/openbb_intrinio/models/fred_historical.py
openbb_platform/providers/intrinio/openbb_intrinio/models/options_chains.py
openbb_platform/providers/polygon/openbb_polygon/models/stock_news.py
openbb_platform/providers/yfinance/openbb_yfinance/models/futures_historical.py

Fix most tests and bugs for stocks and futures.

Fix most tests and bugs

---

openbb_platform/providers/fred/openbb_fred/models/us_yield_curve.py

Fix `fixedincome` integration tests

---

openbb_platform/extensions/charting/integration/test_charting_api.py
openbb_platform/extensions/charting/openbb_charting/core/openbb_figure.py

Fixing charting api integration tests

---

openbb_platform/providers/alpha_vantage/tests/test_alpha_vantage_fetchers.py
openbb_platform/providers/benzinga/tests/test_benzinga_fetchers.py
openbb_platform/providers/cboe/tests/test_cboe_fetchers.py
openbb_platform/providers/fmp/tests/test_fmp_fetchers.py
openbb_platform/providers/fred/tests/test_fred_fetchers.py
openbb_platform/providers/intrinio/tests/test_intrinio_fetchers.py
openbb_platform/providers/oecd/tests/test_oecd_fetchers.py
openbb_platform/providers/polygon/tests/test_polygon_fetchers.py
openbb_platform/providers/quandl/tests/test_quandl_fetchers.py
openbb_platform/providers/tests/utils/unit_tests_generator.py
openbb_platform/providers/tradingeconomics/tests/test_tradingeconomics_fetchers.py
openbb_platform/providers/yfinance/tests/test_yfinance_fetchers.py

export credentials as json

---

CONTRIBUTING.md

Fix typo errors in CONTRIBUTING.md

---

website/content/terminal/usage/guides/api-keys.md

Change Ultima paragraph

---

website/content/pro/main-menu/data-connectors/single-widget.md
website/docusaurus.config.js
website/src/css/custom.css
website/src/theme/Navbar/Layout/index.js

This also fixes the following:

Add light blue banner, blue when clicking sidebar + fix link in docusaurus.config.js

---

website/content/pro/dashboards/index.md
website/content/pro/dashboards/report.md
website/content/pro/main-menu/data-connectors/single-widget.md

fix front matter

---

build/pypi/openbb_platform/PUBLISH.md
build/pypi/openbb_platform/publish.py

Finishing touches to the publishing procedure

---

.github/workflows/platform-core.yml
noxfile.py

Run tests on develop

---

openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_balance_sheet_fetcher.yaml
openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_cash_flow_statement_fetcher.yaml
openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_income_statement_fetcher.yaml
openbb_platform/providers/intrinio/tests/test_intrinio_fetchers.py

Fix threadpool test error

---

openbb_platform/dev_install.py
openbb_platform/providers/ultima/tests/test_ultima_fetchers.py
openbb_platform/pyproject.toml

Remove ultima from deps

---

openbb_platform/platform/core/openbb_core/app/static/package_builder.py

To see linters being applied when building
```
import openbb
openbb.build(verbose=True)
```

Lint python package folder

---

openbb_platform/providers/intrinio/openbb_intrinio/models/company_news.py

Add support for multiple ticker

---

.github/workflows/gh-pages.yml

<details>
</details>
<details>
</details>

fix github pages deployment

---

website/README.md

<details>
</details>
<details>
</details>

small changes

---

examples/README.md
examples/financialStatements.ipynb
examples/findSymbols.ipynb
examples/loadHistoricalPriceData.ipynb
examples/v3/README.md
website/content/platform/development/contributor-guidelines/sharing_extensions.md
website/content/platform/development/contributor-guidelines/write_code_commit.md
website/content/platform/development/dependency_management.md
website/content/platform/development/developer-guidelines/add_data_point.md
website/content/platform/development/developer-guidelines/architectural_considerations.md
website/content/platform/development/developer-guidelines/build_openbb_extensions.md
website/content/platform/development/developer-guidelines/devtools.md
website/content/platform/development/developer-guidelines/obbject.md
website/content/platform/extensions/data_extensions.md
website/content/platform/extensions/index.md
website/content/platform/extensions/toolkit_extensions.md
website/content/platform/installation.md
website/content/platform/usage/basic_syntax.md
website/content/platform/usage/commitment_of_traders.md
website/content/platform/usage/financial_statements.md
website/content/platform/usage/find_symbols.md
website/content/platform/usage/historical_prices.md
website/content/platform/usage/index.md
website/content/platform/usage/market_calendars.md

Doing a bit of a cleanup. @deeleeramone @hjoaquim

Cleanup docs. with @the-praxs

---

openbb_platform/core/openbb_core/provider/standard_models/equity_valuation_multiples.py
openbb_platform/extensions/equity/integration/test_equity_api.py
openbb_platform/extensions/equity/integration/test_equity_python.py
openbb_platform/providers/fmp/openbb_fmp/models/equity_valuation_multiples.py
openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_equity_valuation_multiples_fetcher.yaml
openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_insider_trading_fetcher.yaml

Equity multiples add symbol data field

---

openbb_platform/providers/fmp/openbb_fmp/models/calendar_splits.py
openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_calendar_splits_fetcher.yaml

Fix the future dates not showing on split calendar on FMP

---

openbb_platform/core/openbb_core/app/model/user_settings.py

Avoids unpacking inner class `Profile` in __repr__

User settings, small fix

---

openbb_platform/extensions/equity/integration/test_equity_api.py
openbb_platform/extensions/equity/integration/test_equity_python.py
openbb_platform/extensions/equity/openbb_equity/calendar/calendar_router.py

`equity.calendar.split` -> `equity.calendar.splits`

---

website/src/theme/SearchBar/index.js

<details>
</details>
<details>
</details>

Attempt to fix search button

---

.github/workflows/branch-name-check.yml
.github/workflows/build-release.yml
.github/workflows/labels-PR.yml
.github/workflows/pypi.yml

This PR makes sure we don't accidentally publish v3 packages

Prevent gh-actions from publishing v3 unless explicitly asked to

---

build/pypi/openbb_platform/nightly.py

Fix the nightly script

---

openbb_platform/README.md
website/content/platform/extensions/data_extensions.md

Try to make it more clear what is installed when we run pip install openbb.
Also edited the readme for the pypi version.

Small change in extensions doc 

---

website/content/platform/index.md

<details>
</details>
<details>
</details>

Pointing to the dev section of the docs instead

---

CONTRIBUTING.md

This PR Fixes #5850 with a URL.

hotfix/readme-url: Update CONTRIBUTING.md URL - Fix for #5850

---

openbb_platform/extensions/economy/openbb_economy/economy_router.py
openbb_platform/extensions/regulators/openbb_regulators/cftc/cftc_router.py
openbb_platform/extensions/regulators/openbb_regulators/sec/sec_router.py
openbb_platform/providers/fred/openbb_fred/models/search.py
openbb_platform/providers/fred/tests/record/http/test_fred_fetchers/test_fred_yield_curve_fetcher.yaml
openbb_platform/providers/fred/tests/test_fred_fetchers.py
website/metadata/platform_v4_seo_metadata.json

Fuzzy search --> search
A few doc strings and SEO, that's about it.

hotfix/update-descriptions: updates some descriptions

---

openbb_platform/extensions/news/integration/test_news_api.py
openbb_platform/extensions/news/integration/test_news_python.py
openbb_platform/extensions/news/openbb_news/news_router.py

This PR is blocking https://github.com/OpenBB-finance/OpenBBTerminal/pull/5824

Add sector news route and test placeholders

---

website/content/platform/development/contributor-guidelines/quality_assurance.md
website/content/platform/development/index.md

hotfix/uvicorn-docs: Update Command Syntax - Fixes #5858

---

openbb_platform/extensions/news/integration/test_news_api.py
openbb_platform/extensions/news/integration/test_news_python.py
openbb_platform/providers/ultima/tests/record/http/test_ultima_fetchers/test_ultima_company_news_fetcher.yaml
openbb_platform/providers/ultima/tests/record/http/test_ultima_fetchers/test_ultima_sector_news_fetcher.yaml

This PR makes the news tests use the custom parametrize to stop failing when ultima is not installed

Use custom parametrize from news menu tests

---

openbb_platform/core/openbb_core/app/model/obbject.py
openbb_platform/core/tests/app/model/test_obbject.py

Added the following parameters to `OBBject.to_df()`: 
- index
- sort_by
Better UX. 
NA
<details>
<summary>Not relevant for this PR</summary>
</details>

Parameterize `obbject.to_df` with `index` and `sort_by`

---

openbb_platform/core/openbb_core/provider/registry_map.py

<details>
</details>
<details>
</details>

Refactor method in RegistryMap

---

openbb_platform/core/openbb_core/app/model/obbject.py
openbb_platform/core/openbb_core/app/static/package_builder.py

<details>
</details>
<details>
</details>

Remove Literal from providers in OBBject

---

openbb_platform/core/openbb_core/app/version.py
openbb_terminal/stocks/stocks_helper.py

Fix the version for the case when only openbb-core is installed.

Fix version

---

openbb_platform/extensions/tests/test_routers.py
openbb_platform/extensions/tests/utils/router_testers.py

Fix bug. Add router test.

---

website/content/sdk/data-available/etf.md

docs/fix-example: fix a v3 syntax example

---

openbb_platform/extensions/econometrics/integration/test_econometrics_api.py

Add econometrics API tests

---

website/content/platform/installation.md
website/content/terminal/installation/pypi.md
website/content/terminal/installation/source.md

docs/legacy-install: Add warning at top of page - Instructions on this page are for installing the Terminal

---

website/content/pro/index.md

Update Terminal Pro demo video

---

openbb_platform/providers/fmp/openbb_fmp/models/currency_historical.py

Fixes the error where FMP would return empty data.

Fix vwap FMP error

---

website/src/theme/Root.tsx

<details>
</details>
<details>
</details>

Fix docs crash

---

.github/labeler.yml
.github/workflows/labels-PR.yml

Change-log Automation V2

---

openbb_platform/core/openbb_core/app/logs/handlers/posthog_handler.py

Fixes posthog `identify` for api usage

hotfix/ allow multiple `identify` calls

---

openbb_platform/core/openbb_core/app/logs/logging_service.py

Fixes linting for the logging service

---

openbb_platform/core/openbb_core/app/example_generator.py
openbb_platform/core/openbb_core/app/router.py
openbb_platform/core/openbb_core/provider/standard_models/crypto_search.py
openbb_platform/core/tests/app/static/test_example_generator.py
openbb_platform/openbb/package/crypto.py
openbb_platform/openbb/package/economy.py
openbb_platform/openbb/package/equity.py
openbb_platform/openbb/package/equity_fundamental.py
openbb_platform/openbb/package/equity_ownership.py
openbb_platform/openbb/package/etf.py
openbb_platform/openbb/package/fixedincome_government.py
openbb_platform/openbb/package/index.py
openbb_platform/openbb/package/regulators_sec.py

<details>
</details>
<details>
</details>

feat: add & fix examples

---

build/pypi/openbb_platform/PUBLISH.md
openbb_platform/core/tests/app/test_deprecation.py

Adds a test that will discover endpoints that need to be removed when me get to a certain version.

Test for deprecated endpoints

---

openbb_platform/core/openbb_core/app/command_runner.py

**Why?:**
Nobody needs repeated code.
**What?:**
Deleted a part where code was repeated.
**Impact:**
Performance increase.
**Testing Done:**
The field order works when running a command.

[BugFix] - Remove duplicate code

---

openbb_platform/extensions/technical/openbb_technical/technical_router.py

1. Why?:
To have a better UX of the technical router commands.
2. What?:
Improved the docstrings of the commands on the technical router by satisfying pydocstyle and introducing more verbosity where needed.
3. Impact:
The docstrings that are shown on the documentation pages will change. Minimal impact.

[Enhancement] - Improve the TA docstrings

---

openbb_platform/extensions/economy/openbb_economy/economy_router.py
openbb_platform/openbb/package/economy.py

1. **Why**?:
To have a better UX of the Economy Router commands.
2. **What**?:
Improved the docstrings of the commands on the Economy Router by satisfying pydocstyle and introducing more verbosity where needed.
4. **Impact**:
The docstrings that are shown on the documentation pages will change. Minimal impact.
Tested that the examples work and that they are rendered properly in the static assets.

[Enhancement] Improve the Economy Router docstrings

---

openbb_platform/core/openbb_core/provider/standard_models/world_news.py
openbb_platform/extensions/news/integration/test_news_api.py
openbb_platform/extensions/news/integration/test_news_python.py
openbb_platform/providers/benzinga/openbb_benzinga/models/world_news.py
openbb_platform/providers/benzinga/tests/test_benzinga_fetchers.py
openbb_platform/providers/biztoc/openbb_biztoc/models/world_news.py
openbb_platform/providers/fmp/openbb_fmp/models/world_news.py
openbb_platform/providers/intrinio/openbb_intrinio/models/world_news.py
openbb_platform/providers/intrinio/tests/record/http/test_intrinio_fetchers/test_intrinio_world_news_fetcher.yaml
openbb_platform/providers/tiingo/openbb_tiingo/models/world_news.py
openbb_platform/providers/tiingo/tests/record/http/test_tiingo_fetchers/test_tiingo_world_news_fetcher.yaml
openbb_platform/providers/tiingo/tests/test_tiingo_fetchers.py

1. **Why**? :
- Only Benzinga and Tiingo will accept start/end dates as a query parameter. Filters applied to every provider on output resulted in nothing being returned. 
- Remove `filter_by_date`
- Make default `start_date` more practical - 2 weeks. There are thousands of results per-day, 1-year is beyond the capabilities of any provider to return as a single query.
- Make default limit size 2500, which is about 1-2 days of results from Intrinio.
- It works now.
Before:
After:
6. **Any other information** (optional)

[BugFix] Fix World News

---

openbb_platform/extensions/quantitative/openbb_quantitative/quantitative_router.py

- So that the UX is good and examples work.
- The CAPM examples needed to pass results instead of dataframe.
- Only changes one example.
- Tested that it works.

[BugFix] - Fix CAPM example

---

openbb_platform/extensions/crypto/integration/test_crypto_api.py
openbb_platform/extensions/crypto/integration/test_crypto_python.py
openbb_platform/extensions/derivatives/integration/test_derivatives_api.py
openbb_platform/extensions/econometrics/openbb_econometrics/econometrics_router.py
openbb_platform/extensions/economy/integration/test_economy_api.py
openbb_platform/extensions/economy/integration/test_economy_python.py
openbb_platform/extensions/equity/integration/test_equity_api.py
openbb_platform/extensions/equity/integration/test_equity_python.py
openbb_platform/extensions/index/integration/test_index_api.py
openbb_platform/extensions/index/integration/test_index_python.py
openbb_platform/extensions/news/integration/test_news_python.py
openbb_platform/extensions/tests/conftest.py
openbb_platform/providers/intrinio/openbb_intrinio/models/historical_attributes.py
openbb_platform/providers/intrinio/openbb_intrinio/models/latest_attributes.py

- To ensure quality
- Fixed most integration tests, bugs in two fetchers, and edge cases with dynamic test running.
- Should make more integration tests pass.
- Tested that the new payloads work and that the tests for integration tests pass.

[BugFix] - Fix most integration tests

---

openbb_platform/providers/benzinga/openbb_benzinga/models/price_target.py

- To properly return all data.
- Removed an alias mapping that was not correct.
- A new field will appear in the output.
- Tested that the endpoint still works.

[BugFix] - Fix `analyst` column for Benzinga

---

.github/workflows/unit-test.yml

Please go the the `Preview` tab and select the appropriate PR sub-template:
* [OpenBB Platform](?expand=1&template=platform_pull_request_template.md)
* [OpenBB Terminal](?expand=1&template=terminal_pull_request_template.md)
* [OpenBB Developers](?expand=1&template=obb_developer_pull_request_template.md)

Update unit-test workflow to check for changes to openbb_platform

---

openbb_platform/core/openbb_core/app/model/abstract/tagged.py
openbb_platform/core/openbb_core/app/model/custom_parameter.py
openbb_platform/core/openbb_core/app/static/container.py
openbb_platform/core/openbb_core/app/static/utils/filters.py
openbb_platform/core/openbb_core/provider/standard_models/trailing_dividend_yield.py
openbb_platform/openbb/package/equity_fundamental.py

1. **Why**?
- Prevent bugs by respecting expected types
2. **What**?
- Fix type bugs introduced in https://github.com/OpenBB-finance/OpenBBTerminal/pull/6062
3. **Impact**:
- NA
`mypy openbb_platform/openbb/package`

[Bug fix] - Fix package mypy

---

openbb_platform/core/openbb_core/app/static/package_builder.py
openbb_platform/core/openbb_core/app/static/utils/decorators.py
openbb_platform/openbb/package/crypto.py
openbb_platform/openbb/package/crypto_price.py
openbb_platform/openbb/package/currency.py
openbb_platform/openbb/package/currency_price.py
openbb_platform/openbb/package/derivatives_options.py
openbb_platform/openbb/package/economy.py
openbb_platform/openbb/package/economy_gdp.py
openbb_platform/openbb/package/equity.py
openbb_platform/openbb/package/equity_calendar.py
openbb_platform/openbb/package/equity_compare.py
openbb_platform/openbb/package/equity_discovery.py
openbb_platform/openbb/package/equity_estimates.py
openbb_platform/openbb/package/equity_fundamental.py
openbb_platform/openbb/package/equity_ownership.py
openbb_platform/openbb/package/equity_price.py
openbb_platform/openbb/package/equity_shorts.py
openbb_platform/openbb/package/etf.py
openbb_platform/openbb/package/fixedincome.py
openbb_platform/openbb/package/fixedincome_corporate.py
openbb_platform/openbb/package/fixedincome_government.py
openbb_platform/openbb/package/fixedincome_rate.py
openbb_platform/openbb/package/fixedincome_spreads.py
openbb_platform/openbb/package/index.py
openbb_platform/openbb/package/news.py
openbb_platform/openbb/package/regulators_sec.py

1. **Why**?
To control the verbosity of exceptions and do custom exception handling.
2. **What**?
- Adds the `exception_handler` decorator under `utils/decorator.py`
- Adds condition to check DEBUG_MODE for controlling exception verbosity
4. **Impact**
- Moderate
- Impact Analysis breakdown:
- _UX_ = 0 (Developer use only)
- _Performance_ = 2 (Added imports)
- _Compatibility_ = 4 (Decorator added in static)
- _Security_ = 2 (Decorator handles exception)
- _Scalability_ = 4 (Scalable to handle global level exceptions)
- _Maintenance_ = 2 (Meticulously handle global exceptions)
- _Compliance_ = 0 (No compliance changes)
- _Dependency_ = 2 (Added imports)
- _Total Impact Score_ = 16
- Static built and checked
- Random commands check with `DEBUG_MODE` on and off

[Feature] - Add `exception_handler` decorator to static

---

website/content/platform/extensions/data_extensions.md
website/content/platform/extensions/toolkit_extensions.md

- Non-current list of data provider extensions.
- Updated tables.
- Added dependency list to `openbb-charting` and include a line for installing Rust (if necessary)

[Docs] Update Extensions List

---

openbb_platform/providers/yfinance/openbb_yfinance/models/equity_historical.py

- The fields for corporate actions were missing from the model.
- Added fields for `dividend` and `split_ratio` with descriptions.
- The two fields have been named to match the corresponding fields from Intrinio.
- Improved model metadata.
- Observed the changes and verified that the fields and descriptions are present in the model schema.

[BugFix] Add Missing Field Descriptions to yFinance EquityHistorical Model

---

openbb_platform/providers/tests/test_provider_fetcher.py

- Removing unnecessary code improves code quality.
-  Remove unnecessary function and use `providers` prop instead
- NA
- Tests passing.

[BufFix] Remove unnecessary function and use `providers` prop instead

---

openbb_platform/providers/tradingeconomics/openbb_tradingeconomics/utils/countries.py

Australia did not appear as a country. Now it is.

added australia as a country also

---

openbb_platform/core/openbb_core/provider/standard_models/cik_map.py
openbb_platform/openbb/package/regulators_sec.py
openbb_platform/providers/sec/openbb_sec/models/cik_map.py

1. **Why**?
- Wrong standard model used for query params
- No standard model for data
2. **What**?
- Create standard and use it
- Fix docsring
```python
obb.regulators.sec.cik_map("AAPL").to_df()
```

[Bug fix] - Fix regulator cik map standard model

---

website/generate_excel_markdown.py

^ Fix OBB.GET examples https://github.com/OpenBB-finance/OpenBBTerminal/pull/6145

Fix get reference

---

openbb_platform/core/openbb_core/api/rest_api.py
openbb_platform/extensions/equity/integration/test_equity_api.py
openbb_platform/extensions/equity/integration/test_equity_python.py
openbb_platform/extensions/quantitative/integration/test_quantitative_api.py
openbb_platform/extensions/quantitative/openbb_quantitative/stats/stats_router.py
openbb_platform/extensions/technical/openbb_technical/technical_router.py
openbb_platform/openbb/package/equity_fundamental.py
openbb_platform/providers/intrinio/openbb_intrinio/models/equity_historical.py
openbb_platform/providers/nasdaq/openbb_nasdaq/models/economic_calendar.py

1. **Why**?
- Fixes failing integration tests.
2. **What**?
- Log API errors to help debug
- Freeze api integration tests data start and end dates
- Docstring formatting
- General bug fixes
3. **Impact**:
- NA
- All integration tests passing

[Bug fix] - Fix integration tests

---

.github/labeler.yml
.github/release-drafter.yml

Please go the the `Preview` tab and select the appropriate PR sub-template:
* [OpenBB Platform](?expand=1&template=platform_pull_request_template.md)
* [OpenBB Terminal](?expand=1&template=terminal_pull_request_template.md)
* [OpenBB Developers](?expand=1&template=obb_developer_pull_request_template.md)

Add labels for  `breaking_changes` tag

---

openbb_platform/providers/alpha_vantage/openbb_alpha_vantage/models/equity_historical.py

1. **Why**?
- Bugs when api key is not premium
2. **What**?
- Unpack alpha vantage message and display the information
3. **Impact**
- NA
```python
obb.equity.price.historical("AAPL", provider="alpha_vantage")
```

[Bugfix] - Fix equity/price/historical w/ alphavantage

---

openbb_platform/providers/tmx/openbb_tmx/models/equity_historical.py

- If the date is a datetime object already, handle that.
- Handle exception in validator.
- N/A
- Test on API with daily/intraday.

[BugFix] Handle TMX Date Type

---

build/pypi/openbb_platform/publish.py
openbb_platform/README.md
openbb_platform/providers/tmx/pyproject.toml
openbb_platform/providers/tradier/pyproject.toml
openbb_platform/pyproject.toml

1. **Why**?
To update the readme with correct default providers.
2. **What**?
Update the table with the default providers
3. **Impact**
N/A
4. **Testing Done**
N/A

[BugFix] Update `README` for Platform

---

build/pypi/openbb_platform/PUBLISH.md

1. **Why**?
Improves the publishing procedure
2. **What**?
Adds sections and more info
3. **Impact**
Huge impact for devs
4. **Testing Done**
Checked the contents

[Bugfix] Update `PUBLISH.md` file

---

build/pypi/openbb_platform/PUBLISH.md

1. **Why**?
- We might need to do intermediate releases to patch specific packages, e.g. openbb-core
2. **What**?
- Branch name should respect convention `release/<package>-<version>`
3. **Impact**
- NA 
- NA

[Bugfix] - Small update on PUBLISH.md

---

openbb_platform/core/poetry.lock
openbb_platform/core/pyproject.toml

1. **Why**?
Release the patch issue with obbject extensions
2. **What**?
Fixes the obbject extension issue (#6195)
3. **Impact**
N/A
Tested locally

[Release] openbb-core-1.1.4

---

openbb_platform/extensions/tests/test_routers.py
openbb_platform/extensions/tests/utils/helpers.py
openbb_platform/extensions/tests/utils/router_testers.py

- Examples could have parameters passed that don't exist or are typos.
- Added a check to ensure that the passed Example parameters are supported by the command.
- Won't change anything substantially. Improves the QA.
- Tested that it works.

[Enhancement] - Improve the example test

---

openbb_platform/extensions/crypto/integration/test_crypto_api.py
openbb_platform/extensions/crypto/integration/test_crypto_python.py
openbb_platform/extensions/currency/integration/test_currency_api.py
openbb_platform/extensions/currency/integration/test_currency_python.py
openbb_platform/extensions/equity/integration/test_equity_api.py
openbb_platform/extensions/equity/integration/test_equity_python.py
openbb_platform/extensions/index/integration/test_index_api.py
openbb_platform/extensions/index/integration/test_index_python.py
openbb_platform/providers/fmp/openbb_fmp/models/crypto_historical.py
openbb_platform/providers/fmp/openbb_fmp/models/currency_historical.py
openbb_platform/providers/fmp/openbb_fmp/models/equity_historical.py
openbb_platform/providers/fmp/openbb_fmp/models/index_historical.py

- Results were not appended when not a dictionary.
- Make it work.
- Reconfigure request to do parsing outside of callback function.
- Return all error messages from the API.
```
Error fetching data for ^VIX: Invalid API KEY. Feel free to create a Free API Key or visit https://site.financialmodelingprep.com/faqs?search=why-is-my-api-key-invalid for more information.
```
- Not a breaking change.
- Intraday not empty anymore.
- Ran big lists of tickers through at various intervals

[HotFix] Fix FMP Intraday

---

website/content/pro/main-menu/data-connectors/integrate-your-own-backend.md

https://openbb.atlassian.net/browse/AA-1989

Add Native Integrations Documentation

---

.github/workflows/platform-api-integration-test.yml

1. **Why**?
- Throwing errors as if extensions not installed
2. **What**?
- Manually rebuild to ensure python package is created
3. **Impact**:
- Now they run 
- https://github.com/OpenBB-finance/OpenBBTerminal/actions/runs/8392256963/job/22984485934

[BugFix] - Fix integration tests workflow file

---

CONTRIBUTING.md

1. **Why**?
- Missing documentation on website deployment
2. **What**?
- Adds sections explaining documentation deployment
3. **Impact**
- NA
- NA

[Docs] - Update contributing section

---

website/content/excel/templates.mdx

Just updates Excel template to allow to download templates directly.

Make Excel templates downloadable from docs

---

CONTRIBUTING.md

[Git] - Merge main into develop

---

openbb_platform/core/openbb_core/app/model/obbject.py
openbb_platform/core/openbb_core/provider/abstract/annotated_data.py
openbb_platform/core/openbb_core/provider/abstract/annotated_result.py
openbb_platform/core/openbb_core/provider/abstract/fetcher.py
openbb_platform/providers/fred/openbb_fred/models/series.py

0. **Title**:
- Format: [Type] - Brief Description (e.g., [Hotfix] - Improve Calculation Accuracy).
- State the primary reason for this change.
- Example: "To enhance the accuracy of our risk calculation in response to recent market volatility."
- Describe what has been done in simple terms.
- Example: "Updated the risk calculation algorithm to factor in real-time market fluctuations."
- Briefly note the expected outcome or any potential risks and share the Impact Analysis score.
- Example: "Expected to improve risk assessment accuracy by 15%, with minimal performance impact. Impact score: 10"
> [!TIP]
> Refer to the Impact Analysis …

[Feature] - Annotated results

---

website/content/pro/data-connectors/integrate-your-own-backend.md
website/content/pro/data-connectors/native-integrations.md

Same changes https://github.com/OpenBB-finance/OpenBBTerminal/pull/6286

[Docs] - Pro native integrations

---

openbb_platform/obbject_extensions/charting/openbb_charting/__init__.py
openbb_platform/obbject_extensions/charting/openbb_charting/charting_router.py
openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py
openbb_platform/obbject_extensions/charting/openbb_charting/core/plotly_ta/ta_class.py
openbb_platform/obbject_extensions/charting/openbb_charting/utils/generic_charts.py

1. **Why**?:
- Differences between rendering in PyWry vs. Notebook.
- Describe what has been done in simple terms.
After:
- Should be cosmetic only.
- Jupyter and CL/PyWry.

[BugFix] Charts: Fix Legend & Title Crowding in Jupyter

---

build/docker/api.dockerfile

1. **Why**?:
- This file is in the installation instructions and is still valid for Platform installation.
This Docker file installs all Platform components.

[BugFix] Replace Platform Docker File.

---

.gitignore
website/.gitignore
website/content/excel/functions.json
website/content/excel/openapi.json
website/generate_excel_markdown.py

Same changes https://github.com/OpenBB-finance/OpenBBTerminal/pull/6328

[Docs] - Update excel docs

---

.github/workflows/draft-release.yml

fix the dependencies issues on the changelog summary workflow #6341

[BugFix] - fix the dependencies issues on the changelog summary workflow

---

openbb_platform/providers/fmp/openbb_fmp/models/crypto_historical.py
openbb_platform/providers/fmp/openbb_fmp/models/currency_historical.py
openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_crypto_historical_fetcher.yaml
openbb_platform/providers/fmp/tests/record/http/test_fmp_fetchers/test_fmp_currency_historical_fetcher.yaml

1. **Why**?:
- API endpoint changed without warning or messages.
2. **What**?:
- Updated the request URLs to a working path.
- Recaptured unit tests.
- N/A
- Currency/Crypto historical prices not returning empty now.

[BugFix] Fix FMP Currency/Crypto Historical Prices

---

openbb_platform/providers/sec/openbb_sec/utils/definitions.py

Follow up of https://github.com/OpenBB-finance/OpenBBTerminal/pull/6432

[BugFix] Remove space from literals

---

openbb_platform/obbject_extensions/charting/openbb_charting/core/openbb_figure.py
website/content/platform/developer_guide/metadata.mdx
website/content/platform/user_guides/metadata.mdx

1. **Why**?:
- This functionality needs documentation for both the user and developer experience.
2. **What**?:
- A page for users with examples of the types of metadata returned.
- A page for developers with the instructions for including metadata with the command output.

[Docs] Guides for Metadata and AnnotatedResult

---

openbb_platform/obbject_extensions/charting/examples.md
website/content/platform/getting_started/economic_indicators.mdx
website/content/platform/getting_started/quickstart.mdx

-> https://github.com/OpenBB-finance/OpenBBTerminal/pull/6471#issuecomment-2136127337

[Docs] Make Same PR as the to Main

---

cli/openbb_cli/controllers/base_platform_controller.py

- Getting back to the old Terminal behavior: when exporting, it shouldn't print anything (either to the console or pywry).
- Check if it's an export and act accordingly
- NA / minor UX.
- Trying different exports with and without charting.

[Feature] No prints when exporting 

---

website/content/excel/functions.json
website/content/excel/openapi.json
website/content/excel/openbb-functions.json
website/generate_excel_markdown.py

1. **Why**?
- Update Excel docs to new custom functions UI
- Filter data tabs based on providers available in Excel
2. **What**?
- This update removes a lot of endpoints according to `functions.json`
3. **Impact**:
- NA
- NA

[Docs] Excel docs update

---

.github/workflows/general-linting.yml
openbb_platform/core/tests/api/test_rest_api.py
openbb_platform/extensions/derivatives/pyproject.toml
openbb_platform/openbb/assets/reference.json
openbb_platform/openbb/package/__extensions__.py
openbb_platform/openbb/package/derivatives_options.py
openbb_platform/providers/intrinio/openbb_intrinio/models/forward_eps_estimates.py
openbb_platform/providers/intrinio/openbb_intrinio/models/forward_sales_estimates.py
openbb_platform/providers/intrinio/openbb_intrinio/models/options_chains.py
openbb_platform/providers/intrinio/pyproject.toml

1. **Why**?
- Syntax bug prevents openapi.json to be generated
2. **What**?
- Fix bug, add unit test
- Fix linting action
3. **Impact**
- NA
- Launch the API and hit /openapi.json

[HotFix] Fix openapi.json bug

---

openbb_platform/extensions/tests/utils/integration_tests_testers.py

[BugFix] - Patch test

---

openbb_platform/core/tests/api/test_rest_api.py
openbb_platform/extensions/tests/utils/integration_tests_testers.py

[BugFix] test openapi.json

---

openbb_platform/core/openbb_core/app/static/package_builder.py
openbb_platform/openbb/assets/reference.json

[Docs] Fix provider description in parameter tables

---

openbb_platform/providers/econdb/openbb_econdb/models/economic_indicators.py
openbb_platform/providers/econdb/openbb_econdb/utils/main_indicators.py
openbb_platform/providers/fmp/openbb_fmp/models/currency_snapshots.py

This PR updates code, tests and other things that are broken as a result of application of the security update.
The security update (see target branch) bumped a lot of dependencies some of which are not backwards compatible.
- Fix FMP currency snapshot model after a security update
- Fix EconDB economic indicators

Resolve bugs highlighted by the tests

---

cli/pyproject.toml
openbb_platform/core/pyproject.toml

[Hotfix] Bump versions

---

.github/workflows/gh-branch-name-check.yml

Updates URL to: [https://docs.openbb.co/platform/developer_guide/github#branch-naming-conventions](https://docs.openbb.co/platform/developer_guide/github#branch-naming-conventions)

[BugFix] Fix GitHub Actions Branch Check URL that 404s

---

assets/extensions/provider.json
openbb_platform/openbb/assets/reference.json
openbb_platform/openbb/package/__extensions__.py

Updates the static files before merging dev into main.

[BugFix] Release Static Files

---

openbb_platform/providers/yfinance/poetry.lock
openbb_platform/providers/yfinance/pyproject.toml

This PR patches `openbb-yfinance` on PyPI to resolve a Colabs issue #6645.

[Release] Patch: `openbb-yfinance-1.3.2`

---

openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
openbb_platform/extensions/platform_api/openbb_platform_api/utils/widgets.py

This PR updates the script to include columnsDefs. It's not 100% bullet-proof but we're pretty close to reaching the limits of what can be done automagically across absolutely everything.
- Everything that is labeled as `'x-unit_measurement': 'percent'` is displayed as Red/Green percentage values.
- CIK and other security identifiers are explicitly set as 'text' to avoid interpreting as an integer.

Refactor Widgets Builder For columnsDefs

---

frontend-components/plotly/package-lock.json
frontend-components/plotly/package.json
frontend-components/tables/package-lock.json
frontend-components/tables/package.json

1. Why? 
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1695
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1694
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1693
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1692

[BugFix] Update vite in `package.json`

---

README.md

1. **Why**?:
- Some stray items that did not get the URL updated.

[BugFix] Update missed URLs from repo name change.

---

frontend-components/plotly/package-lock.json
frontend-components/plotly/package.json
frontend-components/tables/package-lock.json
frontend-components/tables/package.json

1. **Why**?:
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1696
- Resolves https://github.com/OpenBB-finance/OpenBB/security/dependabot/1697
2. **What**?:
- Define the package in package.json, update the lock files.
3. **Impact**:
- Makes Dependabot happy.

[BugFix] Update Frontend Components package.json and locks for Dependabot

---

openbb_platform/extensions/platform_api/openbb_platform_api/main.py
openbb_platform/extensions/platform_api/openbb_platform_api/utils/api.py
openbb_platform/extensions/platform_api/openbb_platform_api/utils/widgets.py

Add implementation of widget filtering based on local json configuration

---

openbb_platform/CONTRIBUTING.md

docs: update CONTRIBUTING.md

---

oss.gg/no_code_side_quests/6-social-hero.md

Please go to the `Preview` tab and select the appropriate PR sub-template:
Issue no OSS.gg Social Hero #6772
Added the links of post of twitter and linked of username of twitter  : 12A_56 Mitarth Pandey LinkedIN : Mitarth Pandey

 ADDED POSTS LINK IN social-hero-md

---

oss.gg/no_code_side_quests/6-social-hero.md

#6815 Submitting Code Side Quest harshraj1512

Submitting Code Side Quest harshraj1512

---

oss.gg/no_code_side_quests/4-social-poster.md

[oss.gg] social-poster (50 points)

---

oss.gg/no_code_side_quests/0-set-upper.md

Record your onboarding and first steps with OpenBB Terminal (Points: 150 Points - 300 Points)
After ending the video, I was exploring the app further and I used Copilot to extract some more data and I got error in the chat and when I refreshed the page, errors were gone and clear chat (forgot to take screenshot of the errors).
Apart from that, I love the app design, especially Copilot. You can review the video :)
I'm a newbie in this finance stuff but shared my honest feedback from a newbie perspective. Hope that's useful

feat: Record your onboarding and first steps with OpenBB Terminal

---

oss.gg/no_code_side_quests/4-social-poster.md
oss.gg/no_code_side_quests/6-social-hero.md

POST:
https://x.com/HarshBhatX/status/1849881530887438765
THREAD:
https://x.com/HarshBhatX/status/1849882759637995920
POINTS: 50 for post / 100-500 for thread

chore: Ossgg Two side quests

---

oss.gg/code_side_quests/1-openbb-integration.md

Closes #6853 
- Integrated OpenBB into a Streamlit dashboard.
- **GitHub Repository:** [Integrate-OpenBB-Streamlit-Dashboard](https://github.com/Yash-1511/openbb-dashboard.git)
- **Demo Video:** [Watch the Integration Demo](https://www.loom.com/share/3f422d3c44994e67961d1006053da8f9?sid=3726fa29-fcd4-4825-b806-6ade2ee2bcee)

[🕹️] Code Side Quest Submission #issue 6853

---

oss.gg/no_code_side_quests/5-financial-post.md

**Write a Article Comparing OpenBB and Other Financial Tools** 
Article [_Link_](https://dev.to/k-adi/financial-freedom-through-open-source-openbb-vs-proprietary-tools-2l6j)

feat : [🕹️] Write a Article Comparing OpenBB and Other Financial Tools 

---

oss.gg/no_code_side_quests/2-fundamental-blog.md

My submission for Side Quest: Write a Use-Case Blog for OpenBB in Fundamental Analysis (Points: 300 Points)
I've referred to [openbb docs](https://docs.openbb.co/platform/reference/equity/fundamental/balance). Hope it's beneficial for people to effectively and easily use it :)

feat: Write a Use-Case Blog for OpenBB in Fundamental Analysis

---

openbb_platform/openbb/assets/reference.json
openbb_platform/openbb/package/fixedincome.py
openbb_platform/providers/fred/openbb_fred/models/bond_indices.py

1. **Why**?:
- Resolves #6967 
2. **What**?:
- Adds the list of choices into the docstring.
3. **Impact**:
- Improved clarity.

[Enhancement] Improve Docstring For `obb.fixedincome.bond_indices`

---

frontend-components/tables/package-lock.json
frontend-components/tables/package.json

1. **Why**?:
- Resolves CVE-2024-55565
2. **What**?:
- Updates `package.json` and the lock file.
3. **Impact**:
- N/A

[Security] Update `package.json` In `frontend-components`

---

openbb_platform/dev_install.py

[HotFix] Update dev_install.py

---

openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
openbb_platform/extensions/platform_api/openbb_platform_api/utils/widgets.py

1. **Why**?:
- This fixes an issue where the "$ref" property in openapi.json is being accessed without verifying its existence.
2. **What**?:
- Uses `.get` to access the property that might exist, and fallback to the parent.
3. **Impact**:
- This fixes widget creation when `@router.command(no_validate=True)`
- Allows for custom backends not using Annotations for ultra-lazy widgets.json creation.
- Making a quick router extension with develop branch installs of `openbb-core` and `openbb-platform-api`
```python
from datetime import datetime
from typing import Annotated
from fastapi import Query
from fastapi.responses import JSONResponse
from openbb_core.app.router import Router
router = Router(prefix="", description="A custom OpenBB router extension.")
@router.command( …
```

[BugFix] `openbb-platform-api`: Fix Unsafe Property Access In `get_data_schema_for_widget`

---

.github/workflows/macos-build.yml

An investigation into resolving this:

upload-artifact?

---

openbb_platform/extensions/platform_api/openbb_platform_api/utils/api.py
openbb_platform/extensions/platform_api/tests/test_api.py

This PR changes the `import_app` function to accommodate the following cases:
```
openbb-api --app my_module.main:app
openbb-api --app main.py:app
openbb-api --app my_folder/main.py:app
openbb-api --app main.py --name another_name
openbb-api --app my_module.main:create_app
openbb-api --app main:create_app --factory
```
and others.
So now the launcher can handle python modules, sub-modules, relative paths, absolute paths.
The factory launcher now uses similar logic to what `uvicorn` uses to detect the factory allows us to stop relying on explicit type annotation of the factory function.
Additinonally some tests for `import_app` were added, although 2/3 of them actually work

Improve openbb api launcher

---

openbb_platform/extensions/platform_api/README.md
openbb_platform/extensions/platform_api/openbb_platform_api/query_models.py
openbb_platform/extensions/platform_api/openbb_platform_api/utils/openapi.py
openbb_platform/extensions/platform_api/openbb_platform_api/utils/widgets.py
openbb_platform/extensions/platform_api/tests/mock_openapi.json
openbb_platform/extensions/platform_api/tests/mock_widgets.json
openbb_platform/extensions/platform_api/tests/test_openapi_utils.py

1. **Why**?:
- Keep up with the Jones'
2. **What**?:
- Defines a pattern for the widget factory based on GET/POST for the same API Route.
3. **Impact**:
- No impact to Platform, this only enhances custom apps.
- See README for full example.
- Added a test for finding POST $ref model in `openapi.json`
- Added to entries for `test_build_json`

[Feature] `openbb-platform-api` - Create Entry In `widgets.json` For Forms

---

openbb_platform/core/openbb_core/provider/standard_models/company_filings.py
openbb_platform/extensions/equity/integration/test_equity_api.py
openbb_platform/extensions/equity/integration/test_equity_python.py
openbb_platform/extensions/equity/openbb_equity/fundamental/fundamental_router.py
openbb_platform/providers/fmp/openbb_fmp/models/company_filings.py
openbb_platform/providers/intrinio/openbb_intrinio/models/company_filings.py
openbb_platform/providers/sec/openbb_sec/models/company_filings.py
openbb_platform/providers/sec/openbb_sec/utils/form4.py
openbb_platform/providers/tmx/openbb_tmx/models/company_filings.py

1. **Why**?:
- Some parameters and descriptions were misleading by being defined in the standard model.
2. **What**?:
- Shuffles parameters around so they reflect the providers' properly.
3. **Impact**:
- Better clarity for provider parameters.
- Requires #7069 to rebuild properly.

[Enhacement] Cleanup CompanyFilings

---

openbb_platform/core/openbb_core/provider/standard_models/crypto_historical.py
openbb_platform/extensions/econometrics/openbb_econometrics/utils.py
openbb_platform/extensions/equity/integration/test_equity_python.py
openbb_platform/providers/fmp/openbb_fmp/models/crypto_historical.py
openbb_platform/providers/intrinio/openbb_intrinio/models/forward_pe_estimates.py
openbb_platform/providers/polygon/openbb_polygon/models/index_historical.py
openbb_platform/providers/polygon/openbb_polygon/utils/helpers.py

This PR fixes some minor bugs:
- Raising UnauthorizedError:
- obb.equity.estimates.forward_pe(provider="intrinio")
- obb.index.price.historical(provider="polygon")
- CryptoHistoricalData
- volume is now Optional
- Pandas FutureWarning:
- obb.econometrics.utils.get_engle_granger_two_step_cointegration_test

[BugFix] Fix Some Bugs Before Release

---

frontend-components/plotly/package-lock.json
frontend-components/plotly/package.json
frontend-components/tables/package-lock.json
frontend-components/tables/package.json

1. **Why**?
- Resolves CVE-2025-46565
- https://github.com/OpenBB-finance/OpenBB/security/dependabot/1932
2. **What**?:
- Updates the version in packages.json and packages-lock.json
3. **Impact**:
- Only development servers are impacted, there are no changes.
- N/A

[Security] Bump Vite in `frontend-components`
